// ==============================================================
// RTL generated by Vitis HLS - High-Level Synthesis from C, C++ and OpenCL v2022.2 (64-bit)
// Version: 2022.2
// Copyright (C) Copyright 1986-2022 Xilinx, Inc. All Rights Reserved.
// 
// ===========================================================

`timescale 1 ns / 1 ps 

(* CORE_GENERATION_INFO="test_jacobi_4096_test_jacobi_4096,hls_ip_2022_2,{HLS_INPUT_TYPE=cxx,HLS_INPUT_FLOAT=1,HLS_INPUT_FIXED=0,HLS_INPUT_PART=xc7a100t-csg324-1,HLS_INPUT_CLOCK=10.000000,HLS_INPUT_ARCH=others,HLS_SYN_CLOCK=5.926000,HLS_SYN_LAT=16957441,HLS_SYN_TPT=none,HLS_SYN_MEM=0,HLS_SYN_DSP=0,HLS_SYN_FF=3082,HLS_SYN_LUT=2634,HLS_VERSION=2022_2}" *)

module test_jacobi_4096 (
        ap_clk,
        ap_rst_n,
        v1_0_Addr_A,
        v1_0_EN_A,
        v1_0_WEN_A,
        v1_0_Din_A,
        v1_0_Dout_A,
        v1_0_Clk_A,
        v1_0_Rst_A,
        v1_0_Addr_B,
        v1_0_EN_B,
        v1_0_WEN_B,
        v1_0_Din_B,
        v1_0_Dout_B,
        v1_0_Clk_B,
        v1_0_Rst_B,
        v1_1_Addr_A,
        v1_1_EN_A,
        v1_1_WEN_A,
        v1_1_Din_A,
        v1_1_Dout_A,
        v1_1_Clk_A,
        v1_1_Rst_A,
        v1_1_Addr_B,
        v1_1_EN_B,
        v1_1_WEN_B,
        v1_1_Din_B,
        v1_1_Dout_B,
        v1_1_Clk_B,
        v1_1_Rst_B,
        v1_2_Addr_A,
        v1_2_EN_A,
        v1_2_WEN_A,
        v1_2_Din_A,
        v1_2_Dout_A,
        v1_2_Clk_A,
        v1_2_Rst_A,
        v1_2_Addr_B,
        v1_2_EN_B,
        v1_2_WEN_B,
        v1_2_Din_B,
        v1_2_Dout_B,
        v1_2_Clk_B,
        v1_2_Rst_B,
        v1_3_Addr_A,
        v1_3_EN_A,
        v1_3_WEN_A,
        v1_3_Din_A,
        v1_3_Dout_A,
        v1_3_Clk_A,
        v1_3_Rst_A,
        v1_3_Addr_B,
        v1_3_EN_B,
        v1_3_WEN_B,
        v1_3_Din_B,
        v1_3_Dout_B,
        v1_3_Clk_B,
        v1_3_Rst_B,
        v2_0_Addr_A,
        v2_0_EN_A,
        v2_0_WEN_A,
        v2_0_Din_A,
        v2_0_Dout_A,
        v2_0_Clk_A,
        v2_0_Rst_A,
        v2_0_Addr_B,
        v2_0_EN_B,
        v2_0_WEN_B,
        v2_0_Din_B,
        v2_0_Dout_B,
        v2_0_Clk_B,
        v2_0_Rst_B,
        v2_1_Addr_A,
        v2_1_EN_A,
        v2_1_WEN_A,
        v2_1_Din_A,
        v2_1_Dout_A,
        v2_1_Clk_A,
        v2_1_Rst_A,
        v2_1_Addr_B,
        v2_1_EN_B,
        v2_1_WEN_B,
        v2_1_Din_B,
        v2_1_Dout_B,
        v2_1_Clk_B,
        v2_1_Rst_B,
        v2_2_Addr_A,
        v2_2_EN_A,
        v2_2_WEN_A,
        v2_2_Din_A,
        v2_2_Dout_A,
        v2_2_Clk_A,
        v2_2_Rst_A,
        v2_2_Addr_B,
        v2_2_EN_B,
        v2_2_WEN_B,
        v2_2_Din_B,
        v2_2_Dout_B,
        v2_2_Clk_B,
        v2_2_Rst_B,
        v2_3_Addr_A,
        v2_3_EN_A,
        v2_3_WEN_A,
        v2_3_Din_A,
        v2_3_Dout_A,
        v2_3_Clk_A,
        v2_3_Rst_A,
        v2_3_Addr_B,
        v2_3_EN_B,
        v2_3_WEN_B,
        v2_3_Din_B,
        v2_3_Dout_B,
        v2_3_Clk_B,
        v2_3_Rst_B,
        s_axi_ctrl_AWVALID,
        s_axi_ctrl_AWREADY,
        s_axi_ctrl_AWADDR,
        s_axi_ctrl_WVALID,
        s_axi_ctrl_WREADY,
        s_axi_ctrl_WDATA,
        s_axi_ctrl_WSTRB,
        s_axi_ctrl_ARVALID,
        s_axi_ctrl_ARREADY,
        s_axi_ctrl_ARADDR,
        s_axi_ctrl_RVALID,
        s_axi_ctrl_RREADY,
        s_axi_ctrl_RDATA,
        s_axi_ctrl_RRESP,
        s_axi_ctrl_BVALID,
        s_axi_ctrl_BREADY,
        s_axi_ctrl_BRESP,
        interrupt
);

parameter    ap_ST_fsm_state1 = 5'd1;
parameter    ap_ST_fsm_state2 = 5'd2;
parameter    ap_ST_fsm_state3 = 5'd4;
parameter    ap_ST_fsm_state4 = 5'd8;
parameter    ap_ST_fsm_state5 = 5'd16;
parameter    C_S_AXI_CTRL_DATA_WIDTH = 32;
parameter    C_S_AXI_CTRL_ADDR_WIDTH = 5;
parameter    C_S_AXI_DATA_WIDTH = 32;

parameter C_S_AXI_CTRL_WSTRB_WIDTH = (32 / 8);
parameter C_S_AXI_WSTRB_WIDTH = (32 / 8);

input   ap_clk;
input   ap_rst_n;
output  [31:0] v1_0_Addr_A;
output   v1_0_EN_A;
output  [3:0] v1_0_WEN_A;
output  [31:0] v1_0_Din_A;
input  [31:0] v1_0_Dout_A;
output   v1_0_Clk_A;
output   v1_0_Rst_A;
output  [31:0] v1_0_Addr_B;
output   v1_0_EN_B;
output  [3:0] v1_0_WEN_B;
output  [31:0] v1_0_Din_B;
input  [31:0] v1_0_Dout_B;
output   v1_0_Clk_B;
output   v1_0_Rst_B;
output  [31:0] v1_1_Addr_A;
output   v1_1_EN_A;
output  [3:0] v1_1_WEN_A;
output  [31:0] v1_1_Din_A;
input  [31:0] v1_1_Dout_A;
output   v1_1_Clk_A;
output   v1_1_Rst_A;
output  [31:0] v1_1_Addr_B;
output   v1_1_EN_B;
output  [3:0] v1_1_WEN_B;
output  [31:0] v1_1_Din_B;
input  [31:0] v1_1_Dout_B;
output   v1_1_Clk_B;
output   v1_1_Rst_B;
output  [31:0] v1_2_Addr_A;
output   v1_2_EN_A;
output  [3:0] v1_2_WEN_A;
output  [31:0] v1_2_Din_A;
input  [31:0] v1_2_Dout_A;
output   v1_2_Clk_A;
output   v1_2_Rst_A;
output  [31:0] v1_2_Addr_B;
output   v1_2_EN_B;
output  [3:0] v1_2_WEN_B;
output  [31:0] v1_2_Din_B;
input  [31:0] v1_2_Dout_B;
output   v1_2_Clk_B;
output   v1_2_Rst_B;
output  [31:0] v1_3_Addr_A;
output   v1_3_EN_A;
output  [3:0] v1_3_WEN_A;
output  [31:0] v1_3_Din_A;
input  [31:0] v1_3_Dout_A;
output   v1_3_Clk_A;
output   v1_3_Rst_A;
output  [31:0] v1_3_Addr_B;
output   v1_3_EN_B;
output  [3:0] v1_3_WEN_B;
output  [31:0] v1_3_Din_B;
input  [31:0] v1_3_Dout_B;
output   v1_3_Clk_B;
output   v1_3_Rst_B;
output  [31:0] v2_0_Addr_A;
output   v2_0_EN_A;
output  [3:0] v2_0_WEN_A;
output  [31:0] v2_0_Din_A;
input  [31:0] v2_0_Dout_A;
output   v2_0_Clk_A;
output   v2_0_Rst_A;
output  [31:0] v2_0_Addr_B;
output   v2_0_EN_B;
output  [3:0] v2_0_WEN_B;
output  [31:0] v2_0_Din_B;
input  [31:0] v2_0_Dout_B;
output   v2_0_Clk_B;
output   v2_0_Rst_B;
output  [31:0] v2_1_Addr_A;
output   v2_1_EN_A;
output  [3:0] v2_1_WEN_A;
output  [31:0] v2_1_Din_A;
input  [31:0] v2_1_Dout_A;
output   v2_1_Clk_A;
output   v2_1_Rst_A;
output  [31:0] v2_1_Addr_B;
output   v2_1_EN_B;
output  [3:0] v2_1_WEN_B;
output  [31:0] v2_1_Din_B;
input  [31:0] v2_1_Dout_B;
output   v2_1_Clk_B;
output   v2_1_Rst_B;
output  [31:0] v2_2_Addr_A;
output   v2_2_EN_A;
output  [3:0] v2_2_WEN_A;
output  [31:0] v2_2_Din_A;
input  [31:0] v2_2_Dout_A;
output   v2_2_Clk_A;
output   v2_2_Rst_A;
output  [31:0] v2_2_Addr_B;
output   v2_2_EN_B;
output  [3:0] v2_2_WEN_B;
output  [31:0] v2_2_Din_B;
input  [31:0] v2_2_Dout_B;
output   v2_2_Clk_B;
output   v2_2_Rst_B;
output  [31:0] v2_3_Addr_A;
output   v2_3_EN_A;
output  [3:0] v2_3_WEN_A;
output  [31:0] v2_3_Din_A;
input  [31:0] v2_3_Dout_A;
output   v2_3_Clk_A;
output   v2_3_Rst_A;
output  [31:0] v2_3_Addr_B;
output   v2_3_EN_B;
output  [3:0] v2_3_WEN_B;
output  [31:0] v2_3_Din_B;
input  [31:0] v2_3_Dout_B;
output   v2_3_Clk_B;
output   v2_3_Rst_B;
input   s_axi_ctrl_AWVALID;
output   s_axi_ctrl_AWREADY;
input  [C_S_AXI_CTRL_ADDR_WIDTH - 1:0] s_axi_ctrl_AWADDR;
input   s_axi_ctrl_WVALID;
output   s_axi_ctrl_WREADY;
input  [C_S_AXI_CTRL_DATA_WIDTH - 1:0] s_axi_ctrl_WDATA;
input  [C_S_AXI_CTRL_WSTRB_WIDTH - 1:0] s_axi_ctrl_WSTRB;
input   s_axi_ctrl_ARVALID;
output   s_axi_ctrl_ARREADY;
input  [C_S_AXI_CTRL_ADDR_WIDTH - 1:0] s_axi_ctrl_ARADDR;
output   s_axi_ctrl_RVALID;
input   s_axi_ctrl_RREADY;
output  [C_S_AXI_CTRL_DATA_WIDTH - 1:0] s_axi_ctrl_RDATA;
output  [1:0] s_axi_ctrl_RRESP;
output   s_axi_ctrl_BVALID;
input   s_axi_ctrl_BREADY;
output  [1:0] s_axi_ctrl_BRESP;
output   interrupt;

reg[31:0] v1_0_Addr_A;
reg v1_0_EN_A;
reg[3:0] v1_0_WEN_A;
reg v1_0_EN_B;
reg[31:0] v1_1_Addr_A;
reg v1_1_EN_A;
reg[3:0] v1_1_WEN_A;
reg v1_1_EN_B;
reg[31:0] v1_2_Addr_A;
reg v1_2_EN_A;
reg[3:0] v1_2_WEN_A;
reg v1_2_EN_B;
reg[31:0] v1_3_Addr_A;
reg v1_3_EN_A;
reg[3:0] v1_3_WEN_A;
reg v1_3_EN_B;
reg[31:0] v2_0_Addr_A;
reg v2_0_EN_A;
reg[3:0] v2_0_WEN_A;
reg v2_0_EN_B;
reg[31:0] v2_1_Addr_A;
reg v2_1_EN_A;
reg[3:0] v2_1_WEN_A;
reg v2_1_EN_B;
reg[31:0] v2_2_Addr_A;
reg v2_2_EN_A;
reg[3:0] v2_2_WEN_A;
reg v2_2_EN_B;
reg[31:0] v2_3_Addr_A;
reg v2_3_EN_A;
reg[3:0] v2_3_WEN_A;
reg v2_3_EN_B;

 reg    ap_rst_n_inv;
wire    ap_start;
reg    ap_done;
reg    ap_idle;
(* fsm_encoding = "none" *) reg   [4:0] ap_CS_fsm;
wire    ap_CS_fsm_state1;
reg    ap_ready;
wire   [31:0] v0;
reg   [31:0] v0_read_reg_148;
wire    grp_test_jacobi_4096_Pipeline_VITIS_LOOP_40_2_fu_74_ap_start;
wire    grp_test_jacobi_4096_Pipeline_VITIS_LOOP_40_2_fu_74_ap_done;
wire    grp_test_jacobi_4096_Pipeline_VITIS_LOOP_40_2_fu_74_ap_idle;
wire    grp_test_jacobi_4096_Pipeline_VITIS_LOOP_40_2_fu_74_ap_ready;
wire   [31:0] grp_test_jacobi_4096_Pipeline_VITIS_LOOP_40_2_fu_74_v1_0_Addr_A;
wire    grp_test_jacobi_4096_Pipeline_VITIS_LOOP_40_2_fu_74_v1_0_EN_A;
wire   [3:0] grp_test_jacobi_4096_Pipeline_VITIS_LOOP_40_2_fu_74_v1_0_WEN_A;
wire   [31:0] grp_test_jacobi_4096_Pipeline_VITIS_LOOP_40_2_fu_74_v1_0_Din_A;
wire   [31:0] grp_test_jacobi_4096_Pipeline_VITIS_LOOP_40_2_fu_74_v2_1_Addr_A;
wire    grp_test_jacobi_4096_Pipeline_VITIS_LOOP_40_2_fu_74_v2_1_EN_A;
wire   [3:0] grp_test_jacobi_4096_Pipeline_VITIS_LOOP_40_2_fu_74_v2_1_WEN_A;
wire   [31:0] grp_test_jacobi_4096_Pipeline_VITIS_LOOP_40_2_fu_74_v2_1_Din_A;
wire   [31:0] grp_test_jacobi_4096_Pipeline_VITIS_LOOP_40_2_fu_74_v2_1_Addr_B;
wire    grp_test_jacobi_4096_Pipeline_VITIS_LOOP_40_2_fu_74_v2_1_EN_B;
wire   [3:0] grp_test_jacobi_4096_Pipeline_VITIS_LOOP_40_2_fu_74_v2_1_WEN_B;
wire   [31:0] grp_test_jacobi_4096_Pipeline_VITIS_LOOP_40_2_fu_74_v2_1_Din_B;
wire   [31:0] grp_test_jacobi_4096_Pipeline_VITIS_LOOP_40_2_fu_74_v2_3_Addr_A;
wire    grp_test_jacobi_4096_Pipeline_VITIS_LOOP_40_2_fu_74_v2_3_EN_A;
wire   [3:0] grp_test_jacobi_4096_Pipeline_VITIS_LOOP_40_2_fu_74_v2_3_WEN_A;
wire   [31:0] grp_test_jacobi_4096_Pipeline_VITIS_LOOP_40_2_fu_74_v2_3_Din_A;
wire   [31:0] grp_test_jacobi_4096_Pipeline_VITIS_LOOP_40_2_fu_74_v2_3_Addr_B;
wire    grp_test_jacobi_4096_Pipeline_VITIS_LOOP_40_2_fu_74_v2_3_EN_B;
wire   [3:0] grp_test_jacobi_4096_Pipeline_VITIS_LOOP_40_2_fu_74_v2_3_WEN_B;
wire   [31:0] grp_test_jacobi_4096_Pipeline_VITIS_LOOP_40_2_fu_74_v2_3_Din_B;
wire   [31:0] grp_test_jacobi_4096_Pipeline_VITIS_LOOP_40_2_fu_74_v1_1_Addr_A;
wire    grp_test_jacobi_4096_Pipeline_VITIS_LOOP_40_2_fu_74_v1_1_EN_A;
wire   [3:0] grp_test_jacobi_4096_Pipeline_VITIS_LOOP_40_2_fu_74_v1_1_WEN_A;
wire   [31:0] grp_test_jacobi_4096_Pipeline_VITIS_LOOP_40_2_fu_74_v1_1_Din_A;
wire   [31:0] grp_test_jacobi_4096_Pipeline_VITIS_LOOP_40_2_fu_74_v1_3_Addr_A;
wire    grp_test_jacobi_4096_Pipeline_VITIS_LOOP_40_2_fu_74_v1_3_EN_A;
wire   [3:0] grp_test_jacobi_4096_Pipeline_VITIS_LOOP_40_2_fu_74_v1_3_WEN_A;
wire   [31:0] grp_test_jacobi_4096_Pipeline_VITIS_LOOP_40_2_fu_74_v1_3_Din_A;
wire   [31:0] grp_test_jacobi_4096_Pipeline_VITIS_LOOP_40_2_fu_74_v1_2_Addr_A;
wire    grp_test_jacobi_4096_Pipeline_VITIS_LOOP_40_2_fu_74_v1_2_EN_A;
wire   [3:0] grp_test_jacobi_4096_Pipeline_VITIS_LOOP_40_2_fu_74_v1_2_WEN_A;
wire   [31:0] grp_test_jacobi_4096_Pipeline_VITIS_LOOP_40_2_fu_74_v1_2_Din_A;
wire   [31:0] grp_test_jacobi_4096_Pipeline_VITIS_LOOP_40_2_fu_74_v2_0_Addr_A;
wire    grp_test_jacobi_4096_Pipeline_VITIS_LOOP_40_2_fu_74_v2_0_EN_A;
wire   [3:0] grp_test_jacobi_4096_Pipeline_VITIS_LOOP_40_2_fu_74_v2_0_WEN_A;
wire   [31:0] grp_test_jacobi_4096_Pipeline_VITIS_LOOP_40_2_fu_74_v2_0_Din_A;
wire   [31:0] grp_test_jacobi_4096_Pipeline_VITIS_LOOP_40_2_fu_74_v2_0_Addr_B;
wire    grp_test_jacobi_4096_Pipeline_VITIS_LOOP_40_2_fu_74_v2_0_EN_B;
wire   [3:0] grp_test_jacobi_4096_Pipeline_VITIS_LOOP_40_2_fu_74_v2_0_WEN_B;
wire   [31:0] grp_test_jacobi_4096_Pipeline_VITIS_LOOP_40_2_fu_74_v2_0_Din_B;
wire   [31:0] grp_test_jacobi_4096_Pipeline_VITIS_LOOP_40_2_fu_74_v2_2_Addr_A;
wire    grp_test_jacobi_4096_Pipeline_VITIS_LOOP_40_2_fu_74_v2_2_EN_A;
wire   [3:0] grp_test_jacobi_4096_Pipeline_VITIS_LOOP_40_2_fu_74_v2_2_WEN_A;
wire   [31:0] grp_test_jacobi_4096_Pipeline_VITIS_LOOP_40_2_fu_74_v2_2_Din_A;
wire   [31:0] grp_test_jacobi_4096_Pipeline_VITIS_LOOP_40_2_fu_74_v2_2_Addr_B;
wire    grp_test_jacobi_4096_Pipeline_VITIS_LOOP_40_2_fu_74_v2_2_EN_B;
wire   [3:0] grp_test_jacobi_4096_Pipeline_VITIS_LOOP_40_2_fu_74_v2_2_WEN_B;
wire   [31:0] grp_test_jacobi_4096_Pipeline_VITIS_LOOP_40_2_fu_74_v2_2_Din_B;
wire   [31:0] grp_test_jacobi_4096_Pipeline_VITIS_LOOP_40_2_fu_74_grp_fu_157_p_din0;
wire   [31:0] grp_test_jacobi_4096_Pipeline_VITIS_LOOP_40_2_fu_74_grp_fu_157_p_din1;
wire   [1:0] grp_test_jacobi_4096_Pipeline_VITIS_LOOP_40_2_fu_74_grp_fu_157_p_opcode;
wire    grp_test_jacobi_4096_Pipeline_VITIS_LOOP_40_2_fu_74_grp_fu_157_p_ce;
wire   [31:0] grp_test_jacobi_4096_Pipeline_VITIS_LOOP_40_2_fu_74_grp_fu_161_p_din0;
wire   [31:0] grp_test_jacobi_4096_Pipeline_VITIS_LOOP_40_2_fu_74_grp_fu_161_p_din1;
wire   [1:0] grp_test_jacobi_4096_Pipeline_VITIS_LOOP_40_2_fu_74_grp_fu_161_p_opcode;
wire    grp_test_jacobi_4096_Pipeline_VITIS_LOOP_40_2_fu_74_grp_fu_161_p_ce;
wire   [31:0] grp_test_jacobi_4096_Pipeline_VITIS_LOOP_40_2_fu_74_grp_fu_165_p_din0;
wire   [31:0] grp_test_jacobi_4096_Pipeline_VITIS_LOOP_40_2_fu_74_grp_fu_165_p_din1;
wire   [1:0] grp_test_jacobi_4096_Pipeline_VITIS_LOOP_40_2_fu_74_grp_fu_165_p_opcode;
wire    grp_test_jacobi_4096_Pipeline_VITIS_LOOP_40_2_fu_74_grp_fu_165_p_ce;
wire   [31:0] grp_test_jacobi_4096_Pipeline_VITIS_LOOP_40_2_fu_74_grp_fu_169_p_din0;
wire   [31:0] grp_test_jacobi_4096_Pipeline_VITIS_LOOP_40_2_fu_74_grp_fu_169_p_din1;
wire   [1:0] grp_test_jacobi_4096_Pipeline_VITIS_LOOP_40_2_fu_74_grp_fu_169_p_opcode;
wire    grp_test_jacobi_4096_Pipeline_VITIS_LOOP_40_2_fu_74_grp_fu_169_p_ce;
wire   [31:0] grp_test_jacobi_4096_Pipeline_VITIS_LOOP_40_2_fu_74_grp_fu_173_p_din0;
wire   [31:0] grp_test_jacobi_4096_Pipeline_VITIS_LOOP_40_2_fu_74_grp_fu_173_p_din1;
wire    grp_test_jacobi_4096_Pipeline_VITIS_LOOP_40_2_fu_74_grp_fu_173_p_ce;
wire   [31:0] grp_test_jacobi_4096_Pipeline_VITIS_LOOP_40_2_fu_74_grp_fu_177_p_din0;
wire   [31:0] grp_test_jacobi_4096_Pipeline_VITIS_LOOP_40_2_fu_74_grp_fu_177_p_din1;
wire    grp_test_jacobi_4096_Pipeline_VITIS_LOOP_40_2_fu_74_grp_fu_177_p_ce;
wire    grp_test_jacobi_4096_Pipeline_VITIS_LOOP_55_3_fu_95_ap_start;
wire    grp_test_jacobi_4096_Pipeline_VITIS_LOOP_55_3_fu_95_ap_done;
wire    grp_test_jacobi_4096_Pipeline_VITIS_LOOP_55_3_fu_95_ap_idle;
wire    grp_test_jacobi_4096_Pipeline_VITIS_LOOP_55_3_fu_95_ap_ready;
wire   [31:0] grp_test_jacobi_4096_Pipeline_VITIS_LOOP_55_3_fu_95_v2_0_Addr_A;
wire    grp_test_jacobi_4096_Pipeline_VITIS_LOOP_55_3_fu_95_v2_0_EN_A;
wire   [3:0] grp_test_jacobi_4096_Pipeline_VITIS_LOOP_55_3_fu_95_v2_0_WEN_A;
wire   [31:0] grp_test_jacobi_4096_Pipeline_VITIS_LOOP_55_3_fu_95_v2_0_Din_A;
wire   [31:0] grp_test_jacobi_4096_Pipeline_VITIS_LOOP_55_3_fu_95_v1_1_Addr_A;
wire    grp_test_jacobi_4096_Pipeline_VITIS_LOOP_55_3_fu_95_v1_1_EN_A;
wire   [3:0] grp_test_jacobi_4096_Pipeline_VITIS_LOOP_55_3_fu_95_v1_1_WEN_A;
wire   [31:0] grp_test_jacobi_4096_Pipeline_VITIS_LOOP_55_3_fu_95_v1_1_Din_A;
wire   [31:0] grp_test_jacobi_4096_Pipeline_VITIS_LOOP_55_3_fu_95_v1_1_Addr_B;
wire    grp_test_jacobi_4096_Pipeline_VITIS_LOOP_55_3_fu_95_v1_1_EN_B;
wire   [3:0] grp_test_jacobi_4096_Pipeline_VITIS_LOOP_55_3_fu_95_v1_1_WEN_B;
wire   [31:0] grp_test_jacobi_4096_Pipeline_VITIS_LOOP_55_3_fu_95_v1_1_Din_B;
wire   [31:0] grp_test_jacobi_4096_Pipeline_VITIS_LOOP_55_3_fu_95_v1_3_Addr_A;
wire    grp_test_jacobi_4096_Pipeline_VITIS_LOOP_55_3_fu_95_v1_3_EN_A;
wire   [3:0] grp_test_jacobi_4096_Pipeline_VITIS_LOOP_55_3_fu_95_v1_3_WEN_A;
wire   [31:0] grp_test_jacobi_4096_Pipeline_VITIS_LOOP_55_3_fu_95_v1_3_Din_A;
wire   [31:0] grp_test_jacobi_4096_Pipeline_VITIS_LOOP_55_3_fu_95_v1_3_Addr_B;
wire    grp_test_jacobi_4096_Pipeline_VITIS_LOOP_55_3_fu_95_v1_3_EN_B;
wire   [3:0] grp_test_jacobi_4096_Pipeline_VITIS_LOOP_55_3_fu_95_v1_3_WEN_B;
wire   [31:0] grp_test_jacobi_4096_Pipeline_VITIS_LOOP_55_3_fu_95_v1_3_Din_B;
wire   [31:0] grp_test_jacobi_4096_Pipeline_VITIS_LOOP_55_3_fu_95_v2_1_Addr_A;
wire    grp_test_jacobi_4096_Pipeline_VITIS_LOOP_55_3_fu_95_v2_1_EN_A;
wire   [3:0] grp_test_jacobi_4096_Pipeline_VITIS_LOOP_55_3_fu_95_v2_1_WEN_A;
wire   [31:0] grp_test_jacobi_4096_Pipeline_VITIS_LOOP_55_3_fu_95_v2_1_Din_A;
wire   [31:0] grp_test_jacobi_4096_Pipeline_VITIS_LOOP_55_3_fu_95_v2_3_Addr_A;
wire    grp_test_jacobi_4096_Pipeline_VITIS_LOOP_55_3_fu_95_v2_3_EN_A;
wire   [3:0] grp_test_jacobi_4096_Pipeline_VITIS_LOOP_55_3_fu_95_v2_3_WEN_A;
wire   [31:0] grp_test_jacobi_4096_Pipeline_VITIS_LOOP_55_3_fu_95_v2_3_Din_A;
wire   [31:0] grp_test_jacobi_4096_Pipeline_VITIS_LOOP_55_3_fu_95_v2_2_Addr_A;
wire    grp_test_jacobi_4096_Pipeline_VITIS_LOOP_55_3_fu_95_v2_2_EN_A;
wire   [3:0] grp_test_jacobi_4096_Pipeline_VITIS_LOOP_55_3_fu_95_v2_2_WEN_A;
wire   [31:0] grp_test_jacobi_4096_Pipeline_VITIS_LOOP_55_3_fu_95_v2_2_Din_A;
wire   [31:0] grp_test_jacobi_4096_Pipeline_VITIS_LOOP_55_3_fu_95_v1_0_Addr_A;
wire    grp_test_jacobi_4096_Pipeline_VITIS_LOOP_55_3_fu_95_v1_0_EN_A;
wire   [3:0] grp_test_jacobi_4096_Pipeline_VITIS_LOOP_55_3_fu_95_v1_0_WEN_A;
wire   [31:0] grp_test_jacobi_4096_Pipeline_VITIS_LOOP_55_3_fu_95_v1_0_Din_A;
wire   [31:0] grp_test_jacobi_4096_Pipeline_VITIS_LOOP_55_3_fu_95_v1_0_Addr_B;
wire    grp_test_jacobi_4096_Pipeline_VITIS_LOOP_55_3_fu_95_v1_0_EN_B;
wire   [3:0] grp_test_jacobi_4096_Pipeline_VITIS_LOOP_55_3_fu_95_v1_0_WEN_B;
wire   [31:0] grp_test_jacobi_4096_Pipeline_VITIS_LOOP_55_3_fu_95_v1_0_Din_B;
wire   [31:0] grp_test_jacobi_4096_Pipeline_VITIS_LOOP_55_3_fu_95_v1_2_Addr_A;
wire    grp_test_jacobi_4096_Pipeline_VITIS_LOOP_55_3_fu_95_v1_2_EN_A;
wire   [3:0] grp_test_jacobi_4096_Pipeline_VITIS_LOOP_55_3_fu_95_v1_2_WEN_A;
wire   [31:0] grp_test_jacobi_4096_Pipeline_VITIS_LOOP_55_3_fu_95_v1_2_Din_A;
wire   [31:0] grp_test_jacobi_4096_Pipeline_VITIS_LOOP_55_3_fu_95_v1_2_Addr_B;
wire    grp_test_jacobi_4096_Pipeline_VITIS_LOOP_55_3_fu_95_v1_2_EN_B;
wire   [3:0] grp_test_jacobi_4096_Pipeline_VITIS_LOOP_55_3_fu_95_v1_2_WEN_B;
wire   [31:0] grp_test_jacobi_4096_Pipeline_VITIS_LOOP_55_3_fu_95_v1_2_Din_B;
wire   [31:0] grp_test_jacobi_4096_Pipeline_VITIS_LOOP_55_3_fu_95_grp_fu_157_p_din0;
wire   [31:0] grp_test_jacobi_4096_Pipeline_VITIS_LOOP_55_3_fu_95_grp_fu_157_p_din1;
wire   [1:0] grp_test_jacobi_4096_Pipeline_VITIS_LOOP_55_3_fu_95_grp_fu_157_p_opcode;
wire    grp_test_jacobi_4096_Pipeline_VITIS_LOOP_55_3_fu_95_grp_fu_157_p_ce;
wire   [31:0] grp_test_jacobi_4096_Pipeline_VITIS_LOOP_55_3_fu_95_grp_fu_161_p_din0;
wire   [31:0] grp_test_jacobi_4096_Pipeline_VITIS_LOOP_55_3_fu_95_grp_fu_161_p_din1;
wire   [1:0] grp_test_jacobi_4096_Pipeline_VITIS_LOOP_55_3_fu_95_grp_fu_161_p_opcode;
wire    grp_test_jacobi_4096_Pipeline_VITIS_LOOP_55_3_fu_95_grp_fu_161_p_ce;
wire   [31:0] grp_test_jacobi_4096_Pipeline_VITIS_LOOP_55_3_fu_95_grp_fu_165_p_din0;
wire   [31:0] grp_test_jacobi_4096_Pipeline_VITIS_LOOP_55_3_fu_95_grp_fu_165_p_din1;
wire   [1:0] grp_test_jacobi_4096_Pipeline_VITIS_LOOP_55_3_fu_95_grp_fu_165_p_opcode;
wire    grp_test_jacobi_4096_Pipeline_VITIS_LOOP_55_3_fu_95_grp_fu_165_p_ce;
wire   [31:0] grp_test_jacobi_4096_Pipeline_VITIS_LOOP_55_3_fu_95_grp_fu_169_p_din0;
wire   [31:0] grp_test_jacobi_4096_Pipeline_VITIS_LOOP_55_3_fu_95_grp_fu_169_p_din1;
wire   [1:0] grp_test_jacobi_4096_Pipeline_VITIS_LOOP_55_3_fu_95_grp_fu_169_p_opcode;
wire    grp_test_jacobi_4096_Pipeline_VITIS_LOOP_55_3_fu_95_grp_fu_169_p_ce;
wire   [31:0] grp_test_jacobi_4096_Pipeline_VITIS_LOOP_55_3_fu_95_grp_fu_173_p_din0;
wire   [31:0] grp_test_jacobi_4096_Pipeline_VITIS_LOOP_55_3_fu_95_grp_fu_173_p_din1;
wire    grp_test_jacobi_4096_Pipeline_VITIS_LOOP_55_3_fu_95_grp_fu_173_p_ce;
wire   [31:0] grp_test_jacobi_4096_Pipeline_VITIS_LOOP_55_3_fu_95_grp_fu_177_p_din0;
wire   [31:0] grp_test_jacobi_4096_Pipeline_VITIS_LOOP_55_3_fu_95_grp_fu_177_p_din1;
wire    grp_test_jacobi_4096_Pipeline_VITIS_LOOP_55_3_fu_95_grp_fu_177_p_ce;
reg    grp_test_jacobi_4096_Pipeline_VITIS_LOOP_40_2_fu_74_ap_start_reg;
wire    ap_CS_fsm_state2;
wire   [0:0] icmp_ln39_fu_124_p2;
wire    ap_CS_fsm_state3;
reg    grp_test_jacobi_4096_Pipeline_VITIS_LOOP_55_3_fu_95_ap_start_reg;
wire    ap_CS_fsm_state4;
wire    ap_CS_fsm_state5;
reg   [12:0] v3_fu_64;
wire   [12:0] v3_2_fu_130_p2;
wire   [31:0] grp_fu_157_p2;
reg   [31:0] grp_fu_157_p0;
reg   [31:0] grp_fu_157_p1;
reg    grp_fu_157_ce;
wire   [31:0] grp_fu_161_p2;
reg   [31:0] grp_fu_161_p0;
reg   [31:0] grp_fu_161_p1;
reg    grp_fu_161_ce;
wire   [31:0] grp_fu_165_p2;
reg   [31:0] grp_fu_165_p0;
reg   [31:0] grp_fu_165_p1;
reg    grp_fu_165_ce;
wire   [31:0] grp_fu_169_p2;
reg   [31:0] grp_fu_169_p0;
reg   [31:0] grp_fu_169_p1;
reg    grp_fu_169_ce;
wire   [31:0] grp_fu_173_p2;
reg   [31:0] grp_fu_173_p0;
reg   [31:0] grp_fu_173_p1;
reg    grp_fu_173_ce;
wire   [31:0] grp_fu_177_p2;
reg   [31:0] grp_fu_177_p0;
reg   [31:0] grp_fu_177_p1;
reg    grp_fu_177_ce;
reg   [4:0] ap_NS_fsm;
reg    ap_ST_fsm_state1_blk;
wire    ap_ST_fsm_state2_blk;
reg    ap_ST_fsm_state3_blk;
wire    ap_ST_fsm_state4_blk;
reg    ap_ST_fsm_state5_blk;
wire    ap_ce_reg;

// power-on initialization
initial begin
#0 ap_CS_fsm = 5'd1;
#0 grp_test_jacobi_4096_Pipeline_VITIS_LOOP_40_2_fu_74_ap_start_reg = 1'b0;
#0 grp_test_jacobi_4096_Pipeline_VITIS_LOOP_55_3_fu_95_ap_start_reg = 1'b0;
end

test_jacobi_4096_test_jacobi_4096_Pipeline_VITIS_LOOP_40_2 grp_test_jacobi_4096_Pipeline_VITIS_LOOP_40_2_fu_74(
    .ap_clk(ap_clk),
    .ap_rst(ap_rst_n_inv),
    .ap_start(grp_test_jacobi_4096_Pipeline_VITIS_LOOP_40_2_fu_74_ap_start),
    .ap_done(grp_test_jacobi_4096_Pipeline_VITIS_LOOP_40_2_fu_74_ap_done),
    .ap_idle(grp_test_jacobi_4096_Pipeline_VITIS_LOOP_40_2_fu_74_ap_idle),
    .ap_ready(grp_test_jacobi_4096_Pipeline_VITIS_LOOP_40_2_fu_74_ap_ready),
    .v1_0_Addr_A(grp_test_jacobi_4096_Pipeline_VITIS_LOOP_40_2_fu_74_v1_0_Addr_A),
    .v1_0_EN_A(grp_test_jacobi_4096_Pipeline_VITIS_LOOP_40_2_fu_74_v1_0_EN_A),
    .v1_0_WEN_A(grp_test_jacobi_4096_Pipeline_VITIS_LOOP_40_2_fu_74_v1_0_WEN_A),
    .v1_0_Din_A(grp_test_jacobi_4096_Pipeline_VITIS_LOOP_40_2_fu_74_v1_0_Din_A),
    .v1_0_Dout_A(32'd0),
    .v2_1_Addr_A(grp_test_jacobi_4096_Pipeline_VITIS_LOOP_40_2_fu_74_v2_1_Addr_A),
    .v2_1_EN_A(grp_test_jacobi_4096_Pipeline_VITIS_LOOP_40_2_fu_74_v2_1_EN_A),
    .v2_1_WEN_A(grp_test_jacobi_4096_Pipeline_VITIS_LOOP_40_2_fu_74_v2_1_WEN_A),
    .v2_1_Din_A(grp_test_jacobi_4096_Pipeline_VITIS_LOOP_40_2_fu_74_v2_1_Din_A),
    .v2_1_Dout_A(v2_1_Dout_A),
    .v2_1_Addr_B(grp_test_jacobi_4096_Pipeline_VITIS_LOOP_40_2_fu_74_v2_1_Addr_B),
    .v2_1_EN_B(grp_test_jacobi_4096_Pipeline_VITIS_LOOP_40_2_fu_74_v2_1_EN_B),
    .v2_1_WEN_B(grp_test_jacobi_4096_Pipeline_VITIS_LOOP_40_2_fu_74_v2_1_WEN_B),
    .v2_1_Din_B(grp_test_jacobi_4096_Pipeline_VITIS_LOOP_40_2_fu_74_v2_1_Din_B),
    .v2_1_Dout_B(v2_1_Dout_B),
    .v2_3_Addr_A(grp_test_jacobi_4096_Pipeline_VITIS_LOOP_40_2_fu_74_v2_3_Addr_A),
    .v2_3_EN_A(grp_test_jacobi_4096_Pipeline_VITIS_LOOP_40_2_fu_74_v2_3_EN_A),
    .v2_3_WEN_A(grp_test_jacobi_4096_Pipeline_VITIS_LOOP_40_2_fu_74_v2_3_WEN_A),
    .v2_3_Din_A(grp_test_jacobi_4096_Pipeline_VITIS_LOOP_40_2_fu_74_v2_3_Din_A),
    .v2_3_Dout_A(v2_3_Dout_A),
    .v2_3_Addr_B(grp_test_jacobi_4096_Pipeline_VITIS_LOOP_40_2_fu_74_v2_3_Addr_B),
    .v2_3_EN_B(grp_test_jacobi_4096_Pipeline_VITIS_LOOP_40_2_fu_74_v2_3_EN_B),
    .v2_3_WEN_B(grp_test_jacobi_4096_Pipeline_VITIS_LOOP_40_2_fu_74_v2_3_WEN_B),
    .v2_3_Din_B(grp_test_jacobi_4096_Pipeline_VITIS_LOOP_40_2_fu_74_v2_3_Din_B),
    .v2_3_Dout_B(v2_3_Dout_B),
    .v0(v0_read_reg_148),
    .v1_1_Addr_A(grp_test_jacobi_4096_Pipeline_VITIS_LOOP_40_2_fu_74_v1_1_Addr_A),
    .v1_1_EN_A(grp_test_jacobi_4096_Pipeline_VITIS_LOOP_40_2_fu_74_v1_1_EN_A),
    .v1_1_WEN_A(grp_test_jacobi_4096_Pipeline_VITIS_LOOP_40_2_fu_74_v1_1_WEN_A),
    .v1_1_Din_A(grp_test_jacobi_4096_Pipeline_VITIS_LOOP_40_2_fu_74_v1_1_Din_A),
    .v1_1_Dout_A(32'd0),
    .v1_3_Addr_A(grp_test_jacobi_4096_Pipeline_VITIS_LOOP_40_2_fu_74_v1_3_Addr_A),
    .v1_3_EN_A(grp_test_jacobi_4096_Pipeline_VITIS_LOOP_40_2_fu_74_v1_3_EN_A),
    .v1_3_WEN_A(grp_test_jacobi_4096_Pipeline_VITIS_LOOP_40_2_fu_74_v1_3_WEN_A),
    .v1_3_Din_A(grp_test_jacobi_4096_Pipeline_VITIS_LOOP_40_2_fu_74_v1_3_Din_A),
    .v1_3_Dout_A(32'd0),
    .v1_2_Addr_A(grp_test_jacobi_4096_Pipeline_VITIS_LOOP_40_2_fu_74_v1_2_Addr_A),
    .v1_2_EN_A(grp_test_jacobi_4096_Pipeline_VITIS_LOOP_40_2_fu_74_v1_2_EN_A),
    .v1_2_WEN_A(grp_test_jacobi_4096_Pipeline_VITIS_LOOP_40_2_fu_74_v1_2_WEN_A),
    .v1_2_Din_A(grp_test_jacobi_4096_Pipeline_VITIS_LOOP_40_2_fu_74_v1_2_Din_A),
    .v1_2_Dout_A(32'd0),
    .v2_0_Addr_A(grp_test_jacobi_4096_Pipeline_VITIS_LOOP_40_2_fu_74_v2_0_Addr_A),
    .v2_0_EN_A(grp_test_jacobi_4096_Pipeline_VITIS_LOOP_40_2_fu_74_v2_0_EN_A),
    .v2_0_WEN_A(grp_test_jacobi_4096_Pipeline_VITIS_LOOP_40_2_fu_74_v2_0_WEN_A),
    .v2_0_Din_A(grp_test_jacobi_4096_Pipeline_VITIS_LOOP_40_2_fu_74_v2_0_Din_A),
    .v2_0_Dout_A(v2_0_Dout_A),
    .v2_0_Addr_B(grp_test_jacobi_4096_Pipeline_VITIS_LOOP_40_2_fu_74_v2_0_Addr_B),
    .v2_0_EN_B(grp_test_jacobi_4096_Pipeline_VITIS_LOOP_40_2_fu_74_v2_0_EN_B),
    .v2_0_WEN_B(grp_test_jacobi_4096_Pipeline_VITIS_LOOP_40_2_fu_74_v2_0_WEN_B),
    .v2_0_Din_B(grp_test_jacobi_4096_Pipeline_VITIS_LOOP_40_2_fu_74_v2_0_Din_B),
    .v2_0_Dout_B(v2_0_Dout_B),
    .v2_2_Addr_A(grp_test_jacobi_4096_Pipeline_VITIS_LOOP_40_2_fu_74_v2_2_Addr_A),
    .v2_2_EN_A(grp_test_jacobi_4096_Pipeline_VITIS_LOOP_40_2_fu_74_v2_2_EN_A),
    .v2_2_WEN_A(grp_test_jacobi_4096_Pipeline_VITIS_LOOP_40_2_fu_74_v2_2_WEN_A),
    .v2_2_Din_A(grp_test_jacobi_4096_Pipeline_VITIS_LOOP_40_2_fu_74_v2_2_Din_A),
    .v2_2_Dout_A(v2_2_Dout_A),
    .v2_2_Addr_B(grp_test_jacobi_4096_Pipeline_VITIS_LOOP_40_2_fu_74_v2_2_Addr_B),
    .v2_2_EN_B(grp_test_jacobi_4096_Pipeline_VITIS_LOOP_40_2_fu_74_v2_2_EN_B),
    .v2_2_WEN_B(grp_test_jacobi_4096_Pipeline_VITIS_LOOP_40_2_fu_74_v2_2_WEN_B),
    .v2_2_Din_B(grp_test_jacobi_4096_Pipeline_VITIS_LOOP_40_2_fu_74_v2_2_Din_B),
    .v2_2_Dout_B(v2_2_Dout_B),
    .grp_fu_157_p_din0(grp_test_jacobi_4096_Pipeline_VITIS_LOOP_40_2_fu_74_grp_fu_157_p_din0),
    .grp_fu_157_p_din1(grp_test_jacobi_4096_Pipeline_VITIS_LOOP_40_2_fu_74_grp_fu_157_p_din1),
    .grp_fu_157_p_opcode(grp_test_jacobi_4096_Pipeline_VITIS_LOOP_40_2_fu_74_grp_fu_157_p_opcode),
    .grp_fu_157_p_dout0(grp_fu_157_p2),
    .grp_fu_157_p_ce(grp_test_jacobi_4096_Pipeline_VITIS_LOOP_40_2_fu_74_grp_fu_157_p_ce),
    .grp_fu_161_p_din0(grp_test_jacobi_4096_Pipeline_VITIS_LOOP_40_2_fu_74_grp_fu_161_p_din0),
    .grp_fu_161_p_din1(grp_test_jacobi_4096_Pipeline_VITIS_LOOP_40_2_fu_74_grp_fu_161_p_din1),
    .grp_fu_161_p_opcode(grp_test_jacobi_4096_Pipeline_VITIS_LOOP_40_2_fu_74_grp_fu_161_p_opcode),
    .grp_fu_161_p_dout0(grp_fu_161_p2),
    .grp_fu_161_p_ce(grp_test_jacobi_4096_Pipeline_VITIS_LOOP_40_2_fu_74_grp_fu_161_p_ce),
    .grp_fu_165_p_din0(grp_test_jacobi_4096_Pipeline_VITIS_LOOP_40_2_fu_74_grp_fu_165_p_din0),
    .grp_fu_165_p_din1(grp_test_jacobi_4096_Pipeline_VITIS_LOOP_40_2_fu_74_grp_fu_165_p_din1),
    .grp_fu_165_p_opcode(grp_test_jacobi_4096_Pipeline_VITIS_LOOP_40_2_fu_74_grp_fu_165_p_opcode),
    .grp_fu_165_p_dout0(grp_fu_165_p2),
    .grp_fu_165_p_ce(grp_test_jacobi_4096_Pipeline_VITIS_LOOP_40_2_fu_74_grp_fu_165_p_ce),
    .grp_fu_169_p_din0(grp_test_jacobi_4096_Pipeline_VITIS_LOOP_40_2_fu_74_grp_fu_169_p_din0),
    .grp_fu_169_p_din1(grp_test_jacobi_4096_Pipeline_VITIS_LOOP_40_2_fu_74_grp_fu_169_p_din1),
    .grp_fu_169_p_opcode(grp_test_jacobi_4096_Pipeline_VITIS_LOOP_40_2_fu_74_grp_fu_169_p_opcode),
    .grp_fu_169_p_dout0(grp_fu_169_p2),
    .grp_fu_169_p_ce(grp_test_jacobi_4096_Pipeline_VITIS_LOOP_40_2_fu_74_grp_fu_169_p_ce),
    .grp_fu_173_p_din0(grp_test_jacobi_4096_Pipeline_VITIS_LOOP_40_2_fu_74_grp_fu_173_p_din0),
    .grp_fu_173_p_din1(grp_test_jacobi_4096_Pipeline_VITIS_LOOP_40_2_fu_74_grp_fu_173_p_din1),
    .grp_fu_173_p_dout0(grp_fu_173_p2),
    .grp_fu_173_p_ce(grp_test_jacobi_4096_Pipeline_VITIS_LOOP_40_2_fu_74_grp_fu_173_p_ce),
    .grp_fu_177_p_din0(grp_test_jacobi_4096_Pipeline_VITIS_LOOP_40_2_fu_74_grp_fu_177_p_din0),
    .grp_fu_177_p_din1(grp_test_jacobi_4096_Pipeline_VITIS_LOOP_40_2_fu_74_grp_fu_177_p_din1),
    .grp_fu_177_p_dout0(grp_fu_177_p2),
    .grp_fu_177_p_ce(grp_test_jacobi_4096_Pipeline_VITIS_LOOP_40_2_fu_74_grp_fu_177_p_ce)
);

test_jacobi_4096_test_jacobi_4096_Pipeline_VITIS_LOOP_55_3 grp_test_jacobi_4096_Pipeline_VITIS_LOOP_55_3_fu_95(
    .ap_clk(ap_clk),
    .ap_rst(ap_rst_n_inv),
    .ap_start(grp_test_jacobi_4096_Pipeline_VITIS_LOOP_55_3_fu_95_ap_start),
    .ap_done(grp_test_jacobi_4096_Pipeline_VITIS_LOOP_55_3_fu_95_ap_done),
    .ap_idle(grp_test_jacobi_4096_Pipeline_VITIS_LOOP_55_3_fu_95_ap_idle),
    .ap_ready(grp_test_jacobi_4096_Pipeline_VITIS_LOOP_55_3_fu_95_ap_ready),
    .v2_0_Addr_A(grp_test_jacobi_4096_Pipeline_VITIS_LOOP_55_3_fu_95_v2_0_Addr_A),
    .v2_0_EN_A(grp_test_jacobi_4096_Pipeline_VITIS_LOOP_55_3_fu_95_v2_0_EN_A),
    .v2_0_WEN_A(grp_test_jacobi_4096_Pipeline_VITIS_LOOP_55_3_fu_95_v2_0_WEN_A),
    .v2_0_Din_A(grp_test_jacobi_4096_Pipeline_VITIS_LOOP_55_3_fu_95_v2_0_Din_A),
    .v2_0_Dout_A(32'd0),
    .v1_1_Addr_A(grp_test_jacobi_4096_Pipeline_VITIS_LOOP_55_3_fu_95_v1_1_Addr_A),
    .v1_1_EN_A(grp_test_jacobi_4096_Pipeline_VITIS_LOOP_55_3_fu_95_v1_1_EN_A),
    .v1_1_WEN_A(grp_test_jacobi_4096_Pipeline_VITIS_LOOP_55_3_fu_95_v1_1_WEN_A),
    .v1_1_Din_A(grp_test_jacobi_4096_Pipeline_VITIS_LOOP_55_3_fu_95_v1_1_Din_A),
    .v1_1_Dout_A(v1_1_Dout_A),
    .v1_1_Addr_B(grp_test_jacobi_4096_Pipeline_VITIS_LOOP_55_3_fu_95_v1_1_Addr_B),
    .v1_1_EN_B(grp_test_jacobi_4096_Pipeline_VITIS_LOOP_55_3_fu_95_v1_1_EN_B),
    .v1_1_WEN_B(grp_test_jacobi_4096_Pipeline_VITIS_LOOP_55_3_fu_95_v1_1_WEN_B),
    .v1_1_Din_B(grp_test_jacobi_4096_Pipeline_VITIS_LOOP_55_3_fu_95_v1_1_Din_B),
    .v1_1_Dout_B(v1_1_Dout_B),
    .v1_3_Addr_A(grp_test_jacobi_4096_Pipeline_VITIS_LOOP_55_3_fu_95_v1_3_Addr_A),
    .v1_3_EN_A(grp_test_jacobi_4096_Pipeline_VITIS_LOOP_55_3_fu_95_v1_3_EN_A),
    .v1_3_WEN_A(grp_test_jacobi_4096_Pipeline_VITIS_LOOP_55_3_fu_95_v1_3_WEN_A),
    .v1_3_Din_A(grp_test_jacobi_4096_Pipeline_VITIS_LOOP_55_3_fu_95_v1_3_Din_A),
    .v1_3_Dout_A(v1_3_Dout_A),
    .v1_3_Addr_B(grp_test_jacobi_4096_Pipeline_VITIS_LOOP_55_3_fu_95_v1_3_Addr_B),
    .v1_3_EN_B(grp_test_jacobi_4096_Pipeline_VITIS_LOOP_55_3_fu_95_v1_3_EN_B),
    .v1_3_WEN_B(grp_test_jacobi_4096_Pipeline_VITIS_LOOP_55_3_fu_95_v1_3_WEN_B),
    .v1_3_Din_B(grp_test_jacobi_4096_Pipeline_VITIS_LOOP_55_3_fu_95_v1_3_Din_B),
    .v1_3_Dout_B(v1_3_Dout_B),
    .v0(v0_read_reg_148),
    .v2_1_Addr_A(grp_test_jacobi_4096_Pipeline_VITIS_LOOP_55_3_fu_95_v2_1_Addr_A),
    .v2_1_EN_A(grp_test_jacobi_4096_Pipeline_VITIS_LOOP_55_3_fu_95_v2_1_EN_A),
    .v2_1_WEN_A(grp_test_jacobi_4096_Pipeline_VITIS_LOOP_55_3_fu_95_v2_1_WEN_A),
    .v2_1_Din_A(grp_test_jacobi_4096_Pipeline_VITIS_LOOP_55_3_fu_95_v2_1_Din_A),
    .v2_1_Dout_A(32'd0),
    .v2_3_Addr_A(grp_test_jacobi_4096_Pipeline_VITIS_LOOP_55_3_fu_95_v2_3_Addr_A),
    .v2_3_EN_A(grp_test_jacobi_4096_Pipeline_VITIS_LOOP_55_3_fu_95_v2_3_EN_A),
    .v2_3_WEN_A(grp_test_jacobi_4096_Pipeline_VITIS_LOOP_55_3_fu_95_v2_3_WEN_A),
    .v2_3_Din_A(grp_test_jacobi_4096_Pipeline_VITIS_LOOP_55_3_fu_95_v2_3_Din_A),
    .v2_3_Dout_A(32'd0),
    .v2_2_Addr_A(grp_test_jacobi_4096_Pipeline_VITIS_LOOP_55_3_fu_95_v2_2_Addr_A),
    .v2_2_EN_A(grp_test_jacobi_4096_Pipeline_VITIS_LOOP_55_3_fu_95_v2_2_EN_A),
    .v2_2_WEN_A(grp_test_jacobi_4096_Pipeline_VITIS_LOOP_55_3_fu_95_v2_2_WEN_A),
    .v2_2_Din_A(grp_test_jacobi_4096_Pipeline_VITIS_LOOP_55_3_fu_95_v2_2_Din_A),
    .v2_2_Dout_A(32'd0),
    .v1_0_Addr_A(grp_test_jacobi_4096_Pipeline_VITIS_LOOP_55_3_fu_95_v1_0_Addr_A),
    .v1_0_EN_A(grp_test_jacobi_4096_Pipeline_VITIS_LOOP_55_3_fu_95_v1_0_EN_A),
    .v1_0_WEN_A(grp_test_jacobi_4096_Pipeline_VITIS_LOOP_55_3_fu_95_v1_0_WEN_A),
    .v1_0_Din_A(grp_test_jacobi_4096_Pipeline_VITIS_LOOP_55_3_fu_95_v1_0_Din_A),
    .v1_0_Dout_A(v1_0_Dout_A),
    .v1_0_Addr_B(grp_test_jacobi_4096_Pipeline_VITIS_LOOP_55_3_fu_95_v1_0_Addr_B),
    .v1_0_EN_B(grp_test_jacobi_4096_Pipeline_VITIS_LOOP_55_3_fu_95_v1_0_EN_B),
    .v1_0_WEN_B(grp_test_jacobi_4096_Pipeline_VITIS_LOOP_55_3_fu_95_v1_0_WEN_B),
    .v1_0_Din_B(grp_test_jacobi_4096_Pipeline_VITIS_LOOP_55_3_fu_95_v1_0_Din_B),
    .v1_0_Dout_B(v1_0_Dout_B),
    .v1_2_Addr_A(grp_test_jacobi_4096_Pipeline_VITIS_LOOP_55_3_fu_95_v1_2_Addr_A),
    .v1_2_EN_A(grp_test_jacobi_4096_Pipeline_VITIS_LOOP_55_3_fu_95_v1_2_EN_A),
    .v1_2_WEN_A(grp_test_jacobi_4096_Pipeline_VITIS_LOOP_55_3_fu_95_v1_2_WEN_A),
    .v1_2_Din_A(grp_test_jacobi_4096_Pipeline_VITIS_LOOP_55_3_fu_95_v1_2_Din_A),
    .v1_2_Dout_A(v1_2_Dout_A),
    .v1_2_Addr_B(grp_test_jacobi_4096_Pipeline_VITIS_LOOP_55_3_fu_95_v1_2_Addr_B),
    .v1_2_EN_B(grp_test_jacobi_4096_Pipeline_VITIS_LOOP_55_3_fu_95_v1_2_EN_B),
    .v1_2_WEN_B(grp_test_jacobi_4096_Pipeline_VITIS_LOOP_55_3_fu_95_v1_2_WEN_B),
    .v1_2_Din_B(grp_test_jacobi_4096_Pipeline_VITIS_LOOP_55_3_fu_95_v1_2_Din_B),
    .v1_2_Dout_B(v1_2_Dout_B),
    .grp_fu_157_p_din0(grp_test_jacobi_4096_Pipeline_VITIS_LOOP_55_3_fu_95_grp_fu_157_p_din0),
    .grp_fu_157_p_din1(grp_test_jacobi_4096_Pipeline_VITIS_LOOP_55_3_fu_95_grp_fu_157_p_din1),
    .grp_fu_157_p_opcode(grp_test_jacobi_4096_Pipeline_VITIS_LOOP_55_3_fu_95_grp_fu_157_p_opcode),
    .grp_fu_157_p_dout0(grp_fu_157_p2),
    .grp_fu_157_p_ce(grp_test_jacobi_4096_Pipeline_VITIS_LOOP_55_3_fu_95_grp_fu_157_p_ce),
    .grp_fu_161_p_din0(grp_test_jacobi_4096_Pipeline_VITIS_LOOP_55_3_fu_95_grp_fu_161_p_din0),
    .grp_fu_161_p_din1(grp_test_jacobi_4096_Pipeline_VITIS_LOOP_55_3_fu_95_grp_fu_161_p_din1),
    .grp_fu_161_p_opcode(grp_test_jacobi_4096_Pipeline_VITIS_LOOP_55_3_fu_95_grp_fu_161_p_opcode),
    .grp_fu_161_p_dout0(grp_fu_161_p2),
    .grp_fu_161_p_ce(grp_test_jacobi_4096_Pipeline_VITIS_LOOP_55_3_fu_95_grp_fu_161_p_ce),
    .grp_fu_165_p_din0(grp_test_jacobi_4096_Pipeline_VITIS_LOOP_55_3_fu_95_grp_fu_165_p_din0),
    .grp_fu_165_p_din1(grp_test_jacobi_4096_Pipeline_VITIS_LOOP_55_3_fu_95_grp_fu_165_p_din1),
    .grp_fu_165_p_opcode(grp_test_jacobi_4096_Pipeline_VITIS_LOOP_55_3_fu_95_grp_fu_165_p_opcode),
    .grp_fu_165_p_dout0(grp_fu_165_p2),
    .grp_fu_165_p_ce(grp_test_jacobi_4096_Pipeline_VITIS_LOOP_55_3_fu_95_grp_fu_165_p_ce),
    .grp_fu_169_p_din0(grp_test_jacobi_4096_Pipeline_VITIS_LOOP_55_3_fu_95_grp_fu_169_p_din0),
    .grp_fu_169_p_din1(grp_test_jacobi_4096_Pipeline_VITIS_LOOP_55_3_fu_95_grp_fu_169_p_din1),
    .grp_fu_169_p_opcode(grp_test_jacobi_4096_Pipeline_VITIS_LOOP_55_3_fu_95_grp_fu_169_p_opcode),
    .grp_fu_169_p_dout0(grp_fu_169_p2),
    .grp_fu_169_p_ce(grp_test_jacobi_4096_Pipeline_VITIS_LOOP_55_3_fu_95_grp_fu_169_p_ce),
    .grp_fu_173_p_din0(grp_test_jacobi_4096_Pipeline_VITIS_LOOP_55_3_fu_95_grp_fu_173_p_din0),
    .grp_fu_173_p_din1(grp_test_jacobi_4096_Pipeline_VITIS_LOOP_55_3_fu_95_grp_fu_173_p_din1),
    .grp_fu_173_p_dout0(grp_fu_173_p2),
    .grp_fu_173_p_ce(grp_test_jacobi_4096_Pipeline_VITIS_LOOP_55_3_fu_95_grp_fu_173_p_ce),
    .grp_fu_177_p_din0(grp_test_jacobi_4096_Pipeline_VITIS_LOOP_55_3_fu_95_grp_fu_177_p_din0),
    .grp_fu_177_p_din1(grp_test_jacobi_4096_Pipeline_VITIS_LOOP_55_3_fu_95_grp_fu_177_p_din1),
    .grp_fu_177_p_dout0(grp_fu_177_p2),
    .grp_fu_177_p_ce(grp_test_jacobi_4096_Pipeline_VITIS_LOOP_55_3_fu_95_grp_fu_177_p_ce)
);

test_jacobi_4096_ctrl_s_axi #(
    .C_S_AXI_ADDR_WIDTH( C_S_AXI_CTRL_ADDR_WIDTH ),
    .C_S_AXI_DATA_WIDTH( C_S_AXI_CTRL_DATA_WIDTH ))
ctrl_s_axi_U(
    .AWVALID(s_axi_ctrl_AWVALID),
    .AWREADY(s_axi_ctrl_AWREADY),
    .AWADDR(s_axi_ctrl_AWADDR),
    .WVALID(s_axi_ctrl_WVALID),
    .WREADY(s_axi_ctrl_WREADY),
    .WDATA(s_axi_ctrl_WDATA),
    .WSTRB(s_axi_ctrl_WSTRB),
    .ARVALID(s_axi_ctrl_ARVALID),
    .ARREADY(s_axi_ctrl_ARREADY),
    .ARADDR(s_axi_ctrl_ARADDR),
    .RVALID(s_axi_ctrl_RVALID),
    .RREADY(s_axi_ctrl_RREADY),
    .RDATA(s_axi_ctrl_RDATA),
    .RRESP(s_axi_ctrl_RRESP),
    .BVALID(s_axi_ctrl_BVALID),
    .BREADY(s_axi_ctrl_BREADY),
    .BRESP(s_axi_ctrl_BRESP),
    .ACLK(ap_clk),
    .ARESET(ap_rst_n_inv),
    .ACLK_EN(1'b1),
    .v0(v0),
    .ap_start(ap_start),
    .interrupt(interrupt),
    .ap_ready(ap_ready),
    .ap_done(ap_done),
    .ap_idle(ap_idle)
);

test_jacobi_4096_fadd_32ns_32ns_32_7_full_dsp_1 #(
    .ID( 1 ),
    .NUM_STAGE( 7 ),
    .din0_WIDTH( 32 ),
    .din1_WIDTH( 32 ),
    .dout_WIDTH( 32 ))
fadd_32ns_32ns_32_7_full_dsp_1_U24(
    .clk(ap_clk),
    .reset(ap_rst_n_inv),
    .din0(grp_fu_157_p0),
    .din1(grp_fu_157_p1),
    .ce(grp_fu_157_ce),
    .dout(grp_fu_157_p2)
);

test_jacobi_4096_fadd_32ns_32ns_32_7_full_dsp_1 #(
    .ID( 1 ),
    .NUM_STAGE( 7 ),
    .din0_WIDTH( 32 ),
    .din1_WIDTH( 32 ),
    .dout_WIDTH( 32 ))
fadd_32ns_32ns_32_7_full_dsp_1_U25(
    .clk(ap_clk),
    .reset(ap_rst_n_inv),
    .din0(grp_fu_161_p0),
    .din1(grp_fu_161_p1),
    .ce(grp_fu_161_ce),
    .dout(grp_fu_161_p2)
);

test_jacobi_4096_fadd_32ns_32ns_32_7_full_dsp_1 #(
    .ID( 1 ),
    .NUM_STAGE( 7 ),
    .din0_WIDTH( 32 ),
    .din1_WIDTH( 32 ),
    .dout_WIDTH( 32 ))
fadd_32ns_32ns_32_7_full_dsp_1_U26(
    .clk(ap_clk),
    .reset(ap_rst_n_inv),
    .din0(grp_fu_165_p0),
    .din1(grp_fu_165_p1),
    .ce(grp_fu_165_ce),
    .dout(grp_fu_165_p2)
);

test_jacobi_4096_fadd_32ns_32ns_32_7_full_dsp_1 #(
    .ID( 1 ),
    .NUM_STAGE( 7 ),
    .din0_WIDTH( 32 ),
    .din1_WIDTH( 32 ),
    .dout_WIDTH( 32 ))
fadd_32ns_32ns_32_7_full_dsp_1_U27(
    .clk(ap_clk),
    .reset(ap_rst_n_inv),
    .din0(grp_fu_169_p0),
    .din1(grp_fu_169_p1),
    .ce(grp_fu_169_ce),
    .dout(grp_fu_169_p2)
);

test_jacobi_4096_fmul_32ns_32ns_32_4_max_dsp_1 #(
    .ID( 1 ),
    .NUM_STAGE( 4 ),
    .din0_WIDTH( 32 ),
    .din1_WIDTH( 32 ),
    .dout_WIDTH( 32 ))
fmul_32ns_32ns_32_4_max_dsp_1_U28(
    .clk(ap_clk),
    .reset(ap_rst_n_inv),
    .din0(grp_fu_173_p0),
    .din1(grp_fu_173_p1),
    .ce(grp_fu_173_ce),
    .dout(grp_fu_173_p2)
);

test_jacobi_4096_fmul_32ns_32ns_32_4_max_dsp_1 #(
    .ID( 1 ),
    .NUM_STAGE( 4 ),
    .din0_WIDTH( 32 ),
    .din1_WIDTH( 32 ),
    .dout_WIDTH( 32 ))
fmul_32ns_32ns_32_4_max_dsp_1_U29(
    .clk(ap_clk),
    .reset(ap_rst_n_inv),
    .din0(grp_fu_177_p0),
    .din1(grp_fu_177_p1),
    .ce(grp_fu_177_ce),
    .dout(grp_fu_177_p2)
);

always @ (posedge ap_clk) begin
    if (ap_rst_n_inv == 1'b1) begin
        ap_CS_fsm <= ap_ST_fsm_state1;
    end else begin
        ap_CS_fsm <= ap_NS_fsm;
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst_n_inv == 1'b1) begin
        grp_test_jacobi_4096_Pipeline_VITIS_LOOP_40_2_fu_74_ap_start_reg <= 1'b0;
    end else begin
        if (((icmp_ln39_fu_124_p2 == 1'd0) & (1'b1 == ap_CS_fsm_state2))) begin
            grp_test_jacobi_4096_Pipeline_VITIS_LOOP_40_2_fu_74_ap_start_reg <= 1'b1;
        end else if ((grp_test_jacobi_4096_Pipeline_VITIS_LOOP_40_2_fu_74_ap_ready == 1'b1)) begin
            grp_test_jacobi_4096_Pipeline_VITIS_LOOP_40_2_fu_74_ap_start_reg <= 1'b0;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst_n_inv == 1'b1) begin
        grp_test_jacobi_4096_Pipeline_VITIS_LOOP_55_3_fu_95_ap_start_reg <= 1'b0;
    end else begin
        if ((1'b1 == ap_CS_fsm_state4)) begin
            grp_test_jacobi_4096_Pipeline_VITIS_LOOP_55_3_fu_95_ap_start_reg <= 1'b1;
        end else if ((grp_test_jacobi_4096_Pipeline_VITIS_LOOP_55_3_fu_95_ap_ready == 1'b1)) begin
            grp_test_jacobi_4096_Pipeline_VITIS_LOOP_55_3_fu_95_ap_start_reg <= 1'b0;
        end
    end
end

always @ (posedge ap_clk) begin
    if (((1'b1 == ap_CS_fsm_state1) & (ap_start == 1'b1))) begin
        v3_fu_64 <= 13'd0;
    end else if (((icmp_ln39_fu_124_p2 == 1'd0) & (1'b1 == ap_CS_fsm_state2))) begin
        v3_fu_64 <= v3_2_fu_130_p2;
    end
end

always @ (posedge ap_clk) begin
    if ((1'b1 == ap_CS_fsm_state1)) begin
        v0_read_reg_148 <= v0;
    end
end

always @ (*) begin
    if ((ap_start == 1'b0)) begin
        ap_ST_fsm_state1_blk = 1'b1;
    end else begin
        ap_ST_fsm_state1_blk = 1'b0;
    end
end

assign ap_ST_fsm_state2_blk = 1'b0;

always @ (*) begin
    if ((grp_test_jacobi_4096_Pipeline_VITIS_LOOP_40_2_fu_74_ap_done == 1'b0)) begin
        ap_ST_fsm_state3_blk = 1'b1;
    end else begin
        ap_ST_fsm_state3_blk = 1'b0;
    end
end

assign ap_ST_fsm_state4_blk = 1'b0;

always @ (*) begin
    if ((grp_test_jacobi_4096_Pipeline_VITIS_LOOP_55_3_fu_95_ap_done == 1'b0)) begin
        ap_ST_fsm_state5_blk = 1'b1;
    end else begin
        ap_ST_fsm_state5_blk = 1'b0;
    end
end

always @ (*) begin
    if (((icmp_ln39_fu_124_p2 == 1'd1) & (1'b1 == ap_CS_fsm_state2))) begin
        ap_done = 1'b1;
    end else begin
        ap_done = 1'b0;
    end
end

always @ (*) begin
    if (((1'b1 == ap_CS_fsm_state1) & (ap_start == 1'b0))) begin
        ap_idle = 1'b1;
    end else begin
        ap_idle = 1'b0;
    end
end

always @ (*) begin
    if (((icmp_ln39_fu_124_p2 == 1'd1) & (1'b1 == ap_CS_fsm_state2))) begin
        ap_ready = 1'b1;
    end else begin
        ap_ready = 1'b0;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state5)) begin
        grp_fu_157_ce = grp_test_jacobi_4096_Pipeline_VITIS_LOOP_55_3_fu_95_grp_fu_157_p_ce;
    end else if ((1'b1 == ap_CS_fsm_state3)) begin
        grp_fu_157_ce = grp_test_jacobi_4096_Pipeline_VITIS_LOOP_40_2_fu_74_grp_fu_157_p_ce;
    end else begin
        grp_fu_157_ce = 1'b1;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state5)) begin
        grp_fu_157_p0 = grp_test_jacobi_4096_Pipeline_VITIS_LOOP_55_3_fu_95_grp_fu_157_p_din0;
    end else if ((1'b1 == ap_CS_fsm_state3)) begin
        grp_fu_157_p0 = grp_test_jacobi_4096_Pipeline_VITIS_LOOP_40_2_fu_74_grp_fu_157_p_din0;
    end else begin
        grp_fu_157_p0 = 'bx;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state5)) begin
        grp_fu_157_p1 = grp_test_jacobi_4096_Pipeline_VITIS_LOOP_55_3_fu_95_grp_fu_157_p_din1;
    end else if ((1'b1 == ap_CS_fsm_state3)) begin
        grp_fu_157_p1 = grp_test_jacobi_4096_Pipeline_VITIS_LOOP_40_2_fu_74_grp_fu_157_p_din1;
    end else begin
        grp_fu_157_p1 = 'bx;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state5)) begin
        grp_fu_161_ce = grp_test_jacobi_4096_Pipeline_VITIS_LOOP_55_3_fu_95_grp_fu_161_p_ce;
    end else if ((1'b1 == ap_CS_fsm_state3)) begin
        grp_fu_161_ce = grp_test_jacobi_4096_Pipeline_VITIS_LOOP_40_2_fu_74_grp_fu_161_p_ce;
    end else begin
        grp_fu_161_ce = 1'b1;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state5)) begin
        grp_fu_161_p0 = grp_test_jacobi_4096_Pipeline_VITIS_LOOP_55_3_fu_95_grp_fu_161_p_din0;
    end else if ((1'b1 == ap_CS_fsm_state3)) begin
        grp_fu_161_p0 = grp_test_jacobi_4096_Pipeline_VITIS_LOOP_40_2_fu_74_grp_fu_161_p_din0;
    end else begin
        grp_fu_161_p0 = 'bx;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state5)) begin
        grp_fu_161_p1 = grp_test_jacobi_4096_Pipeline_VITIS_LOOP_55_3_fu_95_grp_fu_161_p_din1;
    end else if ((1'b1 == ap_CS_fsm_state3)) begin
        grp_fu_161_p1 = grp_test_jacobi_4096_Pipeline_VITIS_LOOP_40_2_fu_74_grp_fu_161_p_din1;
    end else begin
        grp_fu_161_p1 = 'bx;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state5)) begin
        grp_fu_165_ce = grp_test_jacobi_4096_Pipeline_VITIS_LOOP_55_3_fu_95_grp_fu_165_p_ce;
    end else if ((1'b1 == ap_CS_fsm_state3)) begin
        grp_fu_165_ce = grp_test_jacobi_4096_Pipeline_VITIS_LOOP_40_2_fu_74_grp_fu_165_p_ce;
    end else begin
        grp_fu_165_ce = 1'b1;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state5)) begin
        grp_fu_165_p0 = grp_test_jacobi_4096_Pipeline_VITIS_LOOP_55_3_fu_95_grp_fu_165_p_din0;
    end else if ((1'b1 == ap_CS_fsm_state3)) begin
        grp_fu_165_p0 = grp_test_jacobi_4096_Pipeline_VITIS_LOOP_40_2_fu_74_grp_fu_165_p_din0;
    end else begin
        grp_fu_165_p0 = 'bx;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state5)) begin
        grp_fu_165_p1 = grp_test_jacobi_4096_Pipeline_VITIS_LOOP_55_3_fu_95_grp_fu_165_p_din1;
    end else if ((1'b1 == ap_CS_fsm_state3)) begin
        grp_fu_165_p1 = grp_test_jacobi_4096_Pipeline_VITIS_LOOP_40_2_fu_74_grp_fu_165_p_din1;
    end else begin
        grp_fu_165_p1 = 'bx;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state5)) begin
        grp_fu_169_ce = grp_test_jacobi_4096_Pipeline_VITIS_LOOP_55_3_fu_95_grp_fu_169_p_ce;
    end else if ((1'b1 == ap_CS_fsm_state3)) begin
        grp_fu_169_ce = grp_test_jacobi_4096_Pipeline_VITIS_LOOP_40_2_fu_74_grp_fu_169_p_ce;
    end else begin
        grp_fu_169_ce = 1'b1;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state5)) begin
        grp_fu_169_p0 = grp_test_jacobi_4096_Pipeline_VITIS_LOOP_55_3_fu_95_grp_fu_169_p_din0;
    end else if ((1'b1 == ap_CS_fsm_state3)) begin
        grp_fu_169_p0 = grp_test_jacobi_4096_Pipeline_VITIS_LOOP_40_2_fu_74_grp_fu_169_p_din0;
    end else begin
        grp_fu_169_p0 = 'bx;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state5)) begin
        grp_fu_169_p1 = grp_test_jacobi_4096_Pipeline_VITIS_LOOP_55_3_fu_95_grp_fu_169_p_din1;
    end else if ((1'b1 == ap_CS_fsm_state3)) begin
        grp_fu_169_p1 = grp_test_jacobi_4096_Pipeline_VITIS_LOOP_40_2_fu_74_grp_fu_169_p_din1;
    end else begin
        grp_fu_169_p1 = 'bx;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state5)) begin
        grp_fu_173_ce = grp_test_jacobi_4096_Pipeline_VITIS_LOOP_55_3_fu_95_grp_fu_173_p_ce;
    end else if ((1'b1 == ap_CS_fsm_state3)) begin
        grp_fu_173_ce = grp_test_jacobi_4096_Pipeline_VITIS_LOOP_40_2_fu_74_grp_fu_173_p_ce;
    end else begin
        grp_fu_173_ce = 1'b1;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state5)) begin
        grp_fu_173_p0 = grp_test_jacobi_4096_Pipeline_VITIS_LOOP_55_3_fu_95_grp_fu_173_p_din0;
    end else if ((1'b1 == ap_CS_fsm_state3)) begin
        grp_fu_173_p0 = grp_test_jacobi_4096_Pipeline_VITIS_LOOP_40_2_fu_74_grp_fu_173_p_din0;
    end else begin
        grp_fu_173_p0 = 'bx;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state5)) begin
        grp_fu_173_p1 = grp_test_jacobi_4096_Pipeline_VITIS_LOOP_55_3_fu_95_grp_fu_173_p_din1;
    end else if ((1'b1 == ap_CS_fsm_state3)) begin
        grp_fu_173_p1 = grp_test_jacobi_4096_Pipeline_VITIS_LOOP_40_2_fu_74_grp_fu_173_p_din1;
    end else begin
        grp_fu_173_p1 = 'bx;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state5)) begin
        grp_fu_177_ce = grp_test_jacobi_4096_Pipeline_VITIS_LOOP_55_3_fu_95_grp_fu_177_p_ce;
    end else if ((1'b1 == ap_CS_fsm_state3)) begin
        grp_fu_177_ce = grp_test_jacobi_4096_Pipeline_VITIS_LOOP_40_2_fu_74_grp_fu_177_p_ce;
    end else begin
        grp_fu_177_ce = 1'b1;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state5)) begin
        grp_fu_177_p0 = grp_test_jacobi_4096_Pipeline_VITIS_LOOP_55_3_fu_95_grp_fu_177_p_din0;
    end else if ((1'b1 == ap_CS_fsm_state3)) begin
        grp_fu_177_p0 = grp_test_jacobi_4096_Pipeline_VITIS_LOOP_40_2_fu_74_grp_fu_177_p_din0;
    end else begin
        grp_fu_177_p0 = 'bx;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state5)) begin
        grp_fu_177_p1 = grp_test_jacobi_4096_Pipeline_VITIS_LOOP_55_3_fu_95_grp_fu_177_p_din1;
    end else if ((1'b1 == ap_CS_fsm_state3)) begin
        grp_fu_177_p1 = grp_test_jacobi_4096_Pipeline_VITIS_LOOP_40_2_fu_74_grp_fu_177_p_din1;
    end else begin
        grp_fu_177_p1 = 'bx;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state5)) begin
        v1_0_Addr_A = grp_test_jacobi_4096_Pipeline_VITIS_LOOP_55_3_fu_95_v1_0_Addr_A;
    end else if ((1'b1 == ap_CS_fsm_state3)) begin
        v1_0_Addr_A = grp_test_jacobi_4096_Pipeline_VITIS_LOOP_40_2_fu_74_v1_0_Addr_A;
    end else begin
        v1_0_Addr_A = 'bx;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state5)) begin
        v1_0_EN_A = grp_test_jacobi_4096_Pipeline_VITIS_LOOP_55_3_fu_95_v1_0_EN_A;
    end else if ((1'b1 == ap_CS_fsm_state3)) begin
        v1_0_EN_A = grp_test_jacobi_4096_Pipeline_VITIS_LOOP_40_2_fu_74_v1_0_EN_A;
    end else begin
        v1_0_EN_A = 1'b0;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state5)) begin
        v1_0_EN_B = grp_test_jacobi_4096_Pipeline_VITIS_LOOP_55_3_fu_95_v1_0_EN_B;
    end else begin
        v1_0_EN_B = 1'b0;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state3)) begin
        v1_0_WEN_A = grp_test_jacobi_4096_Pipeline_VITIS_LOOP_40_2_fu_74_v1_0_WEN_A;
    end else begin
        v1_0_WEN_A = 1'b0;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state5)) begin
        v1_1_Addr_A = grp_test_jacobi_4096_Pipeline_VITIS_LOOP_55_3_fu_95_v1_1_Addr_A;
    end else if ((1'b1 == ap_CS_fsm_state3)) begin
        v1_1_Addr_A = grp_test_jacobi_4096_Pipeline_VITIS_LOOP_40_2_fu_74_v1_1_Addr_A;
    end else begin
        v1_1_Addr_A = 'bx;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state5)) begin
        v1_1_EN_A = grp_test_jacobi_4096_Pipeline_VITIS_LOOP_55_3_fu_95_v1_1_EN_A;
    end else if ((1'b1 == ap_CS_fsm_state3)) begin
        v1_1_EN_A = grp_test_jacobi_4096_Pipeline_VITIS_LOOP_40_2_fu_74_v1_1_EN_A;
    end else begin
        v1_1_EN_A = 1'b0;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state5)) begin
        v1_1_EN_B = grp_test_jacobi_4096_Pipeline_VITIS_LOOP_55_3_fu_95_v1_1_EN_B;
    end else begin
        v1_1_EN_B = 1'b0;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state3)) begin
        v1_1_WEN_A = grp_test_jacobi_4096_Pipeline_VITIS_LOOP_40_2_fu_74_v1_1_WEN_A;
    end else begin
        v1_1_WEN_A = 1'b0;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state5)) begin
        v1_2_Addr_A = grp_test_jacobi_4096_Pipeline_VITIS_LOOP_55_3_fu_95_v1_2_Addr_A;
    end else if ((1'b1 == ap_CS_fsm_state3)) begin
        v1_2_Addr_A = grp_test_jacobi_4096_Pipeline_VITIS_LOOP_40_2_fu_74_v1_2_Addr_A;
    end else begin
        v1_2_Addr_A = 'bx;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state5)) begin
        v1_2_EN_A = grp_test_jacobi_4096_Pipeline_VITIS_LOOP_55_3_fu_95_v1_2_EN_A;
    end else if ((1'b1 == ap_CS_fsm_state3)) begin
        v1_2_EN_A = grp_test_jacobi_4096_Pipeline_VITIS_LOOP_40_2_fu_74_v1_2_EN_A;
    end else begin
        v1_2_EN_A = 1'b0;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state5)) begin
        v1_2_EN_B = grp_test_jacobi_4096_Pipeline_VITIS_LOOP_55_3_fu_95_v1_2_EN_B;
    end else begin
        v1_2_EN_B = 1'b0;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state3)) begin
        v1_2_WEN_A = grp_test_jacobi_4096_Pipeline_VITIS_LOOP_40_2_fu_74_v1_2_WEN_A;
    end else begin
        v1_2_WEN_A = 1'b0;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state5)) begin
        v1_3_Addr_A = grp_test_jacobi_4096_Pipeline_VITIS_LOOP_55_3_fu_95_v1_3_Addr_A;
    end else if ((1'b1 == ap_CS_fsm_state3)) begin
        v1_3_Addr_A = grp_test_jacobi_4096_Pipeline_VITIS_LOOP_40_2_fu_74_v1_3_Addr_A;
    end else begin
        v1_3_Addr_A = 'bx;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state5)) begin
        v1_3_EN_A = grp_test_jacobi_4096_Pipeline_VITIS_LOOP_55_3_fu_95_v1_3_EN_A;
    end else if ((1'b1 == ap_CS_fsm_state3)) begin
        v1_3_EN_A = grp_test_jacobi_4096_Pipeline_VITIS_LOOP_40_2_fu_74_v1_3_EN_A;
    end else begin
        v1_3_EN_A = 1'b0;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state5)) begin
        v1_3_EN_B = grp_test_jacobi_4096_Pipeline_VITIS_LOOP_55_3_fu_95_v1_3_EN_B;
    end else begin
        v1_3_EN_B = 1'b0;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state3)) begin
        v1_3_WEN_A = grp_test_jacobi_4096_Pipeline_VITIS_LOOP_40_2_fu_74_v1_3_WEN_A;
    end else begin
        v1_3_WEN_A = 1'b0;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state5)) begin
        v2_0_Addr_A = grp_test_jacobi_4096_Pipeline_VITIS_LOOP_55_3_fu_95_v2_0_Addr_A;
    end else if ((1'b1 == ap_CS_fsm_state3)) begin
        v2_0_Addr_A = grp_test_jacobi_4096_Pipeline_VITIS_LOOP_40_2_fu_74_v2_0_Addr_A;
    end else begin
        v2_0_Addr_A = 'bx;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state5)) begin
        v2_0_EN_A = grp_test_jacobi_4096_Pipeline_VITIS_LOOP_55_3_fu_95_v2_0_EN_A;
    end else if ((1'b1 == ap_CS_fsm_state3)) begin
        v2_0_EN_A = grp_test_jacobi_4096_Pipeline_VITIS_LOOP_40_2_fu_74_v2_0_EN_A;
    end else begin
        v2_0_EN_A = 1'b0;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state3)) begin
        v2_0_EN_B = grp_test_jacobi_4096_Pipeline_VITIS_LOOP_40_2_fu_74_v2_0_EN_B;
    end else begin
        v2_0_EN_B = 1'b0;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state5)) begin
        v2_0_WEN_A = grp_test_jacobi_4096_Pipeline_VITIS_LOOP_55_3_fu_95_v2_0_WEN_A;
    end else begin
        v2_0_WEN_A = 1'b0;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state5)) begin
        v2_1_Addr_A = grp_test_jacobi_4096_Pipeline_VITIS_LOOP_55_3_fu_95_v2_1_Addr_A;
    end else if ((1'b1 == ap_CS_fsm_state3)) begin
        v2_1_Addr_A = grp_test_jacobi_4096_Pipeline_VITIS_LOOP_40_2_fu_74_v2_1_Addr_A;
    end else begin
        v2_1_Addr_A = 'bx;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state5)) begin
        v2_1_EN_A = grp_test_jacobi_4096_Pipeline_VITIS_LOOP_55_3_fu_95_v2_1_EN_A;
    end else if ((1'b1 == ap_CS_fsm_state3)) begin
        v2_1_EN_A = grp_test_jacobi_4096_Pipeline_VITIS_LOOP_40_2_fu_74_v2_1_EN_A;
    end else begin
        v2_1_EN_A = 1'b0;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state3)) begin
        v2_1_EN_B = grp_test_jacobi_4096_Pipeline_VITIS_LOOP_40_2_fu_74_v2_1_EN_B;
    end else begin
        v2_1_EN_B = 1'b0;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state5)) begin
        v2_1_WEN_A = grp_test_jacobi_4096_Pipeline_VITIS_LOOP_55_3_fu_95_v2_1_WEN_A;
    end else begin
        v2_1_WEN_A = 1'b0;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state5)) begin
        v2_2_Addr_A = grp_test_jacobi_4096_Pipeline_VITIS_LOOP_55_3_fu_95_v2_2_Addr_A;
    end else if ((1'b1 == ap_CS_fsm_state3)) begin
        v2_2_Addr_A = grp_test_jacobi_4096_Pipeline_VITIS_LOOP_40_2_fu_74_v2_2_Addr_A;
    end else begin
        v2_2_Addr_A = 'bx;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state5)) begin
        v2_2_EN_A = grp_test_jacobi_4096_Pipeline_VITIS_LOOP_55_3_fu_95_v2_2_EN_A;
    end else if ((1'b1 == ap_CS_fsm_state3)) begin
        v2_2_EN_A = grp_test_jacobi_4096_Pipeline_VITIS_LOOP_40_2_fu_74_v2_2_EN_A;
    end else begin
        v2_2_EN_A = 1'b0;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state3)) begin
        v2_2_EN_B = grp_test_jacobi_4096_Pipeline_VITIS_LOOP_40_2_fu_74_v2_2_EN_B;
    end else begin
        v2_2_EN_B = 1'b0;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state5)) begin
        v2_2_WEN_A = grp_test_jacobi_4096_Pipeline_VITIS_LOOP_55_3_fu_95_v2_2_WEN_A;
    end else begin
        v2_2_WEN_A = 1'b0;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state5)) begin
        v2_3_Addr_A = grp_test_jacobi_4096_Pipeline_VITIS_LOOP_55_3_fu_95_v2_3_Addr_A;
    end else if ((1'b1 == ap_CS_fsm_state3)) begin
        v2_3_Addr_A = grp_test_jacobi_4096_Pipeline_VITIS_LOOP_40_2_fu_74_v2_3_Addr_A;
    end else begin
        v2_3_Addr_A = 'bx;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state5)) begin
        v2_3_EN_A = grp_test_jacobi_4096_Pipeline_VITIS_LOOP_55_3_fu_95_v2_3_EN_A;
    end else if ((1'b1 == ap_CS_fsm_state3)) begin
        v2_3_EN_A = grp_test_jacobi_4096_Pipeline_VITIS_LOOP_40_2_fu_74_v2_3_EN_A;
    end else begin
        v2_3_EN_A = 1'b0;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state3)) begin
        v2_3_EN_B = grp_test_jacobi_4096_Pipeline_VITIS_LOOP_40_2_fu_74_v2_3_EN_B;
    end else begin
        v2_3_EN_B = 1'b0;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state5)) begin
        v2_3_WEN_A = grp_test_jacobi_4096_Pipeline_VITIS_LOOP_55_3_fu_95_v2_3_WEN_A;
    end else begin
        v2_3_WEN_A = 1'b0;
    end
end

always @ (*) begin
    case (ap_CS_fsm)
        ap_ST_fsm_state1 : begin
            if (((1'b1 == ap_CS_fsm_state1) & (ap_start == 1'b1))) begin
                ap_NS_fsm = ap_ST_fsm_state2;
            end else begin
                ap_NS_fsm = ap_ST_fsm_state1;
            end
        end
        ap_ST_fsm_state2 : begin
            if (((icmp_ln39_fu_124_p2 == 1'd1) & (1'b1 == ap_CS_fsm_state2))) begin
                ap_NS_fsm = ap_ST_fsm_state1;
            end else begin
                ap_NS_fsm = ap_ST_fsm_state3;
            end
        end
        ap_ST_fsm_state3 : begin
            if (((1'b1 == ap_CS_fsm_state3) & (grp_test_jacobi_4096_Pipeline_VITIS_LOOP_40_2_fu_74_ap_done == 1'b1))) begin
                ap_NS_fsm = ap_ST_fsm_state4;
            end else begin
                ap_NS_fsm = ap_ST_fsm_state3;
            end
        end
        ap_ST_fsm_state4 : begin
            ap_NS_fsm = ap_ST_fsm_state5;
        end
        ap_ST_fsm_state5 : begin
            if (((grp_test_jacobi_4096_Pipeline_VITIS_LOOP_55_3_fu_95_ap_done == 1'b1) & (1'b1 == ap_CS_fsm_state5))) begin
                ap_NS_fsm = ap_ST_fsm_state2;
            end else begin
                ap_NS_fsm = ap_ST_fsm_state5;
            end
        end
        default : begin
            ap_NS_fsm = 'bx;
        end
    endcase
end

assign ap_CS_fsm_state1 = ap_CS_fsm[32'd0];

assign ap_CS_fsm_state2 = ap_CS_fsm[32'd1];

assign ap_CS_fsm_state3 = ap_CS_fsm[32'd2];

assign ap_CS_fsm_state4 = ap_CS_fsm[32'd3];

assign ap_CS_fsm_state5 = ap_CS_fsm[32'd4];

always @ (*) begin
    ap_rst_n_inv = ~ap_rst_n;
end

assign grp_test_jacobi_4096_Pipeline_VITIS_LOOP_40_2_fu_74_ap_start = grp_test_jacobi_4096_Pipeline_VITIS_LOOP_40_2_fu_74_ap_start_reg;

assign grp_test_jacobi_4096_Pipeline_VITIS_LOOP_55_3_fu_95_ap_start = grp_test_jacobi_4096_Pipeline_VITIS_LOOP_55_3_fu_95_ap_start_reg;

assign icmp_ln39_fu_124_p2 = ((v3_fu_64 == 13'd4096) ? 1'b1 : 1'b0);

assign v1_0_Addr_B = grp_test_jacobi_4096_Pipeline_VITIS_LOOP_55_3_fu_95_v1_0_Addr_B;

assign v1_0_Clk_A = ap_clk;

assign v1_0_Clk_B = ap_clk;

assign v1_0_Din_A = grp_test_jacobi_4096_Pipeline_VITIS_LOOP_40_2_fu_74_v1_0_Din_A;

assign v1_0_Din_B = 32'd0;

assign v1_0_Rst_A = ap_rst_n_inv;

assign v1_0_Rst_B = ap_rst_n_inv;

assign v1_0_WEN_B = 4'd0;

assign v1_1_Addr_B = grp_test_jacobi_4096_Pipeline_VITIS_LOOP_55_3_fu_95_v1_1_Addr_B;

assign v1_1_Clk_A = ap_clk;

assign v1_1_Clk_B = ap_clk;

assign v1_1_Din_A = grp_test_jacobi_4096_Pipeline_VITIS_LOOP_40_2_fu_74_v1_1_Din_A;

assign v1_1_Din_B = 32'd0;

assign v1_1_Rst_A = ap_rst_n_inv;

assign v1_1_Rst_B = ap_rst_n_inv;

assign v1_1_WEN_B = 4'd0;

assign v1_2_Addr_B = grp_test_jacobi_4096_Pipeline_VITIS_LOOP_55_3_fu_95_v1_2_Addr_B;

assign v1_2_Clk_A = ap_clk;

assign v1_2_Clk_B = ap_clk;

assign v1_2_Din_A = grp_test_jacobi_4096_Pipeline_VITIS_LOOP_40_2_fu_74_v1_2_Din_A;

assign v1_2_Din_B = 32'd0;

assign v1_2_Rst_A = ap_rst_n_inv;

assign v1_2_Rst_B = ap_rst_n_inv;

assign v1_2_WEN_B = 4'd0;

assign v1_3_Addr_B = grp_test_jacobi_4096_Pipeline_VITIS_LOOP_55_3_fu_95_v1_3_Addr_B;

assign v1_3_Clk_A = ap_clk;

assign v1_3_Clk_B = ap_clk;

assign v1_3_Din_A = grp_test_jacobi_4096_Pipeline_VITIS_LOOP_40_2_fu_74_v1_3_Din_A;

assign v1_3_Din_B = 32'd0;

assign v1_3_Rst_A = ap_rst_n_inv;

assign v1_3_Rst_B = ap_rst_n_inv;

assign v1_3_WEN_B = 4'd0;

assign v2_0_Addr_B = grp_test_jacobi_4096_Pipeline_VITIS_LOOP_40_2_fu_74_v2_0_Addr_B;

assign v2_0_Clk_A = ap_clk;

assign v2_0_Clk_B = ap_clk;

assign v2_0_Din_A = grp_test_jacobi_4096_Pipeline_VITIS_LOOP_55_3_fu_95_v2_0_Din_A;

assign v2_0_Din_B = 32'd0;

assign v2_0_Rst_A = ap_rst_n_inv;

assign v2_0_Rst_B = ap_rst_n_inv;

assign v2_0_WEN_B = 4'd0;

assign v2_1_Addr_B = grp_test_jacobi_4096_Pipeline_VITIS_LOOP_40_2_fu_74_v2_1_Addr_B;

assign v2_1_Clk_A = ap_clk;

assign v2_1_Clk_B = ap_clk;

assign v2_1_Din_A = grp_test_jacobi_4096_Pipeline_VITIS_LOOP_55_3_fu_95_v2_1_Din_A;

assign v2_1_Din_B = 32'd0;

assign v2_1_Rst_A = ap_rst_n_inv;

assign v2_1_Rst_B = ap_rst_n_inv;

assign v2_1_WEN_B = 4'd0;

assign v2_2_Addr_B = grp_test_jacobi_4096_Pipeline_VITIS_LOOP_40_2_fu_74_v2_2_Addr_B;

assign v2_2_Clk_A = ap_clk;

assign v2_2_Clk_B = ap_clk;

assign v2_2_Din_A = grp_test_jacobi_4096_Pipeline_VITIS_LOOP_55_3_fu_95_v2_2_Din_A;

assign v2_2_Din_B = 32'd0;

assign v2_2_Rst_A = ap_rst_n_inv;

assign v2_2_Rst_B = ap_rst_n_inv;

assign v2_2_WEN_B = 4'd0;

assign v2_3_Addr_B = grp_test_jacobi_4096_Pipeline_VITIS_LOOP_40_2_fu_74_v2_3_Addr_B;

assign v2_3_Clk_A = ap_clk;

assign v2_3_Clk_B = ap_clk;

assign v2_3_Din_A = grp_test_jacobi_4096_Pipeline_VITIS_LOOP_55_3_fu_95_v2_3_Din_A;

assign v2_3_Din_B = 32'd0;

assign v2_3_Rst_A = ap_rst_n_inv;

assign v2_3_Rst_B = ap_rst_n_inv;

assign v2_3_WEN_B = 4'd0;

assign v3_2_fu_130_p2 = (v3_fu_64 + 13'd1);

endmodule //test_jacobi_4096
