-- ==============================================================
-- RTL generated by Vitis HLS - High-Level Synthesis from C, C++ and OpenCL v2022.2 (64-bit)
-- Version: 2022.2
-- Copyright (C) Copyright 1986-2022 Xilinx, Inc. All Rights Reserved.
-- 
-- ===========================================================

library IEEE;
use IEEE.std_logic_1164.all;
use IEEE.numeric_std.all;

entity test_heat_4096_test_heat_4096_Pipeline_VITIS_LOOP_59_3 is
port (
    ap_clk : IN STD_LOGIC;
    ap_rst : IN STD_LOGIC;
    ap_start : IN STD_LOGIC;
    ap_done : OUT STD_LOGIC;
    ap_idle : OUT STD_LOGIC;
    ap_ready : OUT STD_LOGIC;
    v3_3_Addr_A : OUT STD_LOGIC_VECTOR (31 downto 0);
    v3_3_EN_A : OUT STD_LOGIC;
    v3_3_WEN_A : OUT STD_LOGIC_VECTOR (3 downto 0);
    v3_3_Din_A : OUT STD_LOGIC_VECTOR (31 downto 0);
    v3_3_Dout_A : IN STD_LOGIC_VECTOR (31 downto 0);
    v3_0_Addr_A : OUT STD_LOGIC_VECTOR (31 downto 0);
    v3_0_EN_A : OUT STD_LOGIC;
    v3_0_WEN_A : OUT STD_LOGIC_VECTOR (3 downto 0);
    v3_0_Din_A : OUT STD_LOGIC_VECTOR (31 downto 0);
    v3_0_Dout_A : IN STD_LOGIC_VECTOR (31 downto 0);
    v3_2_Addr_A : OUT STD_LOGIC_VECTOR (31 downto 0);
    v3_2_EN_A : OUT STD_LOGIC;
    v3_2_WEN_A : OUT STD_LOGIC_VECTOR (3 downto 0);
    v3_2_Din_A : OUT STD_LOGIC_VECTOR (31 downto 0);
    v3_2_Dout_A : IN STD_LOGIC_VECTOR (31 downto 0);
    v3_1_Addr_A : OUT STD_LOGIC_VECTOR (31 downto 0);
    v3_1_EN_A : OUT STD_LOGIC;
    v3_1_WEN_A : OUT STD_LOGIC_VECTOR (3 downto 0);
    v3_1_Din_A : OUT STD_LOGIC_VECTOR (31 downto 0);
    v3_1_Dout_A : IN STD_LOGIC_VECTOR (31 downto 0);
    v2_1_Addr_A : OUT STD_LOGIC_VECTOR (31 downto 0);
    v2_1_EN_A : OUT STD_LOGIC;
    v2_1_WEN_A : OUT STD_LOGIC_VECTOR (3 downto 0);
    v2_1_Din_A : OUT STD_LOGIC_VECTOR (31 downto 0);
    v2_1_Dout_A : IN STD_LOGIC_VECTOR (31 downto 0);
    v2_0_Addr_A : OUT STD_LOGIC_VECTOR (31 downto 0);
    v2_0_EN_A : OUT STD_LOGIC;
    v2_0_WEN_A : OUT STD_LOGIC_VECTOR (3 downto 0);
    v2_0_Din_A : OUT STD_LOGIC_VECTOR (31 downto 0);
    v2_0_Dout_A : IN STD_LOGIC_VECTOR (31 downto 0) );
end;


architecture behav of test_heat_4096_test_heat_4096_Pipeline_VITIS_LOOP_59_3 is 
    constant ap_const_logic_1 : STD_LOGIC := '1';
    constant ap_const_logic_0 : STD_LOGIC := '0';
    constant ap_ST_fsm_pp0_stage0 : STD_LOGIC_VECTOR (0 downto 0) := "1";
    constant ap_const_lv32_0 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000000000";
    constant ap_const_boolean_1 : BOOLEAN := true;
    constant ap_const_boolean_0 : BOOLEAN := false;
    constant ap_const_lv1_1 : STD_LOGIC_VECTOR (0 downto 0) := "1";
    constant ap_const_lv1_0 : STD_LOGIC_VECTOR (0 downto 0) := "0";
    constant ap_const_lv11_0 : STD_LOGIC_VECTOR (10 downto 0) := "00000000000";
    constant ap_const_lv32_2 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000000010";
    constant ap_const_lv4_0 : STD_LOGIC_VECTOR (3 downto 0) := "0000";
    constant ap_const_lv4_F : STD_LOGIC_VECTOR (3 downto 0) := "1111";
    constant ap_const_lv32_1 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000000001";
    constant ap_const_lv11_7FF : STD_LOGIC_VECTOR (10 downto 0) := "11111111111";
    constant ap_const_lv11_1 : STD_LOGIC_VECTOR (10 downto 0) := "00000000001";
    constant ap_const_lv2_0 : STD_LOGIC_VECTOR (1 downto 0) := "00";
    constant ap_const_lv13_4 : STD_LOGIC_VECTOR (12 downto 0) := "0000000000100";
    constant ap_const_lv32_C : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000001100";
    constant ap_const_lv12_2 : STD_LOGIC_VECTOR (11 downto 0) := "000000000010";
    constant ap_const_lv32_A : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000001010";
    constant ap_const_lv32_B : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000001011";

attribute shreg_extract : string;
    signal ap_CS_fsm : STD_LOGIC_VECTOR (0 downto 0) := "1";
    attribute fsm_encoding : string;
    attribute fsm_encoding of ap_CS_fsm : signal is "none";
    signal ap_CS_fsm_pp0_stage0 : STD_LOGIC;
    attribute fsm_encoding of ap_CS_fsm_pp0_stage0 : signal is "none";
    signal ap_enable_reg_pp0_iter0 : STD_LOGIC;
    signal ap_enable_reg_pp0_iter1 : STD_LOGIC := '0';
    signal ap_idle_pp0 : STD_LOGIC;
    signal ap_block_state1_pp0_stage0_iter0 : BOOLEAN;
    signal ap_block_state2_pp0_stage0_iter1 : BOOLEAN;
    signal ap_block_pp0_stage0_subdone : BOOLEAN;
    signal icmp_ln59_fu_162_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal ap_condition_exit_pp0_iter0_stage0 : STD_LOGIC;
    signal ap_loop_exit_ready : STD_LOGIC;
    signal ap_ready_int : STD_LOGIC;
    signal v18_1_reg_268 : STD_LOGIC_VECTOR (10 downto 0);
    signal ap_block_pp0_stage0_11001 : BOOLEAN;
    signal trunc_ln62_fu_187_p1 : STD_LOGIC_VECTOR (0 downto 0);
    signal trunc_ln62_reg_282 : STD_LOGIC_VECTOR (0 downto 0);
    signal zext_ln59_fu_174_p1 : STD_LOGIC_VECTOR (63 downto 0);
    signal ap_block_pp0_stage0 : BOOLEAN;
    signal zext_ln63_fu_207_p1 : STD_LOGIC_VECTOR (63 downto 0);
    signal zext_ln62_fu_239_p1 : STD_LOGIC_VECTOR (63 downto 0);
    signal zext_ln64_fu_255_p1 : STD_LOGIC_VECTOR (63 downto 0);
    signal v18_fu_68 : STD_LOGIC_VECTOR (10 downto 0);
    signal add_ln59_fu_168_p2 : STD_LOGIC_VECTOR (10 downto 0);
    signal ap_loop_init : STD_LOGIC;
    signal ap_sig_allocacmp_v18_1 : STD_LOGIC_VECTOR (10 downto 0);
    signal v2_1_Addr_A_orig : STD_LOGIC_VECTOR (31 downto 0);
    signal v2_0_Addr_A_orig : STD_LOGIC_VECTOR (31 downto 0);
    signal v3_1_Addr_A_orig : STD_LOGIC_VECTOR (31 downto 0);
    signal v3_2_Addr_A_orig : STD_LOGIC_VECTOR (31 downto 0);
    signal v3_3_Addr_A_orig : STD_LOGIC_VECTOR (31 downto 0);
    signal v3_0_Addr_A_orig : STD_LOGIC_VECTOR (31 downto 0);
    signal shl_ln61_1_fu_179_p3 : STD_LOGIC_VECTOR (12 downto 0);
    signal add_ln63_1_fu_191_p2 : STD_LOGIC_VECTOR (12 downto 0);
    signal lshr_ln4_fu_197_p4 : STD_LOGIC_VECTOR (10 downto 0);
    signal shl_ln2_fu_217_p3 : STD_LOGIC_VECTOR (11 downto 0);
    signal lshr_ln5_fu_230_p4 : STD_LOGIC_VECTOR (9 downto 0);
    signal add_ln63_fu_224_p2 : STD_LOGIC_VECTOR (11 downto 0);
    signal lshr_ln6_fu_245_p4 : STD_LOGIC_VECTOR (9 downto 0);
    signal ap_done_reg : STD_LOGIC := '0';
    signal ap_continue_int : STD_LOGIC;
    signal ap_done_int : STD_LOGIC;
    signal ap_NS_fsm : STD_LOGIC_VECTOR (0 downto 0);
    signal ap_enable_pp0 : STD_LOGIC;
    signal ap_start_int : STD_LOGIC;
    signal ap_ce_reg : STD_LOGIC;

    component test_heat_4096_flow_control_loop_pipe_sequential_init IS
    port (
        ap_clk : IN STD_LOGIC;
        ap_rst : IN STD_LOGIC;
        ap_start : IN STD_LOGIC;
        ap_ready : OUT STD_LOGIC;
        ap_done : OUT STD_LOGIC;
        ap_start_int : OUT STD_LOGIC;
        ap_loop_init : OUT STD_LOGIC;
        ap_ready_int : IN STD_LOGIC;
        ap_loop_exit_ready : IN STD_LOGIC;
        ap_loop_exit_done : IN STD_LOGIC;
        ap_continue_int : OUT STD_LOGIC;
        ap_done_int : IN STD_LOGIC );
    end component;



begin
    flow_control_loop_pipe_sequential_init_U : component test_heat_4096_flow_control_loop_pipe_sequential_init
    port map (
        ap_clk => ap_clk,
        ap_rst => ap_rst,
        ap_start => ap_start,
        ap_ready => ap_ready,
        ap_done => ap_done,
        ap_start_int => ap_start_int,
        ap_loop_init => ap_loop_init,
        ap_ready_int => ap_ready_int,
        ap_loop_exit_ready => ap_condition_exit_pp0_iter0_stage0,
        ap_loop_exit_done => ap_done_int,
        ap_continue_int => ap_continue_int,
        ap_done_int => ap_done_int);





    ap_CS_fsm_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst = '1') then
                ap_CS_fsm <= ap_ST_fsm_pp0_stage0;
            else
                ap_CS_fsm <= ap_NS_fsm;
            end if;
        end if;
    end process;


    ap_done_reg_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst = '1') then
                ap_done_reg <= ap_const_logic_0;
            else
                if ((ap_continue_int = ap_const_logic_1)) then 
                    ap_done_reg <= ap_const_logic_0;
                elsif (((ap_loop_exit_ready = ap_const_logic_1) and (ap_const_boolean_0 = ap_block_pp0_stage0_subdone) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0))) then 
                    ap_done_reg <= ap_const_logic_1;
                end if; 
            end if;
        end if;
    end process;


    ap_enable_reg_pp0_iter1_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst = '1') then
                ap_enable_reg_pp0_iter1 <= ap_const_logic_0;
            else
                if ((ap_const_logic_1 = ap_condition_exit_pp0_iter0_stage0)) then 
                    ap_enable_reg_pp0_iter1 <= ap_const_logic_0;
                elsif (((ap_const_boolean_0 = ap_block_pp0_stage0_subdone) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0))) then 
                    ap_enable_reg_pp0_iter1 <= ap_start_int;
                end if; 
            end if;
        end if;
    end process;


    v18_fu_68_assign_proc : process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if (((ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0))) then
                if (((icmp_ln59_fu_162_p2 = ap_const_lv1_0) and (ap_enable_reg_pp0_iter0 = ap_const_logic_1))) then 
                    v18_fu_68 <= add_ln59_fu_168_p2;
                elsif ((ap_loop_init = ap_const_logic_1)) then 
                    v18_fu_68 <= ap_const_lv11_0;
                end if;
            end if; 
        end if;
    end process;
    process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if (((icmp_ln59_fu_162_p2 = ap_const_lv1_0) and (ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0))) then
                trunc_ln62_reg_282 <= trunc_ln62_fu_187_p1;
            end if;
        end if;
    end process;
    process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if (((ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0))) then
                v18_1_reg_268 <= ap_sig_allocacmp_v18_1;
            end if;
        end if;
    end process;

    ap_NS_fsm_assign_proc : process (ap_CS_fsm)
    begin
        case ap_CS_fsm is
            when ap_ST_fsm_pp0_stage0 => 
                ap_NS_fsm <= ap_ST_fsm_pp0_stage0;
            when others =>  
                ap_NS_fsm <= "X";
        end case;
    end process;
    add_ln59_fu_168_p2 <= std_logic_vector(unsigned(ap_sig_allocacmp_v18_1) + unsigned(ap_const_lv11_1));
    add_ln63_1_fu_191_p2 <= std_logic_vector(unsigned(shl_ln61_1_fu_179_p3) + unsigned(ap_const_lv13_4));
    add_ln63_fu_224_p2 <= std_logic_vector(unsigned(shl_ln2_fu_217_p3) + unsigned(ap_const_lv12_2));
    ap_CS_fsm_pp0_stage0 <= ap_CS_fsm(0);
        ap_block_pp0_stage0 <= not((ap_const_boolean_1 = ap_const_boolean_1));
        ap_block_pp0_stage0_11001 <= not((ap_const_boolean_1 = ap_const_boolean_1));
        ap_block_pp0_stage0_subdone <= not((ap_const_boolean_1 = ap_const_boolean_1));
        ap_block_state1_pp0_stage0_iter0 <= not((ap_const_boolean_1 = ap_const_boolean_1));
        ap_block_state2_pp0_stage0_iter1 <= not((ap_const_boolean_1 = ap_const_boolean_1));

    ap_condition_exit_pp0_iter0_stage0_assign_proc : process(ap_CS_fsm_pp0_stage0, ap_enable_reg_pp0_iter0, ap_block_pp0_stage0_subdone, icmp_ln59_fu_162_p2)
    begin
        if (((icmp_ln59_fu_162_p2 = ap_const_lv1_1) and (ap_const_boolean_0 = ap_block_pp0_stage0_subdone) and (ap_enable_reg_pp0_iter0 = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0))) then 
            ap_condition_exit_pp0_iter0_stage0 <= ap_const_logic_1;
        else 
            ap_condition_exit_pp0_iter0_stage0 <= ap_const_logic_0;
        end if; 
    end process;


    ap_done_int_assign_proc : process(ap_CS_fsm_pp0_stage0, ap_block_pp0_stage0_subdone, ap_loop_exit_ready, ap_done_reg)
    begin
        if (((ap_loop_exit_ready = ap_const_logic_1) and (ap_const_boolean_0 = ap_block_pp0_stage0_subdone) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0))) then 
            ap_done_int <= ap_const_logic_1;
        else 
            ap_done_int <= ap_done_reg;
        end if; 
    end process;

    ap_enable_pp0 <= (ap_idle_pp0 xor ap_const_logic_1);
    ap_enable_reg_pp0_iter0 <= ap_start_int;

    ap_idle_assign_proc : process(ap_CS_fsm_pp0_stage0, ap_idle_pp0, ap_start_int)
    begin
        if (((ap_idle_pp0 = ap_const_logic_1) and (ap_start_int = ap_const_logic_0) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0))) then 
            ap_idle <= ap_const_logic_1;
        else 
            ap_idle <= ap_const_logic_0;
        end if; 
    end process;


    ap_idle_pp0_assign_proc : process(ap_enable_reg_pp0_iter0, ap_enable_reg_pp0_iter1)
    begin
        if (((ap_enable_reg_pp0_iter1 = ap_const_logic_0) and (ap_enable_reg_pp0_iter0 = ap_const_logic_0))) then 
            ap_idle_pp0 <= ap_const_logic_1;
        else 
            ap_idle_pp0 <= ap_const_logic_0;
        end if; 
    end process;

    ap_loop_exit_ready <= ap_condition_exit_pp0_iter0_stage0;

    ap_ready_int_assign_proc : process(ap_CS_fsm_pp0_stage0, ap_enable_reg_pp0_iter0, ap_block_pp0_stage0_subdone)
    begin
        if (((ap_const_boolean_0 = ap_block_pp0_stage0_subdone) and (ap_enable_reg_pp0_iter0 = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0))) then 
            ap_ready_int <= ap_const_logic_1;
        else 
            ap_ready_int <= ap_const_logic_0;
        end if; 
    end process;


    ap_sig_allocacmp_v18_1_assign_proc : process(ap_CS_fsm_pp0_stage0, ap_block_pp0_stage0, v18_fu_68, ap_loop_init)
    begin
        if (((ap_const_boolean_0 = ap_block_pp0_stage0) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0) and (ap_loop_init = ap_const_logic_1))) then 
            ap_sig_allocacmp_v18_1 <= ap_const_lv11_0;
        else 
            ap_sig_allocacmp_v18_1 <= v18_fu_68;
        end if; 
    end process;

    icmp_ln59_fu_162_p2 <= "1" when (ap_sig_allocacmp_v18_1 = ap_const_lv11_7FF) else "0";
    lshr_ln4_fu_197_p4 <= add_ln63_1_fu_191_p2(12 downto 2);
    lshr_ln5_fu_230_p4 <= v18_1_reg_268(10 downto 1);
    lshr_ln6_fu_245_p4 <= add_ln63_fu_224_p2(11 downto 2);
    shl_ln2_fu_217_p3 <= (v18_1_reg_268 & ap_const_lv1_0);
    shl_ln61_1_fu_179_p3 <= (ap_sig_allocacmp_v18_1 & ap_const_lv2_0);
    trunc_ln62_fu_187_p1 <= ap_sig_allocacmp_v18_1(1 - 1 downto 0);
    v2_0_Addr_A <= std_logic_vector(shift_left(unsigned(v2_0_Addr_A_orig),to_integer(unsigned('0' & ap_const_lv32_2(31-1 downto 0)))));
    v2_0_Addr_A_orig <= zext_ln63_fu_207_p1(32 - 1 downto 0);
    v2_0_Din_A <= ap_const_lv32_0;

    v2_0_EN_A_assign_proc : process(ap_CS_fsm_pp0_stage0, ap_enable_reg_pp0_iter0, ap_block_pp0_stage0_11001)
    begin
        if (((ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (ap_enable_reg_pp0_iter0 = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0))) then 
            v2_0_EN_A <= ap_const_logic_1;
        else 
            v2_0_EN_A <= ap_const_logic_0;
        end if; 
    end process;

    v2_0_WEN_A <= ap_const_lv4_0;
    v2_1_Addr_A <= std_logic_vector(shift_left(unsigned(v2_1_Addr_A_orig),to_integer(unsigned('0' & ap_const_lv32_2(31-1 downto 0)))));
    v2_1_Addr_A_orig <= zext_ln59_fu_174_p1(32 - 1 downto 0);
    v2_1_Din_A <= ap_const_lv32_0;

    v2_1_EN_A_assign_proc : process(ap_CS_fsm_pp0_stage0, ap_enable_reg_pp0_iter0, ap_block_pp0_stage0_11001)
    begin
        if (((ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (ap_enable_reg_pp0_iter0 = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0))) then 
            v2_1_EN_A <= ap_const_logic_1;
        else 
            v2_1_EN_A <= ap_const_logic_0;
        end if; 
    end process;

    v2_1_WEN_A <= ap_const_lv4_0;
    v3_0_Addr_A <= std_logic_vector(shift_left(unsigned(v3_0_Addr_A_orig),to_integer(unsigned('0' & ap_const_lv32_2(31-1 downto 0)))));
    v3_0_Addr_A_orig <= zext_ln64_fu_255_p1(32 - 1 downto 0);
    v3_0_Din_A <= v2_0_Dout_A;

    v3_0_EN_A_assign_proc : process(ap_CS_fsm_pp0_stage0, ap_enable_reg_pp0_iter1, ap_block_pp0_stage0_11001)
    begin
        if (((ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (ap_enable_reg_pp0_iter1 = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0))) then 
            v3_0_EN_A <= ap_const_logic_1;
        else 
            v3_0_EN_A <= ap_const_logic_0;
        end if; 
    end process;


    v3_0_WEN_A_assign_proc : process(ap_CS_fsm_pp0_stage0, ap_enable_reg_pp0_iter1, ap_block_pp0_stage0_11001, trunc_ln62_reg_282)
    begin
        if (((ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (ap_enable_reg_pp0_iter1 = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0) and (trunc_ln62_reg_282 = ap_const_lv1_1))) then 
            v3_0_WEN_A <= ap_const_lv4_F;
        else 
            v3_0_WEN_A <= ap_const_lv4_0;
        end if; 
    end process;

    v3_1_Addr_A <= std_logic_vector(shift_left(unsigned(v3_1_Addr_A_orig),to_integer(unsigned('0' & ap_const_lv32_2(31-1 downto 0)))));
    v3_1_Addr_A_orig <= zext_ln62_fu_239_p1(32 - 1 downto 0);
    v3_1_Din_A <= v2_1_Dout_A;

    v3_1_EN_A_assign_proc : process(ap_CS_fsm_pp0_stage0, ap_enable_reg_pp0_iter1, ap_block_pp0_stage0_11001)
    begin
        if (((ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (ap_enable_reg_pp0_iter1 = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0))) then 
            v3_1_EN_A <= ap_const_logic_1;
        else 
            v3_1_EN_A <= ap_const_logic_0;
        end if; 
    end process;


    v3_1_WEN_A_assign_proc : process(ap_CS_fsm_pp0_stage0, ap_enable_reg_pp0_iter1, ap_block_pp0_stage0_11001, trunc_ln62_reg_282)
    begin
        if (((ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (ap_enable_reg_pp0_iter1 = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0) and (trunc_ln62_reg_282 = ap_const_lv1_0))) then 
            v3_1_WEN_A <= ap_const_lv4_F;
        else 
            v3_1_WEN_A <= ap_const_lv4_0;
        end if; 
    end process;

    v3_2_Addr_A <= std_logic_vector(shift_left(unsigned(v3_2_Addr_A_orig),to_integer(unsigned('0' & ap_const_lv32_2(31-1 downto 0)))));
    v3_2_Addr_A_orig <= zext_ln64_fu_255_p1(32 - 1 downto 0);
    v3_2_Din_A <= v2_0_Dout_A;

    v3_2_EN_A_assign_proc : process(ap_CS_fsm_pp0_stage0, ap_enable_reg_pp0_iter1, ap_block_pp0_stage0_11001)
    begin
        if (((ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (ap_enable_reg_pp0_iter1 = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0))) then 
            v3_2_EN_A <= ap_const_logic_1;
        else 
            v3_2_EN_A <= ap_const_logic_0;
        end if; 
    end process;


    v3_2_WEN_A_assign_proc : process(ap_CS_fsm_pp0_stage0, ap_enable_reg_pp0_iter1, ap_block_pp0_stage0_11001, trunc_ln62_reg_282)
    begin
        if (((ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (ap_enable_reg_pp0_iter1 = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0) and (trunc_ln62_reg_282 = ap_const_lv1_0))) then 
            v3_2_WEN_A <= ap_const_lv4_F;
        else 
            v3_2_WEN_A <= ap_const_lv4_0;
        end if; 
    end process;

    v3_3_Addr_A <= std_logic_vector(shift_left(unsigned(v3_3_Addr_A_orig),to_integer(unsigned('0' & ap_const_lv32_2(31-1 downto 0)))));
    v3_3_Addr_A_orig <= zext_ln62_fu_239_p1(32 - 1 downto 0);
    v3_3_Din_A <= v2_1_Dout_A;

    v3_3_EN_A_assign_proc : process(ap_CS_fsm_pp0_stage0, ap_enable_reg_pp0_iter1, ap_block_pp0_stage0_11001)
    begin
        if (((ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (ap_enable_reg_pp0_iter1 = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0))) then 
            v3_3_EN_A <= ap_const_logic_1;
        else 
            v3_3_EN_A <= ap_const_logic_0;
        end if; 
    end process;


    v3_3_WEN_A_assign_proc : process(ap_CS_fsm_pp0_stage0, ap_enable_reg_pp0_iter1, ap_block_pp0_stage0_11001, trunc_ln62_reg_282)
    begin
        if (((ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (ap_enable_reg_pp0_iter1 = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0) and (trunc_ln62_reg_282 = ap_const_lv1_1))) then 
            v3_3_WEN_A <= ap_const_lv4_F;
        else 
            v3_3_WEN_A <= ap_const_lv4_0;
        end if; 
    end process;

    zext_ln59_fu_174_p1 <= std_logic_vector(IEEE.numeric_std.resize(unsigned(ap_sig_allocacmp_v18_1),64));
    zext_ln62_fu_239_p1 <= std_logic_vector(IEEE.numeric_std.resize(unsigned(lshr_ln5_fu_230_p4),64));
    zext_ln63_fu_207_p1 <= std_logic_vector(IEEE.numeric_std.resize(unsigned(lshr_ln4_fu_197_p4),64));
    zext_ln64_fu_255_p1 <= std_logic_vector(IEEE.numeric_std.resize(unsigned(lshr_ln6_fu_245_p4),64));
end behav;
