// ==============================================================
// RTL generated by Vitis HLS - High-Level Synthesis from C, C++ and OpenCL v2022.2 (64-bit)
// Version: 2022.2
// Copyright (C) Copyright 1986-2022 Xilinx, Inc. All Rights Reserved.
// 
// ===========================================================

`timescale 1 ns / 1 ps 

module test_3mm_2048_test_3mm_2048_Pipeline_VITIS_LOOP_435_11_VITIS_LOOP_436_12 (
        ap_clk,
        ap_rst,
        ap_start,
        ap_done,
        ap_idle,
        ap_ready,
        v7_0_0_Addr_A,
        v7_0_0_EN_A,
        v7_0_0_WEN_A,
        v7_0_0_Din_A,
        v7_0_0_Dout_A,
        v7_0_1_Addr_A,
        v7_0_1_EN_A,
        v7_0_1_WEN_A,
        v7_0_1_Din_A,
        v7_0_1_Dout_A,
        v7_0_2_Addr_A,
        v7_0_2_EN_A,
        v7_0_2_WEN_A,
        v7_0_2_Din_A,
        v7_0_2_Dout_A,
        v7_0_3_Addr_A,
        v7_0_3_EN_A,
        v7_0_3_WEN_A,
        v7_0_3_Din_A,
        v7_0_3_Dout_A,
        v7_0_4_Addr_A,
        v7_0_4_EN_A,
        v7_0_4_WEN_A,
        v7_0_4_Din_A,
        v7_0_4_Dout_A,
        v7_0_5_Addr_A,
        v7_0_5_EN_A,
        v7_0_5_WEN_A,
        v7_0_5_Din_A,
        v7_0_5_Dout_A,
        v7_0_6_Addr_A,
        v7_0_6_EN_A,
        v7_0_6_WEN_A,
        v7_0_6_Din_A,
        v7_0_6_Dout_A,
        v7_0_7_Addr_A,
        v7_0_7_EN_A,
        v7_0_7_WEN_A,
        v7_0_7_Din_A,
        v7_0_7_Dout_A,
        v7_1_0_Addr_A,
        v7_1_0_EN_A,
        v7_1_0_WEN_A,
        v7_1_0_Din_A,
        v7_1_0_Dout_A,
        v7_1_1_Addr_A,
        v7_1_1_EN_A,
        v7_1_1_WEN_A,
        v7_1_1_Din_A,
        v7_1_1_Dout_A,
        v7_1_2_Addr_A,
        v7_1_2_EN_A,
        v7_1_2_WEN_A,
        v7_1_2_Din_A,
        v7_1_2_Dout_A,
        v7_1_3_Addr_A,
        v7_1_3_EN_A,
        v7_1_3_WEN_A,
        v7_1_3_Din_A,
        v7_1_3_Dout_A,
        v7_1_4_Addr_A,
        v7_1_4_EN_A,
        v7_1_4_WEN_A,
        v7_1_4_Din_A,
        v7_1_4_Dout_A,
        v7_1_5_Addr_A,
        v7_1_5_EN_A,
        v7_1_5_WEN_A,
        v7_1_5_Din_A,
        v7_1_5_Dout_A,
        v7_1_6_Addr_A,
        v7_1_6_EN_A,
        v7_1_6_WEN_A,
        v7_1_6_Din_A,
        v7_1_6_Dout_A,
        v7_1_7_Addr_A,
        v7_1_7_EN_A,
        v7_1_7_WEN_A,
        v7_1_7_Din_A,
        v7_1_7_Dout_A,
        v7_2_0_Addr_A,
        v7_2_0_EN_A,
        v7_2_0_WEN_A,
        v7_2_0_Din_A,
        v7_2_0_Dout_A,
        v7_2_1_Addr_A,
        v7_2_1_EN_A,
        v7_2_1_WEN_A,
        v7_2_1_Din_A,
        v7_2_1_Dout_A,
        v7_2_2_Addr_A,
        v7_2_2_EN_A,
        v7_2_2_WEN_A,
        v7_2_2_Din_A,
        v7_2_2_Dout_A,
        v7_2_3_Addr_A,
        v7_2_3_EN_A,
        v7_2_3_WEN_A,
        v7_2_3_Din_A,
        v7_2_3_Dout_A,
        v7_2_4_Addr_A,
        v7_2_4_EN_A,
        v7_2_4_WEN_A,
        v7_2_4_Din_A,
        v7_2_4_Dout_A,
        v7_2_5_Addr_A,
        v7_2_5_EN_A,
        v7_2_5_WEN_A,
        v7_2_5_Din_A,
        v7_2_5_Dout_A,
        v7_2_6_Addr_A,
        v7_2_6_EN_A,
        v7_2_6_WEN_A,
        v7_2_6_Din_A,
        v7_2_6_Dout_A,
        v7_2_7_Addr_A,
        v7_2_7_EN_A,
        v7_2_7_WEN_A,
        v7_2_7_Din_A,
        v7_2_7_Dout_A,
        v7_3_0_Addr_A,
        v7_3_0_EN_A,
        v7_3_0_WEN_A,
        v7_3_0_Din_A,
        v7_3_0_Dout_A,
        v7_3_1_Addr_A,
        v7_3_1_EN_A,
        v7_3_1_WEN_A,
        v7_3_1_Din_A,
        v7_3_1_Dout_A,
        v7_3_2_Addr_A,
        v7_3_2_EN_A,
        v7_3_2_WEN_A,
        v7_3_2_Din_A,
        v7_3_2_Dout_A,
        v7_3_3_Addr_A,
        v7_3_3_EN_A,
        v7_3_3_WEN_A,
        v7_3_3_Din_A,
        v7_3_3_Dout_A,
        v7_3_4_Addr_A,
        v7_3_4_EN_A,
        v7_3_4_WEN_A,
        v7_3_4_Din_A,
        v7_3_4_Dout_A,
        v7_3_5_Addr_A,
        v7_3_5_EN_A,
        v7_3_5_WEN_A,
        v7_3_5_Din_A,
        v7_3_5_Dout_A,
        v7_3_6_Addr_A,
        v7_3_6_EN_A,
        v7_3_6_WEN_A,
        v7_3_6_Din_A,
        v7_3_6_Dout_A,
        v7_3_7_Addr_A,
        v7_3_7_EN_A,
        v7_3_7_WEN_A,
        v7_3_7_Din_A,
        v7_3_7_Dout_A,
        bitcast_ln70
);

parameter    ap_ST_fsm_pp0_stage0 = 1'd1;

input   ap_clk;
input   ap_rst;
input   ap_start;
output   ap_done;
output   ap_idle;
output   ap_ready;
output  [31:0] v7_0_0_Addr_A;
output   v7_0_0_EN_A;
output  [3:0] v7_0_0_WEN_A;
output  [31:0] v7_0_0_Din_A;
input  [31:0] v7_0_0_Dout_A;
output  [31:0] v7_0_1_Addr_A;
output   v7_0_1_EN_A;
output  [3:0] v7_0_1_WEN_A;
output  [31:0] v7_0_1_Din_A;
input  [31:0] v7_0_1_Dout_A;
output  [31:0] v7_0_2_Addr_A;
output   v7_0_2_EN_A;
output  [3:0] v7_0_2_WEN_A;
output  [31:0] v7_0_2_Din_A;
input  [31:0] v7_0_2_Dout_A;
output  [31:0] v7_0_3_Addr_A;
output   v7_0_3_EN_A;
output  [3:0] v7_0_3_WEN_A;
output  [31:0] v7_0_3_Din_A;
input  [31:0] v7_0_3_Dout_A;
output  [31:0] v7_0_4_Addr_A;
output   v7_0_4_EN_A;
output  [3:0] v7_0_4_WEN_A;
output  [31:0] v7_0_4_Din_A;
input  [31:0] v7_0_4_Dout_A;
output  [31:0] v7_0_5_Addr_A;
output   v7_0_5_EN_A;
output  [3:0] v7_0_5_WEN_A;
output  [31:0] v7_0_5_Din_A;
input  [31:0] v7_0_5_Dout_A;
output  [31:0] v7_0_6_Addr_A;
output   v7_0_6_EN_A;
output  [3:0] v7_0_6_WEN_A;
output  [31:0] v7_0_6_Din_A;
input  [31:0] v7_0_6_Dout_A;
output  [31:0] v7_0_7_Addr_A;
output   v7_0_7_EN_A;
output  [3:0] v7_0_7_WEN_A;
output  [31:0] v7_0_7_Din_A;
input  [31:0] v7_0_7_Dout_A;
output  [31:0] v7_1_0_Addr_A;
output   v7_1_0_EN_A;
output  [3:0] v7_1_0_WEN_A;
output  [31:0] v7_1_0_Din_A;
input  [31:0] v7_1_0_Dout_A;
output  [31:0] v7_1_1_Addr_A;
output   v7_1_1_EN_A;
output  [3:0] v7_1_1_WEN_A;
output  [31:0] v7_1_1_Din_A;
input  [31:0] v7_1_1_Dout_A;
output  [31:0] v7_1_2_Addr_A;
output   v7_1_2_EN_A;
output  [3:0] v7_1_2_WEN_A;
output  [31:0] v7_1_2_Din_A;
input  [31:0] v7_1_2_Dout_A;
output  [31:0] v7_1_3_Addr_A;
output   v7_1_3_EN_A;
output  [3:0] v7_1_3_WEN_A;
output  [31:0] v7_1_3_Din_A;
input  [31:0] v7_1_3_Dout_A;
output  [31:0] v7_1_4_Addr_A;
output   v7_1_4_EN_A;
output  [3:0] v7_1_4_WEN_A;
output  [31:0] v7_1_4_Din_A;
input  [31:0] v7_1_4_Dout_A;
output  [31:0] v7_1_5_Addr_A;
output   v7_1_5_EN_A;
output  [3:0] v7_1_5_WEN_A;
output  [31:0] v7_1_5_Din_A;
input  [31:0] v7_1_5_Dout_A;
output  [31:0] v7_1_6_Addr_A;
output   v7_1_6_EN_A;
output  [3:0] v7_1_6_WEN_A;
output  [31:0] v7_1_6_Din_A;
input  [31:0] v7_1_6_Dout_A;
output  [31:0] v7_1_7_Addr_A;
output   v7_1_7_EN_A;
output  [3:0] v7_1_7_WEN_A;
output  [31:0] v7_1_7_Din_A;
input  [31:0] v7_1_7_Dout_A;
output  [31:0] v7_2_0_Addr_A;
output   v7_2_0_EN_A;
output  [3:0] v7_2_0_WEN_A;
output  [31:0] v7_2_0_Din_A;
input  [31:0] v7_2_0_Dout_A;
output  [31:0] v7_2_1_Addr_A;
output   v7_2_1_EN_A;
output  [3:0] v7_2_1_WEN_A;
output  [31:0] v7_2_1_Din_A;
input  [31:0] v7_2_1_Dout_A;
output  [31:0] v7_2_2_Addr_A;
output   v7_2_2_EN_A;
output  [3:0] v7_2_2_WEN_A;
output  [31:0] v7_2_2_Din_A;
input  [31:0] v7_2_2_Dout_A;
output  [31:0] v7_2_3_Addr_A;
output   v7_2_3_EN_A;
output  [3:0] v7_2_3_WEN_A;
output  [31:0] v7_2_3_Din_A;
input  [31:0] v7_2_3_Dout_A;
output  [31:0] v7_2_4_Addr_A;
output   v7_2_4_EN_A;
output  [3:0] v7_2_4_WEN_A;
output  [31:0] v7_2_4_Din_A;
input  [31:0] v7_2_4_Dout_A;
output  [31:0] v7_2_5_Addr_A;
output   v7_2_5_EN_A;
output  [3:0] v7_2_5_WEN_A;
output  [31:0] v7_2_5_Din_A;
input  [31:0] v7_2_5_Dout_A;
output  [31:0] v7_2_6_Addr_A;
output   v7_2_6_EN_A;
output  [3:0] v7_2_6_WEN_A;
output  [31:0] v7_2_6_Din_A;
input  [31:0] v7_2_6_Dout_A;
output  [31:0] v7_2_7_Addr_A;
output   v7_2_7_EN_A;
output  [3:0] v7_2_7_WEN_A;
output  [31:0] v7_2_7_Din_A;
input  [31:0] v7_2_7_Dout_A;
output  [31:0] v7_3_0_Addr_A;
output   v7_3_0_EN_A;
output  [3:0] v7_3_0_WEN_A;
output  [31:0] v7_3_0_Din_A;
input  [31:0] v7_3_0_Dout_A;
output  [31:0] v7_3_1_Addr_A;
output   v7_3_1_EN_A;
output  [3:0] v7_3_1_WEN_A;
output  [31:0] v7_3_1_Din_A;
input  [31:0] v7_3_1_Dout_A;
output  [31:0] v7_3_2_Addr_A;
output   v7_3_2_EN_A;
output  [3:0] v7_3_2_WEN_A;
output  [31:0] v7_3_2_Din_A;
input  [31:0] v7_3_2_Dout_A;
output  [31:0] v7_3_3_Addr_A;
output   v7_3_3_EN_A;
output  [3:0] v7_3_3_WEN_A;
output  [31:0] v7_3_3_Din_A;
input  [31:0] v7_3_3_Dout_A;
output  [31:0] v7_3_4_Addr_A;
output   v7_3_4_EN_A;
output  [3:0] v7_3_4_WEN_A;
output  [31:0] v7_3_4_Din_A;
input  [31:0] v7_3_4_Dout_A;
output  [31:0] v7_3_5_Addr_A;
output   v7_3_5_EN_A;
output  [3:0] v7_3_5_WEN_A;
output  [31:0] v7_3_5_Din_A;
input  [31:0] v7_3_5_Dout_A;
output  [31:0] v7_3_6_Addr_A;
output   v7_3_6_EN_A;
output  [3:0] v7_3_6_WEN_A;
output  [31:0] v7_3_6_Din_A;
input  [31:0] v7_3_6_Dout_A;
output  [31:0] v7_3_7_Addr_A;
output   v7_3_7_EN_A;
output  [3:0] v7_3_7_WEN_A;
output  [31:0] v7_3_7_Din_A;
input  [31:0] v7_3_7_Dout_A;
input  [31:0] bitcast_ln70;

reg ap_idle;
reg v7_0_0_EN_A;
reg[3:0] v7_0_0_WEN_A;
reg v7_0_1_EN_A;
reg[3:0] v7_0_1_WEN_A;
reg v7_0_2_EN_A;
reg[3:0] v7_0_2_WEN_A;
reg v7_0_3_EN_A;
reg[3:0] v7_0_3_WEN_A;
reg v7_0_4_EN_A;
reg[3:0] v7_0_4_WEN_A;
reg v7_0_5_EN_A;
reg[3:0] v7_0_5_WEN_A;
reg v7_0_6_EN_A;
reg[3:0] v7_0_6_WEN_A;
reg v7_0_7_EN_A;
reg[3:0] v7_0_7_WEN_A;
reg v7_1_0_EN_A;
reg[3:0] v7_1_0_WEN_A;
reg v7_1_1_EN_A;
reg[3:0] v7_1_1_WEN_A;
reg v7_1_2_EN_A;
reg[3:0] v7_1_2_WEN_A;
reg v7_1_3_EN_A;
reg[3:0] v7_1_3_WEN_A;
reg v7_1_4_EN_A;
reg[3:0] v7_1_4_WEN_A;
reg v7_1_5_EN_A;
reg[3:0] v7_1_5_WEN_A;
reg v7_1_6_EN_A;
reg[3:0] v7_1_6_WEN_A;
reg v7_1_7_EN_A;
reg[3:0] v7_1_7_WEN_A;
reg v7_2_0_EN_A;
reg[3:0] v7_2_0_WEN_A;
reg v7_2_1_EN_A;
reg[3:0] v7_2_1_WEN_A;
reg v7_2_2_EN_A;
reg[3:0] v7_2_2_WEN_A;
reg v7_2_3_EN_A;
reg[3:0] v7_2_3_WEN_A;
reg v7_2_4_EN_A;
reg[3:0] v7_2_4_WEN_A;
reg v7_2_5_EN_A;
reg[3:0] v7_2_5_WEN_A;
reg v7_2_6_EN_A;
reg[3:0] v7_2_6_WEN_A;
reg v7_2_7_EN_A;
reg[3:0] v7_2_7_WEN_A;
reg v7_3_0_EN_A;
reg[3:0] v7_3_0_WEN_A;
reg v7_3_1_EN_A;
reg[3:0] v7_3_1_WEN_A;
reg v7_3_2_EN_A;
reg[3:0] v7_3_2_WEN_A;
reg v7_3_3_EN_A;
reg[3:0] v7_3_3_WEN_A;
reg v7_3_4_EN_A;
reg[3:0] v7_3_4_WEN_A;
reg v7_3_5_EN_A;
reg[3:0] v7_3_5_WEN_A;
reg v7_3_6_EN_A;
reg[3:0] v7_3_6_WEN_A;
reg v7_3_7_EN_A;
reg[3:0] v7_3_7_WEN_A;

(* fsm_encoding = "none" *) reg   [0:0] ap_CS_fsm;
wire    ap_CS_fsm_pp0_stage0;
wire    ap_enable_reg_pp0_iter0;
reg    ap_enable_reg_pp0_iter1;
reg    ap_enable_reg_pp0_iter2;
reg    ap_idle_pp0;
wire    ap_block_state1_pp0_stage0_iter0;
wire    ap_block_state2_pp0_stage0_iter1;
wire    ap_block_state3_pp0_stage0_iter2;
wire    ap_block_pp0_stage0_subdone;
wire   [0:0] icmp_ln435_fu_566_p2;
reg    ap_condition_exit_pp0_iter1_stage0;
wire    ap_loop_exit_ready;
reg    ap_ready_int;
wire    ap_block_pp0_stage0_11001;
wire   [16:0] add_ln438_fu_628_p2;
reg   [16:0] add_ln438_reg_750;
wire   [63:0] zext_ln438_1_fu_655_p1;
wire    ap_block_pp0_stage0;
reg   [8:0] v235_fu_114;
wire   [8:0] add_ln436_fu_634_p2;
wire    ap_loop_init;
reg   [9:0] v234_fu_118;
wire   [9:0] select_ln435_1_fu_604_p3;
reg   [17:0] indvar_flatten111_fu_122;
wire   [17:0] add_ln435_1_fu_572_p2;
wire   [31:0] v7_0_0_Addr_A_orig;
wire   [31:0] v7_0_1_Addr_A_orig;
wire   [31:0] v7_0_2_Addr_A_orig;
wire   [31:0] v7_0_3_Addr_A_orig;
wire   [31:0] v7_0_4_Addr_A_orig;
wire   [31:0] v7_0_5_Addr_A_orig;
wire   [31:0] v7_0_6_Addr_A_orig;
wire   [31:0] v7_0_7_Addr_A_orig;
wire   [31:0] v7_1_0_Addr_A_orig;
wire   [31:0] v7_1_1_Addr_A_orig;
wire   [31:0] v7_1_2_Addr_A_orig;
wire   [31:0] v7_1_3_Addr_A_orig;
wire   [31:0] v7_1_4_Addr_A_orig;
wire   [31:0] v7_1_5_Addr_A_orig;
wire   [31:0] v7_1_6_Addr_A_orig;
wire   [31:0] v7_1_7_Addr_A_orig;
wire   [31:0] v7_2_0_Addr_A_orig;
wire   [31:0] v7_2_1_Addr_A_orig;
wire   [31:0] v7_2_2_Addr_A_orig;
wire   [31:0] v7_2_3_Addr_A_orig;
wire   [31:0] v7_2_4_Addr_A_orig;
wire   [31:0] v7_2_5_Addr_A_orig;
wire   [31:0] v7_2_6_Addr_A_orig;
wire   [31:0] v7_2_7_Addr_A_orig;
wire   [31:0] v7_3_0_Addr_A_orig;
wire   [31:0] v7_3_1_Addr_A_orig;
wire   [31:0] v7_3_2_Addr_A_orig;
wire   [31:0] v7_3_3_Addr_A_orig;
wire   [31:0] v7_3_4_Addr_A_orig;
wire   [31:0] v7_3_5_Addr_A_orig;
wire   [31:0] v7_3_6_Addr_A_orig;
wire   [31:0] v7_3_7_Addr_A_orig;
wire   [0:0] icmp_ln436_fu_590_p2;
wire   [9:0] add_ln435_fu_584_p2;
wire   [8:0] trunc_ln438_fu_612_p1;
wire   [8:0] select_ln435_fu_596_p3;
wire   [16:0] tmp_s_fu_616_p3;
wire   [16:0] zext_ln438_fu_624_p1;
reg    ap_done_reg;
wire    ap_continue_int;
reg    ap_done_int;
reg   [0:0] ap_NS_fsm;
wire    ap_enable_pp0;
wire    ap_start_int;
wire    ap_ce_reg;

// power-on initialization
initial begin
#0 ap_CS_fsm = 1'd1;
#0 ap_enable_reg_pp0_iter1 = 1'b0;
#0 ap_enable_reg_pp0_iter2 = 1'b0;
#0 ap_done_reg = 1'b0;
end

test_3mm_2048_flow_control_loop_pipe_sequential_init flow_control_loop_pipe_sequential_init_U(
    .ap_clk(ap_clk),
    .ap_rst(ap_rst),
    .ap_start(ap_start),
    .ap_ready(ap_ready),
    .ap_done(ap_done),
    .ap_start_int(ap_start_int),
    .ap_loop_init(ap_loop_init),
    .ap_ready_int(ap_ready_int),
    .ap_loop_exit_ready(ap_condition_exit_pp0_iter1_stage0),
    .ap_loop_exit_done(ap_done_int),
    .ap_continue_int(ap_continue_int),
    .ap_done_int(ap_done_int)
);

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_CS_fsm <= ap_ST_fsm_pp0_stage0;
    end else begin
        ap_CS_fsm <= ap_NS_fsm;
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_done_reg <= 1'b0;
    end else begin
        if ((ap_continue_int == 1'b1)) begin
            ap_done_reg <= 1'b0;
        end else if (((ap_loop_exit_ready == 1'b1) & (1'b0 == ap_block_pp0_stage0_subdone) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
            ap_done_reg <= 1'b1;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_enable_reg_pp0_iter1 <= 1'b0;
    end else begin
        if ((1'b1 == ap_condition_exit_pp0_iter1_stage0)) begin
            ap_enable_reg_pp0_iter1 <= 1'b0;
        end else if (((1'b0 == ap_block_pp0_stage0_subdone) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
            ap_enable_reg_pp0_iter1 <= ap_start_int;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_enable_reg_pp0_iter2 <= 1'b0;
    end else begin
        if ((1'b1 == ap_condition_exit_pp0_iter1_stage0)) begin
            ap_enable_reg_pp0_iter2 <= 1'b0;
        end else if ((1'b0 == ap_block_pp0_stage0_subdone)) begin
            ap_enable_reg_pp0_iter2 <= ap_enable_reg_pp0_iter1;
        end
    end
end

always @ (posedge ap_clk) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        if ((ap_loop_init == 1'b1)) begin
            indvar_flatten111_fu_122 <= 18'd0;
        end else if (((icmp_ln435_fu_566_p2 == 1'd0) & (ap_enable_reg_pp0_iter1 == 1'b1))) begin
            indvar_flatten111_fu_122 <= add_ln435_1_fu_572_p2;
        end
    end
end

always @ (posedge ap_clk) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        if ((ap_loop_init == 1'b1)) begin
            v234_fu_118 <= 10'd0;
        end else if (((icmp_ln435_fu_566_p2 == 1'd0) & (ap_enable_reg_pp0_iter1 == 1'b1))) begin
            v234_fu_118 <= select_ln435_1_fu_604_p3;
        end
    end
end

always @ (posedge ap_clk) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        if ((ap_loop_init == 1'b1)) begin
            v235_fu_114 <= 9'd0;
        end else if (((icmp_ln435_fu_566_p2 == 1'd0) & (ap_enable_reg_pp0_iter1 == 1'b1))) begin
            v235_fu_114 <= add_ln436_fu_634_p2;
        end
    end
end

always @ (posedge ap_clk) begin
    if (((icmp_ln435_fu_566_p2 == 1'd0) & (1'b0 == ap_block_pp0_stage0_11001) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        add_ln438_reg_750 <= add_ln438_fu_628_p2;
    end
end

always @ (*) begin
    if (((icmp_ln435_fu_566_p2 == 1'd1) & (1'b0 == ap_block_pp0_stage0_subdone) & (ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        ap_condition_exit_pp0_iter1_stage0 = 1'b1;
    end else begin
        ap_condition_exit_pp0_iter1_stage0 = 1'b0;
    end
end

always @ (*) begin
    if (((ap_loop_exit_ready == 1'b1) & (1'b0 == ap_block_pp0_stage0_subdone) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        ap_done_int = 1'b1;
    end else begin
        ap_done_int = ap_done_reg;
    end
end

always @ (*) begin
    if (((ap_start_int == 1'b0) & (ap_idle_pp0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        ap_idle = 1'b1;
    end else begin
        ap_idle = 1'b0;
    end
end

always @ (*) begin
    if (((ap_enable_reg_pp0_iter2 == 1'b0) & (ap_enable_reg_pp0_iter1 == 1'b0) & (ap_enable_reg_pp0_iter0 == 1'b0))) begin
        ap_idle_pp0 = 1'b1;
    end else begin
        ap_idle_pp0 = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_subdone) & (ap_enable_reg_pp0_iter0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        ap_ready_int = 1'b1;
    end else begin
        ap_ready_int = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter2 == 1'b1))) begin
        v7_0_0_EN_A = 1'b1;
    end else begin
        v7_0_0_EN_A = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter2 == 1'b1))) begin
        v7_0_0_WEN_A = 4'd15;
    end else begin
        v7_0_0_WEN_A = 4'd0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter2 == 1'b1))) begin
        v7_0_1_EN_A = 1'b1;
    end else begin
        v7_0_1_EN_A = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter2 == 1'b1))) begin
        v7_0_1_WEN_A = 4'd15;
    end else begin
        v7_0_1_WEN_A = 4'd0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter2 == 1'b1))) begin
        v7_0_2_EN_A = 1'b1;
    end else begin
        v7_0_2_EN_A = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter2 == 1'b1))) begin
        v7_0_2_WEN_A = 4'd15;
    end else begin
        v7_0_2_WEN_A = 4'd0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter2 == 1'b1))) begin
        v7_0_3_EN_A = 1'b1;
    end else begin
        v7_0_3_EN_A = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter2 == 1'b1))) begin
        v7_0_3_WEN_A = 4'd15;
    end else begin
        v7_0_3_WEN_A = 4'd0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter2 == 1'b1))) begin
        v7_0_4_EN_A = 1'b1;
    end else begin
        v7_0_4_EN_A = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter2 == 1'b1))) begin
        v7_0_4_WEN_A = 4'd15;
    end else begin
        v7_0_4_WEN_A = 4'd0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter2 == 1'b1))) begin
        v7_0_5_EN_A = 1'b1;
    end else begin
        v7_0_5_EN_A = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter2 == 1'b1))) begin
        v7_0_5_WEN_A = 4'd15;
    end else begin
        v7_0_5_WEN_A = 4'd0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter2 == 1'b1))) begin
        v7_0_6_EN_A = 1'b1;
    end else begin
        v7_0_6_EN_A = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter2 == 1'b1))) begin
        v7_0_6_WEN_A = 4'd15;
    end else begin
        v7_0_6_WEN_A = 4'd0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter2 == 1'b1))) begin
        v7_0_7_EN_A = 1'b1;
    end else begin
        v7_0_7_EN_A = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter2 == 1'b1))) begin
        v7_0_7_WEN_A = 4'd15;
    end else begin
        v7_0_7_WEN_A = 4'd0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter2 == 1'b1))) begin
        v7_1_0_EN_A = 1'b1;
    end else begin
        v7_1_0_EN_A = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter2 == 1'b1))) begin
        v7_1_0_WEN_A = 4'd15;
    end else begin
        v7_1_0_WEN_A = 4'd0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter2 == 1'b1))) begin
        v7_1_1_EN_A = 1'b1;
    end else begin
        v7_1_1_EN_A = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter2 == 1'b1))) begin
        v7_1_1_WEN_A = 4'd15;
    end else begin
        v7_1_1_WEN_A = 4'd0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter2 == 1'b1))) begin
        v7_1_2_EN_A = 1'b1;
    end else begin
        v7_1_2_EN_A = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter2 == 1'b1))) begin
        v7_1_2_WEN_A = 4'd15;
    end else begin
        v7_1_2_WEN_A = 4'd0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter2 == 1'b1))) begin
        v7_1_3_EN_A = 1'b1;
    end else begin
        v7_1_3_EN_A = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter2 == 1'b1))) begin
        v7_1_3_WEN_A = 4'd15;
    end else begin
        v7_1_3_WEN_A = 4'd0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter2 == 1'b1))) begin
        v7_1_4_EN_A = 1'b1;
    end else begin
        v7_1_4_EN_A = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter2 == 1'b1))) begin
        v7_1_4_WEN_A = 4'd15;
    end else begin
        v7_1_4_WEN_A = 4'd0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter2 == 1'b1))) begin
        v7_1_5_EN_A = 1'b1;
    end else begin
        v7_1_5_EN_A = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter2 == 1'b1))) begin
        v7_1_5_WEN_A = 4'd15;
    end else begin
        v7_1_5_WEN_A = 4'd0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter2 == 1'b1))) begin
        v7_1_6_EN_A = 1'b1;
    end else begin
        v7_1_6_EN_A = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter2 == 1'b1))) begin
        v7_1_6_WEN_A = 4'd15;
    end else begin
        v7_1_6_WEN_A = 4'd0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter2 == 1'b1))) begin
        v7_1_7_EN_A = 1'b1;
    end else begin
        v7_1_7_EN_A = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter2 == 1'b1))) begin
        v7_1_7_WEN_A = 4'd15;
    end else begin
        v7_1_7_WEN_A = 4'd0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter2 == 1'b1))) begin
        v7_2_0_EN_A = 1'b1;
    end else begin
        v7_2_0_EN_A = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter2 == 1'b1))) begin
        v7_2_0_WEN_A = 4'd15;
    end else begin
        v7_2_0_WEN_A = 4'd0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter2 == 1'b1))) begin
        v7_2_1_EN_A = 1'b1;
    end else begin
        v7_2_1_EN_A = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter2 == 1'b1))) begin
        v7_2_1_WEN_A = 4'd15;
    end else begin
        v7_2_1_WEN_A = 4'd0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter2 == 1'b1))) begin
        v7_2_2_EN_A = 1'b1;
    end else begin
        v7_2_2_EN_A = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter2 == 1'b1))) begin
        v7_2_2_WEN_A = 4'd15;
    end else begin
        v7_2_2_WEN_A = 4'd0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter2 == 1'b1))) begin
        v7_2_3_EN_A = 1'b1;
    end else begin
        v7_2_3_EN_A = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter2 == 1'b1))) begin
        v7_2_3_WEN_A = 4'd15;
    end else begin
        v7_2_3_WEN_A = 4'd0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter2 == 1'b1))) begin
        v7_2_4_EN_A = 1'b1;
    end else begin
        v7_2_4_EN_A = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter2 == 1'b1))) begin
        v7_2_4_WEN_A = 4'd15;
    end else begin
        v7_2_4_WEN_A = 4'd0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter2 == 1'b1))) begin
        v7_2_5_EN_A = 1'b1;
    end else begin
        v7_2_5_EN_A = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter2 == 1'b1))) begin
        v7_2_5_WEN_A = 4'd15;
    end else begin
        v7_2_5_WEN_A = 4'd0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter2 == 1'b1))) begin
        v7_2_6_EN_A = 1'b1;
    end else begin
        v7_2_6_EN_A = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter2 == 1'b1))) begin
        v7_2_6_WEN_A = 4'd15;
    end else begin
        v7_2_6_WEN_A = 4'd0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter2 == 1'b1))) begin
        v7_2_7_EN_A = 1'b1;
    end else begin
        v7_2_7_EN_A = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter2 == 1'b1))) begin
        v7_2_7_WEN_A = 4'd15;
    end else begin
        v7_2_7_WEN_A = 4'd0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter2 == 1'b1))) begin
        v7_3_0_EN_A = 1'b1;
    end else begin
        v7_3_0_EN_A = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter2 == 1'b1))) begin
        v7_3_0_WEN_A = 4'd15;
    end else begin
        v7_3_0_WEN_A = 4'd0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter2 == 1'b1))) begin
        v7_3_1_EN_A = 1'b1;
    end else begin
        v7_3_1_EN_A = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter2 == 1'b1))) begin
        v7_3_1_WEN_A = 4'd15;
    end else begin
        v7_3_1_WEN_A = 4'd0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter2 == 1'b1))) begin
        v7_3_2_EN_A = 1'b1;
    end else begin
        v7_3_2_EN_A = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter2 == 1'b1))) begin
        v7_3_2_WEN_A = 4'd15;
    end else begin
        v7_3_2_WEN_A = 4'd0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter2 == 1'b1))) begin
        v7_3_3_EN_A = 1'b1;
    end else begin
        v7_3_3_EN_A = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter2 == 1'b1))) begin
        v7_3_3_WEN_A = 4'd15;
    end else begin
        v7_3_3_WEN_A = 4'd0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter2 == 1'b1))) begin
        v7_3_4_EN_A = 1'b1;
    end else begin
        v7_3_4_EN_A = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter2 == 1'b1))) begin
        v7_3_4_WEN_A = 4'd15;
    end else begin
        v7_3_4_WEN_A = 4'd0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter2 == 1'b1))) begin
        v7_3_5_EN_A = 1'b1;
    end else begin
        v7_3_5_EN_A = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter2 == 1'b1))) begin
        v7_3_5_WEN_A = 4'd15;
    end else begin
        v7_3_5_WEN_A = 4'd0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter2 == 1'b1))) begin
        v7_3_6_EN_A = 1'b1;
    end else begin
        v7_3_6_EN_A = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter2 == 1'b1))) begin
        v7_3_6_WEN_A = 4'd15;
    end else begin
        v7_3_6_WEN_A = 4'd0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter2 == 1'b1))) begin
        v7_3_7_EN_A = 1'b1;
    end else begin
        v7_3_7_EN_A = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter2 == 1'b1))) begin
        v7_3_7_WEN_A = 4'd15;
    end else begin
        v7_3_7_WEN_A = 4'd0;
    end
end

always @ (*) begin
    case (ap_CS_fsm)
        ap_ST_fsm_pp0_stage0 : begin
            ap_NS_fsm = ap_ST_fsm_pp0_stage0;
        end
        default : begin
            ap_NS_fsm = 'bx;
        end
    endcase
end

assign add_ln435_1_fu_572_p2 = (indvar_flatten111_fu_122 + 18'd1);

assign add_ln435_fu_584_p2 = (v234_fu_118 + 10'd1);

assign add_ln436_fu_634_p2 = (select_ln435_fu_596_p3 + 9'd1);

assign add_ln438_fu_628_p2 = (tmp_s_fu_616_p3 + zext_ln438_fu_624_p1);

assign ap_CS_fsm_pp0_stage0 = ap_CS_fsm[32'd0];

assign ap_block_pp0_stage0 = ~(1'b1 == 1'b1);

assign ap_block_pp0_stage0_11001 = ~(1'b1 == 1'b1);

assign ap_block_pp0_stage0_subdone = ~(1'b1 == 1'b1);

assign ap_block_state1_pp0_stage0_iter0 = ~(1'b1 == 1'b1);

assign ap_block_state2_pp0_stage0_iter1 = ~(1'b1 == 1'b1);

assign ap_block_state3_pp0_stage0_iter2 = ~(1'b1 == 1'b1);

assign ap_enable_pp0 = (ap_idle_pp0 ^ 1'b1);

assign ap_enable_reg_pp0_iter0 = ap_start_int;

assign ap_loop_exit_ready = ap_condition_exit_pp0_iter1_stage0;

assign icmp_ln435_fu_566_p2 = ((indvar_flatten111_fu_122 == 18'd131072) ? 1'b1 : 1'b0);

assign icmp_ln436_fu_590_p2 = ((v235_fu_114 == 9'd256) ? 1'b1 : 1'b0);

assign select_ln435_1_fu_604_p3 = ((icmp_ln436_fu_590_p2[0:0] == 1'b1) ? add_ln435_fu_584_p2 : v234_fu_118);

assign select_ln435_fu_596_p3 = ((icmp_ln436_fu_590_p2[0:0] == 1'b1) ? 9'd0 : v235_fu_114);

assign tmp_s_fu_616_p3 = {{trunc_ln438_fu_612_p1}, {8'd0}};

assign trunc_ln438_fu_612_p1 = select_ln435_1_fu_604_p3[8:0];

assign v7_0_0_Addr_A = v7_0_0_Addr_A_orig << 32'd2;

assign v7_0_0_Addr_A_orig = zext_ln438_1_fu_655_p1;

assign v7_0_0_Din_A = bitcast_ln70;

assign v7_0_1_Addr_A = v7_0_1_Addr_A_orig << 32'd2;

assign v7_0_1_Addr_A_orig = zext_ln438_1_fu_655_p1;

assign v7_0_1_Din_A = bitcast_ln70;

assign v7_0_2_Addr_A = v7_0_2_Addr_A_orig << 32'd2;

assign v7_0_2_Addr_A_orig = zext_ln438_1_fu_655_p1;

assign v7_0_2_Din_A = bitcast_ln70;

assign v7_0_3_Addr_A = v7_0_3_Addr_A_orig << 32'd2;

assign v7_0_3_Addr_A_orig = zext_ln438_1_fu_655_p1;

assign v7_0_3_Din_A = bitcast_ln70;

assign v7_0_4_Addr_A = v7_0_4_Addr_A_orig << 32'd2;

assign v7_0_4_Addr_A_orig = zext_ln438_1_fu_655_p1;

assign v7_0_4_Din_A = bitcast_ln70;

assign v7_0_5_Addr_A = v7_0_5_Addr_A_orig << 32'd2;

assign v7_0_5_Addr_A_orig = zext_ln438_1_fu_655_p1;

assign v7_0_5_Din_A = bitcast_ln70;

assign v7_0_6_Addr_A = v7_0_6_Addr_A_orig << 32'd2;

assign v7_0_6_Addr_A_orig = zext_ln438_1_fu_655_p1;

assign v7_0_6_Din_A = bitcast_ln70;

assign v7_0_7_Addr_A = v7_0_7_Addr_A_orig << 32'd2;

assign v7_0_7_Addr_A_orig = zext_ln438_1_fu_655_p1;

assign v7_0_7_Din_A = bitcast_ln70;

assign v7_1_0_Addr_A = v7_1_0_Addr_A_orig << 32'd2;

assign v7_1_0_Addr_A_orig = zext_ln438_1_fu_655_p1;

assign v7_1_0_Din_A = bitcast_ln70;

assign v7_1_1_Addr_A = v7_1_1_Addr_A_orig << 32'd2;

assign v7_1_1_Addr_A_orig = zext_ln438_1_fu_655_p1;

assign v7_1_1_Din_A = bitcast_ln70;

assign v7_1_2_Addr_A = v7_1_2_Addr_A_orig << 32'd2;

assign v7_1_2_Addr_A_orig = zext_ln438_1_fu_655_p1;

assign v7_1_2_Din_A = bitcast_ln70;

assign v7_1_3_Addr_A = v7_1_3_Addr_A_orig << 32'd2;

assign v7_1_3_Addr_A_orig = zext_ln438_1_fu_655_p1;

assign v7_1_3_Din_A = bitcast_ln70;

assign v7_1_4_Addr_A = v7_1_4_Addr_A_orig << 32'd2;

assign v7_1_4_Addr_A_orig = zext_ln438_1_fu_655_p1;

assign v7_1_4_Din_A = bitcast_ln70;

assign v7_1_5_Addr_A = v7_1_5_Addr_A_orig << 32'd2;

assign v7_1_5_Addr_A_orig = zext_ln438_1_fu_655_p1;

assign v7_1_5_Din_A = bitcast_ln70;

assign v7_1_6_Addr_A = v7_1_6_Addr_A_orig << 32'd2;

assign v7_1_6_Addr_A_orig = zext_ln438_1_fu_655_p1;

assign v7_1_6_Din_A = bitcast_ln70;

assign v7_1_7_Addr_A = v7_1_7_Addr_A_orig << 32'd2;

assign v7_1_7_Addr_A_orig = zext_ln438_1_fu_655_p1;

assign v7_1_7_Din_A = bitcast_ln70;

assign v7_2_0_Addr_A = v7_2_0_Addr_A_orig << 32'd2;

assign v7_2_0_Addr_A_orig = zext_ln438_1_fu_655_p1;

assign v7_2_0_Din_A = bitcast_ln70;

assign v7_2_1_Addr_A = v7_2_1_Addr_A_orig << 32'd2;

assign v7_2_1_Addr_A_orig = zext_ln438_1_fu_655_p1;

assign v7_2_1_Din_A = bitcast_ln70;

assign v7_2_2_Addr_A = v7_2_2_Addr_A_orig << 32'd2;

assign v7_2_2_Addr_A_orig = zext_ln438_1_fu_655_p1;

assign v7_2_2_Din_A = bitcast_ln70;

assign v7_2_3_Addr_A = v7_2_3_Addr_A_orig << 32'd2;

assign v7_2_3_Addr_A_orig = zext_ln438_1_fu_655_p1;

assign v7_2_3_Din_A = bitcast_ln70;

assign v7_2_4_Addr_A = v7_2_4_Addr_A_orig << 32'd2;

assign v7_2_4_Addr_A_orig = zext_ln438_1_fu_655_p1;

assign v7_2_4_Din_A = bitcast_ln70;

assign v7_2_5_Addr_A = v7_2_5_Addr_A_orig << 32'd2;

assign v7_2_5_Addr_A_orig = zext_ln438_1_fu_655_p1;

assign v7_2_5_Din_A = bitcast_ln70;

assign v7_2_6_Addr_A = v7_2_6_Addr_A_orig << 32'd2;

assign v7_2_6_Addr_A_orig = zext_ln438_1_fu_655_p1;

assign v7_2_6_Din_A = bitcast_ln70;

assign v7_2_7_Addr_A = v7_2_7_Addr_A_orig << 32'd2;

assign v7_2_7_Addr_A_orig = zext_ln438_1_fu_655_p1;

assign v7_2_7_Din_A = bitcast_ln70;

assign v7_3_0_Addr_A = v7_3_0_Addr_A_orig << 32'd2;

assign v7_3_0_Addr_A_orig = zext_ln438_1_fu_655_p1;

assign v7_3_0_Din_A = bitcast_ln70;

assign v7_3_1_Addr_A = v7_3_1_Addr_A_orig << 32'd2;

assign v7_3_1_Addr_A_orig = zext_ln438_1_fu_655_p1;

assign v7_3_1_Din_A = bitcast_ln70;

assign v7_3_2_Addr_A = v7_3_2_Addr_A_orig << 32'd2;

assign v7_3_2_Addr_A_orig = zext_ln438_1_fu_655_p1;

assign v7_3_2_Din_A = bitcast_ln70;

assign v7_3_3_Addr_A = v7_3_3_Addr_A_orig << 32'd2;

assign v7_3_3_Addr_A_orig = zext_ln438_1_fu_655_p1;

assign v7_3_3_Din_A = bitcast_ln70;

assign v7_3_4_Addr_A = v7_3_4_Addr_A_orig << 32'd2;

assign v7_3_4_Addr_A_orig = zext_ln438_1_fu_655_p1;

assign v7_3_4_Din_A = bitcast_ln70;

assign v7_3_5_Addr_A = v7_3_5_Addr_A_orig << 32'd2;

assign v7_3_5_Addr_A_orig = zext_ln438_1_fu_655_p1;

assign v7_3_5_Din_A = bitcast_ln70;

assign v7_3_6_Addr_A = v7_3_6_Addr_A_orig << 32'd2;

assign v7_3_6_Addr_A_orig = zext_ln438_1_fu_655_p1;

assign v7_3_6_Din_A = bitcast_ln70;

assign v7_3_7_Addr_A = v7_3_7_Addr_A_orig << 32'd2;

assign v7_3_7_Addr_A_orig = zext_ln438_1_fu_655_p1;

assign v7_3_7_Din_A = bitcast_ln70;

assign zext_ln438_1_fu_655_p1 = add_ln438_reg_750;

assign zext_ln438_fu_624_p1 = select_ln435_fu_596_p3;

endmodule //test_3mm_2048_test_3mm_2048_Pipeline_VITIS_LOOP_435_11_VITIS_LOOP_436_12
