// ==============================================================
// RTL generated by Vitis HLS - High-Level Synthesis from C, C++ and OpenCL v2022.2 (64-bit)
// Version: 2022.2
// Copyright (C) Copyright 1986-2022 Xilinx, Inc. All Rights Reserved.
// 
// ===========================================================

`timescale 1 ns / 1 ps 

module test_gaussian_4096_test_gaussian_4096_Pipeline_VITIS_LOOP_58_1_VITIS_LOOP_59_2 (
        ap_clk,
        ap_rst,
        ap_start,
        ap_done,
        ap_idle,
        ap_ready,
        v5_0_0_0_Addr_A,
        v5_0_0_0_EN_A,
        v5_0_0_0_WEN_A,
        v5_0_0_0_Din_A,
        v5_0_0_0_Dout_A,
        v5_0_0_1_Addr_A,
        v5_0_0_1_EN_A,
        v5_0_0_1_WEN_A,
        v5_0_0_1_Din_A,
        v5_0_0_1_Dout_A,
        v5_0_0_2_Addr_A,
        v5_0_0_2_EN_A,
        v5_0_0_2_WEN_A,
        v5_0_0_2_Din_A,
        v5_0_0_2_Dout_A,
        v5_0_1_0_Addr_A,
        v5_0_1_0_EN_A,
        v5_0_1_0_WEN_A,
        v5_0_1_0_Din_A,
        v5_0_1_0_Dout_A,
        v5_0_1_1_Addr_A,
        v5_0_1_1_EN_A,
        v5_0_1_1_WEN_A,
        v5_0_1_1_Din_A,
        v5_0_1_1_Dout_A,
        v5_0_1_2_Addr_A,
        v5_0_1_2_EN_A,
        v5_0_1_2_WEN_A,
        v5_0_1_2_Din_A,
        v5_0_1_2_Dout_A,
        v5_0_2_0_Addr_A,
        v5_0_2_0_EN_A,
        v5_0_2_0_WEN_A,
        v5_0_2_0_Din_A,
        v5_0_2_0_Dout_A,
        v5_0_2_1_Addr_A,
        v5_0_2_1_EN_A,
        v5_0_2_1_WEN_A,
        v5_0_2_1_Din_A,
        v5_0_2_1_Dout_A,
        v5_0_2_2_Addr_A,
        v5_0_2_2_EN_A,
        v5_0_2_2_WEN_A,
        v5_0_2_2_Din_A,
        v5_0_2_2_Dout_A,
        v5_1_0_0_Addr_A,
        v5_1_0_0_EN_A,
        v5_1_0_0_WEN_A,
        v5_1_0_0_Din_A,
        v5_1_0_0_Dout_A,
        v5_1_0_1_Addr_A,
        v5_1_0_1_EN_A,
        v5_1_0_1_WEN_A,
        v5_1_0_1_Din_A,
        v5_1_0_1_Dout_A,
        v5_1_0_2_Addr_A,
        v5_1_0_2_EN_A,
        v5_1_0_2_WEN_A,
        v5_1_0_2_Din_A,
        v5_1_0_2_Dout_A,
        v5_1_1_0_Addr_A,
        v5_1_1_0_EN_A,
        v5_1_1_0_WEN_A,
        v5_1_1_0_Din_A,
        v5_1_1_0_Dout_A,
        v5_1_1_1_Addr_A,
        v5_1_1_1_EN_A,
        v5_1_1_1_WEN_A,
        v5_1_1_1_Din_A,
        v5_1_1_1_Dout_A,
        v5_1_1_2_Addr_A,
        v5_1_1_2_EN_A,
        v5_1_1_2_WEN_A,
        v5_1_1_2_Din_A,
        v5_1_1_2_Dout_A,
        v5_1_2_0_Addr_A,
        v5_1_2_0_EN_A,
        v5_1_2_0_WEN_A,
        v5_1_2_0_Din_A,
        v5_1_2_0_Dout_A,
        v5_1_2_1_Addr_A,
        v5_1_2_1_EN_A,
        v5_1_2_1_WEN_A,
        v5_1_2_1_Din_A,
        v5_1_2_1_Dout_A,
        v5_1_2_2_Addr_A,
        v5_1_2_2_EN_A,
        v5_1_2_2_WEN_A,
        v5_1_2_2_Din_A,
        v5_1_2_2_Dout_A,
        v5_2_0_0_Addr_A,
        v5_2_0_0_EN_A,
        v5_2_0_0_WEN_A,
        v5_2_0_0_Din_A,
        v5_2_0_0_Dout_A,
        v5_2_0_1_Addr_A,
        v5_2_0_1_EN_A,
        v5_2_0_1_WEN_A,
        v5_2_0_1_Din_A,
        v5_2_0_1_Dout_A,
        v5_2_0_2_Addr_A,
        v5_2_0_2_EN_A,
        v5_2_0_2_WEN_A,
        v5_2_0_2_Din_A,
        v5_2_0_2_Dout_A,
        v5_2_1_0_Addr_A,
        v5_2_1_0_EN_A,
        v5_2_1_0_WEN_A,
        v5_2_1_0_Din_A,
        v5_2_1_0_Dout_A,
        v5_2_1_1_Addr_A,
        v5_2_1_1_EN_A,
        v5_2_1_1_WEN_A,
        v5_2_1_1_Din_A,
        v5_2_1_1_Dout_A,
        v5_2_1_2_Addr_A,
        v5_2_1_2_EN_A,
        v5_2_1_2_WEN_A,
        v5_2_1_2_Din_A,
        v5_2_1_2_Dout_A,
        v5_2_2_0_Addr_A,
        v5_2_2_0_EN_A,
        v5_2_2_0_WEN_A,
        v5_2_2_0_Din_A,
        v5_2_2_0_Dout_A,
        v5_2_2_1_Addr_A,
        v5_2_2_1_EN_A,
        v5_2_2_1_WEN_A,
        v5_2_2_1_Din_A,
        v5_2_2_1_Dout_A,
        v5_2_2_2_Addr_A,
        v5_2_2_2_EN_A,
        v5_2_2_2_WEN_A,
        v5_2_2_2_Din_A,
        v5_2_2_2_Dout_A,
        v1_0_0_0_Addr_A,
        v1_0_0_0_EN_A,
        v1_0_0_0_WEN_A,
        v1_0_0_0_Din_A,
        v1_0_0_0_Dout_A,
        v1_0_0_1_Addr_A,
        v1_0_0_1_EN_A,
        v1_0_0_1_WEN_A,
        v1_0_0_1_Din_A,
        v1_0_0_1_Dout_A,
        v1_0_0_2_Addr_A,
        v1_0_0_2_EN_A,
        v1_0_0_2_WEN_A,
        v1_0_0_2_Din_A,
        v1_0_0_2_Dout_A,
        v1_0_1_0_Addr_A,
        v1_0_1_0_EN_A,
        v1_0_1_0_WEN_A,
        v1_0_1_0_Din_A,
        v1_0_1_0_Dout_A,
        v1_0_1_1_Addr_A,
        v1_0_1_1_EN_A,
        v1_0_1_1_WEN_A,
        v1_0_1_1_Din_A,
        v1_0_1_1_Dout_A,
        v1_0_1_2_Addr_A,
        v1_0_1_2_EN_A,
        v1_0_1_2_WEN_A,
        v1_0_1_2_Din_A,
        v1_0_1_2_Dout_A,
        v1_0_2_0_Addr_A,
        v1_0_2_0_EN_A,
        v1_0_2_0_WEN_A,
        v1_0_2_0_Din_A,
        v1_0_2_0_Dout_A,
        v1_0_2_1_Addr_A,
        v1_0_2_1_EN_A,
        v1_0_2_1_WEN_A,
        v1_0_2_1_Din_A,
        v1_0_2_1_Dout_A,
        v1_0_2_2_Addr_A,
        v1_0_2_2_EN_A,
        v1_0_2_2_WEN_A,
        v1_0_2_2_Din_A,
        v1_0_2_2_Dout_A,
        v1_1_0_0_Addr_A,
        v1_1_0_0_EN_A,
        v1_1_0_0_WEN_A,
        v1_1_0_0_Din_A,
        v1_1_0_0_Dout_A,
        v1_1_0_1_Addr_A,
        v1_1_0_1_EN_A,
        v1_1_0_1_WEN_A,
        v1_1_0_1_Din_A,
        v1_1_0_1_Dout_A,
        v1_1_0_2_Addr_A,
        v1_1_0_2_EN_A,
        v1_1_0_2_WEN_A,
        v1_1_0_2_Din_A,
        v1_1_0_2_Dout_A,
        v1_1_1_0_Addr_A,
        v1_1_1_0_EN_A,
        v1_1_1_0_WEN_A,
        v1_1_1_0_Din_A,
        v1_1_1_0_Dout_A,
        v1_1_1_1_Addr_A,
        v1_1_1_1_EN_A,
        v1_1_1_1_WEN_A,
        v1_1_1_1_Din_A,
        v1_1_1_1_Dout_A,
        v1_1_1_2_Addr_A,
        v1_1_1_2_EN_A,
        v1_1_1_2_WEN_A,
        v1_1_1_2_Din_A,
        v1_1_1_2_Dout_A,
        v1_1_2_0_Addr_A,
        v1_1_2_0_EN_A,
        v1_1_2_0_WEN_A,
        v1_1_2_0_Din_A,
        v1_1_2_0_Dout_A,
        v1_1_2_1_Addr_A,
        v1_1_2_1_EN_A,
        v1_1_2_1_WEN_A,
        v1_1_2_1_Din_A,
        v1_1_2_1_Dout_A,
        v1_1_2_2_Addr_A,
        v1_1_2_2_EN_A,
        v1_1_2_2_WEN_A,
        v1_1_2_2_Din_A,
        v1_1_2_2_Dout_A,
        v1_2_0_0_Addr_A,
        v1_2_0_0_EN_A,
        v1_2_0_0_WEN_A,
        v1_2_0_0_Din_A,
        v1_2_0_0_Dout_A,
        v1_2_0_1_Addr_A,
        v1_2_0_1_EN_A,
        v1_2_0_1_WEN_A,
        v1_2_0_1_Din_A,
        v1_2_0_1_Dout_A,
        v1_2_0_2_Addr_A,
        v1_2_0_2_EN_A,
        v1_2_0_2_WEN_A,
        v1_2_0_2_Din_A,
        v1_2_0_2_Dout_A,
        v1_2_1_0_Addr_A,
        v1_2_1_0_EN_A,
        v1_2_1_0_WEN_A,
        v1_2_1_0_Din_A,
        v1_2_1_0_Dout_A,
        v1_2_1_1_Addr_A,
        v1_2_1_1_EN_A,
        v1_2_1_1_WEN_A,
        v1_2_1_1_Din_A,
        v1_2_1_1_Dout_A,
        v1_2_1_2_Addr_A,
        v1_2_1_2_EN_A,
        v1_2_1_2_WEN_A,
        v1_2_1_2_Din_A,
        v1_2_1_2_Dout_A,
        v1_2_2_0_Addr_A,
        v1_2_2_0_EN_A,
        v1_2_2_0_WEN_A,
        v1_2_2_0_Din_A,
        v1_2_2_0_Dout_A,
        v1_2_2_1_Addr_A,
        v1_2_2_1_EN_A,
        v1_2_2_1_WEN_A,
        v1_2_2_1_Din_A,
        v1_2_2_1_Dout_A,
        v1_2_2_2_Addr_A,
        v1_2_2_2_EN_A,
        v1_2_2_2_WEN_A,
        v1_2_2_2_Din_A,
        v1_2_2_2_Dout_A,
        bitcast_ln61
);

parameter    ap_ST_fsm_pp0_stage0 = 1'd1;

input   ap_clk;
input   ap_rst;
input   ap_start;
output   ap_done;
output   ap_idle;
output   ap_ready;
output  [31:0] v5_0_0_0_Addr_A;
output   v5_0_0_0_EN_A;
output  [3:0] v5_0_0_0_WEN_A;
output  [31:0] v5_0_0_0_Din_A;
input  [31:0] v5_0_0_0_Dout_A;
output  [31:0] v5_0_0_1_Addr_A;
output   v5_0_0_1_EN_A;
output  [3:0] v5_0_0_1_WEN_A;
output  [31:0] v5_0_0_1_Din_A;
input  [31:0] v5_0_0_1_Dout_A;
output  [31:0] v5_0_0_2_Addr_A;
output   v5_0_0_2_EN_A;
output  [3:0] v5_0_0_2_WEN_A;
output  [31:0] v5_0_0_2_Din_A;
input  [31:0] v5_0_0_2_Dout_A;
output  [31:0] v5_0_1_0_Addr_A;
output   v5_0_1_0_EN_A;
output  [3:0] v5_0_1_0_WEN_A;
output  [31:0] v5_0_1_0_Din_A;
input  [31:0] v5_0_1_0_Dout_A;
output  [31:0] v5_0_1_1_Addr_A;
output   v5_0_1_1_EN_A;
output  [3:0] v5_0_1_1_WEN_A;
output  [31:0] v5_0_1_1_Din_A;
input  [31:0] v5_0_1_1_Dout_A;
output  [31:0] v5_0_1_2_Addr_A;
output   v5_0_1_2_EN_A;
output  [3:0] v5_0_1_2_WEN_A;
output  [31:0] v5_0_1_2_Din_A;
input  [31:0] v5_0_1_2_Dout_A;
output  [31:0] v5_0_2_0_Addr_A;
output   v5_0_2_0_EN_A;
output  [3:0] v5_0_2_0_WEN_A;
output  [31:0] v5_0_2_0_Din_A;
input  [31:0] v5_0_2_0_Dout_A;
output  [31:0] v5_0_2_1_Addr_A;
output   v5_0_2_1_EN_A;
output  [3:0] v5_0_2_1_WEN_A;
output  [31:0] v5_0_2_1_Din_A;
input  [31:0] v5_0_2_1_Dout_A;
output  [31:0] v5_0_2_2_Addr_A;
output   v5_0_2_2_EN_A;
output  [3:0] v5_0_2_2_WEN_A;
output  [31:0] v5_0_2_2_Din_A;
input  [31:0] v5_0_2_2_Dout_A;
output  [31:0] v5_1_0_0_Addr_A;
output   v5_1_0_0_EN_A;
output  [3:0] v5_1_0_0_WEN_A;
output  [31:0] v5_1_0_0_Din_A;
input  [31:0] v5_1_0_0_Dout_A;
output  [31:0] v5_1_0_1_Addr_A;
output   v5_1_0_1_EN_A;
output  [3:0] v5_1_0_1_WEN_A;
output  [31:0] v5_1_0_1_Din_A;
input  [31:0] v5_1_0_1_Dout_A;
output  [31:0] v5_1_0_2_Addr_A;
output   v5_1_0_2_EN_A;
output  [3:0] v5_1_0_2_WEN_A;
output  [31:0] v5_1_0_2_Din_A;
input  [31:0] v5_1_0_2_Dout_A;
output  [31:0] v5_1_1_0_Addr_A;
output   v5_1_1_0_EN_A;
output  [3:0] v5_1_1_0_WEN_A;
output  [31:0] v5_1_1_0_Din_A;
input  [31:0] v5_1_1_0_Dout_A;
output  [31:0] v5_1_1_1_Addr_A;
output   v5_1_1_1_EN_A;
output  [3:0] v5_1_1_1_WEN_A;
output  [31:0] v5_1_1_1_Din_A;
input  [31:0] v5_1_1_1_Dout_A;
output  [31:0] v5_1_1_2_Addr_A;
output   v5_1_1_2_EN_A;
output  [3:0] v5_1_1_2_WEN_A;
output  [31:0] v5_1_1_2_Din_A;
input  [31:0] v5_1_1_2_Dout_A;
output  [31:0] v5_1_2_0_Addr_A;
output   v5_1_2_0_EN_A;
output  [3:0] v5_1_2_0_WEN_A;
output  [31:0] v5_1_2_0_Din_A;
input  [31:0] v5_1_2_0_Dout_A;
output  [31:0] v5_1_2_1_Addr_A;
output   v5_1_2_1_EN_A;
output  [3:0] v5_1_2_1_WEN_A;
output  [31:0] v5_1_2_1_Din_A;
input  [31:0] v5_1_2_1_Dout_A;
output  [31:0] v5_1_2_2_Addr_A;
output   v5_1_2_2_EN_A;
output  [3:0] v5_1_2_2_WEN_A;
output  [31:0] v5_1_2_2_Din_A;
input  [31:0] v5_1_2_2_Dout_A;
output  [31:0] v5_2_0_0_Addr_A;
output   v5_2_0_0_EN_A;
output  [3:0] v5_2_0_0_WEN_A;
output  [31:0] v5_2_0_0_Din_A;
input  [31:0] v5_2_0_0_Dout_A;
output  [31:0] v5_2_0_1_Addr_A;
output   v5_2_0_1_EN_A;
output  [3:0] v5_2_0_1_WEN_A;
output  [31:0] v5_2_0_1_Din_A;
input  [31:0] v5_2_0_1_Dout_A;
output  [31:0] v5_2_0_2_Addr_A;
output   v5_2_0_2_EN_A;
output  [3:0] v5_2_0_2_WEN_A;
output  [31:0] v5_2_0_2_Din_A;
input  [31:0] v5_2_0_2_Dout_A;
output  [31:0] v5_2_1_0_Addr_A;
output   v5_2_1_0_EN_A;
output  [3:0] v5_2_1_0_WEN_A;
output  [31:0] v5_2_1_0_Din_A;
input  [31:0] v5_2_1_0_Dout_A;
output  [31:0] v5_2_1_1_Addr_A;
output   v5_2_1_1_EN_A;
output  [3:0] v5_2_1_1_WEN_A;
output  [31:0] v5_2_1_1_Din_A;
input  [31:0] v5_2_1_1_Dout_A;
output  [31:0] v5_2_1_2_Addr_A;
output   v5_2_1_2_EN_A;
output  [3:0] v5_2_1_2_WEN_A;
output  [31:0] v5_2_1_2_Din_A;
input  [31:0] v5_2_1_2_Dout_A;
output  [31:0] v5_2_2_0_Addr_A;
output   v5_2_2_0_EN_A;
output  [3:0] v5_2_2_0_WEN_A;
output  [31:0] v5_2_2_0_Din_A;
input  [31:0] v5_2_2_0_Dout_A;
output  [31:0] v5_2_2_1_Addr_A;
output   v5_2_2_1_EN_A;
output  [3:0] v5_2_2_1_WEN_A;
output  [31:0] v5_2_2_1_Din_A;
input  [31:0] v5_2_2_1_Dout_A;
output  [31:0] v5_2_2_2_Addr_A;
output   v5_2_2_2_EN_A;
output  [3:0] v5_2_2_2_WEN_A;
output  [31:0] v5_2_2_2_Din_A;
input  [31:0] v5_2_2_2_Dout_A;
output  [31:0] v1_0_0_0_Addr_A;
output   v1_0_0_0_EN_A;
output  [3:0] v1_0_0_0_WEN_A;
output  [31:0] v1_0_0_0_Din_A;
input  [31:0] v1_0_0_0_Dout_A;
output  [31:0] v1_0_0_1_Addr_A;
output   v1_0_0_1_EN_A;
output  [3:0] v1_0_0_1_WEN_A;
output  [31:0] v1_0_0_1_Din_A;
input  [31:0] v1_0_0_1_Dout_A;
output  [31:0] v1_0_0_2_Addr_A;
output   v1_0_0_2_EN_A;
output  [3:0] v1_0_0_2_WEN_A;
output  [31:0] v1_0_0_2_Din_A;
input  [31:0] v1_0_0_2_Dout_A;
output  [31:0] v1_0_1_0_Addr_A;
output   v1_0_1_0_EN_A;
output  [3:0] v1_0_1_0_WEN_A;
output  [31:0] v1_0_1_0_Din_A;
input  [31:0] v1_0_1_0_Dout_A;
output  [31:0] v1_0_1_1_Addr_A;
output   v1_0_1_1_EN_A;
output  [3:0] v1_0_1_1_WEN_A;
output  [31:0] v1_0_1_1_Din_A;
input  [31:0] v1_0_1_1_Dout_A;
output  [31:0] v1_0_1_2_Addr_A;
output   v1_0_1_2_EN_A;
output  [3:0] v1_0_1_2_WEN_A;
output  [31:0] v1_0_1_2_Din_A;
input  [31:0] v1_0_1_2_Dout_A;
output  [31:0] v1_0_2_0_Addr_A;
output   v1_0_2_0_EN_A;
output  [3:0] v1_0_2_0_WEN_A;
output  [31:0] v1_0_2_0_Din_A;
input  [31:0] v1_0_2_0_Dout_A;
output  [31:0] v1_0_2_1_Addr_A;
output   v1_0_2_1_EN_A;
output  [3:0] v1_0_2_1_WEN_A;
output  [31:0] v1_0_2_1_Din_A;
input  [31:0] v1_0_2_1_Dout_A;
output  [31:0] v1_0_2_2_Addr_A;
output   v1_0_2_2_EN_A;
output  [3:0] v1_0_2_2_WEN_A;
output  [31:0] v1_0_2_2_Din_A;
input  [31:0] v1_0_2_2_Dout_A;
output  [31:0] v1_1_0_0_Addr_A;
output   v1_1_0_0_EN_A;
output  [3:0] v1_1_0_0_WEN_A;
output  [31:0] v1_1_0_0_Din_A;
input  [31:0] v1_1_0_0_Dout_A;
output  [31:0] v1_1_0_1_Addr_A;
output   v1_1_0_1_EN_A;
output  [3:0] v1_1_0_1_WEN_A;
output  [31:0] v1_1_0_1_Din_A;
input  [31:0] v1_1_0_1_Dout_A;
output  [31:0] v1_1_0_2_Addr_A;
output   v1_1_0_2_EN_A;
output  [3:0] v1_1_0_2_WEN_A;
output  [31:0] v1_1_0_2_Din_A;
input  [31:0] v1_1_0_2_Dout_A;
output  [31:0] v1_1_1_0_Addr_A;
output   v1_1_1_0_EN_A;
output  [3:0] v1_1_1_0_WEN_A;
output  [31:0] v1_1_1_0_Din_A;
input  [31:0] v1_1_1_0_Dout_A;
output  [31:0] v1_1_1_1_Addr_A;
output   v1_1_1_1_EN_A;
output  [3:0] v1_1_1_1_WEN_A;
output  [31:0] v1_1_1_1_Din_A;
input  [31:0] v1_1_1_1_Dout_A;
output  [31:0] v1_1_1_2_Addr_A;
output   v1_1_1_2_EN_A;
output  [3:0] v1_1_1_2_WEN_A;
output  [31:0] v1_1_1_2_Din_A;
input  [31:0] v1_1_1_2_Dout_A;
output  [31:0] v1_1_2_0_Addr_A;
output   v1_1_2_0_EN_A;
output  [3:0] v1_1_2_0_WEN_A;
output  [31:0] v1_1_2_0_Din_A;
input  [31:0] v1_1_2_0_Dout_A;
output  [31:0] v1_1_2_1_Addr_A;
output   v1_1_2_1_EN_A;
output  [3:0] v1_1_2_1_WEN_A;
output  [31:0] v1_1_2_1_Din_A;
input  [31:0] v1_1_2_1_Dout_A;
output  [31:0] v1_1_2_2_Addr_A;
output   v1_1_2_2_EN_A;
output  [3:0] v1_1_2_2_WEN_A;
output  [31:0] v1_1_2_2_Din_A;
input  [31:0] v1_1_2_2_Dout_A;
output  [31:0] v1_2_0_0_Addr_A;
output   v1_2_0_0_EN_A;
output  [3:0] v1_2_0_0_WEN_A;
output  [31:0] v1_2_0_0_Din_A;
input  [31:0] v1_2_0_0_Dout_A;
output  [31:0] v1_2_0_1_Addr_A;
output   v1_2_0_1_EN_A;
output  [3:0] v1_2_0_1_WEN_A;
output  [31:0] v1_2_0_1_Din_A;
input  [31:0] v1_2_0_1_Dout_A;
output  [31:0] v1_2_0_2_Addr_A;
output   v1_2_0_2_EN_A;
output  [3:0] v1_2_0_2_WEN_A;
output  [31:0] v1_2_0_2_Din_A;
input  [31:0] v1_2_0_2_Dout_A;
output  [31:0] v1_2_1_0_Addr_A;
output   v1_2_1_0_EN_A;
output  [3:0] v1_2_1_0_WEN_A;
output  [31:0] v1_2_1_0_Din_A;
input  [31:0] v1_2_1_0_Dout_A;
output  [31:0] v1_2_1_1_Addr_A;
output   v1_2_1_1_EN_A;
output  [3:0] v1_2_1_1_WEN_A;
output  [31:0] v1_2_1_1_Din_A;
input  [31:0] v1_2_1_1_Dout_A;
output  [31:0] v1_2_1_2_Addr_A;
output   v1_2_1_2_EN_A;
output  [3:0] v1_2_1_2_WEN_A;
output  [31:0] v1_2_1_2_Din_A;
input  [31:0] v1_2_1_2_Dout_A;
output  [31:0] v1_2_2_0_Addr_A;
output   v1_2_2_0_EN_A;
output  [3:0] v1_2_2_0_WEN_A;
output  [31:0] v1_2_2_0_Din_A;
input  [31:0] v1_2_2_0_Dout_A;
output  [31:0] v1_2_2_1_Addr_A;
output   v1_2_2_1_EN_A;
output  [3:0] v1_2_2_1_WEN_A;
output  [31:0] v1_2_2_1_Din_A;
input  [31:0] v1_2_2_1_Dout_A;
output  [31:0] v1_2_2_2_Addr_A;
output   v1_2_2_2_EN_A;
output  [3:0] v1_2_2_2_WEN_A;
output  [31:0] v1_2_2_2_Din_A;
input  [31:0] v1_2_2_2_Dout_A;
input  [31:0] bitcast_ln61;

reg ap_idle;
reg v5_0_0_0_EN_A;
reg[3:0] v5_0_0_0_WEN_A;
reg v5_0_0_1_EN_A;
reg[3:0] v5_0_0_1_WEN_A;
reg v5_0_0_2_EN_A;
reg[3:0] v5_0_0_2_WEN_A;
reg v5_0_1_0_EN_A;
reg[3:0] v5_0_1_0_WEN_A;
reg v5_0_1_1_EN_A;
reg[3:0] v5_0_1_1_WEN_A;
reg v5_0_1_2_EN_A;
reg[3:0] v5_0_1_2_WEN_A;
reg v5_0_2_0_EN_A;
reg[3:0] v5_0_2_0_WEN_A;
reg v5_0_2_1_EN_A;
reg[3:0] v5_0_2_1_WEN_A;
reg v5_0_2_2_EN_A;
reg[3:0] v5_0_2_2_WEN_A;
reg v5_1_0_0_EN_A;
reg[3:0] v5_1_0_0_WEN_A;
reg v5_1_0_1_EN_A;
reg[3:0] v5_1_0_1_WEN_A;
reg v5_1_0_2_EN_A;
reg[3:0] v5_1_0_2_WEN_A;
reg v5_1_1_0_EN_A;
reg[3:0] v5_1_1_0_WEN_A;
reg v5_1_1_1_EN_A;
reg[3:0] v5_1_1_1_WEN_A;
reg v5_1_1_2_EN_A;
reg[3:0] v5_1_1_2_WEN_A;
reg v5_1_2_0_EN_A;
reg[3:0] v5_1_2_0_WEN_A;
reg v5_1_2_1_EN_A;
reg[3:0] v5_1_2_1_WEN_A;
reg v5_1_2_2_EN_A;
reg[3:0] v5_1_2_2_WEN_A;
reg v5_2_0_0_EN_A;
reg[3:0] v5_2_0_0_WEN_A;
reg v5_2_0_1_EN_A;
reg[3:0] v5_2_0_1_WEN_A;
reg v5_2_0_2_EN_A;
reg[3:0] v5_2_0_2_WEN_A;
reg v5_2_1_0_EN_A;
reg[3:0] v5_2_1_0_WEN_A;
reg v5_2_1_1_EN_A;
reg[3:0] v5_2_1_1_WEN_A;
reg v5_2_1_2_EN_A;
reg[3:0] v5_2_1_2_WEN_A;
reg v5_2_2_0_EN_A;
reg[3:0] v5_2_2_0_WEN_A;
reg v5_2_2_1_EN_A;
reg[3:0] v5_2_2_1_WEN_A;
reg v5_2_2_2_EN_A;
reg[3:0] v5_2_2_2_WEN_A;
reg v1_0_0_0_EN_A;
reg[3:0] v1_0_0_0_WEN_A;
reg v1_0_0_1_EN_A;
reg[3:0] v1_0_0_1_WEN_A;
reg v1_0_0_2_EN_A;
reg[3:0] v1_0_0_2_WEN_A;
reg v1_0_1_0_EN_A;
reg[3:0] v1_0_1_0_WEN_A;
reg v1_0_1_1_EN_A;
reg[3:0] v1_0_1_1_WEN_A;
reg v1_0_1_2_EN_A;
reg[3:0] v1_0_1_2_WEN_A;
reg v1_0_2_0_EN_A;
reg[3:0] v1_0_2_0_WEN_A;
reg v1_0_2_1_EN_A;
reg[3:0] v1_0_2_1_WEN_A;
reg v1_0_2_2_EN_A;
reg[3:0] v1_0_2_2_WEN_A;
reg v1_1_0_0_EN_A;
reg[3:0] v1_1_0_0_WEN_A;
reg v1_1_0_1_EN_A;
reg[3:0] v1_1_0_1_WEN_A;
reg v1_1_0_2_EN_A;
reg[3:0] v1_1_0_2_WEN_A;
reg v1_1_1_0_EN_A;
reg[3:0] v1_1_1_0_WEN_A;
reg v1_1_1_1_EN_A;
reg[3:0] v1_1_1_1_WEN_A;
reg v1_1_1_2_EN_A;
reg[3:0] v1_1_1_2_WEN_A;
reg v1_1_2_0_EN_A;
reg[3:0] v1_1_2_0_WEN_A;
reg v1_1_2_1_EN_A;
reg[3:0] v1_1_2_1_WEN_A;
reg v1_1_2_2_EN_A;
reg[3:0] v1_1_2_2_WEN_A;
reg v1_2_0_0_EN_A;
reg[3:0] v1_2_0_0_WEN_A;
reg v1_2_0_1_EN_A;
reg[3:0] v1_2_0_1_WEN_A;
reg v1_2_0_2_EN_A;
reg[3:0] v1_2_0_2_WEN_A;
reg v1_2_1_0_EN_A;
reg[3:0] v1_2_1_0_WEN_A;
reg v1_2_1_1_EN_A;
reg[3:0] v1_2_1_1_WEN_A;
reg v1_2_1_2_EN_A;
reg[3:0] v1_2_1_2_WEN_A;
reg v1_2_2_0_EN_A;
reg[3:0] v1_2_2_0_WEN_A;
reg v1_2_2_1_EN_A;
reg[3:0] v1_2_2_1_WEN_A;
reg v1_2_2_2_EN_A;
reg[3:0] v1_2_2_2_WEN_A;

(* fsm_encoding = "none" *) reg   [0:0] ap_CS_fsm;
wire    ap_CS_fsm_pp0_stage0;
wire    ap_enable_reg_pp0_iter0;
reg    ap_enable_reg_pp0_iter1;
reg    ap_enable_reg_pp0_iter2;
reg    ap_enable_reg_pp0_iter3;
reg    ap_enable_reg_pp0_iter4;
reg    ap_idle_pp0;
wire    ap_block_state1_pp0_stage0_iter0;
wire    ap_block_state2_pp0_stage0_iter1;
wire    ap_block_state3_pp0_stage0_iter2;
wire    ap_block_state4_pp0_stage0_iter3;
wire    ap_block_state5_pp0_stage0_iter4;
wire    ap_block_pp0_stage0_subdone;
wire   [0:0] icmp_ln58_fu_890_p2;
reg    ap_condition_exit_pp0_iter1_stage0;
wire    ap_loop_exit_ready;
reg    ap_ready_int;
wire    ap_block_pp0_stage0_11001;
wire   [10:0] select_ln58_fu_920_p3;
reg   [10:0] select_ln58_reg_1113;
reg   [10:0] select_ln58_reg_1113_pp0_iter2_reg;
wire   [63:0] zext_ln62_1_fu_964_p1;
wire    ap_block_pp0_stage0;
reg   [10:0] v7_fu_152;
wire   [10:0] add_ln59_fu_940_p2;
wire    ap_loop_init;
reg   [10:0] v6_fu_156;
wire   [10:0] select_ln58_1_fu_928_p3;
reg   [20:0] indvar_flatten_fu_160;
wire   [20:0] add_ln58_1_fu_896_p2;
wire   [31:0] v5_0_0_0_Addr_A_orig;
wire   [31:0] v1_0_0_0_Addr_A_orig;
wire   [31:0] v5_0_1_0_Addr_A_orig;
wire   [31:0] v1_0_1_0_Addr_A_orig;
wire   [31:0] v5_0_2_0_Addr_A_orig;
wire   [31:0] v1_0_2_0_Addr_A_orig;
wire   [31:0] v5_1_0_0_Addr_A_orig;
wire   [31:0] v1_1_0_0_Addr_A_orig;
wire   [31:0] v5_1_1_0_Addr_A_orig;
wire   [31:0] v1_1_1_0_Addr_A_orig;
wire   [31:0] v5_1_2_0_Addr_A_orig;
wire   [31:0] v1_1_2_0_Addr_A_orig;
wire   [31:0] v5_2_0_0_Addr_A_orig;
wire   [31:0] v1_2_0_0_Addr_A_orig;
wire   [31:0] v5_2_1_0_Addr_A_orig;
wire   [31:0] v1_2_1_0_Addr_A_orig;
wire   [31:0] v5_2_2_0_Addr_A_orig;
wire   [31:0] v1_2_2_0_Addr_A_orig;
wire   [31:0] v5_0_0_1_Addr_A_orig;
wire   [31:0] v1_0_0_1_Addr_A_orig;
wire   [31:0] v5_0_1_1_Addr_A_orig;
wire   [31:0] v1_0_1_1_Addr_A_orig;
wire   [31:0] v5_0_2_1_Addr_A_orig;
wire   [31:0] v1_0_2_1_Addr_A_orig;
wire   [31:0] v5_1_0_1_Addr_A_orig;
wire   [31:0] v1_1_0_1_Addr_A_orig;
wire   [31:0] v5_1_1_1_Addr_A_orig;
wire   [31:0] v1_1_1_1_Addr_A_orig;
wire   [31:0] v5_1_2_1_Addr_A_orig;
wire   [31:0] v1_1_2_1_Addr_A_orig;
wire   [31:0] v5_2_0_1_Addr_A_orig;
wire   [31:0] v1_2_0_1_Addr_A_orig;
wire   [31:0] v5_2_1_1_Addr_A_orig;
wire   [31:0] v1_2_1_1_Addr_A_orig;
wire   [31:0] v5_2_2_1_Addr_A_orig;
wire   [31:0] v1_2_2_1_Addr_A_orig;
wire   [31:0] v5_0_0_2_Addr_A_orig;
wire   [31:0] v1_0_0_2_Addr_A_orig;
wire   [31:0] v5_0_1_2_Addr_A_orig;
wire   [31:0] v1_0_1_2_Addr_A_orig;
wire   [31:0] v5_0_2_2_Addr_A_orig;
wire   [31:0] v1_0_2_2_Addr_A_orig;
wire   [31:0] v5_1_0_2_Addr_A_orig;
wire   [31:0] v1_1_0_2_Addr_A_orig;
wire   [31:0] v5_1_1_2_Addr_A_orig;
wire   [31:0] v1_1_1_2_Addr_A_orig;
wire   [31:0] v5_1_2_2_Addr_A_orig;
wire   [31:0] v1_1_2_2_Addr_A_orig;
wire   [31:0] v5_2_0_2_Addr_A_orig;
wire   [31:0] v1_2_0_2_Addr_A_orig;
wire   [31:0] v5_2_1_2_Addr_A_orig;
wire   [31:0] v1_2_1_2_Addr_A_orig;
wire   [31:0] v5_2_2_2_Addr_A_orig;
wire   [31:0] v1_2_2_2_Addr_A_orig;
wire   [0:0] icmp_ln59_fu_914_p2;
wire   [10:0] add_ln58_fu_908_p2;
wire   [20:0] grp_fu_1021_p3;
wire   [10:0] grp_fu_1021_p0;
wire   [10:0] grp_fu_1021_p1;
wire   [10:0] grp_fu_1021_p2;
reg    ap_done_reg;
wire    ap_continue_int;
reg    ap_done_int;
reg    ap_loop_exit_ready_pp0_iter2_reg;
reg    ap_loop_exit_ready_pp0_iter3_reg;
reg   [0:0] ap_NS_fsm;
wire    ap_enable_pp0;
wire    ap_start_int;
wire   [20:0] grp_fu_1021_p00;
wire   [20:0] grp_fu_1021_p20;
wire    ap_ce_reg;

// power-on initialization
initial begin
#0 ap_CS_fsm = 1'd1;
#0 ap_enable_reg_pp0_iter1 = 1'b0;
#0 ap_enable_reg_pp0_iter2 = 1'b0;
#0 ap_enable_reg_pp0_iter3 = 1'b0;
#0 ap_enable_reg_pp0_iter4 = 1'b0;
#0 ap_done_reg = 1'b0;
end

test_gaussian_4096_mac_muladd_11ns_11ns_11ns_21_4_1 #(
    .ID( 1 ),
    .NUM_STAGE( 4 ),
    .din0_WIDTH( 11 ),
    .din1_WIDTH( 11 ),
    .din2_WIDTH( 11 ),
    .dout_WIDTH( 21 ))
mac_muladd_11ns_11ns_11ns_21_4_1_U1(
    .clk(ap_clk),
    .reset(ap_rst),
    .din0(grp_fu_1021_p0),
    .din1(grp_fu_1021_p1),
    .din2(grp_fu_1021_p2),
    .ce(1'b1),
    .dout(grp_fu_1021_p3)
);

test_gaussian_4096_flow_control_loop_pipe_sequential_init flow_control_loop_pipe_sequential_init_U(
    .ap_clk(ap_clk),
    .ap_rst(ap_rst),
    .ap_start(ap_start),
    .ap_ready(ap_ready),
    .ap_done(ap_done),
    .ap_start_int(ap_start_int),
    .ap_loop_init(ap_loop_init),
    .ap_ready_int(ap_ready_int),
    .ap_loop_exit_ready(ap_condition_exit_pp0_iter1_stage0),
    .ap_loop_exit_done(ap_done_int),
    .ap_continue_int(ap_continue_int),
    .ap_done_int(ap_done_int)
);

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_CS_fsm <= ap_ST_fsm_pp0_stage0;
    end else begin
        ap_CS_fsm <= ap_NS_fsm;
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_done_reg <= 1'b0;
    end else begin
        if ((ap_continue_int == 1'b1)) begin
            ap_done_reg <= 1'b0;
        end else if (((ap_loop_exit_ready_pp0_iter3_reg == 1'b1) & (1'b0 == ap_block_pp0_stage0_subdone))) begin
            ap_done_reg <= 1'b1;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_enable_reg_pp0_iter1 <= 1'b0;
    end else begin
        if ((1'b1 == ap_condition_exit_pp0_iter1_stage0)) begin
            ap_enable_reg_pp0_iter1 <= 1'b0;
        end else if (((1'b0 == ap_block_pp0_stage0_subdone) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
            ap_enable_reg_pp0_iter1 <= ap_start_int;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_enable_reg_pp0_iter2 <= 1'b0;
    end else begin
        if ((1'b1 == ap_condition_exit_pp0_iter1_stage0)) begin
            ap_enable_reg_pp0_iter2 <= 1'b0;
        end else if ((1'b0 == ap_block_pp0_stage0_subdone)) begin
            ap_enable_reg_pp0_iter2 <= ap_enable_reg_pp0_iter1;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_enable_reg_pp0_iter3 <= 1'b0;
    end else begin
        if ((1'b0 == ap_block_pp0_stage0_subdone)) begin
            ap_enable_reg_pp0_iter3 <= ap_enable_reg_pp0_iter2;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_enable_reg_pp0_iter4 <= 1'b0;
    end else begin
        if ((1'b0 == ap_block_pp0_stage0_subdone)) begin
            ap_enable_reg_pp0_iter4 <= ap_enable_reg_pp0_iter3;
        end
    end
end

always @ (posedge ap_clk) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        if ((ap_loop_init == 1'b1)) begin
            indvar_flatten_fu_160 <= 21'd0;
        end else if (((icmp_ln58_fu_890_p2 == 1'd0) & (ap_enable_reg_pp0_iter1 == 1'b1))) begin
            indvar_flatten_fu_160 <= add_ln58_1_fu_896_p2;
        end
    end
end

always @ (posedge ap_clk) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        if ((ap_loop_init == 1'b1)) begin
            v6_fu_156 <= 11'd0;
        end else if (((icmp_ln58_fu_890_p2 == 1'd0) & (ap_enable_reg_pp0_iter1 == 1'b1))) begin
            v6_fu_156 <= select_ln58_1_fu_928_p3;
        end
    end
end

always @ (posedge ap_clk) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        if ((ap_loop_init == 1'b1)) begin
            v7_fu_152 <= 11'd0;
        end else if (((icmp_ln58_fu_890_p2 == 1'd0) & (ap_enable_reg_pp0_iter1 == 1'b1))) begin
            v7_fu_152 <= add_ln59_fu_940_p2;
        end
    end
end

always @ (posedge ap_clk) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        ap_loop_exit_ready_pp0_iter2_reg <= ap_loop_exit_ready;
    end
end

always @ (posedge ap_clk) begin
    if ((1'b0 == ap_block_pp0_stage0_11001)) begin
        ap_loop_exit_ready_pp0_iter3_reg <= ap_loop_exit_ready_pp0_iter2_reg;
        select_ln58_reg_1113_pp0_iter2_reg <= select_ln58_reg_1113;
    end
end

always @ (posedge ap_clk) begin
    if (((icmp_ln58_fu_890_p2 == 1'd0) & (1'b0 == ap_block_pp0_stage0_11001) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        select_ln58_reg_1113 <= select_ln58_fu_920_p3;
    end
end

always @ (*) begin
    if (((icmp_ln58_fu_890_p2 == 1'd1) & (1'b0 == ap_block_pp0_stage0_subdone) & (ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        ap_condition_exit_pp0_iter1_stage0 = 1'b1;
    end else begin
        ap_condition_exit_pp0_iter1_stage0 = 1'b0;
    end
end

always @ (*) begin
    if (((ap_loop_exit_ready_pp0_iter3_reg == 1'b1) & (1'b0 == ap_block_pp0_stage0_subdone))) begin
        ap_done_int = 1'b1;
    end else begin
        ap_done_int = ap_done_reg;
    end
end

always @ (*) begin
    if (((ap_start_int == 1'b0) & (ap_idle_pp0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        ap_idle = 1'b1;
    end else begin
        ap_idle = 1'b0;
    end
end

always @ (*) begin
    if (((ap_enable_reg_pp0_iter4 == 1'b0) & (ap_enable_reg_pp0_iter3 == 1'b0) & (ap_enable_reg_pp0_iter2 == 1'b0) & (ap_enable_reg_pp0_iter1 == 1'b0) & (ap_enable_reg_pp0_iter0 == 1'b0))) begin
        ap_idle_pp0 = 1'b1;
    end else begin
        ap_idle_pp0 = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_subdone) & (ap_enable_reg_pp0_iter0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        ap_ready_int = 1'b1;
    end else begin
        ap_ready_int = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter4 == 1'b1))) begin
        v1_0_0_0_EN_A = 1'b1;
    end else begin
        v1_0_0_0_EN_A = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter4 == 1'b1))) begin
        v1_0_0_0_WEN_A = 4'd15;
    end else begin
        v1_0_0_0_WEN_A = 4'd0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter4 == 1'b1))) begin
        v1_0_0_1_EN_A = 1'b1;
    end else begin
        v1_0_0_1_EN_A = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter4 == 1'b1))) begin
        v1_0_0_1_WEN_A = 4'd15;
    end else begin
        v1_0_0_1_WEN_A = 4'd0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter4 == 1'b1))) begin
        v1_0_0_2_EN_A = 1'b1;
    end else begin
        v1_0_0_2_EN_A = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter4 == 1'b1))) begin
        v1_0_0_2_WEN_A = 4'd15;
    end else begin
        v1_0_0_2_WEN_A = 4'd0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter4 == 1'b1))) begin
        v1_0_1_0_EN_A = 1'b1;
    end else begin
        v1_0_1_0_EN_A = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter4 == 1'b1))) begin
        v1_0_1_0_WEN_A = 4'd15;
    end else begin
        v1_0_1_0_WEN_A = 4'd0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter4 == 1'b1))) begin
        v1_0_1_1_EN_A = 1'b1;
    end else begin
        v1_0_1_1_EN_A = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter4 == 1'b1))) begin
        v1_0_1_1_WEN_A = 4'd15;
    end else begin
        v1_0_1_1_WEN_A = 4'd0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter4 == 1'b1))) begin
        v1_0_1_2_EN_A = 1'b1;
    end else begin
        v1_0_1_2_EN_A = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter4 == 1'b1))) begin
        v1_0_1_2_WEN_A = 4'd15;
    end else begin
        v1_0_1_2_WEN_A = 4'd0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter4 == 1'b1))) begin
        v1_0_2_0_EN_A = 1'b1;
    end else begin
        v1_0_2_0_EN_A = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter4 == 1'b1))) begin
        v1_0_2_0_WEN_A = 4'd15;
    end else begin
        v1_0_2_0_WEN_A = 4'd0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter4 == 1'b1))) begin
        v1_0_2_1_EN_A = 1'b1;
    end else begin
        v1_0_2_1_EN_A = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter4 == 1'b1))) begin
        v1_0_2_1_WEN_A = 4'd15;
    end else begin
        v1_0_2_1_WEN_A = 4'd0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter4 == 1'b1))) begin
        v1_0_2_2_EN_A = 1'b1;
    end else begin
        v1_0_2_2_EN_A = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter4 == 1'b1))) begin
        v1_0_2_2_WEN_A = 4'd15;
    end else begin
        v1_0_2_2_WEN_A = 4'd0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter4 == 1'b1))) begin
        v1_1_0_0_EN_A = 1'b1;
    end else begin
        v1_1_0_0_EN_A = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter4 == 1'b1))) begin
        v1_1_0_0_WEN_A = 4'd15;
    end else begin
        v1_1_0_0_WEN_A = 4'd0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter4 == 1'b1))) begin
        v1_1_0_1_EN_A = 1'b1;
    end else begin
        v1_1_0_1_EN_A = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter4 == 1'b1))) begin
        v1_1_0_1_WEN_A = 4'd15;
    end else begin
        v1_1_0_1_WEN_A = 4'd0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter4 == 1'b1))) begin
        v1_1_0_2_EN_A = 1'b1;
    end else begin
        v1_1_0_2_EN_A = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter4 == 1'b1))) begin
        v1_1_0_2_WEN_A = 4'd15;
    end else begin
        v1_1_0_2_WEN_A = 4'd0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter4 == 1'b1))) begin
        v1_1_1_0_EN_A = 1'b1;
    end else begin
        v1_1_1_0_EN_A = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter4 == 1'b1))) begin
        v1_1_1_0_WEN_A = 4'd15;
    end else begin
        v1_1_1_0_WEN_A = 4'd0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter4 == 1'b1))) begin
        v1_1_1_1_EN_A = 1'b1;
    end else begin
        v1_1_1_1_EN_A = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter4 == 1'b1))) begin
        v1_1_1_1_WEN_A = 4'd15;
    end else begin
        v1_1_1_1_WEN_A = 4'd0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter4 == 1'b1))) begin
        v1_1_1_2_EN_A = 1'b1;
    end else begin
        v1_1_1_2_EN_A = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter4 == 1'b1))) begin
        v1_1_1_2_WEN_A = 4'd15;
    end else begin
        v1_1_1_2_WEN_A = 4'd0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter4 == 1'b1))) begin
        v1_1_2_0_EN_A = 1'b1;
    end else begin
        v1_1_2_0_EN_A = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter4 == 1'b1))) begin
        v1_1_2_0_WEN_A = 4'd15;
    end else begin
        v1_1_2_0_WEN_A = 4'd0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter4 == 1'b1))) begin
        v1_1_2_1_EN_A = 1'b1;
    end else begin
        v1_1_2_1_EN_A = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter4 == 1'b1))) begin
        v1_1_2_1_WEN_A = 4'd15;
    end else begin
        v1_1_2_1_WEN_A = 4'd0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter4 == 1'b1))) begin
        v1_1_2_2_EN_A = 1'b1;
    end else begin
        v1_1_2_2_EN_A = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter4 == 1'b1))) begin
        v1_1_2_2_WEN_A = 4'd15;
    end else begin
        v1_1_2_2_WEN_A = 4'd0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter4 == 1'b1))) begin
        v1_2_0_0_EN_A = 1'b1;
    end else begin
        v1_2_0_0_EN_A = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter4 == 1'b1))) begin
        v1_2_0_0_WEN_A = 4'd15;
    end else begin
        v1_2_0_0_WEN_A = 4'd0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter4 == 1'b1))) begin
        v1_2_0_1_EN_A = 1'b1;
    end else begin
        v1_2_0_1_EN_A = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter4 == 1'b1))) begin
        v1_2_0_1_WEN_A = 4'd15;
    end else begin
        v1_2_0_1_WEN_A = 4'd0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter4 == 1'b1))) begin
        v1_2_0_2_EN_A = 1'b1;
    end else begin
        v1_2_0_2_EN_A = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter4 == 1'b1))) begin
        v1_2_0_2_WEN_A = 4'd15;
    end else begin
        v1_2_0_2_WEN_A = 4'd0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter4 == 1'b1))) begin
        v1_2_1_0_EN_A = 1'b1;
    end else begin
        v1_2_1_0_EN_A = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter4 == 1'b1))) begin
        v1_2_1_0_WEN_A = 4'd15;
    end else begin
        v1_2_1_0_WEN_A = 4'd0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter4 == 1'b1))) begin
        v1_2_1_1_EN_A = 1'b1;
    end else begin
        v1_2_1_1_EN_A = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter4 == 1'b1))) begin
        v1_2_1_1_WEN_A = 4'd15;
    end else begin
        v1_2_1_1_WEN_A = 4'd0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter4 == 1'b1))) begin
        v1_2_1_2_EN_A = 1'b1;
    end else begin
        v1_2_1_2_EN_A = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter4 == 1'b1))) begin
        v1_2_1_2_WEN_A = 4'd15;
    end else begin
        v1_2_1_2_WEN_A = 4'd0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter4 == 1'b1))) begin
        v1_2_2_0_EN_A = 1'b1;
    end else begin
        v1_2_2_0_EN_A = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter4 == 1'b1))) begin
        v1_2_2_0_WEN_A = 4'd15;
    end else begin
        v1_2_2_0_WEN_A = 4'd0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter4 == 1'b1))) begin
        v1_2_2_1_EN_A = 1'b1;
    end else begin
        v1_2_2_1_EN_A = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter4 == 1'b1))) begin
        v1_2_2_1_WEN_A = 4'd15;
    end else begin
        v1_2_2_1_WEN_A = 4'd0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter4 == 1'b1))) begin
        v1_2_2_2_EN_A = 1'b1;
    end else begin
        v1_2_2_2_EN_A = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter4 == 1'b1))) begin
        v1_2_2_2_WEN_A = 4'd15;
    end else begin
        v1_2_2_2_WEN_A = 4'd0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter4 == 1'b1))) begin
        v5_0_0_0_EN_A = 1'b1;
    end else begin
        v5_0_0_0_EN_A = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter4 == 1'b1))) begin
        v5_0_0_0_WEN_A = 4'd15;
    end else begin
        v5_0_0_0_WEN_A = 4'd0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter4 == 1'b1))) begin
        v5_0_0_1_EN_A = 1'b1;
    end else begin
        v5_0_0_1_EN_A = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter4 == 1'b1))) begin
        v5_0_0_1_WEN_A = 4'd15;
    end else begin
        v5_0_0_1_WEN_A = 4'd0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter4 == 1'b1))) begin
        v5_0_0_2_EN_A = 1'b1;
    end else begin
        v5_0_0_2_EN_A = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter4 == 1'b1))) begin
        v5_0_0_2_WEN_A = 4'd15;
    end else begin
        v5_0_0_2_WEN_A = 4'd0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter4 == 1'b1))) begin
        v5_0_1_0_EN_A = 1'b1;
    end else begin
        v5_0_1_0_EN_A = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter4 == 1'b1))) begin
        v5_0_1_0_WEN_A = 4'd15;
    end else begin
        v5_0_1_0_WEN_A = 4'd0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter4 == 1'b1))) begin
        v5_0_1_1_EN_A = 1'b1;
    end else begin
        v5_0_1_1_EN_A = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter4 == 1'b1))) begin
        v5_0_1_1_WEN_A = 4'd15;
    end else begin
        v5_0_1_1_WEN_A = 4'd0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter4 == 1'b1))) begin
        v5_0_1_2_EN_A = 1'b1;
    end else begin
        v5_0_1_2_EN_A = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter4 == 1'b1))) begin
        v5_0_1_2_WEN_A = 4'd15;
    end else begin
        v5_0_1_2_WEN_A = 4'd0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter4 == 1'b1))) begin
        v5_0_2_0_EN_A = 1'b1;
    end else begin
        v5_0_2_0_EN_A = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter4 == 1'b1))) begin
        v5_0_2_0_WEN_A = 4'd15;
    end else begin
        v5_0_2_0_WEN_A = 4'd0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter4 == 1'b1))) begin
        v5_0_2_1_EN_A = 1'b1;
    end else begin
        v5_0_2_1_EN_A = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter4 == 1'b1))) begin
        v5_0_2_1_WEN_A = 4'd15;
    end else begin
        v5_0_2_1_WEN_A = 4'd0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter4 == 1'b1))) begin
        v5_0_2_2_EN_A = 1'b1;
    end else begin
        v5_0_2_2_EN_A = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter4 == 1'b1))) begin
        v5_0_2_2_WEN_A = 4'd15;
    end else begin
        v5_0_2_2_WEN_A = 4'd0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter4 == 1'b1))) begin
        v5_1_0_0_EN_A = 1'b1;
    end else begin
        v5_1_0_0_EN_A = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter4 == 1'b1))) begin
        v5_1_0_0_WEN_A = 4'd15;
    end else begin
        v5_1_0_0_WEN_A = 4'd0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter4 == 1'b1))) begin
        v5_1_0_1_EN_A = 1'b1;
    end else begin
        v5_1_0_1_EN_A = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter4 == 1'b1))) begin
        v5_1_0_1_WEN_A = 4'd15;
    end else begin
        v5_1_0_1_WEN_A = 4'd0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter4 == 1'b1))) begin
        v5_1_0_2_EN_A = 1'b1;
    end else begin
        v5_1_0_2_EN_A = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter4 == 1'b1))) begin
        v5_1_0_2_WEN_A = 4'd15;
    end else begin
        v5_1_0_2_WEN_A = 4'd0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter4 == 1'b1))) begin
        v5_1_1_0_EN_A = 1'b1;
    end else begin
        v5_1_1_0_EN_A = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter4 == 1'b1))) begin
        v5_1_1_0_WEN_A = 4'd15;
    end else begin
        v5_1_1_0_WEN_A = 4'd0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter4 == 1'b1))) begin
        v5_1_1_1_EN_A = 1'b1;
    end else begin
        v5_1_1_1_EN_A = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter4 == 1'b1))) begin
        v5_1_1_1_WEN_A = 4'd15;
    end else begin
        v5_1_1_1_WEN_A = 4'd0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter4 == 1'b1))) begin
        v5_1_1_2_EN_A = 1'b1;
    end else begin
        v5_1_1_2_EN_A = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter4 == 1'b1))) begin
        v5_1_1_2_WEN_A = 4'd15;
    end else begin
        v5_1_1_2_WEN_A = 4'd0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter4 == 1'b1))) begin
        v5_1_2_0_EN_A = 1'b1;
    end else begin
        v5_1_2_0_EN_A = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter4 == 1'b1))) begin
        v5_1_2_0_WEN_A = 4'd15;
    end else begin
        v5_1_2_0_WEN_A = 4'd0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter4 == 1'b1))) begin
        v5_1_2_1_EN_A = 1'b1;
    end else begin
        v5_1_2_1_EN_A = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter4 == 1'b1))) begin
        v5_1_2_1_WEN_A = 4'd15;
    end else begin
        v5_1_2_1_WEN_A = 4'd0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter4 == 1'b1))) begin
        v5_1_2_2_EN_A = 1'b1;
    end else begin
        v5_1_2_2_EN_A = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter4 == 1'b1))) begin
        v5_1_2_2_WEN_A = 4'd15;
    end else begin
        v5_1_2_2_WEN_A = 4'd0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter4 == 1'b1))) begin
        v5_2_0_0_EN_A = 1'b1;
    end else begin
        v5_2_0_0_EN_A = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter4 == 1'b1))) begin
        v5_2_0_0_WEN_A = 4'd15;
    end else begin
        v5_2_0_0_WEN_A = 4'd0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter4 == 1'b1))) begin
        v5_2_0_1_EN_A = 1'b1;
    end else begin
        v5_2_0_1_EN_A = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter4 == 1'b1))) begin
        v5_2_0_1_WEN_A = 4'd15;
    end else begin
        v5_2_0_1_WEN_A = 4'd0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter4 == 1'b1))) begin
        v5_2_0_2_EN_A = 1'b1;
    end else begin
        v5_2_0_2_EN_A = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter4 == 1'b1))) begin
        v5_2_0_2_WEN_A = 4'd15;
    end else begin
        v5_2_0_2_WEN_A = 4'd0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter4 == 1'b1))) begin
        v5_2_1_0_EN_A = 1'b1;
    end else begin
        v5_2_1_0_EN_A = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter4 == 1'b1))) begin
        v5_2_1_0_WEN_A = 4'd15;
    end else begin
        v5_2_1_0_WEN_A = 4'd0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter4 == 1'b1))) begin
        v5_2_1_1_EN_A = 1'b1;
    end else begin
        v5_2_1_1_EN_A = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter4 == 1'b1))) begin
        v5_2_1_1_WEN_A = 4'd15;
    end else begin
        v5_2_1_1_WEN_A = 4'd0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter4 == 1'b1))) begin
        v5_2_1_2_EN_A = 1'b1;
    end else begin
        v5_2_1_2_EN_A = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter4 == 1'b1))) begin
        v5_2_1_2_WEN_A = 4'd15;
    end else begin
        v5_2_1_2_WEN_A = 4'd0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter4 == 1'b1))) begin
        v5_2_2_0_EN_A = 1'b1;
    end else begin
        v5_2_2_0_EN_A = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter4 == 1'b1))) begin
        v5_2_2_0_WEN_A = 4'd15;
    end else begin
        v5_2_2_0_WEN_A = 4'd0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter4 == 1'b1))) begin
        v5_2_2_1_EN_A = 1'b1;
    end else begin
        v5_2_2_1_EN_A = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter4 == 1'b1))) begin
        v5_2_2_1_WEN_A = 4'd15;
    end else begin
        v5_2_2_1_WEN_A = 4'd0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter4 == 1'b1))) begin
        v5_2_2_2_EN_A = 1'b1;
    end else begin
        v5_2_2_2_EN_A = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter4 == 1'b1))) begin
        v5_2_2_2_WEN_A = 4'd15;
    end else begin
        v5_2_2_2_WEN_A = 4'd0;
    end
end

always @ (*) begin
    case (ap_CS_fsm)
        ap_ST_fsm_pp0_stage0 : begin
            ap_NS_fsm = ap_ST_fsm_pp0_stage0;
        end
        default : begin
            ap_NS_fsm = 'bx;
        end
    endcase
end

assign add_ln58_1_fu_896_p2 = (indvar_flatten_fu_160 + 21'd1);

assign add_ln58_fu_908_p2 = (v6_fu_156 + 11'd1);

assign add_ln59_fu_940_p2 = (select_ln58_fu_920_p3 + 11'd1);

assign ap_CS_fsm_pp0_stage0 = ap_CS_fsm[32'd0];

assign ap_block_pp0_stage0 = ~(1'b1 == 1'b1);

assign ap_block_pp0_stage0_11001 = ~(1'b1 == 1'b1);

assign ap_block_pp0_stage0_subdone = ~(1'b1 == 1'b1);

assign ap_block_state1_pp0_stage0_iter0 = ~(1'b1 == 1'b1);

assign ap_block_state2_pp0_stage0_iter1 = ~(1'b1 == 1'b1);

assign ap_block_state3_pp0_stage0_iter2 = ~(1'b1 == 1'b1);

assign ap_block_state4_pp0_stage0_iter3 = ~(1'b1 == 1'b1);

assign ap_block_state5_pp0_stage0_iter4 = ~(1'b1 == 1'b1);

assign ap_enable_pp0 = (ap_idle_pp0 ^ 1'b1);

assign ap_enable_reg_pp0_iter0 = ap_start_int;

assign ap_loop_exit_ready = ap_condition_exit_pp0_iter1_stage0;

assign grp_fu_1021_p0 = grp_fu_1021_p00;

assign grp_fu_1021_p00 = select_ln58_1_fu_928_p3;

assign grp_fu_1021_p1 = 21'd1366;

assign grp_fu_1021_p2 = grp_fu_1021_p20;

assign grp_fu_1021_p20 = select_ln58_reg_1113_pp0_iter2_reg;

assign icmp_ln58_fu_890_p2 = ((indvar_flatten_fu_160 == 21'd1857769) ? 1'b1 : 1'b0);

assign icmp_ln59_fu_914_p2 = ((v7_fu_152 == 11'd1363) ? 1'b1 : 1'b0);

assign select_ln58_1_fu_928_p3 = ((icmp_ln59_fu_914_p2[0:0] == 1'b1) ? add_ln58_fu_908_p2 : v6_fu_156);

assign select_ln58_fu_920_p3 = ((icmp_ln59_fu_914_p2[0:0] == 1'b1) ? 11'd0 : v7_fu_152);

assign v1_0_0_0_Addr_A = v1_0_0_0_Addr_A_orig << 32'd2;

assign v1_0_0_0_Addr_A_orig = zext_ln62_1_fu_964_p1;

assign v1_0_0_0_Din_A = bitcast_ln61;

assign v1_0_0_1_Addr_A = v1_0_0_1_Addr_A_orig << 32'd2;

assign v1_0_0_1_Addr_A_orig = zext_ln62_1_fu_964_p1;

assign v1_0_0_1_Din_A = bitcast_ln61;

assign v1_0_0_2_Addr_A = v1_0_0_2_Addr_A_orig << 32'd2;

assign v1_0_0_2_Addr_A_orig = zext_ln62_1_fu_964_p1;

assign v1_0_0_2_Din_A = bitcast_ln61;

assign v1_0_1_0_Addr_A = v1_0_1_0_Addr_A_orig << 32'd2;

assign v1_0_1_0_Addr_A_orig = zext_ln62_1_fu_964_p1;

assign v1_0_1_0_Din_A = bitcast_ln61;

assign v1_0_1_1_Addr_A = v1_0_1_1_Addr_A_orig << 32'd2;

assign v1_0_1_1_Addr_A_orig = zext_ln62_1_fu_964_p1;

assign v1_0_1_1_Din_A = bitcast_ln61;

assign v1_0_1_2_Addr_A = v1_0_1_2_Addr_A_orig << 32'd2;

assign v1_0_1_2_Addr_A_orig = zext_ln62_1_fu_964_p1;

assign v1_0_1_2_Din_A = bitcast_ln61;

assign v1_0_2_0_Addr_A = v1_0_2_0_Addr_A_orig << 32'd2;

assign v1_0_2_0_Addr_A_orig = zext_ln62_1_fu_964_p1;

assign v1_0_2_0_Din_A = bitcast_ln61;

assign v1_0_2_1_Addr_A = v1_0_2_1_Addr_A_orig << 32'd2;

assign v1_0_2_1_Addr_A_orig = zext_ln62_1_fu_964_p1;

assign v1_0_2_1_Din_A = bitcast_ln61;

assign v1_0_2_2_Addr_A = v1_0_2_2_Addr_A_orig << 32'd2;

assign v1_0_2_2_Addr_A_orig = zext_ln62_1_fu_964_p1;

assign v1_0_2_2_Din_A = bitcast_ln61;

assign v1_1_0_0_Addr_A = v1_1_0_0_Addr_A_orig << 32'd2;

assign v1_1_0_0_Addr_A_orig = zext_ln62_1_fu_964_p1;

assign v1_1_0_0_Din_A = bitcast_ln61;

assign v1_1_0_1_Addr_A = v1_1_0_1_Addr_A_orig << 32'd2;

assign v1_1_0_1_Addr_A_orig = zext_ln62_1_fu_964_p1;

assign v1_1_0_1_Din_A = bitcast_ln61;

assign v1_1_0_2_Addr_A = v1_1_0_2_Addr_A_orig << 32'd2;

assign v1_1_0_2_Addr_A_orig = zext_ln62_1_fu_964_p1;

assign v1_1_0_2_Din_A = bitcast_ln61;

assign v1_1_1_0_Addr_A = v1_1_1_0_Addr_A_orig << 32'd2;

assign v1_1_1_0_Addr_A_orig = zext_ln62_1_fu_964_p1;

assign v1_1_1_0_Din_A = bitcast_ln61;

assign v1_1_1_1_Addr_A = v1_1_1_1_Addr_A_orig << 32'd2;

assign v1_1_1_1_Addr_A_orig = zext_ln62_1_fu_964_p1;

assign v1_1_1_1_Din_A = bitcast_ln61;

assign v1_1_1_2_Addr_A = v1_1_1_2_Addr_A_orig << 32'd2;

assign v1_1_1_2_Addr_A_orig = zext_ln62_1_fu_964_p1;

assign v1_1_1_2_Din_A = bitcast_ln61;

assign v1_1_2_0_Addr_A = v1_1_2_0_Addr_A_orig << 32'd2;

assign v1_1_2_0_Addr_A_orig = zext_ln62_1_fu_964_p1;

assign v1_1_2_0_Din_A = bitcast_ln61;

assign v1_1_2_1_Addr_A = v1_1_2_1_Addr_A_orig << 32'd2;

assign v1_1_2_1_Addr_A_orig = zext_ln62_1_fu_964_p1;

assign v1_1_2_1_Din_A = bitcast_ln61;

assign v1_1_2_2_Addr_A = v1_1_2_2_Addr_A_orig << 32'd2;

assign v1_1_2_2_Addr_A_orig = zext_ln62_1_fu_964_p1;

assign v1_1_2_2_Din_A = bitcast_ln61;

assign v1_2_0_0_Addr_A = v1_2_0_0_Addr_A_orig << 32'd2;

assign v1_2_0_0_Addr_A_orig = zext_ln62_1_fu_964_p1;

assign v1_2_0_0_Din_A = bitcast_ln61;

assign v1_2_0_1_Addr_A = v1_2_0_1_Addr_A_orig << 32'd2;

assign v1_2_0_1_Addr_A_orig = zext_ln62_1_fu_964_p1;

assign v1_2_0_1_Din_A = bitcast_ln61;

assign v1_2_0_2_Addr_A = v1_2_0_2_Addr_A_orig << 32'd2;

assign v1_2_0_2_Addr_A_orig = zext_ln62_1_fu_964_p1;

assign v1_2_0_2_Din_A = bitcast_ln61;

assign v1_2_1_0_Addr_A = v1_2_1_0_Addr_A_orig << 32'd2;

assign v1_2_1_0_Addr_A_orig = zext_ln62_1_fu_964_p1;

assign v1_2_1_0_Din_A = bitcast_ln61;

assign v1_2_1_1_Addr_A = v1_2_1_1_Addr_A_orig << 32'd2;

assign v1_2_1_1_Addr_A_orig = zext_ln62_1_fu_964_p1;

assign v1_2_1_1_Din_A = bitcast_ln61;

assign v1_2_1_2_Addr_A = v1_2_1_2_Addr_A_orig << 32'd2;

assign v1_2_1_2_Addr_A_orig = zext_ln62_1_fu_964_p1;

assign v1_2_1_2_Din_A = bitcast_ln61;

assign v1_2_2_0_Addr_A = v1_2_2_0_Addr_A_orig << 32'd2;

assign v1_2_2_0_Addr_A_orig = zext_ln62_1_fu_964_p1;

assign v1_2_2_0_Din_A = bitcast_ln61;

assign v1_2_2_1_Addr_A = v1_2_2_1_Addr_A_orig << 32'd2;

assign v1_2_2_1_Addr_A_orig = zext_ln62_1_fu_964_p1;

assign v1_2_2_1_Din_A = bitcast_ln61;

assign v1_2_2_2_Addr_A = v1_2_2_2_Addr_A_orig << 32'd2;

assign v1_2_2_2_Addr_A_orig = zext_ln62_1_fu_964_p1;

assign v1_2_2_2_Din_A = bitcast_ln61;

assign v5_0_0_0_Addr_A = v5_0_0_0_Addr_A_orig << 32'd2;

assign v5_0_0_0_Addr_A_orig = zext_ln62_1_fu_964_p1;

assign v5_0_0_0_Din_A = bitcast_ln61;

assign v5_0_0_1_Addr_A = v5_0_0_1_Addr_A_orig << 32'd2;

assign v5_0_0_1_Addr_A_orig = zext_ln62_1_fu_964_p1;

assign v5_0_0_1_Din_A = bitcast_ln61;

assign v5_0_0_2_Addr_A = v5_0_0_2_Addr_A_orig << 32'd2;

assign v5_0_0_2_Addr_A_orig = zext_ln62_1_fu_964_p1;

assign v5_0_0_2_Din_A = bitcast_ln61;

assign v5_0_1_0_Addr_A = v5_0_1_0_Addr_A_orig << 32'd2;

assign v5_0_1_0_Addr_A_orig = zext_ln62_1_fu_964_p1;

assign v5_0_1_0_Din_A = bitcast_ln61;

assign v5_0_1_1_Addr_A = v5_0_1_1_Addr_A_orig << 32'd2;

assign v5_0_1_1_Addr_A_orig = zext_ln62_1_fu_964_p1;

assign v5_0_1_1_Din_A = bitcast_ln61;

assign v5_0_1_2_Addr_A = v5_0_1_2_Addr_A_orig << 32'd2;

assign v5_0_1_2_Addr_A_orig = zext_ln62_1_fu_964_p1;

assign v5_0_1_2_Din_A = bitcast_ln61;

assign v5_0_2_0_Addr_A = v5_0_2_0_Addr_A_orig << 32'd2;

assign v5_0_2_0_Addr_A_orig = zext_ln62_1_fu_964_p1;

assign v5_0_2_0_Din_A = bitcast_ln61;

assign v5_0_2_1_Addr_A = v5_0_2_1_Addr_A_orig << 32'd2;

assign v5_0_2_1_Addr_A_orig = zext_ln62_1_fu_964_p1;

assign v5_0_2_1_Din_A = bitcast_ln61;

assign v5_0_2_2_Addr_A = v5_0_2_2_Addr_A_orig << 32'd2;

assign v5_0_2_2_Addr_A_orig = zext_ln62_1_fu_964_p1;

assign v5_0_2_2_Din_A = bitcast_ln61;

assign v5_1_0_0_Addr_A = v5_1_0_0_Addr_A_orig << 32'd2;

assign v5_1_0_0_Addr_A_orig = zext_ln62_1_fu_964_p1;

assign v5_1_0_0_Din_A = bitcast_ln61;

assign v5_1_0_1_Addr_A = v5_1_0_1_Addr_A_orig << 32'd2;

assign v5_1_0_1_Addr_A_orig = zext_ln62_1_fu_964_p1;

assign v5_1_0_1_Din_A = bitcast_ln61;

assign v5_1_0_2_Addr_A = v5_1_0_2_Addr_A_orig << 32'd2;

assign v5_1_0_2_Addr_A_orig = zext_ln62_1_fu_964_p1;

assign v5_1_0_2_Din_A = bitcast_ln61;

assign v5_1_1_0_Addr_A = v5_1_1_0_Addr_A_orig << 32'd2;

assign v5_1_1_0_Addr_A_orig = zext_ln62_1_fu_964_p1;

assign v5_1_1_0_Din_A = bitcast_ln61;

assign v5_1_1_1_Addr_A = v5_1_1_1_Addr_A_orig << 32'd2;

assign v5_1_1_1_Addr_A_orig = zext_ln62_1_fu_964_p1;

assign v5_1_1_1_Din_A = bitcast_ln61;

assign v5_1_1_2_Addr_A = v5_1_1_2_Addr_A_orig << 32'd2;

assign v5_1_1_2_Addr_A_orig = zext_ln62_1_fu_964_p1;

assign v5_1_1_2_Din_A = bitcast_ln61;

assign v5_1_2_0_Addr_A = v5_1_2_0_Addr_A_orig << 32'd2;

assign v5_1_2_0_Addr_A_orig = zext_ln62_1_fu_964_p1;

assign v5_1_2_0_Din_A = bitcast_ln61;

assign v5_1_2_1_Addr_A = v5_1_2_1_Addr_A_orig << 32'd2;

assign v5_1_2_1_Addr_A_orig = zext_ln62_1_fu_964_p1;

assign v5_1_2_1_Din_A = bitcast_ln61;

assign v5_1_2_2_Addr_A = v5_1_2_2_Addr_A_orig << 32'd2;

assign v5_1_2_2_Addr_A_orig = zext_ln62_1_fu_964_p1;

assign v5_1_2_2_Din_A = bitcast_ln61;

assign v5_2_0_0_Addr_A = v5_2_0_0_Addr_A_orig << 32'd2;

assign v5_2_0_0_Addr_A_orig = zext_ln62_1_fu_964_p1;

assign v5_2_0_0_Din_A = bitcast_ln61;

assign v5_2_0_1_Addr_A = v5_2_0_1_Addr_A_orig << 32'd2;

assign v5_2_0_1_Addr_A_orig = zext_ln62_1_fu_964_p1;

assign v5_2_0_1_Din_A = bitcast_ln61;

assign v5_2_0_2_Addr_A = v5_2_0_2_Addr_A_orig << 32'd2;

assign v5_2_0_2_Addr_A_orig = zext_ln62_1_fu_964_p1;

assign v5_2_0_2_Din_A = bitcast_ln61;

assign v5_2_1_0_Addr_A = v5_2_1_0_Addr_A_orig << 32'd2;

assign v5_2_1_0_Addr_A_orig = zext_ln62_1_fu_964_p1;

assign v5_2_1_0_Din_A = bitcast_ln61;

assign v5_2_1_1_Addr_A = v5_2_1_1_Addr_A_orig << 32'd2;

assign v5_2_1_1_Addr_A_orig = zext_ln62_1_fu_964_p1;

assign v5_2_1_1_Din_A = bitcast_ln61;

assign v5_2_1_2_Addr_A = v5_2_1_2_Addr_A_orig << 32'd2;

assign v5_2_1_2_Addr_A_orig = zext_ln62_1_fu_964_p1;

assign v5_2_1_2_Din_A = bitcast_ln61;

assign v5_2_2_0_Addr_A = v5_2_2_0_Addr_A_orig << 32'd2;

assign v5_2_2_0_Addr_A_orig = zext_ln62_1_fu_964_p1;

assign v5_2_2_0_Din_A = bitcast_ln61;

assign v5_2_2_1_Addr_A = v5_2_2_1_Addr_A_orig << 32'd2;

assign v5_2_2_1_Addr_A_orig = zext_ln62_1_fu_964_p1;

assign v5_2_2_1_Din_A = bitcast_ln61;

assign v5_2_2_2_Addr_A = v5_2_2_2_Addr_A_orig << 32'd2;

assign v5_2_2_2_Addr_A_orig = zext_ln62_1_fu_964_p1;

assign v5_2_2_2_Din_A = bitcast_ln61;

assign zext_ln62_1_fu_964_p1 = grp_fu_1021_p3;

endmodule //test_gaussian_4096_test_gaussian_4096_Pipeline_VITIS_LOOP_58_1_VITIS_LOOP_59_2
