// ==============================================================
// RTL generated by Vitis HLS - High-Level Synthesis from C, C++ and OpenCL v2022.2 (64-bit)
// Version: 2022.2
// Copyright (C) Copyright 1986-2022 Xilinx, Inc. All Rights Reserved.
// 
// ===========================================================

`timescale 1 ns / 1 ps 

module test_vgg16_test_vgg16_Pipeline_VITIS_LOOP_827_121_VITIS_LOOP_829_123_VITIS_LOOP_831_125_VIT (
        ap_clk,
        ap_rst,
        ap_start,
        ap_done,
        ap_idle,
        ap_ready,
        v8_0_Addr_A,
        v8_0_EN_A,
        v8_0_WEN_A,
        v8_0_Din_A,
        v8_0_Dout_A,
        v8_1_Addr_A,
        v8_1_EN_A,
        v8_1_WEN_A,
        v8_1_Din_A,
        v8_1_Dout_A,
        v8_2_Addr_A,
        v8_2_EN_A,
        v8_2_WEN_A,
        v8_2_Din_A,
        v8_2_Dout_A,
        v8_3_Addr_A,
        v8_3_EN_A,
        v8_3_WEN_A,
        v8_3_Din_A,
        v8_3_Dout_A,
        v8_4_Addr_A,
        v8_4_EN_A,
        v8_4_WEN_A,
        v8_4_Din_A,
        v8_4_Dout_A,
        v8_5_Addr_A,
        v8_5_EN_A,
        v8_5_WEN_A,
        v8_5_Din_A,
        v8_5_Dout_A,
        v8_6_Addr_A,
        v8_6_EN_A,
        v8_6_WEN_A,
        v8_6_Din_A,
        v8_6_Dout_A,
        v8_7_Addr_A,
        v8_7_EN_A,
        v8_7_WEN_A,
        v8_7_Din_A,
        v8_7_Dout_A,
        v14_0_Addr_A,
        v14_0_EN_A,
        v14_0_WEN_A,
        v14_0_Din_A,
        v14_0_Dout_A,
        v14_0_Addr_B,
        v14_0_EN_B,
        v14_0_WEN_B,
        v14_0_Din_B,
        v14_0_Dout_B,
        v14_1_Addr_A,
        v14_1_EN_A,
        v14_1_WEN_A,
        v14_1_Din_A,
        v14_1_Dout_A,
        v14_1_Addr_B,
        v14_1_EN_B,
        v14_1_WEN_B,
        v14_1_Din_B,
        v14_1_Dout_B,
        v14_2_Addr_A,
        v14_2_EN_A,
        v14_2_WEN_A,
        v14_2_Din_A,
        v14_2_Dout_A,
        v14_2_Addr_B,
        v14_2_EN_B,
        v14_2_WEN_B,
        v14_2_Din_B,
        v14_2_Dout_B,
        v14_3_Addr_A,
        v14_3_EN_A,
        v14_3_WEN_A,
        v14_3_Din_A,
        v14_3_Dout_A,
        v14_3_Addr_B,
        v14_3_EN_B,
        v14_3_WEN_B,
        v14_3_Din_B,
        v14_3_Dout_B,
        v14_4_Addr_A,
        v14_4_EN_A,
        v14_4_WEN_A,
        v14_4_Din_A,
        v14_4_Dout_A,
        v14_4_Addr_B,
        v14_4_EN_B,
        v14_4_WEN_B,
        v14_4_Din_B,
        v14_4_Dout_B,
        v14_5_Addr_A,
        v14_5_EN_A,
        v14_5_WEN_A,
        v14_5_Din_A,
        v14_5_Dout_A,
        v14_5_Addr_B,
        v14_5_EN_B,
        v14_5_WEN_B,
        v14_5_Din_B,
        v14_5_Dout_B,
        v14_6_Addr_A,
        v14_6_EN_A,
        v14_6_WEN_A,
        v14_6_Din_A,
        v14_6_Dout_A,
        v14_6_Addr_B,
        v14_6_EN_B,
        v14_6_WEN_B,
        v14_6_Din_B,
        v14_6_Dout_B,
        v14_7_Addr_A,
        v14_7_EN_A,
        v14_7_WEN_A,
        v14_7_Din_A,
        v14_7_Dout_A,
        v14_7_Addr_B,
        v14_7_EN_B,
        v14_7_WEN_B,
        v14_7_Din_B,
        v14_7_Dout_B,
        v13_0_Addr_A,
        v13_0_EN_A,
        v13_0_WEN_A,
        v13_0_Din_A,
        v13_0_Dout_A,
        v13_1_Addr_A,
        v13_1_EN_A,
        v13_1_WEN_A,
        v13_1_Din_A,
        v13_1_Dout_A,
        v13_2_Addr_A,
        v13_2_EN_A,
        v13_2_WEN_A,
        v13_2_Din_A,
        v13_2_Dout_A,
        v13_3_Addr_A,
        v13_3_EN_A,
        v13_3_WEN_A,
        v13_3_Din_A,
        v13_3_Dout_A,
        v13_4_Addr_A,
        v13_4_EN_A,
        v13_4_WEN_A,
        v13_4_Din_A,
        v13_4_Dout_A,
        v13_5_Addr_A,
        v13_5_EN_A,
        v13_5_WEN_A,
        v13_5_Din_A,
        v13_5_Dout_A,
        v13_6_Addr_A,
        v13_6_EN_A,
        v13_6_WEN_A,
        v13_6_Din_A,
        v13_6_Dout_A,
        v13_7_Addr_A,
        v13_7_EN_A,
        v13_7_WEN_A,
        v13_7_Din_A,
        v13_7_Dout_A,
        grp_fu_12576_p_din0,
        grp_fu_12576_p_din1,
        grp_fu_12576_p_opcode,
        grp_fu_12576_p_dout0,
        grp_fu_12576_p_ce,
        grp_fu_12580_p_din0,
        grp_fu_12580_p_din1,
        grp_fu_12580_p_opcode,
        grp_fu_12580_p_dout0,
        grp_fu_12580_p_ce,
        grp_fu_12584_p_din0,
        grp_fu_12584_p_din1,
        grp_fu_12584_p_opcode,
        grp_fu_12584_p_dout0,
        grp_fu_12584_p_ce,
        grp_fu_12588_p_din0,
        grp_fu_12588_p_din1,
        grp_fu_12588_p_opcode,
        grp_fu_12588_p_dout0,
        grp_fu_12588_p_ce,
        grp_fu_12592_p_din0,
        grp_fu_12592_p_din1,
        grp_fu_12592_p_opcode,
        grp_fu_12592_p_dout0,
        grp_fu_12592_p_ce,
        grp_fu_12596_p_din0,
        grp_fu_12596_p_din1,
        grp_fu_12596_p_opcode,
        grp_fu_12596_p_dout0,
        grp_fu_12596_p_ce,
        grp_fu_12600_p_din0,
        grp_fu_12600_p_din1,
        grp_fu_12600_p_opcode,
        grp_fu_12600_p_dout0,
        grp_fu_12600_p_ce,
        grp_fu_12604_p_din0,
        grp_fu_12604_p_din1,
        grp_fu_12604_p_opcode,
        grp_fu_12604_p_dout0,
        grp_fu_12604_p_ce,
        grp_fu_12608_p_din0,
        grp_fu_12608_p_din1,
        grp_fu_12608_p_dout0,
        grp_fu_12608_p_ce,
        grp_fu_12612_p_din0,
        grp_fu_12612_p_din1,
        grp_fu_12612_p_dout0,
        grp_fu_12612_p_ce,
        grp_fu_12616_p_din0,
        grp_fu_12616_p_din1,
        grp_fu_12616_p_dout0,
        grp_fu_12616_p_ce,
        grp_fu_12620_p_din0,
        grp_fu_12620_p_din1,
        grp_fu_12620_p_dout0,
        grp_fu_12620_p_ce,
        grp_fu_12624_p_din0,
        grp_fu_12624_p_din1,
        grp_fu_12624_p_dout0,
        grp_fu_12624_p_ce,
        grp_fu_12628_p_din0,
        grp_fu_12628_p_din1,
        grp_fu_12628_p_dout0,
        grp_fu_12628_p_ce,
        grp_fu_12632_p_din0,
        grp_fu_12632_p_din1,
        grp_fu_12632_p_dout0,
        grp_fu_12632_p_ce,
        grp_fu_12636_p_din0,
        grp_fu_12636_p_din1,
        grp_fu_12636_p_dout0,
        grp_fu_12636_p_ce
);

parameter    ap_ST_fsm_pp0_stage0 = 1'd1;

input   ap_clk;
input   ap_rst;
input   ap_start;
output   ap_done;
output   ap_idle;
output   ap_ready;
output  [31:0] v8_0_Addr_A;
output   v8_0_EN_A;
output  [3:0] v8_0_WEN_A;
output  [31:0] v8_0_Din_A;
input  [31:0] v8_0_Dout_A;
output  [31:0] v8_1_Addr_A;
output   v8_1_EN_A;
output  [3:0] v8_1_WEN_A;
output  [31:0] v8_1_Din_A;
input  [31:0] v8_1_Dout_A;
output  [31:0] v8_2_Addr_A;
output   v8_2_EN_A;
output  [3:0] v8_2_WEN_A;
output  [31:0] v8_2_Din_A;
input  [31:0] v8_2_Dout_A;
output  [31:0] v8_3_Addr_A;
output   v8_3_EN_A;
output  [3:0] v8_3_WEN_A;
output  [31:0] v8_3_Din_A;
input  [31:0] v8_3_Dout_A;
output  [31:0] v8_4_Addr_A;
output   v8_4_EN_A;
output  [3:0] v8_4_WEN_A;
output  [31:0] v8_4_Din_A;
input  [31:0] v8_4_Dout_A;
output  [31:0] v8_5_Addr_A;
output   v8_5_EN_A;
output  [3:0] v8_5_WEN_A;
output  [31:0] v8_5_Din_A;
input  [31:0] v8_5_Dout_A;
output  [31:0] v8_6_Addr_A;
output   v8_6_EN_A;
output  [3:0] v8_6_WEN_A;
output  [31:0] v8_6_Din_A;
input  [31:0] v8_6_Dout_A;
output  [31:0] v8_7_Addr_A;
output   v8_7_EN_A;
output  [3:0] v8_7_WEN_A;
output  [31:0] v8_7_Din_A;
input  [31:0] v8_7_Dout_A;
output  [31:0] v14_0_Addr_A;
output   v14_0_EN_A;
output  [3:0] v14_0_WEN_A;
output  [31:0] v14_0_Din_A;
input  [31:0] v14_0_Dout_A;
output  [31:0] v14_0_Addr_B;
output   v14_0_EN_B;
output  [3:0] v14_0_WEN_B;
output  [31:0] v14_0_Din_B;
input  [31:0] v14_0_Dout_B;
output  [31:0] v14_1_Addr_A;
output   v14_1_EN_A;
output  [3:0] v14_1_WEN_A;
output  [31:0] v14_1_Din_A;
input  [31:0] v14_1_Dout_A;
output  [31:0] v14_1_Addr_B;
output   v14_1_EN_B;
output  [3:0] v14_1_WEN_B;
output  [31:0] v14_1_Din_B;
input  [31:0] v14_1_Dout_B;
output  [31:0] v14_2_Addr_A;
output   v14_2_EN_A;
output  [3:0] v14_2_WEN_A;
output  [31:0] v14_2_Din_A;
input  [31:0] v14_2_Dout_A;
output  [31:0] v14_2_Addr_B;
output   v14_2_EN_B;
output  [3:0] v14_2_WEN_B;
output  [31:0] v14_2_Din_B;
input  [31:0] v14_2_Dout_B;
output  [31:0] v14_3_Addr_A;
output   v14_3_EN_A;
output  [3:0] v14_3_WEN_A;
output  [31:0] v14_3_Din_A;
input  [31:0] v14_3_Dout_A;
output  [31:0] v14_3_Addr_B;
output   v14_3_EN_B;
output  [3:0] v14_3_WEN_B;
output  [31:0] v14_3_Din_B;
input  [31:0] v14_3_Dout_B;
output  [31:0] v14_4_Addr_A;
output   v14_4_EN_A;
output  [3:0] v14_4_WEN_A;
output  [31:0] v14_4_Din_A;
input  [31:0] v14_4_Dout_A;
output  [31:0] v14_4_Addr_B;
output   v14_4_EN_B;
output  [3:0] v14_4_WEN_B;
output  [31:0] v14_4_Din_B;
input  [31:0] v14_4_Dout_B;
output  [31:0] v14_5_Addr_A;
output   v14_5_EN_A;
output  [3:0] v14_5_WEN_A;
output  [31:0] v14_5_Din_A;
input  [31:0] v14_5_Dout_A;
output  [31:0] v14_5_Addr_B;
output   v14_5_EN_B;
output  [3:0] v14_5_WEN_B;
output  [31:0] v14_5_Din_B;
input  [31:0] v14_5_Dout_B;
output  [31:0] v14_6_Addr_A;
output   v14_6_EN_A;
output  [3:0] v14_6_WEN_A;
output  [31:0] v14_6_Din_A;
input  [31:0] v14_6_Dout_A;
output  [31:0] v14_6_Addr_B;
output   v14_6_EN_B;
output  [3:0] v14_6_WEN_B;
output  [31:0] v14_6_Din_B;
input  [31:0] v14_6_Dout_B;
output  [31:0] v14_7_Addr_A;
output   v14_7_EN_A;
output  [3:0] v14_7_WEN_A;
output  [31:0] v14_7_Din_A;
input  [31:0] v14_7_Dout_A;
output  [31:0] v14_7_Addr_B;
output   v14_7_EN_B;
output  [3:0] v14_7_WEN_B;
output  [31:0] v14_7_Din_B;
input  [31:0] v14_7_Dout_B;
output  [31:0] v13_0_Addr_A;
output   v13_0_EN_A;
output  [3:0] v13_0_WEN_A;
output  [31:0] v13_0_Din_A;
input  [31:0] v13_0_Dout_A;
output  [31:0] v13_1_Addr_A;
output   v13_1_EN_A;
output  [3:0] v13_1_WEN_A;
output  [31:0] v13_1_Din_A;
input  [31:0] v13_1_Dout_A;
output  [31:0] v13_2_Addr_A;
output   v13_2_EN_A;
output  [3:0] v13_2_WEN_A;
output  [31:0] v13_2_Din_A;
input  [31:0] v13_2_Dout_A;
output  [31:0] v13_3_Addr_A;
output   v13_3_EN_A;
output  [3:0] v13_3_WEN_A;
output  [31:0] v13_3_Din_A;
input  [31:0] v13_3_Dout_A;
output  [31:0] v13_4_Addr_A;
output   v13_4_EN_A;
output  [3:0] v13_4_WEN_A;
output  [31:0] v13_4_Din_A;
input  [31:0] v13_4_Dout_A;
output  [31:0] v13_5_Addr_A;
output   v13_5_EN_A;
output  [3:0] v13_5_WEN_A;
output  [31:0] v13_5_Din_A;
input  [31:0] v13_5_Dout_A;
output  [31:0] v13_6_Addr_A;
output   v13_6_EN_A;
output  [3:0] v13_6_WEN_A;
output  [31:0] v13_6_Din_A;
input  [31:0] v13_6_Dout_A;
output  [31:0] v13_7_Addr_A;
output   v13_7_EN_A;
output  [3:0] v13_7_WEN_A;
output  [31:0] v13_7_Din_A;
input  [31:0] v13_7_Dout_A;
output  [31:0] grp_fu_12576_p_din0;
output  [31:0] grp_fu_12576_p_din1;
output  [1:0] grp_fu_12576_p_opcode;
input  [31:0] grp_fu_12576_p_dout0;
output   grp_fu_12576_p_ce;
output  [31:0] grp_fu_12580_p_din0;
output  [31:0] grp_fu_12580_p_din1;
output  [1:0] grp_fu_12580_p_opcode;
input  [31:0] grp_fu_12580_p_dout0;
output   grp_fu_12580_p_ce;
output  [31:0] grp_fu_12584_p_din0;
output  [31:0] grp_fu_12584_p_din1;
output  [1:0] grp_fu_12584_p_opcode;
input  [31:0] grp_fu_12584_p_dout0;
output   grp_fu_12584_p_ce;
output  [31:0] grp_fu_12588_p_din0;
output  [31:0] grp_fu_12588_p_din1;
output  [1:0] grp_fu_12588_p_opcode;
input  [31:0] grp_fu_12588_p_dout0;
output   grp_fu_12588_p_ce;
output  [31:0] grp_fu_12592_p_din0;
output  [31:0] grp_fu_12592_p_din1;
output  [1:0] grp_fu_12592_p_opcode;
input  [31:0] grp_fu_12592_p_dout0;
output   grp_fu_12592_p_ce;
output  [31:0] grp_fu_12596_p_din0;
output  [31:0] grp_fu_12596_p_din1;
output  [1:0] grp_fu_12596_p_opcode;
input  [31:0] grp_fu_12596_p_dout0;
output   grp_fu_12596_p_ce;
output  [31:0] grp_fu_12600_p_din0;
output  [31:0] grp_fu_12600_p_din1;
output  [1:0] grp_fu_12600_p_opcode;
input  [31:0] grp_fu_12600_p_dout0;
output   grp_fu_12600_p_ce;
output  [31:0] grp_fu_12604_p_din0;
output  [31:0] grp_fu_12604_p_din1;
output  [1:0] grp_fu_12604_p_opcode;
input  [31:0] grp_fu_12604_p_dout0;
output   grp_fu_12604_p_ce;
output  [31:0] grp_fu_12608_p_din0;
output  [31:0] grp_fu_12608_p_din1;
input  [31:0] grp_fu_12608_p_dout0;
output   grp_fu_12608_p_ce;
output  [31:0] grp_fu_12612_p_din0;
output  [31:0] grp_fu_12612_p_din1;
input  [31:0] grp_fu_12612_p_dout0;
output   grp_fu_12612_p_ce;
output  [31:0] grp_fu_12616_p_din0;
output  [31:0] grp_fu_12616_p_din1;
input  [31:0] grp_fu_12616_p_dout0;
output   grp_fu_12616_p_ce;
output  [31:0] grp_fu_12620_p_din0;
output  [31:0] grp_fu_12620_p_din1;
input  [31:0] grp_fu_12620_p_dout0;
output   grp_fu_12620_p_ce;
output  [31:0] grp_fu_12624_p_din0;
output  [31:0] grp_fu_12624_p_din1;
input  [31:0] grp_fu_12624_p_dout0;
output   grp_fu_12624_p_ce;
output  [31:0] grp_fu_12628_p_din0;
output  [31:0] grp_fu_12628_p_din1;
input  [31:0] grp_fu_12628_p_dout0;
output   grp_fu_12628_p_ce;
output  [31:0] grp_fu_12632_p_din0;
output  [31:0] grp_fu_12632_p_din1;
input  [31:0] grp_fu_12632_p_dout0;
output   grp_fu_12632_p_ce;
output  [31:0] grp_fu_12636_p_din0;
output  [31:0] grp_fu_12636_p_din1;
input  [31:0] grp_fu_12636_p_dout0;
output   grp_fu_12636_p_ce;

reg ap_idle;
reg v8_0_EN_A;
reg v8_1_EN_A;
reg v8_2_EN_A;
reg v8_3_EN_A;
reg v8_4_EN_A;
reg v8_5_EN_A;
reg v8_6_EN_A;
reg v8_7_EN_A;
reg v14_0_EN_A;
reg[3:0] v14_0_WEN_A;
reg v14_0_EN_B;
reg v14_1_EN_A;
reg[3:0] v14_1_WEN_A;
reg v14_1_EN_B;
reg v14_2_EN_A;
reg[3:0] v14_2_WEN_A;
reg v14_2_EN_B;
reg v14_3_EN_A;
reg[3:0] v14_3_WEN_A;
reg v14_3_EN_B;
reg v14_4_EN_A;
reg[3:0] v14_4_WEN_A;
reg v14_4_EN_B;
reg v14_5_EN_A;
reg[3:0] v14_5_WEN_A;
reg v14_5_EN_B;
reg v14_6_EN_A;
reg[3:0] v14_6_WEN_A;
reg v14_6_EN_B;
reg v14_7_EN_A;
reg[3:0] v14_7_WEN_A;
reg v14_7_EN_B;
reg v13_0_EN_A;
reg v13_1_EN_A;
reg v13_2_EN_A;
reg v13_3_EN_A;
reg v13_4_EN_A;
reg v13_5_EN_A;
reg v13_6_EN_A;
reg v13_7_EN_A;

(* fsm_encoding = "none" *) reg   [0:0] ap_CS_fsm;
wire    ap_CS_fsm_pp0_stage0;
wire    ap_enable_reg_pp0_iter0;
reg    ap_enable_reg_pp0_iter1;
reg    ap_enable_reg_pp0_iter2;
reg    ap_enable_reg_pp0_iter3;
reg    ap_enable_reg_pp0_iter4;
reg    ap_enable_reg_pp0_iter5;
reg    ap_enable_reg_pp0_iter6;
reg    ap_enable_reg_pp0_iter7;
reg    ap_enable_reg_pp0_iter8;
reg    ap_enable_reg_pp0_iter9;
reg    ap_enable_reg_pp0_iter10;
reg    ap_enable_reg_pp0_iter11;
reg    ap_enable_reg_pp0_iter12;
reg    ap_enable_reg_pp0_iter13;
reg    ap_enable_reg_pp0_iter14;
reg    ap_enable_reg_pp0_iter15;
reg    ap_enable_reg_pp0_iter16;
reg    ap_enable_reg_pp0_iter17;
reg    ap_enable_reg_pp0_iter18;
reg    ap_enable_reg_pp0_iter19;
reg    ap_enable_reg_pp0_iter20;
reg    ap_idle_pp0;
wire    ap_block_state1_pp0_stage0_iter0;
wire    ap_block_state2_pp0_stage0_iter1;
wire    ap_block_state3_pp0_stage0_iter2;
wire    ap_block_state4_pp0_stage0_iter3;
wire    ap_block_state5_pp0_stage0_iter4;
wire    ap_block_state6_pp0_stage0_iter5;
wire    ap_block_state7_pp0_stage0_iter6;
wire    ap_block_state8_pp0_stage0_iter7;
wire    ap_block_state9_pp0_stage0_iter8;
wire    ap_block_state10_pp0_stage0_iter9;
wire    ap_block_state11_pp0_stage0_iter10;
wire    ap_block_state12_pp0_stage0_iter11;
wire    ap_block_state13_pp0_stage0_iter12;
wire    ap_block_state14_pp0_stage0_iter13;
wire    ap_block_state15_pp0_stage0_iter14;
wire    ap_block_state16_pp0_stage0_iter15;
wire    ap_block_state17_pp0_stage0_iter16;
wire    ap_block_state18_pp0_stage0_iter17;
wire    ap_block_state19_pp0_stage0_iter18;
wire    ap_block_state20_pp0_stage0_iter19;
wire    ap_block_state21_pp0_stage0_iter20;
wire    ap_block_pp0_stage0_subdone;
wire   [0:0] icmp_ln827_fu_664_p2;
reg    ap_condition_exit_pp0_iter1_stage0;
wire    ap_loop_exit_ready;
reg    ap_ready_int;
wire    ap_block_pp0_stage0_11001;
reg   [0:0] icmp_ln827_reg_1767;
reg   [0:0] icmp_ln827_reg_1767_pp0_iter2_reg;
reg   [0:0] icmp_ln827_reg_1767_pp0_iter3_reg;
reg   [0:0] icmp_ln827_reg_1767_pp0_iter4_reg;
wire   [0:0] icmp_ln828_fu_679_p2;
reg   [0:0] icmp_ln828_reg_1771;
reg   [0:0] icmp_ln828_reg_1771_pp0_iter2_reg;
reg   [0:0] icmp_ln828_reg_1771_pp0_iter3_reg;
reg   [0:0] icmp_ln828_reg_1771_pp0_iter4_reg;
wire   [0:0] xor_ln827_fu_712_p2;
reg   [0:0] xor_ln827_reg_1784;
reg   [0:0] xor_ln827_reg_1784_pp0_iter3_reg;
reg   [0:0] xor_ln827_reg_1784_pp0_iter4_reg;
wire   [0:0] icmp_ln829_fu_717_p2;
reg   [0:0] icmp_ln829_reg_1791;
wire   [0:0] and_ln827_3_fu_723_p2;
reg   [0:0] and_ln827_3_reg_1796;
reg   [0:0] and_ln827_3_reg_1796_pp0_iter3_reg;
reg   [0:0] and_ln827_3_reg_1796_pp0_iter4_reg;
wire   [0:0] or_ln828_fu_729_p2;
reg   [0:0] or_ln828_reg_1804;
reg   [0:0] or_ln828_reg_1804_pp0_iter3_reg;
reg   [0:0] or_ln828_reg_1804_pp0_iter4_reg;
wire   [0:0] or_ln828_1_fu_772_p2;
reg   [0:0] or_ln828_1_reg_1810;
reg   [0:0] or_ln828_1_reg_1810_pp0_iter4_reg;
wire   [0:0] and_ln828_2_fu_777_p2;
reg   [0:0] and_ln828_2_reg_1816;
reg   [0:0] and_ln828_2_reg_1816_pp0_iter4_reg;
reg   [0:0] and_ln828_2_reg_1816_pp0_iter5_reg;
wire   [0:0] or_ln829_fu_783_p2;
reg   [0:0] or_ln829_reg_1826;
reg   [0:0] or_ln829_reg_1826_pp0_iter4_reg;
wire   [0:0] or_ln829_1_fu_788_p2;
reg   [0:0] or_ln829_1_reg_1831;
reg   [1:0] v468_1_reg_1837;
wire   [18:0] empty_164_fu_875_p1;
reg   [18:0] empty_164_reg_1842;
wire   [16:0] empty_165_fu_879_p1;
reg   [16:0] empty_165_reg_1847;
wire   [9:0] add_ln827_fu_886_p2;
reg   [9:0] add_ln827_reg_1852;
wire   [9:0] select_ln827_1_fu_899_p3;
reg   [9:0] select_ln827_1_reg_1858;
reg   [5:0] p_cast99_mid2_v_reg_1863;
reg   [5:0] p_cast99_mid2_v_reg_1863_pp0_iter5_reg;
reg   [5:0] p_cast99_mid2_v_reg_1863_pp0_iter6_reg;
wire   [2:0] trunc_ln827_fu_920_p1;
reg   [2:0] trunc_ln827_reg_1868;
reg   [2:0] trunc_ln827_reg_1868_pp0_iter5_reg;
reg   [2:0] trunc_ln827_reg_1868_pp0_iter6_reg;
reg   [2:0] trunc_ln827_reg_1868_pp0_iter7_reg;
wire   [1:0] add_ln828_fu_935_p2;
reg   [1:0] add_ln828_reg_1873;
wire   [1:0] select_ln828_1_fu_941_p3;
reg   [1:0] select_ln828_1_reg_1879;
wire   [12:0] empty_171_fu_960_p2;
reg   [12:0] empty_171_reg_1886;
wire   [0:0] and_ln828_1_fu_966_p2;
reg   [0:0] and_ln828_1_reg_1891;
wire   [0:0] xor_ln829_fu_978_p2;
reg   [0:0] xor_ln829_reg_1896;
wire   [0:0] and_ln829_1_fu_983_p2;
reg   [0:0] and_ln829_1_reg_1901;
reg   [0:0] and_ln829_1_reg_1901_pp0_iter5_reg;
wire   [6:0] add_ln830_fu_989_p2;
reg   [6:0] add_ln830_reg_1908;
wire   [0:0] or_ln830_1_fu_1000_p2;
reg   [0:0] or_ln830_1_reg_1913;
wire   [5:0] select_ln830_3_fu_1028_p3;
reg   [5:0] select_ln830_3_reg_1918;
reg   [5:0] select_ln830_3_reg_1918_pp0_iter5_reg;
reg   [5:0] select_ln830_3_reg_1918_pp0_iter6_reg;
reg   [5:0] select_ln830_3_reg_1918_pp0_iter7_reg;
reg   [5:0] select_ln830_3_reg_1918_pp0_iter8_reg;
reg   [5:0] select_ln830_3_reg_1918_pp0_iter9_reg;
reg   [5:0] select_ln830_3_reg_1918_pp0_iter10_reg;
wire   [18:0] select_ln828_2_fu_1208_p3;
reg   [18:0] select_ln828_2_reg_1923;
wire   [1:0] add_ln829_fu_1220_p2;
reg   [1:0] add_ln829_reg_1928;
wire   [1:0] select_ln829_1_fu_1226_p3;
reg   [1:0] select_ln829_1_reg_1933;
reg   [1:0] select_ln829_1_reg_1933_pp0_iter6_reg;
wire  signed [13:0] empty_174_fu_1233_p2;
reg  signed [13:0] empty_174_reg_1939;
wire   [18:0] empty_180_fu_1296_p1;
reg   [18:0] empty_180_reg_1945;
wire   [16:0] empty_181_fu_1300_p1;
reg   [16:0] empty_181_reg_1950;
wire   [2:0] select_ln831_fu_1341_p3;
reg   [2:0] select_ln831_reg_1955;
reg   [2:0] select_ln831_reg_1955_pp0_iter6_reg;
reg   [2:0] select_ln831_reg_1955_pp0_iter7_reg;
reg   [2:0] select_ln831_reg_1955_pp0_iter8_reg;
reg   [2:0] select_ln831_reg_1955_pp0_iter9_reg;
reg   [2:0] select_ln831_reg_1955_pp0_iter10_reg;
wire   [2:0] select_ln831_1_fu_1349_p3;
reg   [2:0] select_ln831_1_reg_1961;
reg   [2:0] select_ln831_1_reg_1961_pp0_iter6_reg;
reg   [2:0] select_ln831_1_reg_1961_pp0_iter7_reg;
reg   [2:0] select_ln831_1_reg_1961_pp0_iter8_reg;
reg   [2:0] select_ln831_1_reg_1961_pp0_iter9_reg;
reg   [2:0] select_ln831_1_reg_1961_pp0_iter10_reg;
wire   [2:0] select_ln831_2_fu_1391_p3;
reg   [2:0] select_ln831_2_reg_1966;
reg   [2:0] select_ln831_2_reg_1966_pp0_iter6_reg;
wire   [18:0] select_ln830_1_fu_1476_p3;
reg   [18:0] select_ln830_1_reg_1971;
reg   [31:0] v8_0_load_reg_2056;
reg   [31:0] v8_1_load_reg_2061;
reg   [31:0] v8_2_load_reg_2066;
reg   [31:0] v8_3_load_reg_2071;
reg   [31:0] v8_4_load_reg_2076;
reg   [31:0] v8_5_load_reg_2081;
reg   [31:0] v8_6_load_reg_2086;
reg   [31:0] v8_7_load_reg_2091;
wire   [31:0] v473_fu_1554_p10;
reg   [31:0] v473_reg_2096;
wire   [31:0] bitcast_ln830_fu_1575_p1;
wire   [31:0] bitcast_ln830_1_fu_1579_p1;
wire   [31:0] bitcast_ln830_2_fu_1583_p1;
wire   [31:0] bitcast_ln830_3_fu_1587_p1;
wire   [31:0] bitcast_ln830_4_fu_1591_p1;
wire   [31:0] bitcast_ln830_5_fu_1595_p1;
wire   [31:0] bitcast_ln830_6_fu_1599_p1;
wire   [31:0] bitcast_ln830_7_fu_1603_p1;
reg   [11:0] v14_0_addr_reg_2148;
reg   [11:0] v14_0_addr_reg_2148_pp0_iter12_reg;
reg   [11:0] v14_0_addr_reg_2148_pp0_iter13_reg;
reg   [11:0] v14_0_addr_reg_2148_pp0_iter14_reg;
reg   [11:0] v14_0_addr_reg_2148_pp0_iter15_reg;
reg   [11:0] v14_0_addr_reg_2148_pp0_iter16_reg;
reg   [11:0] v14_0_addr_reg_2148_pp0_iter17_reg;
reg   [11:0] v14_0_addr_reg_2148_pp0_iter18_reg;
reg   [11:0] v14_0_addr_reg_2148_pp0_iter19_reg;
reg   [11:0] v14_1_addr_reg_2154;
reg   [11:0] v14_1_addr_reg_2154_pp0_iter12_reg;
reg   [11:0] v14_1_addr_reg_2154_pp0_iter13_reg;
reg   [11:0] v14_1_addr_reg_2154_pp0_iter14_reg;
reg   [11:0] v14_1_addr_reg_2154_pp0_iter15_reg;
reg   [11:0] v14_1_addr_reg_2154_pp0_iter16_reg;
reg   [11:0] v14_1_addr_reg_2154_pp0_iter17_reg;
reg   [11:0] v14_1_addr_reg_2154_pp0_iter18_reg;
reg   [11:0] v14_1_addr_reg_2154_pp0_iter19_reg;
reg   [11:0] v14_2_addr_reg_2160;
reg   [11:0] v14_2_addr_reg_2160_pp0_iter12_reg;
reg   [11:0] v14_2_addr_reg_2160_pp0_iter13_reg;
reg   [11:0] v14_2_addr_reg_2160_pp0_iter14_reg;
reg   [11:0] v14_2_addr_reg_2160_pp0_iter15_reg;
reg   [11:0] v14_2_addr_reg_2160_pp0_iter16_reg;
reg   [11:0] v14_2_addr_reg_2160_pp0_iter17_reg;
reg   [11:0] v14_2_addr_reg_2160_pp0_iter18_reg;
reg   [11:0] v14_2_addr_reg_2160_pp0_iter19_reg;
reg   [11:0] v14_3_addr_reg_2166;
reg   [11:0] v14_3_addr_reg_2166_pp0_iter12_reg;
reg   [11:0] v14_3_addr_reg_2166_pp0_iter13_reg;
reg   [11:0] v14_3_addr_reg_2166_pp0_iter14_reg;
reg   [11:0] v14_3_addr_reg_2166_pp0_iter15_reg;
reg   [11:0] v14_3_addr_reg_2166_pp0_iter16_reg;
reg   [11:0] v14_3_addr_reg_2166_pp0_iter17_reg;
reg   [11:0] v14_3_addr_reg_2166_pp0_iter18_reg;
reg   [11:0] v14_3_addr_reg_2166_pp0_iter19_reg;
reg   [11:0] v14_4_addr_reg_2172;
reg   [11:0] v14_4_addr_reg_2172_pp0_iter12_reg;
reg   [11:0] v14_4_addr_reg_2172_pp0_iter13_reg;
reg   [11:0] v14_4_addr_reg_2172_pp0_iter14_reg;
reg   [11:0] v14_4_addr_reg_2172_pp0_iter15_reg;
reg   [11:0] v14_4_addr_reg_2172_pp0_iter16_reg;
reg   [11:0] v14_4_addr_reg_2172_pp0_iter17_reg;
reg   [11:0] v14_4_addr_reg_2172_pp0_iter18_reg;
reg   [11:0] v14_4_addr_reg_2172_pp0_iter19_reg;
reg   [11:0] v14_5_addr_reg_2178;
reg   [11:0] v14_5_addr_reg_2178_pp0_iter12_reg;
reg   [11:0] v14_5_addr_reg_2178_pp0_iter13_reg;
reg   [11:0] v14_5_addr_reg_2178_pp0_iter14_reg;
reg   [11:0] v14_5_addr_reg_2178_pp0_iter15_reg;
reg   [11:0] v14_5_addr_reg_2178_pp0_iter16_reg;
reg   [11:0] v14_5_addr_reg_2178_pp0_iter17_reg;
reg   [11:0] v14_5_addr_reg_2178_pp0_iter18_reg;
reg   [11:0] v14_5_addr_reg_2178_pp0_iter19_reg;
reg   [11:0] v14_6_addr_reg_2184;
reg   [11:0] v14_6_addr_reg_2184_pp0_iter12_reg;
reg   [11:0] v14_6_addr_reg_2184_pp0_iter13_reg;
reg   [11:0] v14_6_addr_reg_2184_pp0_iter14_reg;
reg   [11:0] v14_6_addr_reg_2184_pp0_iter15_reg;
reg   [11:0] v14_6_addr_reg_2184_pp0_iter16_reg;
reg   [11:0] v14_6_addr_reg_2184_pp0_iter17_reg;
reg   [11:0] v14_6_addr_reg_2184_pp0_iter18_reg;
reg   [11:0] v14_6_addr_reg_2184_pp0_iter19_reg;
reg   [11:0] v14_7_addr_reg_2190;
reg   [11:0] v14_7_addr_reg_2190_pp0_iter12_reg;
reg   [11:0] v14_7_addr_reg_2190_pp0_iter13_reg;
reg   [11:0] v14_7_addr_reg_2190_pp0_iter14_reg;
reg   [11:0] v14_7_addr_reg_2190_pp0_iter15_reg;
reg   [11:0] v14_7_addr_reg_2190_pp0_iter16_reg;
reg   [11:0] v14_7_addr_reg_2190_pp0_iter17_reg;
reg   [11:0] v14_7_addr_reg_2190_pp0_iter18_reg;
reg   [11:0] v14_7_addr_reg_2190_pp0_iter19_reg;
reg   [31:0] v475_reg_2196;
reg   [31:0] v14_0_load_reg_2201;
reg   [31:0] v479_reg_2206;
reg   [31:0] v14_1_load_reg_2211;
reg   [31:0] v483_reg_2216;
reg   [31:0] v14_2_load_reg_2221;
reg   [31:0] v487_reg_2226;
reg   [31:0] v14_3_load_reg_2231;
reg   [31:0] v491_reg_2236;
reg   [31:0] v14_4_load_reg_2241;
reg   [31:0] v495_reg_2246;
reg   [31:0] v14_5_load_reg_2251;
reg   [31:0] v499_reg_2256;
reg   [31:0] v14_6_load_reg_2261;
reg   [31:0] v503_reg_2266;
reg   [31:0] v14_7_load_reg_2271;
wire   [31:0] v476_fu_1626_p1;
wire   [31:0] v480_fu_1630_p1;
wire   [31:0] v484_fu_1634_p1;
wire   [31:0] v488_fu_1638_p1;
wire   [31:0] v492_fu_1642_p1;
wire   [31:0] v496_fu_1646_p1;
wire   [31:0] v500_fu_1650_p1;
wire   [31:0] v504_fu_1654_p1;
reg   [31:0] v477_reg_2316;
reg   [31:0] v481_reg_2321;
reg   [31:0] v485_reg_2326;
reg   [31:0] v489_reg_2331;
reg   [31:0] v493_reg_2336;
reg   [31:0] v497_reg_2341;
reg   [31:0] v501_reg_2346;
reg   [31:0] v505_reg_2351;
reg    ap_condition_exit_pp0_iter5_stage0;
wire   [63:0] select_ln830_2_cast_fu_1486_p1;
wire    ap_block_pp0_stage0;
wire   [63:0] zext_ln834_fu_1510_p1;
wire   [63:0] zext_ln837_fu_1614_p1;
reg   [2:0] v472_fu_154;
wire   [2:0] add_ln832_fu_1399_p2;
wire    ap_loop_init;
reg   [2:0] v471_fu_158;
reg   [5:0] indvar_flatten2714_fu_162;
wire   [5:0] select_ln831_3_fu_1042_p3;
reg   [6:0] v470_fu_166;
wire   [6:0] select_ln830_2_fu_1005_p3;
reg   [11:0] indvar_flatten2740_fu_170;
wire   [11:0] select_ln830_5_fu_799_p3;
reg   [1:0] v469_fu_174;
reg   [12:0] indvar_flatten2816_fu_178;
wire   [12:0] select_ln829_5_fu_740_p3;
reg   [1:0] v468_fu_182;
reg   [13:0] indvar_flatten2904_fu_186;
wire   [13:0] select_ln828_4_fu_691_p3;
reg   [9:0] v467_fu_190;
reg   [22:0] indvar_flatten3007_fu_194;
wire   [22:0] add_ln827_1_fu_670_p2;
wire   [31:0] v8_0_Addr_A_orig;
wire   [31:0] v8_1_Addr_A_orig;
wire   [31:0] v8_2_Addr_A_orig;
wire   [31:0] v8_3_Addr_A_orig;
wire   [31:0] v8_4_Addr_A_orig;
wire   [31:0] v8_5_Addr_A_orig;
wire   [31:0] v8_6_Addr_A_orig;
wire   [31:0] v8_7_Addr_A_orig;
wire   [31:0] v13_0_Addr_A_orig;
wire   [31:0] v13_1_Addr_A_orig;
wire   [31:0] v13_2_Addr_A_orig;
wire   [31:0] v13_3_Addr_A_orig;
wire   [31:0] v13_4_Addr_A_orig;
wire   [31:0] v13_5_Addr_A_orig;
wire   [31:0] v13_6_Addr_A_orig;
wire   [31:0] v13_7_Addr_A_orig;
wire   [31:0] v14_0_Addr_B_orig;
wire   [31:0] v14_0_Addr_A_orig;
wire   [31:0] v14_1_Addr_B_orig;
wire   [31:0] v14_1_Addr_A_orig;
wire   [31:0] v14_2_Addr_B_orig;
wire   [31:0] v14_2_Addr_A_orig;
wire   [31:0] v14_3_Addr_B_orig;
wire   [31:0] v14_3_Addr_A_orig;
wire   [31:0] v14_4_Addr_B_orig;
wire   [31:0] v14_4_Addr_A_orig;
wire   [31:0] v14_5_Addr_B_orig;
wire   [31:0] v14_5_Addr_A_orig;
wire   [31:0] v14_6_Addr_B_orig;
wire   [31:0] v14_6_Addr_A_orig;
wire   [31:0] v14_7_Addr_B_orig;
wire   [31:0] v14_7_Addr_A_orig;
wire   [13:0] add_ln828_1_fu_685_p2;
wire   [12:0] add_ln829_1_fu_734_p2;
wire   [0:0] icmp_ln830_fu_756_p2;
wire   [0:0] xor_ln828_fu_767_p2;
wire   [0:0] and_ln827_2_fu_762_p2;
wire   [11:0] add_ln830_1_fu_793_p2;
wire   [15:0] tmp_s_fu_829_p3;
wire   [16:0] tmp_290_cast_fu_837_p1;
wire   [16:0] zext_ln827_fu_821_p1;
wire   [16:0] empty_fu_841_p2;
wire   [18:0] tmp_fu_851_p3;
wire   [61:0] p_shl56_fu_859_p1;
wire   [61:0] p_cast_fu_847_p1;
wire   [61:0] empty_162_fu_863_p2;
wire   [61:0] zext_ln828_fu_825_p1;
wire   [61:0] empty_163_fu_869_p2;
wire   [0:0] icmp_ln831_fu_924_p2;
wire   [1:0] select_ln827_fu_892_p3;
wire   [11:0] tmp_17_fu_948_p3;
wire   [12:0] tmp_295_cast_fu_956_p1;
wire   [12:0] zext_ln827_3_fu_906_p1;
wire   [0:0] and_ln827_1_fu_930_p2;
wire   [6:0] select_ln829_fu_971_p3;
wire   [0:0] or_ln830_fu_995_p2;
wire   [5:0] empty_185_fu_1017_p1;
wire   [5:0] empty_184_fu_1013_p1;
wire   [5:0] select_ln829_3_fu_1021_p3;
wire   [5:0] add_ln831_1_fu_1036_p2;
wire   [18:0] p_shl_fu_1083_p3;
wire   [18:0] empty_166_fu_1090_p2;
wire   [18:0] zext_ln829_fu_1079_p1;
wire   [2:0] zext_ln828_1_fu_1076_p1;
wire   [12:0] tmp_16_fu_1116_p3;
wire   [13:0] tmp_294_cast_fu_1123_p1;
wire   [13:0] zext_ln827_1_fu_1110_p1;
wire   [13:0] empty_170_fu_1127_p2;
wire   [18:0] zext_ln830_fu_1133_p1;
wire   [18:0] empty_167_fu_1095_p2;
wire   [0:0] icmp_ln832_fu_1144_p2;
wire  signed [13:0] p_cast3_fu_1177_p1;
wire   [13:0] zext_ln828_3_fu_1165_p1;
wire  signed [13:0] empty_172_fu_1180_p2;
wire   [15:0] tmp_14_fu_1190_p3;
wire  signed [18:0] p_shl58_fu_1198_p1;
wire  signed [18:0] p_cast4_fu_1186_p1;
wire   [18:0] empty_173_fu_1202_p2;
wire   [18:0] select_ln827_2_fu_1137_p3;
wire   [0:0] and_ln827_fu_1150_p2;
wire   [1:0] select_ln828_fu_1155_p3;
wire   [13:0] zext_ln828_5_fu_1171_p1;
wire   [0:0] and_ln828_fu_1215_p2;
wire   [15:0] tmp_18_fu_1251_p3;
wire   [16:0] tmp_298_cast_fu_1258_p1;
wire   [16:0] zext_ln827_2_fu_1113_p1;
wire   [16:0] empty_177_fu_1262_p2;
wire   [18:0] tmp_19_fu_1272_p3;
wire   [61:0] p_shl60_fu_1280_p1;
wire   [61:0] p_cast8_fu_1268_p1;
wire   [61:0] empty_178_fu_1284_p2;
wire   [61:0] zext_ln828_4_fu_1168_p1;
wire   [61:0] empty_179_fu_1290_p2;
wire   [0:0] xor_ln830_fu_1304_p2;
wire   [0:0] and_ln829_fu_1239_p2;
wire   [0:0] or_ln830_2_fu_1309_p2;
wire   [2:0] select_ln830_fu_1244_p3;
wire   [0:0] and_ln830_fu_1314_p2;
wire   [0:0] or_ln831_fu_1326_p2;
wire   [0:0] or_ln831_1_fu_1331_p2;
wire   [0:0] or_ln831_2_fu_1336_p2;
wire   [2:0] add_ln831_fu_1320_p2;
wire   [2:0] zext_ln828_6_fu_1174_p1;
wire   [2:0] empty_168_fu_1101_p2;
wire   [2:0] zext_ln828_2_fu_1162_p1;
wire   [2:0] select_ln827_3_fu_1363_p3;
wire   [2:0] select_ln828_3_fu_1370_p3;
wire   [2:0] select_ln829_4_fu_1377_p3;
wire   [2:0] p_mid12712_fu_1357_p2;
wire   [2:0] select_ln830_4_fu_1384_p3;
wire   [15:0] tmp_15_fu_1429_p3;
wire  signed [18:0] p_shl59_fu_1436_p1;
wire  signed [18:0] p_cast6_fu_1426_p1;
wire   [18:0] empty_175_fu_1440_p2;
wire   [18:0] zext_ln829_1_fu_1420_p1;
wire   [18:0] empty_176_fu_1446_p2;
wire   [18:0] p_shl3_fu_1458_p3;
wire   [18:0] empty_182_fu_1465_p2;
wire   [18:0] zext_ln829_2_fu_1423_p1;
wire   [18:0] empty_183_fu_1470_p2;
wire   [18:0] select_ln829_2_fu_1452_p3;
wire   [2:0] select_ln829_3_cast_fu_1483_p1;
wire   [2:0] add_ln834_fu_1497_p2;
wire   [11:0] tmp_21_fu_1502_p4;
wire   [31:0] v473_fu_1554_p1;
wire   [31:0] v473_fu_1554_p2;
wire   [31:0] v473_fu_1554_p3;
wire   [31:0] v473_fu_1554_p4;
wire   [31:0] v473_fu_1554_p5;
wire   [31:0] v473_fu_1554_p6;
wire   [31:0] v473_fu_1554_p7;
wire   [31:0] v473_fu_1554_p8;
wire   [11:0] tmp_20_fu_1607_p4;
reg    ap_done_reg;
wire    ap_continue_int;
reg    ap_done_int;
reg    ap_loop_exit_ready_pp0_iter2_reg;
reg    ap_loop_exit_ready_pp0_iter3_reg;
reg    ap_loop_exit_ready_pp0_iter4_reg;
reg    ap_loop_exit_ready_pp0_iter5_reg;
reg    ap_loop_exit_ready_pp0_iter6_reg;
reg    ap_loop_exit_ready_pp0_iter7_reg;
reg    ap_loop_exit_ready_pp0_iter8_reg;
reg    ap_loop_exit_ready_pp0_iter9_reg;
reg    ap_loop_exit_ready_pp0_iter10_reg;
reg    ap_loop_exit_ready_pp0_iter11_reg;
reg    ap_loop_exit_ready_pp0_iter12_reg;
reg    ap_loop_exit_ready_pp0_iter13_reg;
reg    ap_loop_exit_ready_pp0_iter14_reg;
reg    ap_loop_exit_ready_pp0_iter15_reg;
reg    ap_loop_exit_ready_pp0_iter16_reg;
reg    ap_loop_exit_ready_pp0_iter17_reg;
reg    ap_loop_exit_ready_pp0_iter18_reg;
reg    ap_loop_exit_ready_pp0_iter19_reg;
reg   [0:0] ap_NS_fsm;
wire    ap_enable_pp0;
wire    ap_start_int;
wire    ap_block_pp0_stage0_00001;
wire    ap_ce_reg;

// power-on initialization
initial begin
#0 ap_CS_fsm = 1'd1;
#0 ap_enable_reg_pp0_iter1 = 1'b0;
#0 ap_enable_reg_pp0_iter2 = 1'b0;
#0 ap_enable_reg_pp0_iter3 = 1'b0;
#0 ap_enable_reg_pp0_iter4 = 1'b0;
#0 ap_enable_reg_pp0_iter5 = 1'b0;
#0 ap_enable_reg_pp0_iter6 = 1'b0;
#0 ap_enable_reg_pp0_iter7 = 1'b0;
#0 ap_enable_reg_pp0_iter8 = 1'b0;
#0 ap_enable_reg_pp0_iter9 = 1'b0;
#0 ap_enable_reg_pp0_iter10 = 1'b0;
#0 ap_enable_reg_pp0_iter11 = 1'b0;
#0 ap_enable_reg_pp0_iter12 = 1'b0;
#0 ap_enable_reg_pp0_iter13 = 1'b0;
#0 ap_enable_reg_pp0_iter14 = 1'b0;
#0 ap_enable_reg_pp0_iter15 = 1'b0;
#0 ap_enable_reg_pp0_iter16 = 1'b0;
#0 ap_enable_reg_pp0_iter17 = 1'b0;
#0 ap_enable_reg_pp0_iter18 = 1'b0;
#0 ap_enable_reg_pp0_iter19 = 1'b0;
#0 ap_enable_reg_pp0_iter20 = 1'b0;
#0 ap_done_reg = 1'b0;
end

test_vgg16_mux_83_32_1_1 #(
    .ID( 1 ),
    .NUM_STAGE( 1 ),
    .din0_WIDTH( 32 ),
    .din1_WIDTH( 32 ),
    .din2_WIDTH( 32 ),
    .din3_WIDTH( 32 ),
    .din4_WIDTH( 32 ),
    .din5_WIDTH( 32 ),
    .din6_WIDTH( 32 ),
    .din7_WIDTH( 32 ),
    .din8_WIDTH( 3 ),
    .dout_WIDTH( 32 ))
mux_83_32_1_1_U167(
    .din0(v473_fu_1554_p1),
    .din1(v473_fu_1554_p2),
    .din2(v473_fu_1554_p3),
    .din3(v473_fu_1554_p4),
    .din4(v473_fu_1554_p5),
    .din5(v473_fu_1554_p6),
    .din6(v473_fu_1554_p7),
    .din7(v473_fu_1554_p8),
    .din8(trunc_ln827_reg_1868_pp0_iter7_reg),
    .dout(v473_fu_1554_p10)
);

test_vgg16_flow_control_loop_pipe_sequential_init flow_control_loop_pipe_sequential_init_U(
    .ap_clk(ap_clk),
    .ap_rst(ap_rst),
    .ap_start(ap_start),
    .ap_ready(ap_ready),
    .ap_done(ap_done),
    .ap_start_int(ap_start_int),
    .ap_loop_init(ap_loop_init),
    .ap_ready_int(ap_ready_int),
    .ap_loop_exit_ready(ap_condition_exit_pp0_iter1_stage0),
    .ap_loop_exit_done(ap_done_int),
    .ap_continue_int(ap_continue_int),
    .ap_done_int(ap_done_int)
);

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_CS_fsm <= ap_ST_fsm_pp0_stage0;
    end else begin
        ap_CS_fsm <= ap_NS_fsm;
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_done_reg <= 1'b0;
    end else begin
        if ((ap_continue_int == 1'b1)) begin
            ap_done_reg <= 1'b0;
        end else if (((ap_loop_exit_ready_pp0_iter19_reg == 1'b1) & (1'b0 == ap_block_pp0_stage0_subdone))) begin
            ap_done_reg <= 1'b1;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_enable_reg_pp0_iter1 <= 1'b0;
    end else begin
        if ((1'b1 == ap_condition_exit_pp0_iter1_stage0)) begin
            ap_enable_reg_pp0_iter1 <= 1'b0;
        end else if (((1'b1 == ap_CS_fsm_pp0_stage0) & (1'b0 == ap_block_pp0_stage0_subdone))) begin
            ap_enable_reg_pp0_iter1 <= ap_start_int;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_enable_reg_pp0_iter10 <= 1'b0;
    end else begin
        if ((1'b0 == ap_block_pp0_stage0_subdone)) begin
            ap_enable_reg_pp0_iter10 <= ap_enable_reg_pp0_iter9;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_enable_reg_pp0_iter11 <= 1'b0;
    end else begin
        if ((1'b0 == ap_block_pp0_stage0_subdone)) begin
            ap_enable_reg_pp0_iter11 <= ap_enable_reg_pp0_iter10;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_enable_reg_pp0_iter12 <= 1'b0;
    end else begin
        if ((1'b0 == ap_block_pp0_stage0_subdone)) begin
            ap_enable_reg_pp0_iter12 <= ap_enable_reg_pp0_iter11;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_enable_reg_pp0_iter13 <= 1'b0;
    end else begin
        if ((1'b0 == ap_block_pp0_stage0_subdone)) begin
            ap_enable_reg_pp0_iter13 <= ap_enable_reg_pp0_iter12;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_enable_reg_pp0_iter14 <= 1'b0;
    end else begin
        if ((1'b0 == ap_block_pp0_stage0_subdone)) begin
            ap_enable_reg_pp0_iter14 <= ap_enable_reg_pp0_iter13;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_enable_reg_pp0_iter15 <= 1'b0;
    end else begin
        if ((1'b0 == ap_block_pp0_stage0_subdone)) begin
            ap_enable_reg_pp0_iter15 <= ap_enable_reg_pp0_iter14;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_enable_reg_pp0_iter16 <= 1'b0;
    end else begin
        if ((1'b0 == ap_block_pp0_stage0_subdone)) begin
            ap_enable_reg_pp0_iter16 <= ap_enable_reg_pp0_iter15;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_enable_reg_pp0_iter17 <= 1'b0;
    end else begin
        if ((1'b0 == ap_block_pp0_stage0_subdone)) begin
            ap_enable_reg_pp0_iter17 <= ap_enable_reg_pp0_iter16;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_enable_reg_pp0_iter18 <= 1'b0;
    end else begin
        if ((1'b0 == ap_block_pp0_stage0_subdone)) begin
            ap_enable_reg_pp0_iter18 <= ap_enable_reg_pp0_iter17;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_enable_reg_pp0_iter19 <= 1'b0;
    end else begin
        if ((1'b0 == ap_block_pp0_stage0_subdone)) begin
            ap_enable_reg_pp0_iter19 <= ap_enable_reg_pp0_iter18;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_enable_reg_pp0_iter2 <= 1'b0;
    end else begin
        if ((1'b0 == ap_block_pp0_stage0_subdone)) begin
            ap_enable_reg_pp0_iter2 <= ap_enable_reg_pp0_iter1;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_enable_reg_pp0_iter20 <= 1'b0;
    end else begin
        if ((1'b0 == ap_block_pp0_stage0_subdone)) begin
            ap_enable_reg_pp0_iter20 <= ap_enable_reg_pp0_iter19;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_enable_reg_pp0_iter3 <= 1'b0;
    end else begin
        if ((1'b0 == ap_block_pp0_stage0_subdone)) begin
            ap_enable_reg_pp0_iter3 <= ap_enable_reg_pp0_iter2;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_enable_reg_pp0_iter4 <= 1'b0;
    end else begin
        if ((1'b0 == ap_block_pp0_stage0_subdone)) begin
            ap_enable_reg_pp0_iter4 <= ap_enable_reg_pp0_iter3;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_enable_reg_pp0_iter5 <= 1'b0;
    end else begin
        if ((1'b0 == ap_block_pp0_stage0_subdone)) begin
            ap_enable_reg_pp0_iter5 <= ap_enable_reg_pp0_iter4;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_enable_reg_pp0_iter6 <= 1'b0;
    end else begin
        if ((1'b1 == ap_condition_exit_pp0_iter5_stage0)) begin
            ap_enable_reg_pp0_iter6 <= 1'b0;
        end else if ((1'b0 == ap_block_pp0_stage0_subdone)) begin
            ap_enable_reg_pp0_iter6 <= ap_enable_reg_pp0_iter5;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_enable_reg_pp0_iter7 <= 1'b0;
    end else begin
        if ((1'b0 == ap_block_pp0_stage0_subdone)) begin
            ap_enable_reg_pp0_iter7 <= ap_enable_reg_pp0_iter6;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_enable_reg_pp0_iter8 <= 1'b0;
    end else begin
        if ((1'b0 == ap_block_pp0_stage0_subdone)) begin
            ap_enable_reg_pp0_iter8 <= ap_enable_reg_pp0_iter7;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_enable_reg_pp0_iter9 <= 1'b0;
    end else begin
        if ((1'b0 == ap_block_pp0_stage0_subdone)) begin
            ap_enable_reg_pp0_iter9 <= ap_enable_reg_pp0_iter8;
        end
    end
end

always @ (posedge ap_clk) begin
    if ((1'b0 == ap_block_pp0_stage0_11001)) begin
        if (((ap_loop_init == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
            indvar_flatten2714_fu_162 <= 6'd0;
        end else if (((icmp_ln827_reg_1767_pp0_iter3_reg == 1'd0) & (ap_enable_reg_pp0_iter4 == 1'b1))) begin
            indvar_flatten2714_fu_162 <= select_ln831_3_fu_1042_p3;
        end
    end
end

always @ (posedge ap_clk) begin
    if ((1'b0 == ap_block_pp0_stage0_11001)) begin
        if (((ap_loop_init == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
            indvar_flatten2740_fu_170 <= 12'd0;
        end else if (((icmp_ln827_reg_1767_pp0_iter2_reg == 1'd0) & (ap_enable_reg_pp0_iter3 == 1'b1))) begin
            indvar_flatten2740_fu_170 <= select_ln830_5_fu_799_p3;
        end
    end
end

always @ (posedge ap_clk) begin
    if ((1'b0 == ap_block_pp0_stage0_11001)) begin
        if (((ap_loop_init == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
            indvar_flatten2816_fu_178 <= 13'd0;
        end else if (((icmp_ln827_reg_1767 == 1'd0) & (ap_enable_reg_pp0_iter2 == 1'b1))) begin
            indvar_flatten2816_fu_178 <= select_ln829_5_fu_740_p3;
        end
    end
end

always @ (posedge ap_clk) begin
    if (((1'b1 == ap_CS_fsm_pp0_stage0) & (1'b0 == ap_block_pp0_stage0_11001))) begin
        if ((ap_loop_init == 1'b1)) begin
            indvar_flatten2904_fu_186 <= 14'd0;
        end else if (((ap_enable_reg_pp0_iter1 == 1'b1) & (icmp_ln827_fu_664_p2 == 1'd0))) begin
            indvar_flatten2904_fu_186 <= select_ln828_4_fu_691_p3;
        end
    end
end

always @ (posedge ap_clk) begin
    if (((1'b1 == ap_CS_fsm_pp0_stage0) & (1'b0 == ap_block_pp0_stage0_11001))) begin
        if ((ap_loop_init == 1'b1)) begin
            indvar_flatten3007_fu_194 <= 23'd0;
        end else if (((ap_enable_reg_pp0_iter1 == 1'b1) & (icmp_ln827_fu_664_p2 == 1'd0))) begin
            indvar_flatten3007_fu_194 <= add_ln827_1_fu_670_p2;
        end
    end
end

always @ (posedge ap_clk) begin
    if ((1'b0 == ap_block_pp0_stage0_11001)) begin
        if (((ap_loop_init == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
            v467_fu_190 <= 10'd0;
        end else if (((icmp_ln827_reg_1767_pp0_iter3_reg == 1'd0) & (ap_enable_reg_pp0_iter4 == 1'b1))) begin
            v467_fu_190 <= select_ln827_1_fu_899_p3;
        end
    end
end

always @ (posedge ap_clk) begin
    if ((1'b0 == ap_block_pp0_stage0_11001)) begin
        if (((ap_loop_init == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
            v468_fu_182 <= 2'd0;
        end else if (((icmp_ln827_reg_1767_pp0_iter3_reg == 1'd0) & (ap_enable_reg_pp0_iter4 == 1'b1))) begin
            v468_fu_182 <= select_ln828_1_fu_941_p3;
        end
    end
end

always @ (posedge ap_clk) begin
    if ((1'b0 == ap_block_pp0_stage0_11001)) begin
        if (((ap_loop_init == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
            v469_fu_174 <= 2'd0;
        end else if (((icmp_ln827_reg_1767_pp0_iter4_reg == 1'd0) & (ap_enable_reg_pp0_iter5 == 1'b1))) begin
            v469_fu_174 <= select_ln829_1_fu_1226_p3;
        end
    end
end

always @ (posedge ap_clk) begin
    if ((1'b0 == ap_block_pp0_stage0_11001)) begin
        if (((ap_loop_init == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
            v470_fu_166 <= 7'd0;
        end else if (((icmp_ln827_reg_1767_pp0_iter3_reg == 1'd0) & (ap_enable_reg_pp0_iter4 == 1'b1))) begin
            v470_fu_166 <= select_ln830_2_fu_1005_p3;
        end
    end
end

always @ (posedge ap_clk) begin
    if ((1'b0 == ap_block_pp0_stage0_11001)) begin
        if (((ap_loop_init == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
            v471_fu_158 <= 3'd0;
        end else if (((icmp_ln827_reg_1767_pp0_iter4_reg == 1'd0) & (ap_enable_reg_pp0_iter5 == 1'b1))) begin
            v471_fu_158 <= select_ln831_1_fu_1349_p3;
        end
    end
end

always @ (posedge ap_clk) begin
    if ((1'b0 == ap_block_pp0_stage0_11001)) begin
        if (((ap_loop_init == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
            v472_fu_154 <= 3'd0;
        end else if (((icmp_ln827_reg_1767_pp0_iter4_reg == 1'd0) & (ap_enable_reg_pp0_iter5 == 1'b1))) begin
            v472_fu_154 <= add_ln832_fu_1399_p2;
        end
    end
end

always @ (posedge ap_clk) begin
    if (((icmp_ln827_reg_1767_pp0_iter3_reg == 1'd0) & (1'b0 == ap_block_pp0_stage0_11001))) begin
        add_ln827_reg_1852 <= add_ln827_fu_886_p2;
        add_ln828_reg_1873 <= add_ln828_fu_935_p2;
        add_ln830_reg_1908 <= add_ln830_fu_989_p2;
        and_ln828_1_reg_1891 <= and_ln828_1_fu_966_p2;
        and_ln829_1_reg_1901 <= and_ln829_1_fu_983_p2;
        empty_171_reg_1886 <= empty_171_fu_960_p2;
        or_ln830_1_reg_1913 <= or_ln830_1_fu_1000_p2;
        p_cast99_mid2_v_reg_1863 <= {{select_ln827_1_fu_899_p3[8:3]}};
        select_ln827_1_reg_1858 <= select_ln827_1_fu_899_p3;
        select_ln828_1_reg_1879 <= select_ln828_1_fu_941_p3;
        select_ln830_3_reg_1918 <= select_ln830_3_fu_1028_p3;
        trunc_ln827_reg_1868 <= trunc_ln827_fu_920_p1;
        xor_ln829_reg_1896 <= xor_ln829_fu_978_p2;
    end
end

always @ (posedge ap_clk) begin
    if (((icmp_ln827_reg_1767_pp0_iter4_reg == 1'd0) & (1'b0 == ap_block_pp0_stage0_11001))) begin
        add_ln829_reg_1928 <= add_ln829_fu_1220_p2;
        select_ln829_1_reg_1933 <= select_ln829_1_fu_1226_p3;
        select_ln831_1_reg_1961 <= select_ln831_1_fu_1349_p3;
        select_ln831_2_reg_1966 <= select_ln831_2_fu_1391_p3;
        select_ln831_reg_1955 <= select_ln831_fu_1341_p3;
    end
end

always @ (posedge ap_clk) begin
    if (((icmp_ln827_reg_1767 == 1'd0) & (1'b0 == ap_block_pp0_stage0_11001))) begin
        and_ln827_3_reg_1796 <= and_ln827_3_fu_723_p2;
        icmp_ln829_reg_1791 <= icmp_ln829_fu_717_p2;
        or_ln828_reg_1804 <= or_ln828_fu_729_p2;
        xor_ln827_reg_1784 <= xor_ln827_fu_712_p2;
    end
end

always @ (posedge ap_clk) begin
    if ((1'b0 == ap_block_pp0_stage0_11001)) begin
        and_ln827_3_reg_1796_pp0_iter3_reg <= and_ln827_3_reg_1796;
        and_ln827_3_reg_1796_pp0_iter4_reg <= and_ln827_3_reg_1796_pp0_iter3_reg;
        and_ln828_2_reg_1816_pp0_iter4_reg <= and_ln828_2_reg_1816;
        and_ln828_2_reg_1816_pp0_iter5_reg <= and_ln828_2_reg_1816_pp0_iter4_reg;
        and_ln829_1_reg_1901_pp0_iter5_reg <= and_ln829_1_reg_1901;
        ap_loop_exit_ready_pp0_iter10_reg <= ap_loop_exit_ready_pp0_iter9_reg;
        ap_loop_exit_ready_pp0_iter11_reg <= ap_loop_exit_ready_pp0_iter10_reg;
        ap_loop_exit_ready_pp0_iter12_reg <= ap_loop_exit_ready_pp0_iter11_reg;
        ap_loop_exit_ready_pp0_iter13_reg <= ap_loop_exit_ready_pp0_iter12_reg;
        ap_loop_exit_ready_pp0_iter14_reg <= ap_loop_exit_ready_pp0_iter13_reg;
        ap_loop_exit_ready_pp0_iter15_reg <= ap_loop_exit_ready_pp0_iter14_reg;
        ap_loop_exit_ready_pp0_iter16_reg <= ap_loop_exit_ready_pp0_iter15_reg;
        ap_loop_exit_ready_pp0_iter17_reg <= ap_loop_exit_ready_pp0_iter16_reg;
        ap_loop_exit_ready_pp0_iter18_reg <= ap_loop_exit_ready_pp0_iter17_reg;
        ap_loop_exit_ready_pp0_iter19_reg <= ap_loop_exit_ready_pp0_iter18_reg;
        ap_loop_exit_ready_pp0_iter3_reg <= ap_loop_exit_ready_pp0_iter2_reg;
        ap_loop_exit_ready_pp0_iter4_reg <= ap_loop_exit_ready_pp0_iter3_reg;
        ap_loop_exit_ready_pp0_iter5_reg <= ap_loop_exit_ready_pp0_iter4_reg;
        ap_loop_exit_ready_pp0_iter6_reg <= ap_loop_exit_ready_pp0_iter5_reg;
        ap_loop_exit_ready_pp0_iter7_reg <= ap_loop_exit_ready_pp0_iter6_reg;
        ap_loop_exit_ready_pp0_iter8_reg <= ap_loop_exit_ready_pp0_iter7_reg;
        ap_loop_exit_ready_pp0_iter9_reg <= ap_loop_exit_ready_pp0_iter8_reg;
        icmp_ln827_reg_1767_pp0_iter2_reg <= icmp_ln827_reg_1767;
        icmp_ln827_reg_1767_pp0_iter3_reg <= icmp_ln827_reg_1767_pp0_iter2_reg;
        icmp_ln827_reg_1767_pp0_iter4_reg <= icmp_ln827_reg_1767_pp0_iter3_reg;
        icmp_ln828_reg_1771_pp0_iter2_reg <= icmp_ln828_reg_1771;
        icmp_ln828_reg_1771_pp0_iter3_reg <= icmp_ln828_reg_1771_pp0_iter2_reg;
        icmp_ln828_reg_1771_pp0_iter4_reg <= icmp_ln828_reg_1771_pp0_iter3_reg;
        or_ln828_1_reg_1810_pp0_iter4_reg <= or_ln828_1_reg_1810;
        or_ln828_reg_1804_pp0_iter3_reg <= or_ln828_reg_1804;
        or_ln828_reg_1804_pp0_iter4_reg <= or_ln828_reg_1804_pp0_iter3_reg;
        or_ln829_reg_1826_pp0_iter4_reg <= or_ln829_reg_1826;
        p_cast99_mid2_v_reg_1863_pp0_iter5_reg <= p_cast99_mid2_v_reg_1863;
        p_cast99_mid2_v_reg_1863_pp0_iter6_reg <= p_cast99_mid2_v_reg_1863_pp0_iter5_reg;
        select_ln829_1_reg_1933_pp0_iter6_reg <= select_ln829_1_reg_1933;
        select_ln830_1_reg_1971 <= select_ln830_1_fu_1476_p3;
        select_ln830_3_reg_1918_pp0_iter10_reg <= select_ln830_3_reg_1918_pp0_iter9_reg;
        select_ln830_3_reg_1918_pp0_iter5_reg <= select_ln830_3_reg_1918;
        select_ln830_3_reg_1918_pp0_iter6_reg <= select_ln830_3_reg_1918_pp0_iter5_reg;
        select_ln830_3_reg_1918_pp0_iter7_reg <= select_ln830_3_reg_1918_pp0_iter6_reg;
        select_ln830_3_reg_1918_pp0_iter8_reg <= select_ln830_3_reg_1918_pp0_iter7_reg;
        select_ln830_3_reg_1918_pp0_iter9_reg <= select_ln830_3_reg_1918_pp0_iter8_reg;
        select_ln831_1_reg_1961_pp0_iter10_reg <= select_ln831_1_reg_1961_pp0_iter9_reg;
        select_ln831_1_reg_1961_pp0_iter6_reg <= select_ln831_1_reg_1961;
        select_ln831_1_reg_1961_pp0_iter7_reg <= select_ln831_1_reg_1961_pp0_iter6_reg;
        select_ln831_1_reg_1961_pp0_iter8_reg <= select_ln831_1_reg_1961_pp0_iter7_reg;
        select_ln831_1_reg_1961_pp0_iter9_reg <= select_ln831_1_reg_1961_pp0_iter8_reg;
        select_ln831_2_reg_1966_pp0_iter6_reg <= select_ln831_2_reg_1966;
        select_ln831_reg_1955_pp0_iter10_reg <= select_ln831_reg_1955_pp0_iter9_reg;
        select_ln831_reg_1955_pp0_iter6_reg <= select_ln831_reg_1955;
        select_ln831_reg_1955_pp0_iter7_reg <= select_ln831_reg_1955_pp0_iter6_reg;
        select_ln831_reg_1955_pp0_iter8_reg <= select_ln831_reg_1955_pp0_iter7_reg;
        select_ln831_reg_1955_pp0_iter9_reg <= select_ln831_reg_1955_pp0_iter8_reg;
        trunc_ln827_reg_1868_pp0_iter5_reg <= trunc_ln827_reg_1868;
        trunc_ln827_reg_1868_pp0_iter6_reg <= trunc_ln827_reg_1868_pp0_iter5_reg;
        trunc_ln827_reg_1868_pp0_iter7_reg <= trunc_ln827_reg_1868_pp0_iter6_reg;
        v14_0_addr_reg_2148 <= zext_ln837_fu_1614_p1;
        v14_0_addr_reg_2148_pp0_iter12_reg <= v14_0_addr_reg_2148;
        v14_0_addr_reg_2148_pp0_iter13_reg <= v14_0_addr_reg_2148_pp0_iter12_reg;
        v14_0_addr_reg_2148_pp0_iter14_reg <= v14_0_addr_reg_2148_pp0_iter13_reg;
        v14_0_addr_reg_2148_pp0_iter15_reg <= v14_0_addr_reg_2148_pp0_iter14_reg;
        v14_0_addr_reg_2148_pp0_iter16_reg <= v14_0_addr_reg_2148_pp0_iter15_reg;
        v14_0_addr_reg_2148_pp0_iter17_reg <= v14_0_addr_reg_2148_pp0_iter16_reg;
        v14_0_addr_reg_2148_pp0_iter18_reg <= v14_0_addr_reg_2148_pp0_iter17_reg;
        v14_0_addr_reg_2148_pp0_iter19_reg <= v14_0_addr_reg_2148_pp0_iter18_reg;
        v14_1_addr_reg_2154 <= zext_ln837_fu_1614_p1;
        v14_1_addr_reg_2154_pp0_iter12_reg <= v14_1_addr_reg_2154;
        v14_1_addr_reg_2154_pp0_iter13_reg <= v14_1_addr_reg_2154_pp0_iter12_reg;
        v14_1_addr_reg_2154_pp0_iter14_reg <= v14_1_addr_reg_2154_pp0_iter13_reg;
        v14_1_addr_reg_2154_pp0_iter15_reg <= v14_1_addr_reg_2154_pp0_iter14_reg;
        v14_1_addr_reg_2154_pp0_iter16_reg <= v14_1_addr_reg_2154_pp0_iter15_reg;
        v14_1_addr_reg_2154_pp0_iter17_reg <= v14_1_addr_reg_2154_pp0_iter16_reg;
        v14_1_addr_reg_2154_pp0_iter18_reg <= v14_1_addr_reg_2154_pp0_iter17_reg;
        v14_1_addr_reg_2154_pp0_iter19_reg <= v14_1_addr_reg_2154_pp0_iter18_reg;
        v14_2_addr_reg_2160 <= zext_ln837_fu_1614_p1;
        v14_2_addr_reg_2160_pp0_iter12_reg <= v14_2_addr_reg_2160;
        v14_2_addr_reg_2160_pp0_iter13_reg <= v14_2_addr_reg_2160_pp0_iter12_reg;
        v14_2_addr_reg_2160_pp0_iter14_reg <= v14_2_addr_reg_2160_pp0_iter13_reg;
        v14_2_addr_reg_2160_pp0_iter15_reg <= v14_2_addr_reg_2160_pp0_iter14_reg;
        v14_2_addr_reg_2160_pp0_iter16_reg <= v14_2_addr_reg_2160_pp0_iter15_reg;
        v14_2_addr_reg_2160_pp0_iter17_reg <= v14_2_addr_reg_2160_pp0_iter16_reg;
        v14_2_addr_reg_2160_pp0_iter18_reg <= v14_2_addr_reg_2160_pp0_iter17_reg;
        v14_2_addr_reg_2160_pp0_iter19_reg <= v14_2_addr_reg_2160_pp0_iter18_reg;
        v14_3_addr_reg_2166 <= zext_ln837_fu_1614_p1;
        v14_3_addr_reg_2166_pp0_iter12_reg <= v14_3_addr_reg_2166;
        v14_3_addr_reg_2166_pp0_iter13_reg <= v14_3_addr_reg_2166_pp0_iter12_reg;
        v14_3_addr_reg_2166_pp0_iter14_reg <= v14_3_addr_reg_2166_pp0_iter13_reg;
        v14_3_addr_reg_2166_pp0_iter15_reg <= v14_3_addr_reg_2166_pp0_iter14_reg;
        v14_3_addr_reg_2166_pp0_iter16_reg <= v14_3_addr_reg_2166_pp0_iter15_reg;
        v14_3_addr_reg_2166_pp0_iter17_reg <= v14_3_addr_reg_2166_pp0_iter16_reg;
        v14_3_addr_reg_2166_pp0_iter18_reg <= v14_3_addr_reg_2166_pp0_iter17_reg;
        v14_3_addr_reg_2166_pp0_iter19_reg <= v14_3_addr_reg_2166_pp0_iter18_reg;
        v14_4_addr_reg_2172 <= zext_ln837_fu_1614_p1;
        v14_4_addr_reg_2172_pp0_iter12_reg <= v14_4_addr_reg_2172;
        v14_4_addr_reg_2172_pp0_iter13_reg <= v14_4_addr_reg_2172_pp0_iter12_reg;
        v14_4_addr_reg_2172_pp0_iter14_reg <= v14_4_addr_reg_2172_pp0_iter13_reg;
        v14_4_addr_reg_2172_pp0_iter15_reg <= v14_4_addr_reg_2172_pp0_iter14_reg;
        v14_4_addr_reg_2172_pp0_iter16_reg <= v14_4_addr_reg_2172_pp0_iter15_reg;
        v14_4_addr_reg_2172_pp0_iter17_reg <= v14_4_addr_reg_2172_pp0_iter16_reg;
        v14_4_addr_reg_2172_pp0_iter18_reg <= v14_4_addr_reg_2172_pp0_iter17_reg;
        v14_4_addr_reg_2172_pp0_iter19_reg <= v14_4_addr_reg_2172_pp0_iter18_reg;
        v14_5_addr_reg_2178 <= zext_ln837_fu_1614_p1;
        v14_5_addr_reg_2178_pp0_iter12_reg <= v14_5_addr_reg_2178;
        v14_5_addr_reg_2178_pp0_iter13_reg <= v14_5_addr_reg_2178_pp0_iter12_reg;
        v14_5_addr_reg_2178_pp0_iter14_reg <= v14_5_addr_reg_2178_pp0_iter13_reg;
        v14_5_addr_reg_2178_pp0_iter15_reg <= v14_5_addr_reg_2178_pp0_iter14_reg;
        v14_5_addr_reg_2178_pp0_iter16_reg <= v14_5_addr_reg_2178_pp0_iter15_reg;
        v14_5_addr_reg_2178_pp0_iter17_reg <= v14_5_addr_reg_2178_pp0_iter16_reg;
        v14_5_addr_reg_2178_pp0_iter18_reg <= v14_5_addr_reg_2178_pp0_iter17_reg;
        v14_5_addr_reg_2178_pp0_iter19_reg <= v14_5_addr_reg_2178_pp0_iter18_reg;
        v14_6_addr_reg_2184 <= zext_ln837_fu_1614_p1;
        v14_6_addr_reg_2184_pp0_iter12_reg <= v14_6_addr_reg_2184;
        v14_6_addr_reg_2184_pp0_iter13_reg <= v14_6_addr_reg_2184_pp0_iter12_reg;
        v14_6_addr_reg_2184_pp0_iter14_reg <= v14_6_addr_reg_2184_pp0_iter13_reg;
        v14_6_addr_reg_2184_pp0_iter15_reg <= v14_6_addr_reg_2184_pp0_iter14_reg;
        v14_6_addr_reg_2184_pp0_iter16_reg <= v14_6_addr_reg_2184_pp0_iter15_reg;
        v14_6_addr_reg_2184_pp0_iter17_reg <= v14_6_addr_reg_2184_pp0_iter16_reg;
        v14_6_addr_reg_2184_pp0_iter18_reg <= v14_6_addr_reg_2184_pp0_iter17_reg;
        v14_6_addr_reg_2184_pp0_iter19_reg <= v14_6_addr_reg_2184_pp0_iter18_reg;
        v14_7_addr_reg_2190 <= zext_ln837_fu_1614_p1;
        v14_7_addr_reg_2190_pp0_iter12_reg <= v14_7_addr_reg_2190;
        v14_7_addr_reg_2190_pp0_iter13_reg <= v14_7_addr_reg_2190_pp0_iter12_reg;
        v14_7_addr_reg_2190_pp0_iter14_reg <= v14_7_addr_reg_2190_pp0_iter13_reg;
        v14_7_addr_reg_2190_pp0_iter15_reg <= v14_7_addr_reg_2190_pp0_iter14_reg;
        v14_7_addr_reg_2190_pp0_iter16_reg <= v14_7_addr_reg_2190_pp0_iter15_reg;
        v14_7_addr_reg_2190_pp0_iter17_reg <= v14_7_addr_reg_2190_pp0_iter16_reg;
        v14_7_addr_reg_2190_pp0_iter18_reg <= v14_7_addr_reg_2190_pp0_iter17_reg;
        v14_7_addr_reg_2190_pp0_iter19_reg <= v14_7_addr_reg_2190_pp0_iter18_reg;
        v468_1_reg_1837 <= v468_fu_182;
        v473_reg_2096 <= v473_fu_1554_p10;
        v475_reg_2196 <= grp_fu_12608_p_dout0;
        v477_reg_2316 <= grp_fu_12576_p_dout0;
        v479_reg_2206 <= grp_fu_12612_p_dout0;
        v481_reg_2321 <= grp_fu_12580_p_dout0;
        v483_reg_2216 <= grp_fu_12616_p_dout0;
        v485_reg_2326 <= grp_fu_12584_p_dout0;
        v487_reg_2226 <= grp_fu_12620_p_dout0;
        v489_reg_2331 <= grp_fu_12588_p_dout0;
        v491_reg_2236 <= grp_fu_12624_p_dout0;
        v493_reg_2336 <= grp_fu_12592_p_dout0;
        v495_reg_2246 <= grp_fu_12628_p_dout0;
        v497_reg_2341 <= grp_fu_12596_p_dout0;
        v499_reg_2256 <= grp_fu_12632_p_dout0;
        v501_reg_2346 <= grp_fu_12600_p_dout0;
        v503_reg_2266 <= grp_fu_12636_p_dout0;
        v505_reg_2351 <= grp_fu_12604_p_dout0;
        v8_0_load_reg_2056 <= v8_0_Dout_A;
        v8_1_load_reg_2061 <= v8_1_Dout_A;
        v8_2_load_reg_2066 <= v8_2_Dout_A;
        v8_3_load_reg_2071 <= v8_3_Dout_A;
        v8_4_load_reg_2076 <= v8_4_Dout_A;
        v8_5_load_reg_2081 <= v8_5_Dout_A;
        v8_6_load_reg_2086 <= v8_6_Dout_A;
        v8_7_load_reg_2091 <= v8_7_Dout_A;
        xor_ln827_reg_1784_pp0_iter3_reg <= xor_ln827_reg_1784;
        xor_ln827_reg_1784_pp0_iter4_reg <= xor_ln827_reg_1784_pp0_iter3_reg;
    end
end

always @ (posedge ap_clk) begin
    if (((icmp_ln827_reg_1767_pp0_iter2_reg == 1'd0) & (1'b0 == ap_block_pp0_stage0_11001))) begin
        and_ln828_2_reg_1816 <= and_ln828_2_fu_777_p2;
        or_ln828_1_reg_1810 <= or_ln828_1_fu_772_p2;
        or_ln829_1_reg_1831 <= or_ln829_1_fu_788_p2;
        or_ln829_reg_1826 <= or_ln829_fu_783_p2;
    end
end

always @ (posedge ap_clk) begin
    if (((1'b1 == ap_CS_fsm_pp0_stage0) & (1'b0 == ap_block_pp0_stage0_11001))) begin
        ap_loop_exit_ready_pp0_iter2_reg <= ap_loop_exit_ready;
        icmp_ln827_reg_1767 <= icmp_ln827_fu_664_p2;
    end
end

always @ (posedge ap_clk) begin
    if (((icmp_ln828_reg_1771_pp0_iter3_reg == 1'd0) & (1'd0 == and_ln828_2_reg_1816) & (1'd0 == and_ln827_3_reg_1796_pp0_iter3_reg) & (1'b0 == ap_block_pp0_stage0_11001))) begin
        empty_164_reg_1842 <= empty_164_fu_875_p1;
        empty_165_reg_1847 <= empty_165_fu_879_p1;
    end
end

always @ (posedge ap_clk) begin
    if (((1'd0 == and_ln829_1_reg_1901) & (icmp_ln827_reg_1767_pp0_iter4_reg == 1'd0) & (1'd1 == and_ln828_2_reg_1816_pp0_iter4_reg) & (1'b0 == ap_block_pp0_stage0_11001))) begin
        empty_174_reg_1939 <= empty_174_fu_1233_p2;
    end
end

always @ (posedge ap_clk) begin
    if (((icmp_ln827_reg_1767_pp0_iter4_reg == 1'd0) & (1'd1 == and_ln829_1_reg_1901) & (1'b0 == ap_block_pp0_stage0_11001))) begin
        empty_180_reg_1945 <= empty_180_fu_1296_p1;
        empty_181_reg_1950 <= empty_181_fu_1300_p1;
    end
end

always @ (posedge ap_clk) begin
    if (((1'b1 == ap_CS_fsm_pp0_stage0) & (icmp_ln827_fu_664_p2 == 1'd0) & (1'b0 == ap_block_pp0_stage0_11001))) begin
        icmp_ln828_reg_1771 <= icmp_ln828_fu_679_p2;
    end
end

always @ (posedge ap_clk) begin
    if (((1'd0 == and_ln829_1_reg_1901) & (1'd0 == and_ln828_2_reg_1816_pp0_iter4_reg) & (icmp_ln827_reg_1767_pp0_iter4_reg == 1'd0) & (1'b0 == ap_block_pp0_stage0_11001))) begin
        select_ln828_2_reg_1923 <= select_ln828_2_fu_1208_p3;
    end
end

always @ (posedge ap_clk) begin
    if (((ap_enable_reg_pp0_iter12 == 1'b1) & (1'b0 == ap_block_pp0_stage0_11001))) begin
        v14_0_load_reg_2201 <= v14_0_Dout_B;
        v14_1_load_reg_2211 <= v14_1_Dout_B;
        v14_2_load_reg_2221 <= v14_2_Dout_B;
        v14_3_load_reg_2231 <= v14_3_Dout_B;
        v14_4_load_reg_2241 <= v14_4_Dout_B;
        v14_5_load_reg_2251 <= v14_5_Dout_B;
        v14_6_load_reg_2261 <= v14_6_Dout_B;
        v14_7_load_reg_2271 <= v14_7_Dout_B;
    end
end

always @ (*) begin
    if (((ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0) & (icmp_ln827_fu_664_p2 == 1'd1) & (1'b0 == ap_block_pp0_stage0_subdone))) begin
        ap_condition_exit_pp0_iter1_stage0 = 1'b1;
    end else begin
        ap_condition_exit_pp0_iter1_stage0 = 1'b0;
    end
end

always @ (*) begin
    if (((icmp_ln827_reg_1767_pp0_iter4_reg == 1'd1) & (ap_enable_reg_pp0_iter5 == 1'b1) & (1'b0 == ap_block_pp0_stage0_subdone))) begin
        ap_condition_exit_pp0_iter5_stage0 = 1'b1;
    end else begin
        ap_condition_exit_pp0_iter5_stage0 = 1'b0;
    end
end

always @ (*) begin
    if (((ap_loop_exit_ready_pp0_iter19_reg == 1'b1) & (1'b0 == ap_block_pp0_stage0_subdone))) begin
        ap_done_int = 1'b1;
    end else begin
        ap_done_int = ap_done_reg;
    end
end

always @ (*) begin
    if (((ap_idle_pp0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0) & (ap_start_int == 1'b0))) begin
        ap_idle = 1'b1;
    end else begin
        ap_idle = 1'b0;
    end
end

always @ (*) begin
    if (((ap_enable_reg_pp0_iter20 == 1'b0) & (ap_enable_reg_pp0_iter19 == 1'b0) & (ap_enable_reg_pp0_iter18 == 1'b0) & (ap_enable_reg_pp0_iter17 == 1'b0) & (ap_enable_reg_pp0_iter16 == 1'b0) & (ap_enable_reg_pp0_iter15 == 1'b0) & (ap_enable_reg_pp0_iter14 == 1'b0) & (ap_enable_reg_pp0_iter13 == 1'b0) & (ap_enable_reg_pp0_iter12 == 1'b0) & (ap_enable_reg_pp0_iter11 == 1'b0) & (ap_enable_reg_pp0_iter10 == 1'b0) & (ap_enable_reg_pp0_iter9 == 1'b0) & (ap_enable_reg_pp0_iter8 == 1'b0) & (ap_enable_reg_pp0_iter7 == 1'b0) & (ap_enable_reg_pp0_iter6 == 1'b0) & (ap_enable_reg_pp0_iter5 == 1'b0) & (ap_enable_reg_pp0_iter4 == 1'b0) & (ap_enable_reg_pp0_iter3 == 1'b0) & (ap_enable_reg_pp0_iter2 == 1'b0) & (ap_enable_reg_pp0_iter1 == 1'b0) & (ap_enable_reg_pp0_iter0 == 1'b0))) begin
        ap_idle_pp0 = 1'b1;
    end else begin
        ap_idle_pp0 = 1'b0;
    end
end

always @ (*) begin
    if (((ap_enable_reg_pp0_iter0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0) & (1'b0 == ap_block_pp0_stage0_subdone))) begin
        ap_ready_int = 1'b1;
    end else begin
        ap_ready_int = 1'b0;
    end
end

always @ (*) begin
    if (((ap_enable_reg_pp0_iter7 == 1'b1) & (1'b0 == ap_block_pp0_stage0_11001))) begin
        v13_0_EN_A = 1'b1;
    end else begin
        v13_0_EN_A = 1'b0;
    end
end

always @ (*) begin
    if (((ap_enable_reg_pp0_iter7 == 1'b1) & (1'b0 == ap_block_pp0_stage0_11001))) begin
        v13_1_EN_A = 1'b1;
    end else begin
        v13_1_EN_A = 1'b0;
    end
end

always @ (*) begin
    if (((ap_enable_reg_pp0_iter7 == 1'b1) & (1'b0 == ap_block_pp0_stage0_11001))) begin
        v13_2_EN_A = 1'b1;
    end else begin
        v13_2_EN_A = 1'b0;
    end
end

always @ (*) begin
    if (((ap_enable_reg_pp0_iter7 == 1'b1) & (1'b0 == ap_block_pp0_stage0_11001))) begin
        v13_3_EN_A = 1'b1;
    end else begin
        v13_3_EN_A = 1'b0;
    end
end

always @ (*) begin
    if (((ap_enable_reg_pp0_iter7 == 1'b1) & (1'b0 == ap_block_pp0_stage0_11001))) begin
        v13_4_EN_A = 1'b1;
    end else begin
        v13_4_EN_A = 1'b0;
    end
end

always @ (*) begin
    if (((ap_enable_reg_pp0_iter7 == 1'b1) & (1'b0 == ap_block_pp0_stage0_11001))) begin
        v13_5_EN_A = 1'b1;
    end else begin
        v13_5_EN_A = 1'b0;
    end
end

always @ (*) begin
    if (((ap_enable_reg_pp0_iter7 == 1'b1) & (1'b0 == ap_block_pp0_stage0_11001))) begin
        v13_6_EN_A = 1'b1;
    end else begin
        v13_6_EN_A = 1'b0;
    end
end

always @ (*) begin
    if (((ap_enable_reg_pp0_iter7 == 1'b1) & (1'b0 == ap_block_pp0_stage0_11001))) begin
        v13_7_EN_A = 1'b1;
    end else begin
        v13_7_EN_A = 1'b0;
    end
end

always @ (*) begin
    if (((ap_enable_reg_pp0_iter20 == 1'b1) & (1'b0 == ap_block_pp0_stage0_11001))) begin
        v14_0_EN_A = 1'b1;
    end else begin
        v14_0_EN_A = 1'b0;
    end
end

always @ (*) begin
    if (((ap_enable_reg_pp0_iter11 == 1'b1) & (1'b0 == ap_block_pp0_stage0_11001))) begin
        v14_0_EN_B = 1'b1;
    end else begin
        v14_0_EN_B = 1'b0;
    end
end

always @ (*) begin
    if (((ap_enable_reg_pp0_iter20 == 1'b1) & (1'b0 == ap_block_pp0_stage0_11001))) begin
        v14_0_WEN_A = 4'd15;
    end else begin
        v14_0_WEN_A = 4'd0;
    end
end

always @ (*) begin
    if (((ap_enable_reg_pp0_iter20 == 1'b1) & (1'b0 == ap_block_pp0_stage0_11001))) begin
        v14_1_EN_A = 1'b1;
    end else begin
        v14_1_EN_A = 1'b0;
    end
end

always @ (*) begin
    if (((ap_enable_reg_pp0_iter11 == 1'b1) & (1'b0 == ap_block_pp0_stage0_11001))) begin
        v14_1_EN_B = 1'b1;
    end else begin
        v14_1_EN_B = 1'b0;
    end
end

always @ (*) begin
    if (((ap_enable_reg_pp0_iter20 == 1'b1) & (1'b0 == ap_block_pp0_stage0_11001))) begin
        v14_1_WEN_A = 4'd15;
    end else begin
        v14_1_WEN_A = 4'd0;
    end
end

always @ (*) begin
    if (((ap_enable_reg_pp0_iter20 == 1'b1) & (1'b0 == ap_block_pp0_stage0_11001))) begin
        v14_2_EN_A = 1'b1;
    end else begin
        v14_2_EN_A = 1'b0;
    end
end

always @ (*) begin
    if (((ap_enable_reg_pp0_iter11 == 1'b1) & (1'b0 == ap_block_pp0_stage0_11001))) begin
        v14_2_EN_B = 1'b1;
    end else begin
        v14_2_EN_B = 1'b0;
    end
end

always @ (*) begin
    if (((ap_enable_reg_pp0_iter20 == 1'b1) & (1'b0 == ap_block_pp0_stage0_11001))) begin
        v14_2_WEN_A = 4'd15;
    end else begin
        v14_2_WEN_A = 4'd0;
    end
end

always @ (*) begin
    if (((ap_enable_reg_pp0_iter20 == 1'b1) & (1'b0 == ap_block_pp0_stage0_11001))) begin
        v14_3_EN_A = 1'b1;
    end else begin
        v14_3_EN_A = 1'b0;
    end
end

always @ (*) begin
    if (((ap_enable_reg_pp0_iter11 == 1'b1) & (1'b0 == ap_block_pp0_stage0_11001))) begin
        v14_3_EN_B = 1'b1;
    end else begin
        v14_3_EN_B = 1'b0;
    end
end

always @ (*) begin
    if (((ap_enable_reg_pp0_iter20 == 1'b1) & (1'b0 == ap_block_pp0_stage0_11001))) begin
        v14_3_WEN_A = 4'd15;
    end else begin
        v14_3_WEN_A = 4'd0;
    end
end

always @ (*) begin
    if (((ap_enable_reg_pp0_iter20 == 1'b1) & (1'b0 == ap_block_pp0_stage0_11001))) begin
        v14_4_EN_A = 1'b1;
    end else begin
        v14_4_EN_A = 1'b0;
    end
end

always @ (*) begin
    if (((ap_enable_reg_pp0_iter11 == 1'b1) & (1'b0 == ap_block_pp0_stage0_11001))) begin
        v14_4_EN_B = 1'b1;
    end else begin
        v14_4_EN_B = 1'b0;
    end
end

always @ (*) begin
    if (((ap_enable_reg_pp0_iter20 == 1'b1) & (1'b0 == ap_block_pp0_stage0_11001))) begin
        v14_4_WEN_A = 4'd15;
    end else begin
        v14_4_WEN_A = 4'd0;
    end
end

always @ (*) begin
    if (((ap_enable_reg_pp0_iter20 == 1'b1) & (1'b0 == ap_block_pp0_stage0_11001))) begin
        v14_5_EN_A = 1'b1;
    end else begin
        v14_5_EN_A = 1'b0;
    end
end

always @ (*) begin
    if (((ap_enable_reg_pp0_iter11 == 1'b1) & (1'b0 == ap_block_pp0_stage0_11001))) begin
        v14_5_EN_B = 1'b1;
    end else begin
        v14_5_EN_B = 1'b0;
    end
end

always @ (*) begin
    if (((ap_enable_reg_pp0_iter20 == 1'b1) & (1'b0 == ap_block_pp0_stage0_11001))) begin
        v14_5_WEN_A = 4'd15;
    end else begin
        v14_5_WEN_A = 4'd0;
    end
end

always @ (*) begin
    if (((ap_enable_reg_pp0_iter20 == 1'b1) & (1'b0 == ap_block_pp0_stage0_11001))) begin
        v14_6_EN_A = 1'b1;
    end else begin
        v14_6_EN_A = 1'b0;
    end
end

always @ (*) begin
    if (((ap_enable_reg_pp0_iter11 == 1'b1) & (1'b0 == ap_block_pp0_stage0_11001))) begin
        v14_6_EN_B = 1'b1;
    end else begin
        v14_6_EN_B = 1'b0;
    end
end

always @ (*) begin
    if (((ap_enable_reg_pp0_iter20 == 1'b1) & (1'b0 == ap_block_pp0_stage0_11001))) begin
        v14_6_WEN_A = 4'd15;
    end else begin
        v14_6_WEN_A = 4'd0;
    end
end

always @ (*) begin
    if (((ap_enable_reg_pp0_iter20 == 1'b1) & (1'b0 == ap_block_pp0_stage0_11001))) begin
        v14_7_EN_A = 1'b1;
    end else begin
        v14_7_EN_A = 1'b0;
    end
end

always @ (*) begin
    if (((ap_enable_reg_pp0_iter11 == 1'b1) & (1'b0 == ap_block_pp0_stage0_11001))) begin
        v14_7_EN_B = 1'b1;
    end else begin
        v14_7_EN_B = 1'b0;
    end
end

always @ (*) begin
    if (((ap_enable_reg_pp0_iter20 == 1'b1) & (1'b0 == ap_block_pp0_stage0_11001))) begin
        v14_7_WEN_A = 4'd15;
    end else begin
        v14_7_WEN_A = 4'd0;
    end
end

always @ (*) begin
    if (((ap_enable_reg_pp0_iter7 == 1'b1) & (1'b0 == ap_block_pp0_stage0_11001))) begin
        v8_0_EN_A = 1'b1;
    end else begin
        v8_0_EN_A = 1'b0;
    end
end

always @ (*) begin
    if (((ap_enable_reg_pp0_iter7 == 1'b1) & (1'b0 == ap_block_pp0_stage0_11001))) begin
        v8_1_EN_A = 1'b1;
    end else begin
        v8_1_EN_A = 1'b0;
    end
end

always @ (*) begin
    if (((ap_enable_reg_pp0_iter7 == 1'b1) & (1'b0 == ap_block_pp0_stage0_11001))) begin
        v8_2_EN_A = 1'b1;
    end else begin
        v8_2_EN_A = 1'b0;
    end
end

always @ (*) begin
    if (((ap_enable_reg_pp0_iter7 == 1'b1) & (1'b0 == ap_block_pp0_stage0_11001))) begin
        v8_3_EN_A = 1'b1;
    end else begin
        v8_3_EN_A = 1'b0;
    end
end

always @ (*) begin
    if (((ap_enable_reg_pp0_iter7 == 1'b1) & (1'b0 == ap_block_pp0_stage0_11001))) begin
        v8_4_EN_A = 1'b1;
    end else begin
        v8_4_EN_A = 1'b0;
    end
end

always @ (*) begin
    if (((ap_enable_reg_pp0_iter7 == 1'b1) & (1'b0 == ap_block_pp0_stage0_11001))) begin
        v8_5_EN_A = 1'b1;
    end else begin
        v8_5_EN_A = 1'b0;
    end
end

always @ (*) begin
    if (((ap_enable_reg_pp0_iter7 == 1'b1) & (1'b0 == ap_block_pp0_stage0_11001))) begin
        v8_6_EN_A = 1'b1;
    end else begin
        v8_6_EN_A = 1'b0;
    end
end

always @ (*) begin
    if (((ap_enable_reg_pp0_iter7 == 1'b1) & (1'b0 == ap_block_pp0_stage0_11001))) begin
        v8_7_EN_A = 1'b1;
    end else begin
        v8_7_EN_A = 1'b0;
    end
end

always @ (*) begin
    case (ap_CS_fsm)
        ap_ST_fsm_pp0_stage0 : begin
            ap_NS_fsm = ap_ST_fsm_pp0_stage0;
        end
        default : begin
            ap_NS_fsm = 'bx;
        end
    endcase
end

assign add_ln827_1_fu_670_p2 = (indvar_flatten3007_fu_194 + 23'd1);

assign add_ln827_fu_886_p2 = (v467_fu_190 + 10'd1);

assign add_ln828_1_fu_685_p2 = (indvar_flatten2904_fu_186 + 14'd1);

assign add_ln828_fu_935_p2 = (select_ln827_fu_892_p3 + 2'd1);

assign add_ln829_1_fu_734_p2 = (indvar_flatten2816_fu_178 + 13'd1);

assign add_ln829_fu_1220_p2 = (select_ln828_fu_1155_p3 + 2'd1);

assign add_ln830_1_fu_793_p2 = (indvar_flatten2740_fu_170 + 12'd1);

assign add_ln830_fu_989_p2 = (select_ln829_fu_971_p3 + 7'd1);

assign add_ln831_1_fu_1036_p2 = (indvar_flatten2714_fu_162 + 6'd1);

assign add_ln831_fu_1320_p2 = (select_ln830_fu_1244_p3 + 3'd1);

assign add_ln832_fu_1399_p2 = (select_ln831_fu_1341_p3 + 3'd1);

assign add_ln834_fu_1497_p2 = (select_ln831_reg_1955_pp0_iter6_reg + select_ln829_3_cast_fu_1483_p1);

assign and_ln827_1_fu_930_p2 = (xor_ln827_reg_1784_pp0_iter3_reg & icmp_ln831_fu_924_p2);

assign and_ln827_2_fu_762_p2 = (xor_ln827_reg_1784 & icmp_ln830_fu_756_p2);

assign and_ln827_3_fu_723_p2 = (xor_ln827_fu_712_p2 & icmp_ln829_fu_717_p2);

assign and_ln827_fu_1150_p2 = (xor_ln827_reg_1784_pp0_iter4_reg & icmp_ln832_fu_1144_p2);

assign and_ln828_1_fu_966_p2 = (or_ln828_1_reg_1810 & and_ln827_1_fu_930_p2);

assign and_ln828_2_fu_777_p2 = (or_ln828_1_fu_772_p2 & and_ln827_2_fu_762_p2);

assign and_ln828_fu_1215_p2 = (or_ln828_1_reg_1810_pp0_iter4_reg & and_ln827_fu_1150_p2);

assign and_ln829_1_fu_983_p2 = (xor_ln829_fu_978_p2 & and_ln828_1_fu_966_p2);

assign and_ln829_fu_1239_p2 = (xor_ln829_reg_1896 & and_ln828_fu_1215_p2);

assign and_ln830_fu_1314_p2 = (or_ln830_2_fu_1309_p2 & and_ln829_fu_1239_p2);

assign ap_CS_fsm_pp0_stage0 = ap_CS_fsm[32'd0];

assign ap_block_pp0_stage0 = ~(1'b1 == 1'b1);

assign ap_block_pp0_stage0_00001 = ~(1'b1 == 1'b1);

assign ap_block_pp0_stage0_11001 = ~(1'b1 == 1'b1);

assign ap_block_pp0_stage0_subdone = ~(1'b1 == 1'b1);

assign ap_block_state10_pp0_stage0_iter9 = ~(1'b1 == 1'b1);

assign ap_block_state11_pp0_stage0_iter10 = ~(1'b1 == 1'b1);

assign ap_block_state12_pp0_stage0_iter11 = ~(1'b1 == 1'b1);

assign ap_block_state13_pp0_stage0_iter12 = ~(1'b1 == 1'b1);

assign ap_block_state14_pp0_stage0_iter13 = ~(1'b1 == 1'b1);

assign ap_block_state15_pp0_stage0_iter14 = ~(1'b1 == 1'b1);

assign ap_block_state16_pp0_stage0_iter15 = ~(1'b1 == 1'b1);

assign ap_block_state17_pp0_stage0_iter16 = ~(1'b1 == 1'b1);

assign ap_block_state18_pp0_stage0_iter17 = ~(1'b1 == 1'b1);

assign ap_block_state19_pp0_stage0_iter18 = ~(1'b1 == 1'b1);

assign ap_block_state1_pp0_stage0_iter0 = ~(1'b1 == 1'b1);

assign ap_block_state20_pp0_stage0_iter19 = ~(1'b1 == 1'b1);

assign ap_block_state21_pp0_stage0_iter20 = ~(1'b1 == 1'b1);

assign ap_block_state2_pp0_stage0_iter1 = ~(1'b1 == 1'b1);

assign ap_block_state3_pp0_stage0_iter2 = ~(1'b1 == 1'b1);

assign ap_block_state4_pp0_stage0_iter3 = ~(1'b1 == 1'b1);

assign ap_block_state5_pp0_stage0_iter4 = ~(1'b1 == 1'b1);

assign ap_block_state6_pp0_stage0_iter5 = ~(1'b1 == 1'b1);

assign ap_block_state7_pp0_stage0_iter6 = ~(1'b1 == 1'b1);

assign ap_block_state8_pp0_stage0_iter7 = ~(1'b1 == 1'b1);

assign ap_block_state9_pp0_stage0_iter8 = ~(1'b1 == 1'b1);

assign ap_enable_pp0 = (ap_idle_pp0 ^ 1'b1);

assign ap_enable_reg_pp0_iter0 = ap_start_int;

assign ap_loop_exit_ready = ap_condition_exit_pp0_iter1_stage0;

assign bitcast_ln830_1_fu_1579_p1 = v8_1_load_reg_2061;

assign bitcast_ln830_2_fu_1583_p1 = v8_2_load_reg_2066;

assign bitcast_ln830_3_fu_1587_p1 = v8_3_load_reg_2071;

assign bitcast_ln830_4_fu_1591_p1 = v8_4_load_reg_2076;

assign bitcast_ln830_5_fu_1595_p1 = v8_5_load_reg_2081;

assign bitcast_ln830_6_fu_1599_p1 = v8_6_load_reg_2086;

assign bitcast_ln830_7_fu_1603_p1 = v8_7_load_reg_2091;

assign bitcast_ln830_fu_1575_p1 = v8_0_load_reg_2056;

assign empty_162_fu_863_p2 = (p_shl56_fu_859_p1 - p_cast_fu_847_p1);

assign empty_163_fu_869_p2 = (empty_162_fu_863_p2 + zext_ln828_fu_825_p1);

assign empty_164_fu_875_p1 = empty_163_fu_869_p2[18:0];

assign empty_165_fu_879_p1 = empty_163_fu_869_p2[16:0];

assign empty_166_fu_1090_p2 = (p_shl_fu_1083_p3 - empty_164_reg_1842);

assign empty_167_fu_1095_p2 = (empty_166_fu_1090_p2 + zext_ln829_fu_1079_p1);

assign empty_168_fu_1101_p2 = (v471_fu_158 + zext_ln828_1_fu_1076_p1);

assign empty_170_fu_1127_p2 = (tmp_294_cast_fu_1123_p1 + zext_ln827_1_fu_1110_p1);

assign empty_171_fu_960_p2 = (tmp_295_cast_fu_956_p1 - zext_ln827_3_fu_906_p1);

assign empty_172_fu_1180_p2 = ($signed(p_cast3_fu_1177_p1) + $signed(zext_ln828_3_fu_1165_p1));

assign empty_173_fu_1202_p2 = ($signed(p_shl58_fu_1198_p1) - $signed(p_cast4_fu_1186_p1));

assign empty_174_fu_1233_p2 = ($signed(p_cast3_fu_1177_p1) + $signed(zext_ln828_5_fu_1171_p1));

assign empty_175_fu_1440_p2 = ($signed(p_shl59_fu_1436_p1) - $signed(p_cast6_fu_1426_p1));

assign empty_176_fu_1446_p2 = (empty_175_fu_1440_p2 + zext_ln829_1_fu_1420_p1);

assign empty_177_fu_1262_p2 = (tmp_298_cast_fu_1258_p1 + zext_ln827_2_fu_1113_p1);

assign empty_178_fu_1284_p2 = (p_shl60_fu_1280_p1 - p_cast8_fu_1268_p1);

assign empty_179_fu_1290_p2 = (empty_178_fu_1284_p2 + zext_ln828_4_fu_1168_p1);

assign empty_180_fu_1296_p1 = empty_179_fu_1290_p2[18:0];

assign empty_181_fu_1300_p1 = empty_179_fu_1290_p2[16:0];

assign empty_182_fu_1465_p2 = (p_shl3_fu_1458_p3 - empty_180_reg_1945);

assign empty_183_fu_1470_p2 = (empty_182_fu_1465_p2 + zext_ln829_2_fu_1423_p1);

assign empty_184_fu_1013_p1 = add_ln830_fu_989_p2[5:0];

assign empty_185_fu_1017_p1 = v470_fu_166[5:0];

assign empty_fu_841_p2 = (tmp_290_cast_fu_837_p1 + zext_ln827_fu_821_p1);

assign grp_fu_12576_p_ce = 1'b1;

assign grp_fu_12576_p_din0 = v475_reg_2196;

assign grp_fu_12576_p_din1 = v476_fu_1626_p1;

assign grp_fu_12576_p_opcode = 2'd0;

assign grp_fu_12580_p_ce = 1'b1;

assign grp_fu_12580_p_din0 = v479_reg_2206;

assign grp_fu_12580_p_din1 = v480_fu_1630_p1;

assign grp_fu_12580_p_opcode = 2'd0;

assign grp_fu_12584_p_ce = 1'b1;

assign grp_fu_12584_p_din0 = v483_reg_2216;

assign grp_fu_12584_p_din1 = v484_fu_1634_p1;

assign grp_fu_12584_p_opcode = 2'd0;

assign grp_fu_12588_p_ce = 1'b1;

assign grp_fu_12588_p_din0 = v487_reg_2226;

assign grp_fu_12588_p_din1 = v488_fu_1638_p1;

assign grp_fu_12588_p_opcode = 2'd0;

assign grp_fu_12592_p_ce = 1'b1;

assign grp_fu_12592_p_din0 = v491_reg_2236;

assign grp_fu_12592_p_din1 = v492_fu_1642_p1;

assign grp_fu_12592_p_opcode = 2'd0;

assign grp_fu_12596_p_ce = 1'b1;

assign grp_fu_12596_p_din0 = v495_reg_2246;

assign grp_fu_12596_p_din1 = v496_fu_1646_p1;

assign grp_fu_12596_p_opcode = 2'd0;

assign grp_fu_12600_p_ce = 1'b1;

assign grp_fu_12600_p_din0 = v499_reg_2256;

assign grp_fu_12600_p_din1 = v500_fu_1650_p1;

assign grp_fu_12600_p_opcode = 2'd0;

assign grp_fu_12604_p_ce = 1'b1;

assign grp_fu_12604_p_din0 = v503_reg_2266;

assign grp_fu_12604_p_din1 = v504_fu_1654_p1;

assign grp_fu_12604_p_opcode = 2'd0;

assign grp_fu_12608_p_ce = 1'b1;

assign grp_fu_12608_p_din0 = v473_reg_2096;

assign grp_fu_12608_p_din1 = bitcast_ln830_fu_1575_p1;

assign grp_fu_12612_p_ce = 1'b1;

assign grp_fu_12612_p_din0 = v473_reg_2096;

assign grp_fu_12612_p_din1 = bitcast_ln830_1_fu_1579_p1;

assign grp_fu_12616_p_ce = 1'b1;

assign grp_fu_12616_p_din0 = v473_reg_2096;

assign grp_fu_12616_p_din1 = bitcast_ln830_2_fu_1583_p1;

assign grp_fu_12620_p_ce = 1'b1;

assign grp_fu_12620_p_din0 = v473_reg_2096;

assign grp_fu_12620_p_din1 = bitcast_ln830_3_fu_1587_p1;

assign grp_fu_12624_p_ce = 1'b1;

assign grp_fu_12624_p_din0 = v473_reg_2096;

assign grp_fu_12624_p_din1 = bitcast_ln830_4_fu_1591_p1;

assign grp_fu_12628_p_ce = 1'b1;

assign grp_fu_12628_p_din0 = v473_reg_2096;

assign grp_fu_12628_p_din1 = bitcast_ln830_5_fu_1595_p1;

assign grp_fu_12632_p_ce = 1'b1;

assign grp_fu_12632_p_din0 = v473_reg_2096;

assign grp_fu_12632_p_din1 = bitcast_ln830_6_fu_1599_p1;

assign grp_fu_12636_p_ce = 1'b1;

assign grp_fu_12636_p_din0 = v473_reg_2096;

assign grp_fu_12636_p_din1 = bitcast_ln830_7_fu_1603_p1;

assign icmp_ln827_fu_664_p2 = ((indvar_flatten3007_fu_194 == 23'd4718592) ? 1'b1 : 1'b0);

assign icmp_ln828_fu_679_p2 = ((indvar_flatten2904_fu_186 == 14'd9216) ? 1'b1 : 1'b0);

assign icmp_ln829_fu_717_p2 = ((indvar_flatten2816_fu_178 == 13'd3072) ? 1'b1 : 1'b0);

assign icmp_ln830_fu_756_p2 = ((indvar_flatten2740_fu_170 == 12'd1024) ? 1'b1 : 1'b0);

assign icmp_ln831_fu_924_p2 = ((indvar_flatten2714_fu_162 == 6'd16) ? 1'b1 : 1'b0);

assign icmp_ln832_fu_1144_p2 = ((v472_fu_154 == 3'd4) ? 1'b1 : 1'b0);

assign or_ln828_1_fu_772_p2 = (xor_ln828_fu_767_p2 | icmp_ln828_reg_1771_pp0_iter2_reg);

assign or_ln828_fu_729_p2 = (icmp_ln828_reg_1771 | and_ln827_3_fu_723_p2);

assign or_ln829_1_fu_788_p2 = (or_ln829_fu_783_p2 | icmp_ln828_reg_1771_pp0_iter2_reg);

assign or_ln829_fu_783_p2 = (and_ln828_2_fu_777_p2 | and_ln827_3_reg_1796);

assign or_ln830_1_fu_1000_p2 = (or_ln830_fu_995_p2 | or_ln828_reg_1804_pp0_iter3_reg);

assign or_ln830_2_fu_1309_p2 = (xor_ln830_fu_1304_p2 | and_ln828_2_reg_1816_pp0_iter4_reg);

assign or_ln830_fu_995_p2 = (and_ln829_1_fu_983_p2 | and_ln828_2_reg_1816);

assign or_ln831_1_fu_1331_p2 = (or_ln831_fu_1326_p2 | or_ln829_reg_1826_pp0_iter4_reg);

assign or_ln831_2_fu_1336_p2 = (or_ln831_1_fu_1331_p2 | icmp_ln828_reg_1771_pp0_iter4_reg);

assign or_ln831_fu_1326_p2 = (and_ln830_fu_1314_p2 | and_ln829_1_reg_1901);

assign p_cast3_fu_1177_p1 = $signed(empty_171_reg_1886);

assign p_cast4_fu_1186_p1 = empty_172_fu_1180_p2;

assign p_cast6_fu_1426_p1 = empty_174_reg_1939;

assign p_cast8_fu_1268_p1 = empty_177_fu_1262_p2;

assign p_cast_fu_847_p1 = empty_fu_841_p2;

assign p_mid12712_fu_1357_p2 = (add_ln831_fu_1320_p2 + zext_ln828_6_fu_1174_p1);

assign p_shl3_fu_1458_p3 = {{empty_181_reg_1950}, {2'd0}};

assign p_shl56_fu_859_p1 = tmp_fu_851_p3;

assign p_shl58_fu_1198_p1 = $signed(tmp_14_fu_1190_p3);

assign p_shl59_fu_1436_p1 = $signed(tmp_15_fu_1429_p3);

assign p_shl60_fu_1280_p1 = tmp_19_fu_1272_p3;

assign p_shl_fu_1083_p3 = {{empty_165_reg_1847}, {2'd0}};

assign select_ln827_1_fu_899_p3 = ((icmp_ln828_reg_1771_pp0_iter3_reg[0:0] == 1'b1) ? add_ln827_fu_886_p2 : v467_fu_190);

assign select_ln827_2_fu_1137_p3 = ((icmp_ln828_reg_1771_pp0_iter4_reg[0:0] == 1'b1) ? zext_ln830_fu_1133_p1 : empty_167_fu_1095_p2);

assign select_ln827_3_fu_1363_p3 = ((icmp_ln828_reg_1771_pp0_iter4_reg[0:0] == 1'b1) ? 3'd0 : empty_168_fu_1101_p2);

assign select_ln827_fu_892_p3 = ((icmp_ln828_reg_1771_pp0_iter3_reg[0:0] == 1'b1) ? 2'd0 : v468_fu_182);

assign select_ln828_1_fu_941_p3 = ((and_ln827_3_reg_1796_pp0_iter3_reg[0:0] == 1'b1) ? add_ln828_fu_935_p2 : select_ln827_fu_892_p3);

assign select_ln828_2_fu_1208_p3 = ((and_ln827_3_reg_1796_pp0_iter4_reg[0:0] == 1'b1) ? empty_173_fu_1202_p2 : select_ln827_2_fu_1137_p3);

assign select_ln828_3_fu_1370_p3 = ((and_ln827_3_reg_1796_pp0_iter4_reg[0:0] == 1'b1) ? zext_ln828_2_fu_1162_p1 : select_ln827_3_fu_1363_p3);

assign select_ln828_4_fu_691_p3 = ((icmp_ln828_fu_679_p2[0:0] == 1'b1) ? 14'd1 : add_ln828_1_fu_685_p2);

assign select_ln828_fu_1155_p3 = ((or_ln828_reg_1804_pp0_iter4_reg[0:0] == 1'b1) ? 2'd0 : v469_fu_174);

assign select_ln829_1_fu_1226_p3 = ((and_ln828_2_reg_1816_pp0_iter4_reg[0:0] == 1'b1) ? add_ln829_fu_1220_p2 : select_ln828_fu_1155_p3);

assign select_ln829_2_fu_1452_p3 = ((and_ln828_2_reg_1816_pp0_iter5_reg[0:0] == 1'b1) ? empty_176_fu_1446_p2 : select_ln828_2_reg_1923);

assign select_ln829_3_cast_fu_1483_p1 = select_ln829_1_reg_1933_pp0_iter6_reg;

assign select_ln829_3_fu_1021_p3 = ((or_ln829_1_reg_1831[0:0] == 1'b1) ? 6'd0 : empty_185_fu_1017_p1);

assign select_ln829_4_fu_1377_p3 = ((and_ln828_2_reg_1816_pp0_iter4_reg[0:0] == 1'b1) ? zext_ln828_6_fu_1174_p1 : select_ln828_3_fu_1370_p3);

assign select_ln829_5_fu_740_p3 = ((or_ln828_fu_729_p2[0:0] == 1'b1) ? 13'd1 : add_ln829_1_fu_734_p2);

assign select_ln829_fu_971_p3 = ((or_ln829_1_reg_1831[0:0] == 1'b1) ? 7'd0 : v470_fu_166);

assign select_ln830_1_fu_1476_p3 = ((and_ln829_1_reg_1901_pp0_iter5_reg[0:0] == 1'b1) ? empty_183_fu_1470_p2 : select_ln829_2_fu_1452_p3);

assign select_ln830_2_cast_fu_1486_p1 = select_ln830_1_reg_1971;

assign select_ln830_2_fu_1005_p3 = ((and_ln829_1_fu_983_p2[0:0] == 1'b1) ? add_ln830_fu_989_p2 : select_ln829_fu_971_p3);

assign select_ln830_3_fu_1028_p3 = ((and_ln829_1_fu_983_p2[0:0] == 1'b1) ? empty_184_fu_1013_p1 : select_ln829_3_fu_1021_p3);

assign select_ln830_4_fu_1384_p3 = ((and_ln829_1_reg_1901[0:0] == 1'b1) ? zext_ln828_6_fu_1174_p1 : select_ln829_4_fu_1377_p3);

assign select_ln830_5_fu_799_p3 = ((or_ln829_1_fu_788_p2[0:0] == 1'b1) ? 12'd1 : add_ln830_1_fu_793_p2);

assign select_ln830_fu_1244_p3 = ((or_ln830_1_reg_1913[0:0] == 1'b1) ? 3'd0 : v471_fu_158);

assign select_ln831_1_fu_1349_p3 = ((and_ln830_fu_1314_p2[0:0] == 1'b1) ? add_ln831_fu_1320_p2 : select_ln830_fu_1244_p3);

assign select_ln831_2_fu_1391_p3 = ((and_ln830_fu_1314_p2[0:0] == 1'b1) ? p_mid12712_fu_1357_p2 : select_ln830_4_fu_1384_p3);

assign select_ln831_3_fu_1042_p3 = ((or_ln830_1_fu_1000_p2[0:0] == 1'b1) ? 6'd1 : add_ln831_1_fu_1036_p2);

assign select_ln831_fu_1341_p3 = ((or_ln831_2_fu_1336_p2[0:0] == 1'b1) ? 3'd0 : v472_fu_154);

assign tmp_14_fu_1190_p3 = {{empty_172_fu_1180_p2}, {2'd0}};

assign tmp_15_fu_1429_p3 = {{empty_174_reg_1939}, {2'd0}};

assign tmp_16_fu_1116_p3 = {{add_ln827_reg_1852}, {3'd0}};

assign tmp_17_fu_948_p3 = {{select_ln827_1_fu_899_p3}, {2'd0}};

assign tmp_18_fu_1251_p3 = {{add_ln830_reg_1908}, {9'd0}};

assign tmp_19_fu_1272_p3 = {{empty_177_fu_1262_p2}, {2'd0}};

assign tmp_20_fu_1607_p4 = {{{select_ln830_3_reg_1918_pp0_iter10_reg}, {select_ln831_1_reg_1961_pp0_iter10_reg}}, {select_ln831_reg_1955_pp0_iter10_reg}};

assign tmp_21_fu_1502_p4 = {{{p_cast99_mid2_v_reg_1863_pp0_iter6_reg}, {select_ln831_2_reg_1966_pp0_iter6_reg}}, {add_ln834_fu_1497_p2}};

assign tmp_290_cast_fu_837_p1 = tmp_s_fu_829_p3;

assign tmp_294_cast_fu_1123_p1 = tmp_16_fu_1116_p3;

assign tmp_295_cast_fu_956_p1 = tmp_17_fu_948_p3;

assign tmp_298_cast_fu_1258_p1 = tmp_18_fu_1251_p3;

assign tmp_fu_851_p3 = {{empty_fu_841_p2}, {2'd0}};

assign tmp_s_fu_829_p3 = {{v470_fu_166}, {9'd0}};

assign trunc_ln827_fu_920_p1 = select_ln827_1_fu_899_p3[2:0];

assign v13_0_Addr_A = v13_0_Addr_A_orig << 32'd2;

assign v13_0_Addr_A_orig = zext_ln834_fu_1510_p1;

assign v13_0_Din_A = 32'd0;

assign v13_0_WEN_A = 4'd0;

assign v13_1_Addr_A = v13_1_Addr_A_orig << 32'd2;

assign v13_1_Addr_A_orig = zext_ln834_fu_1510_p1;

assign v13_1_Din_A = 32'd0;

assign v13_1_WEN_A = 4'd0;

assign v13_2_Addr_A = v13_2_Addr_A_orig << 32'd2;

assign v13_2_Addr_A_orig = zext_ln834_fu_1510_p1;

assign v13_2_Din_A = 32'd0;

assign v13_2_WEN_A = 4'd0;

assign v13_3_Addr_A = v13_3_Addr_A_orig << 32'd2;

assign v13_3_Addr_A_orig = zext_ln834_fu_1510_p1;

assign v13_3_Din_A = 32'd0;

assign v13_3_WEN_A = 4'd0;

assign v13_4_Addr_A = v13_4_Addr_A_orig << 32'd2;

assign v13_4_Addr_A_orig = zext_ln834_fu_1510_p1;

assign v13_4_Din_A = 32'd0;

assign v13_4_WEN_A = 4'd0;

assign v13_5_Addr_A = v13_5_Addr_A_orig << 32'd2;

assign v13_5_Addr_A_orig = zext_ln834_fu_1510_p1;

assign v13_5_Din_A = 32'd0;

assign v13_5_WEN_A = 4'd0;

assign v13_6_Addr_A = v13_6_Addr_A_orig << 32'd2;

assign v13_6_Addr_A_orig = zext_ln834_fu_1510_p1;

assign v13_6_Din_A = 32'd0;

assign v13_6_WEN_A = 4'd0;

assign v13_7_Addr_A = v13_7_Addr_A_orig << 32'd2;

assign v13_7_Addr_A_orig = zext_ln834_fu_1510_p1;

assign v13_7_Din_A = 32'd0;

assign v13_7_WEN_A = 4'd0;

assign v14_0_Addr_A = v14_0_Addr_A_orig << 32'd2;

assign v14_0_Addr_A_orig = v14_0_addr_reg_2148_pp0_iter19_reg;

assign v14_0_Addr_B = v14_0_Addr_B_orig << 32'd2;

assign v14_0_Addr_B_orig = zext_ln837_fu_1614_p1;

assign v14_0_Din_A = v477_reg_2316;

assign v14_0_Din_B = 32'd0;

assign v14_0_WEN_B = 4'd0;

assign v14_1_Addr_A = v14_1_Addr_A_orig << 32'd2;

assign v14_1_Addr_A_orig = v14_1_addr_reg_2154_pp0_iter19_reg;

assign v14_1_Addr_B = v14_1_Addr_B_orig << 32'd2;

assign v14_1_Addr_B_orig = zext_ln837_fu_1614_p1;

assign v14_1_Din_A = v481_reg_2321;

assign v14_1_Din_B = 32'd0;

assign v14_1_WEN_B = 4'd0;

assign v14_2_Addr_A = v14_2_Addr_A_orig << 32'd2;

assign v14_2_Addr_A_orig = v14_2_addr_reg_2160_pp0_iter19_reg;

assign v14_2_Addr_B = v14_2_Addr_B_orig << 32'd2;

assign v14_2_Addr_B_orig = zext_ln837_fu_1614_p1;

assign v14_2_Din_A = v485_reg_2326;

assign v14_2_Din_B = 32'd0;

assign v14_2_WEN_B = 4'd0;

assign v14_3_Addr_A = v14_3_Addr_A_orig << 32'd2;

assign v14_3_Addr_A_orig = v14_3_addr_reg_2166_pp0_iter19_reg;

assign v14_3_Addr_B = v14_3_Addr_B_orig << 32'd2;

assign v14_3_Addr_B_orig = zext_ln837_fu_1614_p1;

assign v14_3_Din_A = v489_reg_2331;

assign v14_3_Din_B = 32'd0;

assign v14_3_WEN_B = 4'd0;

assign v14_4_Addr_A = v14_4_Addr_A_orig << 32'd2;

assign v14_4_Addr_A_orig = v14_4_addr_reg_2172_pp0_iter19_reg;

assign v14_4_Addr_B = v14_4_Addr_B_orig << 32'd2;

assign v14_4_Addr_B_orig = zext_ln837_fu_1614_p1;

assign v14_4_Din_A = v493_reg_2336;

assign v14_4_Din_B = 32'd0;

assign v14_4_WEN_B = 4'd0;

assign v14_5_Addr_A = v14_5_Addr_A_orig << 32'd2;

assign v14_5_Addr_A_orig = v14_5_addr_reg_2178_pp0_iter19_reg;

assign v14_5_Addr_B = v14_5_Addr_B_orig << 32'd2;

assign v14_5_Addr_B_orig = zext_ln837_fu_1614_p1;

assign v14_5_Din_A = v497_reg_2341;

assign v14_5_Din_B = 32'd0;

assign v14_5_WEN_B = 4'd0;

assign v14_6_Addr_A = v14_6_Addr_A_orig << 32'd2;

assign v14_6_Addr_A_orig = v14_6_addr_reg_2184_pp0_iter19_reg;

assign v14_6_Addr_B = v14_6_Addr_B_orig << 32'd2;

assign v14_6_Addr_B_orig = zext_ln837_fu_1614_p1;

assign v14_6_Din_A = v501_reg_2346;

assign v14_6_Din_B = 32'd0;

assign v14_6_WEN_B = 4'd0;

assign v14_7_Addr_A = v14_7_Addr_A_orig << 32'd2;

assign v14_7_Addr_A_orig = v14_7_addr_reg_2190_pp0_iter19_reg;

assign v14_7_Addr_B = v14_7_Addr_B_orig << 32'd2;

assign v14_7_Addr_B_orig = zext_ln837_fu_1614_p1;

assign v14_7_Din_A = v505_reg_2351;

assign v14_7_Din_B = 32'd0;

assign v14_7_WEN_B = 4'd0;

assign v473_fu_1554_p1 = v13_0_Dout_A;

assign v473_fu_1554_p2 = v13_1_Dout_A;

assign v473_fu_1554_p3 = v13_2_Dout_A;

assign v473_fu_1554_p4 = v13_3_Dout_A;

assign v473_fu_1554_p5 = v13_4_Dout_A;

assign v473_fu_1554_p6 = v13_5_Dout_A;

assign v473_fu_1554_p7 = v13_6_Dout_A;

assign v473_fu_1554_p8 = v13_7_Dout_A;

assign v476_fu_1626_p1 = v14_0_load_reg_2201;

assign v480_fu_1630_p1 = v14_1_load_reg_2211;

assign v484_fu_1634_p1 = v14_2_load_reg_2221;

assign v488_fu_1638_p1 = v14_3_load_reg_2231;

assign v492_fu_1642_p1 = v14_4_load_reg_2241;

assign v496_fu_1646_p1 = v14_5_load_reg_2251;

assign v500_fu_1650_p1 = v14_6_load_reg_2261;

assign v504_fu_1654_p1 = v14_7_load_reg_2271;

assign v8_0_Addr_A = v8_0_Addr_A_orig << 32'd2;

assign v8_0_Addr_A_orig = select_ln830_2_cast_fu_1486_p1;

assign v8_0_Din_A = 32'd0;

assign v8_0_WEN_A = 4'd0;

assign v8_1_Addr_A = v8_1_Addr_A_orig << 32'd2;

assign v8_1_Addr_A_orig = select_ln830_2_cast_fu_1486_p1;

assign v8_1_Din_A = 32'd0;

assign v8_1_WEN_A = 4'd0;

assign v8_2_Addr_A = v8_2_Addr_A_orig << 32'd2;

assign v8_2_Addr_A_orig = select_ln830_2_cast_fu_1486_p1;

assign v8_2_Din_A = 32'd0;

assign v8_2_WEN_A = 4'd0;

assign v8_3_Addr_A = v8_3_Addr_A_orig << 32'd2;

assign v8_3_Addr_A_orig = select_ln830_2_cast_fu_1486_p1;

assign v8_3_Din_A = 32'd0;

assign v8_3_WEN_A = 4'd0;

assign v8_4_Addr_A = v8_4_Addr_A_orig << 32'd2;

assign v8_4_Addr_A_orig = select_ln830_2_cast_fu_1486_p1;

assign v8_4_Din_A = 32'd0;

assign v8_4_WEN_A = 4'd0;

assign v8_5_Addr_A = v8_5_Addr_A_orig << 32'd2;

assign v8_5_Addr_A_orig = select_ln830_2_cast_fu_1486_p1;

assign v8_5_Din_A = 32'd0;

assign v8_5_WEN_A = 4'd0;

assign v8_6_Addr_A = v8_6_Addr_A_orig << 32'd2;

assign v8_6_Addr_A_orig = select_ln830_2_cast_fu_1486_p1;

assign v8_6_Din_A = 32'd0;

assign v8_6_WEN_A = 4'd0;

assign v8_7_Addr_A = v8_7_Addr_A_orig << 32'd2;

assign v8_7_Addr_A_orig = select_ln830_2_cast_fu_1486_p1;

assign v8_7_Din_A = 32'd0;

assign v8_7_WEN_A = 4'd0;

assign xor_ln827_fu_712_p2 = (icmp_ln828_reg_1771 ^ 1'd1);

assign xor_ln828_fu_767_p2 = (icmp_ln829_reg_1791 ^ 1'd1);

assign xor_ln829_fu_978_p2 = (1'd1 ^ and_ln828_2_reg_1816);

assign xor_ln830_fu_1304_p2 = (1'd1 ^ and_ln828_1_reg_1891);

assign zext_ln827_1_fu_1110_p1 = add_ln827_reg_1852;

assign zext_ln827_2_fu_1113_p1 = select_ln827_1_reg_1858;

assign zext_ln827_3_fu_906_p1 = select_ln827_1_fu_899_p3;

assign zext_ln827_fu_821_p1 = v467_fu_190;

assign zext_ln828_1_fu_1076_p1 = v468_1_reg_1837;

assign zext_ln828_2_fu_1162_p1 = add_ln828_reg_1873;

assign zext_ln828_3_fu_1165_p1 = add_ln828_reg_1873;

assign zext_ln828_4_fu_1168_p1 = select_ln828_1_reg_1879;

assign zext_ln828_5_fu_1171_p1 = select_ln828_1_reg_1879;

assign zext_ln828_6_fu_1174_p1 = select_ln828_1_reg_1879;

assign zext_ln828_fu_825_p1 = v468_fu_182;

assign zext_ln829_1_fu_1420_p1 = add_ln829_reg_1928;

assign zext_ln829_2_fu_1423_p1 = select_ln829_1_reg_1933;

assign zext_ln829_fu_1079_p1 = v469_fu_174;

assign zext_ln830_fu_1133_p1 = empty_170_fu_1127_p2;

assign zext_ln834_fu_1510_p1 = tmp_21_fu_1502_p4;

assign zext_ln837_fu_1614_p1 = tmp_20_fu_1607_p4;

endmodule //test_vgg16_test_vgg16_Pipeline_VITIS_LOOP_827_121_VITIS_LOOP_829_123_VITIS_LOOP_831_125_VIT
