// ==============================================================
// RTL generated by Vitis HLS - High-Level Synthesis from C, C++ and OpenCL v2022.2 (64-bit)
// Version: 2022.2
// Copyright (C) Copyright 1986-2022 Xilinx, Inc. All Rights Reserved.
// 
// ===========================================================

`timescale 1 ns / 1 ps 

module test_vgg16_test_vgg16_Pipeline_VITIS_LOOP_170_4_VITIS_LOOP_172_6_VITIS_LOOP_174_8_VITIS_LOO (
        ap_clk,
        ap_rst,
        ap_start,
        ap_done,
        ap_idle,
        ap_ready,
        v1_0_Addr_A,
        v1_0_EN_A,
        v1_0_WEN_A,
        v1_0_Din_A,
        v1_0_Dout_A,
        v1_1_Addr_A,
        v1_1_EN_A,
        v1_1_WEN_A,
        v1_1_Din_A,
        v1_1_Dout_A,
        v1_2_Addr_A,
        v1_2_EN_A,
        v1_2_WEN_A,
        v1_2_Din_A,
        v1_2_Dout_A,
        v1_3_Addr_A,
        v1_3_EN_A,
        v1_3_WEN_A,
        v1_3_Din_A,
        v1_3_Dout_A,
        v1_4_Addr_A,
        v1_4_EN_A,
        v1_4_WEN_A,
        v1_4_Din_A,
        v1_4_Dout_A,
        v1_5_Addr_A,
        v1_5_EN_A,
        v1_5_WEN_A,
        v1_5_Din_A,
        v1_5_Dout_A,
        v1_6_Addr_A,
        v1_6_EN_A,
        v1_6_WEN_A,
        v1_6_Din_A,
        v1_6_Dout_A,
        v1_7_Addr_A,
        v1_7_EN_A,
        v1_7_WEN_A,
        v1_7_Din_A,
        v1_7_Dout_A,
        v10_0_Addr_A,
        v10_0_EN_A,
        v10_0_WEN_A,
        v10_0_Din_A,
        v10_0_Dout_A,
        v10_0_Addr_B,
        v10_0_EN_B,
        v10_0_WEN_B,
        v10_0_Din_B,
        v10_0_Dout_B,
        v10_1_Addr_A,
        v10_1_EN_A,
        v10_1_WEN_A,
        v10_1_Din_A,
        v10_1_Dout_A,
        v10_1_Addr_B,
        v10_1_EN_B,
        v10_1_WEN_B,
        v10_1_Din_B,
        v10_1_Dout_B,
        v10_2_Addr_A,
        v10_2_EN_A,
        v10_2_WEN_A,
        v10_2_Din_A,
        v10_2_Dout_A,
        v10_2_Addr_B,
        v10_2_EN_B,
        v10_2_WEN_B,
        v10_2_Din_B,
        v10_2_Dout_B,
        v10_3_Addr_A,
        v10_3_EN_A,
        v10_3_WEN_A,
        v10_3_Din_A,
        v10_3_Dout_A,
        v10_3_Addr_B,
        v10_3_EN_B,
        v10_3_WEN_B,
        v10_3_Din_B,
        v10_3_Dout_B,
        v10_4_Addr_A,
        v10_4_EN_A,
        v10_4_WEN_A,
        v10_4_Din_A,
        v10_4_Dout_A,
        v10_4_Addr_B,
        v10_4_EN_B,
        v10_4_WEN_B,
        v10_4_Din_B,
        v10_4_Dout_B,
        v10_5_Addr_A,
        v10_5_EN_A,
        v10_5_WEN_A,
        v10_5_Din_A,
        v10_5_Dout_A,
        v10_5_Addr_B,
        v10_5_EN_B,
        v10_5_WEN_B,
        v10_5_Din_B,
        v10_5_Dout_B,
        v10_6_Addr_A,
        v10_6_EN_A,
        v10_6_WEN_A,
        v10_6_Din_A,
        v10_6_Dout_A,
        v10_6_Addr_B,
        v10_6_EN_B,
        v10_6_WEN_B,
        v10_6_Din_B,
        v10_6_Dout_B,
        v10_7_Addr_A,
        v10_7_EN_A,
        v10_7_WEN_A,
        v10_7_Din_A,
        v10_7_Dout_A,
        v10_7_Addr_B,
        v10_7_EN_B,
        v10_7_WEN_B,
        v10_7_Din_B,
        v10_7_Dout_B,
        v28_Addr_A,
        v28_EN_A,
        v28_WEN_A,
        v28_Din_A,
        v28_Dout_A,
        grp_fu_12576_p_din0,
        grp_fu_12576_p_din1,
        grp_fu_12576_p_opcode,
        grp_fu_12576_p_dout0,
        grp_fu_12576_p_ce,
        grp_fu_12580_p_din0,
        grp_fu_12580_p_din1,
        grp_fu_12580_p_opcode,
        grp_fu_12580_p_dout0,
        grp_fu_12580_p_ce,
        grp_fu_12584_p_din0,
        grp_fu_12584_p_din1,
        grp_fu_12584_p_opcode,
        grp_fu_12584_p_dout0,
        grp_fu_12584_p_ce,
        grp_fu_12588_p_din0,
        grp_fu_12588_p_din1,
        grp_fu_12588_p_opcode,
        grp_fu_12588_p_dout0,
        grp_fu_12588_p_ce,
        grp_fu_12592_p_din0,
        grp_fu_12592_p_din1,
        grp_fu_12592_p_opcode,
        grp_fu_12592_p_dout0,
        grp_fu_12592_p_ce,
        grp_fu_12596_p_din0,
        grp_fu_12596_p_din1,
        grp_fu_12596_p_opcode,
        grp_fu_12596_p_dout0,
        grp_fu_12596_p_ce,
        grp_fu_12600_p_din0,
        grp_fu_12600_p_din1,
        grp_fu_12600_p_opcode,
        grp_fu_12600_p_dout0,
        grp_fu_12600_p_ce,
        grp_fu_12604_p_din0,
        grp_fu_12604_p_din1,
        grp_fu_12604_p_opcode,
        grp_fu_12604_p_dout0,
        grp_fu_12604_p_ce,
        grp_fu_12608_p_din0,
        grp_fu_12608_p_din1,
        grp_fu_12608_p_dout0,
        grp_fu_12608_p_ce,
        grp_fu_12612_p_din0,
        grp_fu_12612_p_din1,
        grp_fu_12612_p_dout0,
        grp_fu_12612_p_ce,
        grp_fu_12616_p_din0,
        grp_fu_12616_p_din1,
        grp_fu_12616_p_dout0,
        grp_fu_12616_p_ce,
        grp_fu_12620_p_din0,
        grp_fu_12620_p_din1,
        grp_fu_12620_p_dout0,
        grp_fu_12620_p_ce,
        grp_fu_12624_p_din0,
        grp_fu_12624_p_din1,
        grp_fu_12624_p_dout0,
        grp_fu_12624_p_ce,
        grp_fu_12628_p_din0,
        grp_fu_12628_p_din1,
        grp_fu_12628_p_dout0,
        grp_fu_12628_p_ce,
        grp_fu_12632_p_din0,
        grp_fu_12632_p_din1,
        grp_fu_12632_p_dout0,
        grp_fu_12632_p_ce,
        grp_fu_12636_p_din0,
        grp_fu_12636_p_din1,
        grp_fu_12636_p_dout0,
        grp_fu_12636_p_ce
);

parameter    ap_ST_fsm_pp0_stage0 = 1'd1;

input   ap_clk;
input   ap_rst;
input   ap_start;
output   ap_done;
output   ap_idle;
output   ap_ready;
output  [31:0] v1_0_Addr_A;
output   v1_0_EN_A;
output  [3:0] v1_0_WEN_A;
output  [31:0] v1_0_Din_A;
input  [31:0] v1_0_Dout_A;
output  [31:0] v1_1_Addr_A;
output   v1_1_EN_A;
output  [3:0] v1_1_WEN_A;
output  [31:0] v1_1_Din_A;
input  [31:0] v1_1_Dout_A;
output  [31:0] v1_2_Addr_A;
output   v1_2_EN_A;
output  [3:0] v1_2_WEN_A;
output  [31:0] v1_2_Din_A;
input  [31:0] v1_2_Dout_A;
output  [31:0] v1_3_Addr_A;
output   v1_3_EN_A;
output  [3:0] v1_3_WEN_A;
output  [31:0] v1_3_Din_A;
input  [31:0] v1_3_Dout_A;
output  [31:0] v1_4_Addr_A;
output   v1_4_EN_A;
output  [3:0] v1_4_WEN_A;
output  [31:0] v1_4_Din_A;
input  [31:0] v1_4_Dout_A;
output  [31:0] v1_5_Addr_A;
output   v1_5_EN_A;
output  [3:0] v1_5_WEN_A;
output  [31:0] v1_5_Din_A;
input  [31:0] v1_5_Dout_A;
output  [31:0] v1_6_Addr_A;
output   v1_6_EN_A;
output  [3:0] v1_6_WEN_A;
output  [31:0] v1_6_Din_A;
input  [31:0] v1_6_Dout_A;
output  [31:0] v1_7_Addr_A;
output   v1_7_EN_A;
output  [3:0] v1_7_WEN_A;
output  [31:0] v1_7_Din_A;
input  [31:0] v1_7_Dout_A;
output  [31:0] v10_0_Addr_A;
output   v10_0_EN_A;
output  [3:0] v10_0_WEN_A;
output  [31:0] v10_0_Din_A;
input  [31:0] v10_0_Dout_A;
output  [31:0] v10_0_Addr_B;
output   v10_0_EN_B;
output  [3:0] v10_0_WEN_B;
output  [31:0] v10_0_Din_B;
input  [31:0] v10_0_Dout_B;
output  [31:0] v10_1_Addr_A;
output   v10_1_EN_A;
output  [3:0] v10_1_WEN_A;
output  [31:0] v10_1_Din_A;
input  [31:0] v10_1_Dout_A;
output  [31:0] v10_1_Addr_B;
output   v10_1_EN_B;
output  [3:0] v10_1_WEN_B;
output  [31:0] v10_1_Din_B;
input  [31:0] v10_1_Dout_B;
output  [31:0] v10_2_Addr_A;
output   v10_2_EN_A;
output  [3:0] v10_2_WEN_A;
output  [31:0] v10_2_Din_A;
input  [31:0] v10_2_Dout_A;
output  [31:0] v10_2_Addr_B;
output   v10_2_EN_B;
output  [3:0] v10_2_WEN_B;
output  [31:0] v10_2_Din_B;
input  [31:0] v10_2_Dout_B;
output  [31:0] v10_3_Addr_A;
output   v10_3_EN_A;
output  [3:0] v10_3_WEN_A;
output  [31:0] v10_3_Din_A;
input  [31:0] v10_3_Dout_A;
output  [31:0] v10_3_Addr_B;
output   v10_3_EN_B;
output  [3:0] v10_3_WEN_B;
output  [31:0] v10_3_Din_B;
input  [31:0] v10_3_Dout_B;
output  [31:0] v10_4_Addr_A;
output   v10_4_EN_A;
output  [3:0] v10_4_WEN_A;
output  [31:0] v10_4_Din_A;
input  [31:0] v10_4_Dout_A;
output  [31:0] v10_4_Addr_B;
output   v10_4_EN_B;
output  [3:0] v10_4_WEN_B;
output  [31:0] v10_4_Din_B;
input  [31:0] v10_4_Dout_B;
output  [31:0] v10_5_Addr_A;
output   v10_5_EN_A;
output  [3:0] v10_5_WEN_A;
output  [31:0] v10_5_Din_A;
input  [31:0] v10_5_Dout_A;
output  [31:0] v10_5_Addr_B;
output   v10_5_EN_B;
output  [3:0] v10_5_WEN_B;
output  [31:0] v10_5_Din_B;
input  [31:0] v10_5_Dout_B;
output  [31:0] v10_6_Addr_A;
output   v10_6_EN_A;
output  [3:0] v10_6_WEN_A;
output  [31:0] v10_6_Din_A;
input  [31:0] v10_6_Dout_A;
output  [31:0] v10_6_Addr_B;
output   v10_6_EN_B;
output  [3:0] v10_6_WEN_B;
output  [31:0] v10_6_Din_B;
input  [31:0] v10_6_Dout_B;
output  [31:0] v10_7_Addr_A;
output   v10_7_EN_A;
output  [3:0] v10_7_WEN_A;
output  [31:0] v10_7_Din_A;
input  [31:0] v10_7_Dout_A;
output  [31:0] v10_7_Addr_B;
output   v10_7_EN_B;
output  [3:0] v10_7_WEN_B;
output  [31:0] v10_7_Din_B;
input  [31:0] v10_7_Dout_B;
output  [31:0] v28_Addr_A;
output   v28_EN_A;
output  [3:0] v28_WEN_A;
output  [31:0] v28_Din_A;
input  [31:0] v28_Dout_A;
output  [31:0] grp_fu_12576_p_din0;
output  [31:0] grp_fu_12576_p_din1;
output  [1:0] grp_fu_12576_p_opcode;
input  [31:0] grp_fu_12576_p_dout0;
output   grp_fu_12576_p_ce;
output  [31:0] grp_fu_12580_p_din0;
output  [31:0] grp_fu_12580_p_din1;
output  [1:0] grp_fu_12580_p_opcode;
input  [31:0] grp_fu_12580_p_dout0;
output   grp_fu_12580_p_ce;
output  [31:0] grp_fu_12584_p_din0;
output  [31:0] grp_fu_12584_p_din1;
output  [1:0] grp_fu_12584_p_opcode;
input  [31:0] grp_fu_12584_p_dout0;
output   grp_fu_12584_p_ce;
output  [31:0] grp_fu_12588_p_din0;
output  [31:0] grp_fu_12588_p_din1;
output  [1:0] grp_fu_12588_p_opcode;
input  [31:0] grp_fu_12588_p_dout0;
output   grp_fu_12588_p_ce;
output  [31:0] grp_fu_12592_p_din0;
output  [31:0] grp_fu_12592_p_din1;
output  [1:0] grp_fu_12592_p_opcode;
input  [31:0] grp_fu_12592_p_dout0;
output   grp_fu_12592_p_ce;
output  [31:0] grp_fu_12596_p_din0;
output  [31:0] grp_fu_12596_p_din1;
output  [1:0] grp_fu_12596_p_opcode;
input  [31:0] grp_fu_12596_p_dout0;
output   grp_fu_12596_p_ce;
output  [31:0] grp_fu_12600_p_din0;
output  [31:0] grp_fu_12600_p_din1;
output  [1:0] grp_fu_12600_p_opcode;
input  [31:0] grp_fu_12600_p_dout0;
output   grp_fu_12600_p_ce;
output  [31:0] grp_fu_12604_p_din0;
output  [31:0] grp_fu_12604_p_din1;
output  [1:0] grp_fu_12604_p_opcode;
input  [31:0] grp_fu_12604_p_dout0;
output   grp_fu_12604_p_ce;
output  [31:0] grp_fu_12608_p_din0;
output  [31:0] grp_fu_12608_p_din1;
input  [31:0] grp_fu_12608_p_dout0;
output   grp_fu_12608_p_ce;
output  [31:0] grp_fu_12612_p_din0;
output  [31:0] grp_fu_12612_p_din1;
input  [31:0] grp_fu_12612_p_dout0;
output   grp_fu_12612_p_ce;
output  [31:0] grp_fu_12616_p_din0;
output  [31:0] grp_fu_12616_p_din1;
input  [31:0] grp_fu_12616_p_dout0;
output   grp_fu_12616_p_ce;
output  [31:0] grp_fu_12620_p_din0;
output  [31:0] grp_fu_12620_p_din1;
input  [31:0] grp_fu_12620_p_dout0;
output   grp_fu_12620_p_ce;
output  [31:0] grp_fu_12624_p_din0;
output  [31:0] grp_fu_12624_p_din1;
input  [31:0] grp_fu_12624_p_dout0;
output   grp_fu_12624_p_ce;
output  [31:0] grp_fu_12628_p_din0;
output  [31:0] grp_fu_12628_p_din1;
input  [31:0] grp_fu_12628_p_dout0;
output   grp_fu_12628_p_ce;
output  [31:0] grp_fu_12632_p_din0;
output  [31:0] grp_fu_12632_p_din1;
input  [31:0] grp_fu_12632_p_dout0;
output   grp_fu_12632_p_ce;
output  [31:0] grp_fu_12636_p_din0;
output  [31:0] grp_fu_12636_p_din1;
input  [31:0] grp_fu_12636_p_dout0;
output   grp_fu_12636_p_ce;

reg ap_idle;
reg v1_0_EN_A;
reg v1_1_EN_A;
reg v1_2_EN_A;
reg v1_3_EN_A;
reg v1_4_EN_A;
reg v1_5_EN_A;
reg v1_6_EN_A;
reg v1_7_EN_A;
reg v10_0_EN_A;
reg[3:0] v10_0_WEN_A;
reg v10_0_EN_B;
reg v10_1_EN_A;
reg[3:0] v10_1_WEN_A;
reg v10_1_EN_B;
reg v10_2_EN_A;
reg[3:0] v10_2_WEN_A;
reg v10_2_EN_B;
reg v10_3_EN_A;
reg[3:0] v10_3_WEN_A;
reg v10_3_EN_B;
reg v10_4_EN_A;
reg[3:0] v10_4_WEN_A;
reg v10_4_EN_B;
reg v10_5_EN_A;
reg[3:0] v10_5_WEN_A;
reg v10_5_EN_B;
reg v10_6_EN_A;
reg[3:0] v10_6_WEN_A;
reg v10_6_EN_B;
reg v10_7_EN_A;
reg[3:0] v10_7_WEN_A;
reg v10_7_EN_B;
reg v28_EN_A;

(* fsm_encoding = "none" *) reg   [0:0] ap_CS_fsm;
wire    ap_CS_fsm_pp0_stage0;
wire    ap_enable_reg_pp0_iter0;
reg    ap_enable_reg_pp0_iter1;
reg    ap_enable_reg_pp0_iter2;
reg    ap_enable_reg_pp0_iter3;
reg    ap_enable_reg_pp0_iter4;
reg    ap_enable_reg_pp0_iter5;
reg    ap_enable_reg_pp0_iter6;
reg    ap_enable_reg_pp0_iter7;
reg    ap_enable_reg_pp0_iter8;
reg    ap_enable_reg_pp0_iter9;
reg    ap_enable_reg_pp0_iter10;
reg    ap_enable_reg_pp0_iter11;
reg    ap_enable_reg_pp0_iter12;
reg    ap_enable_reg_pp0_iter13;
reg    ap_enable_reg_pp0_iter14;
reg    ap_enable_reg_pp0_iter15;
reg    ap_enable_reg_pp0_iter16;
reg    ap_enable_reg_pp0_iter17;
reg    ap_enable_reg_pp0_iter18;
reg    ap_enable_reg_pp0_iter19;
reg    ap_idle_pp0;
wire    ap_block_state1_pp0_stage0_iter0;
wire    ap_block_state2_pp0_stage0_iter1;
wire    ap_block_state3_pp0_stage0_iter2;
wire    ap_block_state4_pp0_stage0_iter3;
wire    ap_block_state5_pp0_stage0_iter4;
wire    ap_block_state6_pp0_stage0_iter5;
wire    ap_block_state7_pp0_stage0_iter6;
wire    ap_block_state8_pp0_stage0_iter7;
wire    ap_block_state9_pp0_stage0_iter8;
wire    ap_block_state10_pp0_stage0_iter9;
wire    ap_block_state11_pp0_stage0_iter10;
wire    ap_block_state12_pp0_stage0_iter11;
wire    ap_block_state13_pp0_stage0_iter12;
wire    ap_block_state14_pp0_stage0_iter13;
wire    ap_block_state15_pp0_stage0_iter14;
wire    ap_block_state16_pp0_stage0_iter15;
wire    ap_block_state17_pp0_stage0_iter16;
wire    ap_block_state18_pp0_stage0_iter17;
wire    ap_block_state19_pp0_stage0_iter18;
wire    ap_block_state20_pp0_stage0_iter19;
wire    ap_block_pp0_stage0_subdone;
wire   [0:0] icmp_ln170_fu_557_p2;
reg    ap_condition_exit_pp0_iter1_stage0;
wire    ap_loop_exit_ready;
reg    ap_ready_int;
wire    ap_block_pp0_stage0_11001;
reg   [0:0] icmp_ln170_reg_1663;
reg   [0:0] icmp_ln170_reg_1663_pp0_iter2_reg;
reg   [0:0] icmp_ln170_reg_1663_pp0_iter3_reg;
reg   [0:0] icmp_ln170_reg_1663_pp0_iter4_reg;
wire   [0:0] icmp_ln171_fu_572_p2;
reg   [0:0] icmp_ln171_reg_1667;
reg   [0:0] icmp_ln171_reg_1667_pp0_iter2_reg;
reg   [0:0] icmp_ln171_reg_1667_pp0_iter3_reg;
reg   [0:0] icmp_ln171_reg_1667_pp0_iter4_reg;
reg   [0:0] icmp_ln171_reg_1667_pp0_iter5_reg;
wire   [0:0] xor_ln170_fu_605_p2;
reg   [0:0] xor_ln170_reg_1680;
reg   [0:0] xor_ln170_reg_1680_pp0_iter3_reg;
reg   [0:0] xor_ln170_reg_1680_pp0_iter4_reg;
wire   [0:0] icmp_ln172_fu_610_p2;
reg   [0:0] icmp_ln172_reg_1687;
wire   [0:0] and_ln170_3_fu_616_p2;
reg   [0:0] and_ln170_3_reg_1692;
reg   [0:0] and_ln170_3_reg_1692_pp0_iter3_reg;
reg   [0:0] and_ln170_3_reg_1692_pp0_iter4_reg;
reg   [0:0] and_ln170_3_reg_1692_pp0_iter5_reg;
wire   [0:0] or_ln171_fu_622_p2;
reg   [0:0] or_ln171_reg_1700;
reg   [0:0] or_ln171_reg_1700_pp0_iter3_reg;
reg   [0:0] or_ln171_reg_1700_pp0_iter4_reg;
wire   [0:0] or_ln171_1_fu_665_p2;
reg   [0:0] or_ln171_1_reg_1706;
reg   [0:0] or_ln171_1_reg_1706_pp0_iter4_reg;
wire   [0:0] and_ln171_2_fu_670_p2;
reg   [0:0] and_ln171_2_reg_1712;
reg   [0:0] and_ln171_2_reg_1712_pp0_iter4_reg;
reg   [0:0] and_ln171_2_reg_1712_pp0_iter5_reg;
wire   [0:0] or_ln172_fu_676_p2;
reg   [0:0] or_ln172_reg_1722;
reg   [0:0] or_ln172_reg_1722_pp0_iter4_reg;
wire   [0:0] or_ln172_1_fu_681_p2;
reg   [0:0] or_ln172_1_reg_1727;
reg   [1:0] v33_1_reg_1732;
wire  signed [7:0] empty_364_fu_744_p2;
reg  signed [7:0] empty_364_reg_1738;
wire   [1:0] add_ln170_fu_753_p2;
reg   [1:0] add_ln170_reg_1744;
reg   [1:0] add_ln170_reg_1744_pp0_iter5_reg;
wire   [1:0] select_ln170_1_fu_766_p3;
reg   [1:0] select_ln170_1_reg_1750;
wire   [1:0] add_ln171_fu_792_p2;
reg   [1:0] add_ln171_reg_1756;
wire   [1:0] select_ln171_1_fu_798_p3;
reg   [1:0] select_ln171_1_reg_1761;
wire   [4:0] empty_373_fu_817_p2;
reg   [4:0] empty_373_reg_1767;
wire   [0:0] and_ln171_1_fu_823_p2;
reg   [0:0] and_ln171_1_reg_1772;
wire   [0:0] xor_ln172_fu_835_p2;
reg   [0:0] xor_ln172_reg_1777;
wire   [0:0] and_ln172_1_fu_840_p2;
reg   [0:0] and_ln172_1_reg_1782;
reg   [0:0] and_ln172_1_reg_1782_pp0_iter5_reg;
wire   [0:0] or_ln173_1_fu_857_p2;
reg   [0:0] or_ln173_1_reg_1789;
wire  signed [7:0] empty_380_fu_888_p2;
reg  signed [7:0] empty_380_reg_1794;
wire   [2:0] trunc_ln180_fu_902_p1;
reg   [2:0] trunc_ln180_reg_1800;
wire   [7:0] empty_370_fu_1004_p2;
reg   [7:0] empty_370_reg_1805;
wire   [7:0] empty_375_fu_1088_p2;
reg   [7:0] empty_375_reg_1810;
wire   [7:0] empty_378_fu_1155_p2;
reg   [7:0] empty_378_reg_1815;
wire   [7:0] empty_386_fu_1228_p2;
reg   [7:0] empty_386_reg_1820;
wire   [5:0] select_ln174_fu_1285_p3;
reg   [5:0] select_ln174_reg_1825;
wire   [7:0] add_ln180_fu_1305_p2;
reg   [7:0] add_ln180_reg_1830;
wire   [7:0] add_ln177_1_fu_1329_p2;
reg   [7:0] add_ln177_1_reg_1835;
wire   [6:0] trunc_ln177_fu_1335_p1;
reg   [6:0] trunc_ln177_reg_1840;
wire   [5:0] add_ln177_fu_1339_p2;
reg   [5:0] add_ln177_reg_1845;
wire   [12:0] add_ln180_1_fu_1448_p2;
reg   [12:0] add_ln180_1_reg_1890;
reg   [12:0] add_ln180_1_reg_1890_pp0_iter7_reg;
reg   [12:0] add_ln180_1_reg_1890_pp0_iter8_reg;
reg   [12:0] add_ln180_1_reg_1890_pp0_iter9_reg;
reg   [31:0] v1_0_load_reg_1900;
reg   [31:0] v1_1_load_reg_1905;
reg   [31:0] v1_2_load_reg_1910;
reg   [31:0] v1_3_load_reg_1915;
reg   [31:0] v1_4_load_reg_1920;
reg   [31:0] v1_5_load_reg_1925;
reg   [31:0] v1_6_load_reg_1930;
reg   [31:0] v1_7_load_reg_1935;
reg   [31:0] v28_load_reg_1940;
wire   [31:0] bitcast_ln173_fu_1468_p1;
wire   [31:0] bitcast_ln173_1_fu_1472_p1;
wire   [31:0] bitcast_ln173_2_fu_1476_p1;
wire   [31:0] bitcast_ln173_3_fu_1480_p1;
wire   [31:0] bitcast_ln173_4_fu_1484_p1;
wire   [31:0] bitcast_ln173_5_fu_1488_p1;
wire   [31:0] bitcast_ln173_6_fu_1492_p1;
wire   [31:0] bitcast_ln173_7_fu_1496_p1;
wire   [31:0] v38_fu_1500_p1;
reg   [12:0] v10_0_addr_reg_1997;
reg   [12:0] v10_0_addr_reg_1997_pp0_iter11_reg;
reg   [12:0] v10_0_addr_reg_1997_pp0_iter12_reg;
reg   [12:0] v10_0_addr_reg_1997_pp0_iter13_reg;
reg   [12:0] v10_0_addr_reg_1997_pp0_iter14_reg;
reg   [12:0] v10_0_addr_reg_1997_pp0_iter15_reg;
reg   [12:0] v10_0_addr_reg_1997_pp0_iter16_reg;
reg   [12:0] v10_0_addr_reg_1997_pp0_iter17_reg;
reg   [12:0] v10_0_addr_reg_1997_pp0_iter18_reg;
reg   [12:0] v10_1_addr_reg_2003;
reg   [12:0] v10_1_addr_reg_2003_pp0_iter11_reg;
reg   [12:0] v10_1_addr_reg_2003_pp0_iter12_reg;
reg   [12:0] v10_1_addr_reg_2003_pp0_iter13_reg;
reg   [12:0] v10_1_addr_reg_2003_pp0_iter14_reg;
reg   [12:0] v10_1_addr_reg_2003_pp0_iter15_reg;
reg   [12:0] v10_1_addr_reg_2003_pp0_iter16_reg;
reg   [12:0] v10_1_addr_reg_2003_pp0_iter17_reg;
reg   [12:0] v10_1_addr_reg_2003_pp0_iter18_reg;
reg   [12:0] v10_2_addr_reg_2009;
reg   [12:0] v10_2_addr_reg_2009_pp0_iter11_reg;
reg   [12:0] v10_2_addr_reg_2009_pp0_iter12_reg;
reg   [12:0] v10_2_addr_reg_2009_pp0_iter13_reg;
reg   [12:0] v10_2_addr_reg_2009_pp0_iter14_reg;
reg   [12:0] v10_2_addr_reg_2009_pp0_iter15_reg;
reg   [12:0] v10_2_addr_reg_2009_pp0_iter16_reg;
reg   [12:0] v10_2_addr_reg_2009_pp0_iter17_reg;
reg   [12:0] v10_2_addr_reg_2009_pp0_iter18_reg;
reg   [12:0] v10_3_addr_reg_2015;
reg   [12:0] v10_3_addr_reg_2015_pp0_iter11_reg;
reg   [12:0] v10_3_addr_reg_2015_pp0_iter12_reg;
reg   [12:0] v10_3_addr_reg_2015_pp0_iter13_reg;
reg   [12:0] v10_3_addr_reg_2015_pp0_iter14_reg;
reg   [12:0] v10_3_addr_reg_2015_pp0_iter15_reg;
reg   [12:0] v10_3_addr_reg_2015_pp0_iter16_reg;
reg   [12:0] v10_3_addr_reg_2015_pp0_iter17_reg;
reg   [12:0] v10_3_addr_reg_2015_pp0_iter18_reg;
reg   [12:0] v10_4_addr_reg_2021;
reg   [12:0] v10_4_addr_reg_2021_pp0_iter11_reg;
reg   [12:0] v10_4_addr_reg_2021_pp0_iter12_reg;
reg   [12:0] v10_4_addr_reg_2021_pp0_iter13_reg;
reg   [12:0] v10_4_addr_reg_2021_pp0_iter14_reg;
reg   [12:0] v10_4_addr_reg_2021_pp0_iter15_reg;
reg   [12:0] v10_4_addr_reg_2021_pp0_iter16_reg;
reg   [12:0] v10_4_addr_reg_2021_pp0_iter17_reg;
reg   [12:0] v10_4_addr_reg_2021_pp0_iter18_reg;
reg   [12:0] v10_5_addr_reg_2027;
reg   [12:0] v10_5_addr_reg_2027_pp0_iter11_reg;
reg   [12:0] v10_5_addr_reg_2027_pp0_iter12_reg;
reg   [12:0] v10_5_addr_reg_2027_pp0_iter13_reg;
reg   [12:0] v10_5_addr_reg_2027_pp0_iter14_reg;
reg   [12:0] v10_5_addr_reg_2027_pp0_iter15_reg;
reg   [12:0] v10_5_addr_reg_2027_pp0_iter16_reg;
reg   [12:0] v10_5_addr_reg_2027_pp0_iter17_reg;
reg   [12:0] v10_5_addr_reg_2027_pp0_iter18_reg;
reg   [12:0] v10_6_addr_reg_2033;
reg   [12:0] v10_6_addr_reg_2033_pp0_iter11_reg;
reg   [12:0] v10_6_addr_reg_2033_pp0_iter12_reg;
reg   [12:0] v10_6_addr_reg_2033_pp0_iter13_reg;
reg   [12:0] v10_6_addr_reg_2033_pp0_iter14_reg;
reg   [12:0] v10_6_addr_reg_2033_pp0_iter15_reg;
reg   [12:0] v10_6_addr_reg_2033_pp0_iter16_reg;
reg   [12:0] v10_6_addr_reg_2033_pp0_iter17_reg;
reg   [12:0] v10_6_addr_reg_2033_pp0_iter18_reg;
reg   [12:0] v10_7_addr_reg_2039;
reg   [12:0] v10_7_addr_reg_2039_pp0_iter11_reg;
reg   [12:0] v10_7_addr_reg_2039_pp0_iter12_reg;
reg   [12:0] v10_7_addr_reg_2039_pp0_iter13_reg;
reg   [12:0] v10_7_addr_reg_2039_pp0_iter14_reg;
reg   [12:0] v10_7_addr_reg_2039_pp0_iter15_reg;
reg   [12:0] v10_7_addr_reg_2039_pp0_iter16_reg;
reg   [12:0] v10_7_addr_reg_2039_pp0_iter17_reg;
reg   [12:0] v10_7_addr_reg_2039_pp0_iter18_reg;
reg   [31:0] v40_reg_2045;
reg   [31:0] v10_0_load_reg_2050;
reg   [31:0] v44_reg_2055;
reg   [31:0] v10_1_load_reg_2060;
reg   [31:0] v48_reg_2065;
reg   [31:0] v10_2_load_reg_2070;
reg   [31:0] v52_reg_2075;
reg   [31:0] v10_3_load_reg_2080;
reg   [31:0] v56_reg_2085;
reg   [31:0] v10_4_load_reg_2090;
reg   [31:0] v60_reg_2095;
reg   [31:0] v10_5_load_reg_2100;
reg   [31:0] v64_reg_2105;
reg   [31:0] v10_6_load_reg_2110;
reg   [31:0] v68_reg_2115;
reg   [31:0] v10_7_load_reg_2120;
wire   [31:0] v41_fu_1522_p1;
wire   [31:0] v45_fu_1526_p1;
wire   [31:0] v49_fu_1530_p1;
wire   [31:0] v53_fu_1534_p1;
wire   [31:0] v57_fu_1538_p1;
wire   [31:0] v61_fu_1542_p1;
wire   [31:0] v65_fu_1546_p1;
wire   [31:0] v69_fu_1550_p1;
reg   [31:0] v42_reg_2165;
reg   [31:0] v46_reg_2170;
reg   [31:0] v50_reg_2175;
reg   [31:0] v54_reg_2180;
reg   [31:0] v58_reg_2185;
reg   [31:0] v62_reg_2190;
reg   [31:0] v66_reg_2195;
reg   [31:0] v70_reg_2200;
reg    ap_condition_exit_pp0_iter5_stage0;
wire   [63:0] select_ln173_2_cast_fu_1402_p1;
wire    ap_block_pp0_stage0;
wire   [63:0] zext_ln177_5_fu_1463_p1;
wire   [63:0] zext_ln180_2_fu_1511_p1;
reg   [5:0] v37_fu_138;
wire   [5:0] add_ln175_fu_1345_p2;
wire    ap_loop_init;
reg   [5:0] v36_fu_142;
wire   [5:0] select_ln174_1_fu_1293_p3;
reg   [11:0] indvar_flatten_fu_146;
wire   [11:0] select_ln174_3_fu_912_p3;
reg   [3:0] v35_fu_150;
wire   [3:0] select_ln173_1_fu_894_p3;
reg   [14:0] indvar_flatten25_fu_154;
wire   [14:0] select_ln173_4_fu_692_p3;
reg   [1:0] v34_fu_158;
wire   [1:0] select_ln172_1_fu_1116_p3;
reg   [15:0] indvar_flatten101_fu_162;
wire   [15:0] select_ln172_4_fu_633_p3;
reg   [1:0] v33_fu_166;
reg   [16:0] indvar_flatten189_fu_170;
wire   [16:0] select_ln171_4_fu_584_p3;
reg   [1:0] v32_fu_174;
reg   [17:0] indvar_flatten289_fu_178;
wire   [17:0] add_ln170_1_fu_563_p2;
wire   [31:0] v1_0_Addr_A_orig;
wire   [31:0] v1_1_Addr_A_orig;
wire   [31:0] v1_2_Addr_A_orig;
wire   [31:0] v1_3_Addr_A_orig;
wire   [31:0] v1_4_Addr_A_orig;
wire   [31:0] v1_5_Addr_A_orig;
wire   [31:0] v1_6_Addr_A_orig;
wire   [31:0] v1_7_Addr_A_orig;
wire   [31:0] v28_Addr_A_orig;
wire   [31:0] v10_0_Addr_B_orig;
wire   [31:0] v10_0_Addr_A_orig;
wire   [31:0] v10_1_Addr_B_orig;
wire   [31:0] v10_1_Addr_A_orig;
wire   [31:0] v10_2_Addr_B_orig;
wire   [31:0] v10_2_Addr_A_orig;
wire   [31:0] v10_3_Addr_B_orig;
wire   [31:0] v10_3_Addr_A_orig;
wire   [31:0] v10_4_Addr_B_orig;
wire   [31:0] v10_4_Addr_A_orig;
wire   [31:0] v10_5_Addr_B_orig;
wire   [31:0] v10_5_Addr_A_orig;
wire   [31:0] v10_6_Addr_B_orig;
wire   [31:0] v10_6_Addr_A_orig;
wire   [31:0] v10_7_Addr_B_orig;
wire   [31:0] v10_7_Addr_A_orig;
wire   [16:0] add_ln171_1_fu_578_p2;
wire   [15:0] add_ln172_1_fu_627_p2;
wire   [0:0] icmp_ln173_fu_649_p2;
wire   [0:0] xor_ln171_fu_660_p2;
wire   [0:0] and_ln170_2_fu_655_p2;
wire   [14:0] add_ln173_1_fu_686_p2;
wire   [5:0] tmp_45_fu_722_p3;
wire   [6:0] tmp_45_cast_fu_730_p1;
wire   [6:0] v35_cast_fu_718_p1;
wire   [6:0] empty_fu_734_p2;
wire  signed [7:0] p_cast_fu_740_p1;
wire   [7:0] zext_ln170_fu_714_p1;
wire   [0:0] icmp_ln174_fu_781_p2;
wire   [1:0] select_ln170_fu_759_p3;
wire   [3:0] tmp_53_fu_805_p3;
wire   [4:0] tmp_53_cast_fu_813_p1;
wire   [4:0] zext_ln177_1_fu_777_p1;
wire   [0:0] and_ln170_1_fu_787_p2;
wire   [3:0] select_ln172_fu_828_p3;
wire   [0:0] or_ln173_fu_852_p2;
wire   [3:0] add_ln173_fu_846_p2;
wire   [5:0] tmp_56_fu_866_p3;
wire   [6:0] tmp_56_cast_fu_874_p1;
wire   [6:0] add_ln173_cast_fu_862_p1;
wire   [6:0] empty_379_fu_878_p2;
wire  signed [7:0] p_cast7_fu_884_p1;
wire   [7:0] zext_ln177_fu_773_p1;
wire   [11:0] add_ln174_1_fu_906_p2;
wire   [9:0] tmp_fu_959_p3;
wire  signed [61:0] p_shl1_fu_966_p1;
wire  signed [61:0] p_cast1_fu_956_p1;
wire   [61:0] empty_365_fu_970_p2;
wire   [61:0] zext_ln171_fu_946_p1;
wire   [61:0] empty_366_fu_976_p2;
wire   [5:0] empty_368_fu_986_p1;
wire   [7:0] p_shl_fu_990_p3;
wire   [7:0] empty_367_fu_982_p1;
wire   [7:0] empty_369_fu_998_p2;
wire   [7:0] zext_ln172_fu_952_p1;
wire   [5:0] zext_ln171_1_fu_949_p1;
wire   [6:0] or_ln_fu_1019_p5;
wire   [5:0] empty_371_fu_1010_p2;
wire   [0:0] icmp_ln175_fu_1040_p2;
wire  signed [5:0] p_cast4_fu_1067_p1;
wire   [5:0] zext_ln171_2_fu_1058_p1;
wire  signed [5:0] empty_374_fu_1070_p2;
wire   [7:0] p_shl2_fu_1080_p3;
wire  signed [7:0] p_cast5_fu_1076_p1;
wire   [5:0] select_ln170_3_fu_1033_p3;
wire   [0:0] and_ln170_fu_1046_p2;
wire   [1:0] select_ln171_fu_1051_p3;
wire   [1:0] add_ln172_fu_1106_p2;
wire   [5:0] zext_ln171_4_fu_1064_p1;
wire  signed [5:0] empty_376_fu_1131_p2;
wire   [7:0] p_shl3_fu_1141_p3;
wire  signed [7:0] p_cast6_fu_1137_p1;
wire   [7:0] empty_377_fu_1149_p2;
wire   [7:0] zext_ln172_1_fu_1112_p1;
wire   [5:0] select_ln171_3_fu_1094_p3;
wire   [0:0] and_ln171_fu_1101_p2;
wire   [9:0] tmp_69_fu_1183_p3;
wire  signed [61:0] p_shl4_fu_1190_p1;
wire  signed [61:0] p_cast9_fu_1180_p1;
wire   [61:0] empty_381_fu_1194_p2;
wire   [61:0] zext_ln171_3_fu_1061_p1;
wire   [61:0] empty_382_fu_1200_p2;
wire   [5:0] empty_384_fu_1210_p1;
wire   [7:0] p_shl5_fu_1214_p3;
wire   [7:0] empty_383_fu_1206_p1;
wire   [7:0] empty_385_fu_1222_p2;
wire   [7:0] zext_ln172_2_fu_1123_p1;
wire   [5:0] select_ln172_3_fu_1161_p3;
wire   [0:0] xor_ln173_fu_1248_p2;
wire   [0:0] and_ln172_fu_1168_p2;
wire   [0:0] or_ln173_2_fu_1253_p2;
wire   [5:0] select_ln173_fu_1173_p3;
wire   [0:0] and_ln173_fu_1258_p2;
wire   [0:0] or_ln174_fu_1270_p2;
wire   [0:0] or_ln174_1_fu_1275_p2;
wire   [0:0] or_ln174_2_fu_1280_p2;
wire   [5:0] add_ln174_fu_1264_p2;
wire   [7:0] tmp_59_cast_fu_1234_p3;
wire   [7:0] zext_ln180_fu_1301_p1;
wire   [5:0] p_mid1_fu_1311_p2;
wire   [5:0] select_ln173_3_fu_1241_p3;
wire   [5:0] select_ln174_2_fu_1317_p3;
wire   [7:0] zext_ln170_1_fu_1029_p1;
wire   [7:0] zext_ln177_2_fu_1325_p1;
wire   [5:0] select_ln172_3_cast_fu_1127_p1;
wire   [4:0] tmp_68_fu_1366_p4;
wire   [7:0] zext_ln173_fu_1374_p1;
wire   [7:0] select_ln170_2_fu_1378_p3;
wire   [7:0] select_ln171_2_fu_1384_p3;
wire   [7:0] select_ln172_2_fu_1390_p3;
wire   [7:0] select_ln173_2_fu_1396_p3;
wire   [8:0] tmp_70_fu_1428_p3;
wire   [11:0] p_shl6_fu_1421_p3;
wire   [11:0] zext_ln177_3_fu_1435_p1;
wire   [12:0] tmp_61_fu_1414_p3;
wire   [12:0] zext_ln180_1_fu_1445_p1;
wire   [11:0] add_ln177_2_fu_1439_p2;
wire   [11:0] zext_ln177_4_fu_1454_p1;
wire   [11:0] add_ln177_3_fu_1457_p2;
reg    ap_done_reg;
wire    ap_continue_int;
reg    ap_done_int;
reg    ap_loop_exit_ready_pp0_iter2_reg;
reg    ap_loop_exit_ready_pp0_iter3_reg;
reg    ap_loop_exit_ready_pp0_iter4_reg;
reg    ap_loop_exit_ready_pp0_iter5_reg;
reg    ap_loop_exit_ready_pp0_iter6_reg;
reg    ap_loop_exit_ready_pp0_iter7_reg;
reg    ap_loop_exit_ready_pp0_iter8_reg;
reg    ap_loop_exit_ready_pp0_iter9_reg;
reg    ap_loop_exit_ready_pp0_iter10_reg;
reg    ap_loop_exit_ready_pp0_iter11_reg;
reg    ap_loop_exit_ready_pp0_iter12_reg;
reg    ap_loop_exit_ready_pp0_iter13_reg;
reg    ap_loop_exit_ready_pp0_iter14_reg;
reg    ap_loop_exit_ready_pp0_iter15_reg;
reg    ap_loop_exit_ready_pp0_iter16_reg;
reg    ap_loop_exit_ready_pp0_iter17_reg;
reg    ap_loop_exit_ready_pp0_iter18_reg;
reg   [0:0] ap_NS_fsm;
wire    ap_enable_pp0;
wire    ap_start_int;
wire    ap_block_pp0_stage0_00001;
wire    ap_ce_reg;

// power-on initialization
initial begin
#0 ap_CS_fsm = 1'd1;
#0 ap_enable_reg_pp0_iter1 = 1'b0;
#0 ap_enable_reg_pp0_iter2 = 1'b0;
#0 ap_enable_reg_pp0_iter3 = 1'b0;
#0 ap_enable_reg_pp0_iter4 = 1'b0;
#0 ap_enable_reg_pp0_iter5 = 1'b0;
#0 ap_enable_reg_pp0_iter6 = 1'b0;
#0 ap_enable_reg_pp0_iter7 = 1'b0;
#0 ap_enable_reg_pp0_iter8 = 1'b0;
#0 ap_enable_reg_pp0_iter9 = 1'b0;
#0 ap_enable_reg_pp0_iter10 = 1'b0;
#0 ap_enable_reg_pp0_iter11 = 1'b0;
#0 ap_enable_reg_pp0_iter12 = 1'b0;
#0 ap_enable_reg_pp0_iter13 = 1'b0;
#0 ap_enable_reg_pp0_iter14 = 1'b0;
#0 ap_enable_reg_pp0_iter15 = 1'b0;
#0 ap_enable_reg_pp0_iter16 = 1'b0;
#0 ap_enable_reg_pp0_iter17 = 1'b0;
#0 ap_enable_reg_pp0_iter18 = 1'b0;
#0 ap_enable_reg_pp0_iter19 = 1'b0;
#0 ap_done_reg = 1'b0;
end

test_vgg16_flow_control_loop_pipe_sequential_init flow_control_loop_pipe_sequential_init_U(
    .ap_clk(ap_clk),
    .ap_rst(ap_rst),
    .ap_start(ap_start),
    .ap_ready(ap_ready),
    .ap_done(ap_done),
    .ap_start_int(ap_start_int),
    .ap_loop_init(ap_loop_init),
    .ap_ready_int(ap_ready_int),
    .ap_loop_exit_ready(ap_condition_exit_pp0_iter1_stage0),
    .ap_loop_exit_done(ap_done_int),
    .ap_continue_int(ap_continue_int),
    .ap_done_int(ap_done_int)
);

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_CS_fsm <= ap_ST_fsm_pp0_stage0;
    end else begin
        ap_CS_fsm <= ap_NS_fsm;
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_done_reg <= 1'b0;
    end else begin
        if ((ap_continue_int == 1'b1)) begin
            ap_done_reg <= 1'b0;
        end else if (((ap_loop_exit_ready_pp0_iter18_reg == 1'b1) & (1'b0 == ap_block_pp0_stage0_subdone))) begin
            ap_done_reg <= 1'b1;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_enable_reg_pp0_iter1 <= 1'b0;
    end else begin
        if ((1'b1 == ap_condition_exit_pp0_iter1_stage0)) begin
            ap_enable_reg_pp0_iter1 <= 1'b0;
        end else if (((1'b1 == ap_CS_fsm_pp0_stage0) & (1'b0 == ap_block_pp0_stage0_subdone))) begin
            ap_enable_reg_pp0_iter1 <= ap_start_int;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_enable_reg_pp0_iter10 <= 1'b0;
    end else begin
        if ((1'b0 == ap_block_pp0_stage0_subdone)) begin
            ap_enable_reg_pp0_iter10 <= ap_enable_reg_pp0_iter9;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_enable_reg_pp0_iter11 <= 1'b0;
    end else begin
        if ((1'b0 == ap_block_pp0_stage0_subdone)) begin
            ap_enable_reg_pp0_iter11 <= ap_enable_reg_pp0_iter10;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_enable_reg_pp0_iter12 <= 1'b0;
    end else begin
        if ((1'b0 == ap_block_pp0_stage0_subdone)) begin
            ap_enable_reg_pp0_iter12 <= ap_enable_reg_pp0_iter11;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_enable_reg_pp0_iter13 <= 1'b0;
    end else begin
        if ((1'b0 == ap_block_pp0_stage0_subdone)) begin
            ap_enable_reg_pp0_iter13 <= ap_enable_reg_pp0_iter12;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_enable_reg_pp0_iter14 <= 1'b0;
    end else begin
        if ((1'b0 == ap_block_pp0_stage0_subdone)) begin
            ap_enable_reg_pp0_iter14 <= ap_enable_reg_pp0_iter13;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_enable_reg_pp0_iter15 <= 1'b0;
    end else begin
        if ((1'b0 == ap_block_pp0_stage0_subdone)) begin
            ap_enable_reg_pp0_iter15 <= ap_enable_reg_pp0_iter14;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_enable_reg_pp0_iter16 <= 1'b0;
    end else begin
        if ((1'b0 == ap_block_pp0_stage0_subdone)) begin
            ap_enable_reg_pp0_iter16 <= ap_enable_reg_pp0_iter15;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_enable_reg_pp0_iter17 <= 1'b0;
    end else begin
        if ((1'b0 == ap_block_pp0_stage0_subdone)) begin
            ap_enable_reg_pp0_iter17 <= ap_enable_reg_pp0_iter16;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_enable_reg_pp0_iter18 <= 1'b0;
    end else begin
        if ((1'b0 == ap_block_pp0_stage0_subdone)) begin
            ap_enable_reg_pp0_iter18 <= ap_enable_reg_pp0_iter17;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_enable_reg_pp0_iter19 <= 1'b0;
    end else begin
        if ((1'b0 == ap_block_pp0_stage0_subdone)) begin
            ap_enable_reg_pp0_iter19 <= ap_enable_reg_pp0_iter18;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_enable_reg_pp0_iter2 <= 1'b0;
    end else begin
        if ((1'b0 == ap_block_pp0_stage0_subdone)) begin
            ap_enable_reg_pp0_iter2 <= ap_enable_reg_pp0_iter1;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_enable_reg_pp0_iter3 <= 1'b0;
    end else begin
        if ((1'b0 == ap_block_pp0_stage0_subdone)) begin
            ap_enable_reg_pp0_iter3 <= ap_enable_reg_pp0_iter2;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_enable_reg_pp0_iter4 <= 1'b0;
    end else begin
        if ((1'b0 == ap_block_pp0_stage0_subdone)) begin
            ap_enable_reg_pp0_iter4 <= ap_enable_reg_pp0_iter3;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_enable_reg_pp0_iter5 <= 1'b0;
    end else begin
        if ((1'b0 == ap_block_pp0_stage0_subdone)) begin
            ap_enable_reg_pp0_iter5 <= ap_enable_reg_pp0_iter4;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_enable_reg_pp0_iter6 <= 1'b0;
    end else begin
        if ((1'b1 == ap_condition_exit_pp0_iter5_stage0)) begin
            ap_enable_reg_pp0_iter6 <= 1'b0;
        end else if ((1'b0 == ap_block_pp0_stage0_subdone)) begin
            ap_enable_reg_pp0_iter6 <= ap_enable_reg_pp0_iter5;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_enable_reg_pp0_iter7 <= 1'b0;
    end else begin
        if ((1'b0 == ap_block_pp0_stage0_subdone)) begin
            ap_enable_reg_pp0_iter7 <= ap_enable_reg_pp0_iter6;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_enable_reg_pp0_iter8 <= 1'b0;
    end else begin
        if ((1'b0 == ap_block_pp0_stage0_subdone)) begin
            ap_enable_reg_pp0_iter8 <= ap_enable_reg_pp0_iter7;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_enable_reg_pp0_iter9 <= 1'b0;
    end else begin
        if ((1'b0 == ap_block_pp0_stage0_subdone)) begin
            ap_enable_reg_pp0_iter9 <= ap_enable_reg_pp0_iter8;
        end
    end
end

always @ (posedge ap_clk) begin
    if ((1'b0 == ap_block_pp0_stage0_11001)) begin
        if (((ap_loop_init == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
            indvar_flatten101_fu_162 <= 16'd0;
        end else if (((icmp_ln170_reg_1663 == 1'd0) & (ap_enable_reg_pp0_iter2 == 1'b1))) begin
            indvar_flatten101_fu_162 <= select_ln172_4_fu_633_p3;
        end
    end
end

always @ (posedge ap_clk) begin
    if (((1'b1 == ap_CS_fsm_pp0_stage0) & (1'b0 == ap_block_pp0_stage0_11001))) begin
        if ((ap_loop_init == 1'b1)) begin
            indvar_flatten189_fu_170 <= 17'd0;
        end else if (((ap_enable_reg_pp0_iter1 == 1'b1) & (icmp_ln170_fu_557_p2 == 1'd0))) begin
            indvar_flatten189_fu_170 <= select_ln171_4_fu_584_p3;
        end
    end
end

always @ (posedge ap_clk) begin
    if ((1'b0 == ap_block_pp0_stage0_11001)) begin
        if (((ap_loop_init == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
            indvar_flatten25_fu_154 <= 15'd0;
        end else if (((icmp_ln170_reg_1663_pp0_iter2_reg == 1'd0) & (ap_enable_reg_pp0_iter3 == 1'b1))) begin
            indvar_flatten25_fu_154 <= select_ln173_4_fu_692_p3;
        end
    end
end

always @ (posedge ap_clk) begin
    if (((1'b1 == ap_CS_fsm_pp0_stage0) & (1'b0 == ap_block_pp0_stage0_11001))) begin
        if ((ap_loop_init == 1'b1)) begin
            indvar_flatten289_fu_178 <= 18'd0;
        end else if (((ap_enable_reg_pp0_iter1 == 1'b1) & (icmp_ln170_fu_557_p2 == 1'd0))) begin
            indvar_flatten289_fu_178 <= add_ln170_1_fu_563_p2;
        end
    end
end

always @ (posedge ap_clk) begin
    if ((1'b0 == ap_block_pp0_stage0_11001)) begin
        if (((ap_loop_init == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
            indvar_flatten_fu_146 <= 12'd0;
        end else if (((icmp_ln170_reg_1663_pp0_iter3_reg == 1'd0) & (ap_enable_reg_pp0_iter4 == 1'b1))) begin
            indvar_flatten_fu_146 <= select_ln174_3_fu_912_p3;
        end
    end
end

always @ (posedge ap_clk) begin
    if ((1'b0 == ap_block_pp0_stage0_11001)) begin
        if (((ap_loop_init == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
            v32_fu_174 <= 2'd0;
        end else if (((icmp_ln170_reg_1663_pp0_iter3_reg == 1'd0) & (ap_enable_reg_pp0_iter4 == 1'b1))) begin
            v32_fu_174 <= select_ln170_1_fu_766_p3;
        end
    end
end

always @ (posedge ap_clk) begin
    if ((1'b0 == ap_block_pp0_stage0_11001)) begin
        if (((ap_loop_init == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
            v33_fu_166 <= 2'd0;
        end else if (((icmp_ln170_reg_1663_pp0_iter3_reg == 1'd0) & (ap_enable_reg_pp0_iter4 == 1'b1))) begin
            v33_fu_166 <= select_ln171_1_fu_798_p3;
        end
    end
end

always @ (posedge ap_clk) begin
    if ((1'b0 == ap_block_pp0_stage0_11001)) begin
        if (((ap_loop_init == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
            v34_fu_158 <= 2'd0;
        end else if (((ap_enable_reg_pp0_iter5 == 1'b1) & (icmp_ln170_reg_1663_pp0_iter4_reg == 1'd0))) begin
            v34_fu_158 <= select_ln172_1_fu_1116_p3;
        end
    end
end

always @ (posedge ap_clk) begin
    if ((1'b0 == ap_block_pp0_stage0_11001)) begin
        if (((ap_loop_init == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
            v35_fu_150 <= 4'd0;
        end else if (((icmp_ln170_reg_1663_pp0_iter3_reg == 1'd0) & (ap_enable_reg_pp0_iter4 == 1'b1))) begin
            v35_fu_150 <= select_ln173_1_fu_894_p3;
        end
    end
end

always @ (posedge ap_clk) begin
    if ((1'b0 == ap_block_pp0_stage0_11001)) begin
        if (((ap_loop_init == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
            v36_fu_142 <= 6'd0;
        end else if (((ap_enable_reg_pp0_iter5 == 1'b1) & (icmp_ln170_reg_1663_pp0_iter4_reg == 1'd0))) begin
            v36_fu_142 <= select_ln174_1_fu_1293_p3;
        end
    end
end

always @ (posedge ap_clk) begin
    if ((1'b0 == ap_block_pp0_stage0_11001)) begin
        if (((ap_loop_init == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
            v37_fu_138 <= 6'd0;
        end else if (((ap_enable_reg_pp0_iter5 == 1'b1) & (icmp_ln170_reg_1663_pp0_iter4_reg == 1'd0))) begin
            v37_fu_138 <= add_ln175_fu_1345_p2;
        end
    end
end

always @ (posedge ap_clk) begin
    if (((icmp_ln170_reg_1663_pp0_iter3_reg == 1'd0) & (1'b0 == ap_block_pp0_stage0_11001))) begin
        add_ln170_reg_1744 <= add_ln170_fu_753_p2;
        add_ln171_reg_1756 <= add_ln171_fu_792_p2;
        and_ln171_1_reg_1772 <= and_ln171_1_fu_823_p2;
        and_ln172_1_reg_1782 <= and_ln172_1_fu_840_p2;
        empty_373_reg_1767 <= empty_373_fu_817_p2;
        empty_380_reg_1794 <= empty_380_fu_888_p2;
        or_ln173_1_reg_1789 <= or_ln173_1_fu_857_p2;
        select_ln170_1_reg_1750 <= select_ln170_1_fu_766_p3;
        select_ln171_1_reg_1761 <= select_ln171_1_fu_798_p3;
        trunc_ln180_reg_1800 <= trunc_ln180_fu_902_p1;
        xor_ln172_reg_1777 <= xor_ln172_fu_835_p2;
    end
end

always @ (posedge ap_clk) begin
    if ((1'b0 == ap_block_pp0_stage0_11001)) begin
        add_ln170_reg_1744_pp0_iter5_reg <= add_ln170_reg_1744;
        add_ln180_1_reg_1890 <= add_ln180_1_fu_1448_p2;
        add_ln180_1_reg_1890_pp0_iter7_reg <= add_ln180_1_reg_1890;
        add_ln180_1_reg_1890_pp0_iter8_reg <= add_ln180_1_reg_1890_pp0_iter7_reg;
        add_ln180_1_reg_1890_pp0_iter9_reg <= add_ln180_1_reg_1890_pp0_iter8_reg;
        and_ln170_3_reg_1692_pp0_iter3_reg <= and_ln170_3_reg_1692;
        and_ln170_3_reg_1692_pp0_iter4_reg <= and_ln170_3_reg_1692_pp0_iter3_reg;
        and_ln170_3_reg_1692_pp0_iter5_reg <= and_ln170_3_reg_1692_pp0_iter4_reg;
        and_ln171_2_reg_1712_pp0_iter4_reg <= and_ln171_2_reg_1712;
        and_ln171_2_reg_1712_pp0_iter5_reg <= and_ln171_2_reg_1712_pp0_iter4_reg;
        and_ln172_1_reg_1782_pp0_iter5_reg <= and_ln172_1_reg_1782;
        ap_loop_exit_ready_pp0_iter10_reg <= ap_loop_exit_ready_pp0_iter9_reg;
        ap_loop_exit_ready_pp0_iter11_reg <= ap_loop_exit_ready_pp0_iter10_reg;
        ap_loop_exit_ready_pp0_iter12_reg <= ap_loop_exit_ready_pp0_iter11_reg;
        ap_loop_exit_ready_pp0_iter13_reg <= ap_loop_exit_ready_pp0_iter12_reg;
        ap_loop_exit_ready_pp0_iter14_reg <= ap_loop_exit_ready_pp0_iter13_reg;
        ap_loop_exit_ready_pp0_iter15_reg <= ap_loop_exit_ready_pp0_iter14_reg;
        ap_loop_exit_ready_pp0_iter16_reg <= ap_loop_exit_ready_pp0_iter15_reg;
        ap_loop_exit_ready_pp0_iter17_reg <= ap_loop_exit_ready_pp0_iter16_reg;
        ap_loop_exit_ready_pp0_iter18_reg <= ap_loop_exit_ready_pp0_iter17_reg;
        ap_loop_exit_ready_pp0_iter3_reg <= ap_loop_exit_ready_pp0_iter2_reg;
        ap_loop_exit_ready_pp0_iter4_reg <= ap_loop_exit_ready_pp0_iter3_reg;
        ap_loop_exit_ready_pp0_iter5_reg <= ap_loop_exit_ready_pp0_iter4_reg;
        ap_loop_exit_ready_pp0_iter6_reg <= ap_loop_exit_ready_pp0_iter5_reg;
        ap_loop_exit_ready_pp0_iter7_reg <= ap_loop_exit_ready_pp0_iter6_reg;
        ap_loop_exit_ready_pp0_iter8_reg <= ap_loop_exit_ready_pp0_iter7_reg;
        ap_loop_exit_ready_pp0_iter9_reg <= ap_loop_exit_ready_pp0_iter8_reg;
        icmp_ln170_reg_1663_pp0_iter2_reg <= icmp_ln170_reg_1663;
        icmp_ln170_reg_1663_pp0_iter3_reg <= icmp_ln170_reg_1663_pp0_iter2_reg;
        icmp_ln170_reg_1663_pp0_iter4_reg <= icmp_ln170_reg_1663_pp0_iter3_reg;
        icmp_ln171_reg_1667_pp0_iter2_reg <= icmp_ln171_reg_1667;
        icmp_ln171_reg_1667_pp0_iter3_reg <= icmp_ln171_reg_1667_pp0_iter2_reg;
        icmp_ln171_reg_1667_pp0_iter4_reg <= icmp_ln171_reg_1667_pp0_iter3_reg;
        icmp_ln171_reg_1667_pp0_iter5_reg <= icmp_ln171_reg_1667_pp0_iter4_reg;
        or_ln171_1_reg_1706_pp0_iter4_reg <= or_ln171_1_reg_1706;
        or_ln171_reg_1700_pp0_iter3_reg <= or_ln171_reg_1700;
        or_ln171_reg_1700_pp0_iter4_reg <= or_ln171_reg_1700_pp0_iter3_reg;
        or_ln172_reg_1722_pp0_iter4_reg <= or_ln172_reg_1722;
        v10_0_addr_reg_1997 <= zext_ln180_2_fu_1511_p1;
        v10_0_addr_reg_1997_pp0_iter11_reg <= v10_0_addr_reg_1997;
        v10_0_addr_reg_1997_pp0_iter12_reg <= v10_0_addr_reg_1997_pp0_iter11_reg;
        v10_0_addr_reg_1997_pp0_iter13_reg <= v10_0_addr_reg_1997_pp0_iter12_reg;
        v10_0_addr_reg_1997_pp0_iter14_reg <= v10_0_addr_reg_1997_pp0_iter13_reg;
        v10_0_addr_reg_1997_pp0_iter15_reg <= v10_0_addr_reg_1997_pp0_iter14_reg;
        v10_0_addr_reg_1997_pp0_iter16_reg <= v10_0_addr_reg_1997_pp0_iter15_reg;
        v10_0_addr_reg_1997_pp0_iter17_reg <= v10_0_addr_reg_1997_pp0_iter16_reg;
        v10_0_addr_reg_1997_pp0_iter18_reg <= v10_0_addr_reg_1997_pp0_iter17_reg;
        v10_1_addr_reg_2003 <= zext_ln180_2_fu_1511_p1;
        v10_1_addr_reg_2003_pp0_iter11_reg <= v10_1_addr_reg_2003;
        v10_1_addr_reg_2003_pp0_iter12_reg <= v10_1_addr_reg_2003_pp0_iter11_reg;
        v10_1_addr_reg_2003_pp0_iter13_reg <= v10_1_addr_reg_2003_pp0_iter12_reg;
        v10_1_addr_reg_2003_pp0_iter14_reg <= v10_1_addr_reg_2003_pp0_iter13_reg;
        v10_1_addr_reg_2003_pp0_iter15_reg <= v10_1_addr_reg_2003_pp0_iter14_reg;
        v10_1_addr_reg_2003_pp0_iter16_reg <= v10_1_addr_reg_2003_pp0_iter15_reg;
        v10_1_addr_reg_2003_pp0_iter17_reg <= v10_1_addr_reg_2003_pp0_iter16_reg;
        v10_1_addr_reg_2003_pp0_iter18_reg <= v10_1_addr_reg_2003_pp0_iter17_reg;
        v10_2_addr_reg_2009 <= zext_ln180_2_fu_1511_p1;
        v10_2_addr_reg_2009_pp0_iter11_reg <= v10_2_addr_reg_2009;
        v10_2_addr_reg_2009_pp0_iter12_reg <= v10_2_addr_reg_2009_pp0_iter11_reg;
        v10_2_addr_reg_2009_pp0_iter13_reg <= v10_2_addr_reg_2009_pp0_iter12_reg;
        v10_2_addr_reg_2009_pp0_iter14_reg <= v10_2_addr_reg_2009_pp0_iter13_reg;
        v10_2_addr_reg_2009_pp0_iter15_reg <= v10_2_addr_reg_2009_pp0_iter14_reg;
        v10_2_addr_reg_2009_pp0_iter16_reg <= v10_2_addr_reg_2009_pp0_iter15_reg;
        v10_2_addr_reg_2009_pp0_iter17_reg <= v10_2_addr_reg_2009_pp0_iter16_reg;
        v10_2_addr_reg_2009_pp0_iter18_reg <= v10_2_addr_reg_2009_pp0_iter17_reg;
        v10_3_addr_reg_2015 <= zext_ln180_2_fu_1511_p1;
        v10_3_addr_reg_2015_pp0_iter11_reg <= v10_3_addr_reg_2015;
        v10_3_addr_reg_2015_pp0_iter12_reg <= v10_3_addr_reg_2015_pp0_iter11_reg;
        v10_3_addr_reg_2015_pp0_iter13_reg <= v10_3_addr_reg_2015_pp0_iter12_reg;
        v10_3_addr_reg_2015_pp0_iter14_reg <= v10_3_addr_reg_2015_pp0_iter13_reg;
        v10_3_addr_reg_2015_pp0_iter15_reg <= v10_3_addr_reg_2015_pp0_iter14_reg;
        v10_3_addr_reg_2015_pp0_iter16_reg <= v10_3_addr_reg_2015_pp0_iter15_reg;
        v10_3_addr_reg_2015_pp0_iter17_reg <= v10_3_addr_reg_2015_pp0_iter16_reg;
        v10_3_addr_reg_2015_pp0_iter18_reg <= v10_3_addr_reg_2015_pp0_iter17_reg;
        v10_4_addr_reg_2021 <= zext_ln180_2_fu_1511_p1;
        v10_4_addr_reg_2021_pp0_iter11_reg <= v10_4_addr_reg_2021;
        v10_4_addr_reg_2021_pp0_iter12_reg <= v10_4_addr_reg_2021_pp0_iter11_reg;
        v10_4_addr_reg_2021_pp0_iter13_reg <= v10_4_addr_reg_2021_pp0_iter12_reg;
        v10_4_addr_reg_2021_pp0_iter14_reg <= v10_4_addr_reg_2021_pp0_iter13_reg;
        v10_4_addr_reg_2021_pp0_iter15_reg <= v10_4_addr_reg_2021_pp0_iter14_reg;
        v10_4_addr_reg_2021_pp0_iter16_reg <= v10_4_addr_reg_2021_pp0_iter15_reg;
        v10_4_addr_reg_2021_pp0_iter17_reg <= v10_4_addr_reg_2021_pp0_iter16_reg;
        v10_4_addr_reg_2021_pp0_iter18_reg <= v10_4_addr_reg_2021_pp0_iter17_reg;
        v10_5_addr_reg_2027 <= zext_ln180_2_fu_1511_p1;
        v10_5_addr_reg_2027_pp0_iter11_reg <= v10_5_addr_reg_2027;
        v10_5_addr_reg_2027_pp0_iter12_reg <= v10_5_addr_reg_2027_pp0_iter11_reg;
        v10_5_addr_reg_2027_pp0_iter13_reg <= v10_5_addr_reg_2027_pp0_iter12_reg;
        v10_5_addr_reg_2027_pp0_iter14_reg <= v10_5_addr_reg_2027_pp0_iter13_reg;
        v10_5_addr_reg_2027_pp0_iter15_reg <= v10_5_addr_reg_2027_pp0_iter14_reg;
        v10_5_addr_reg_2027_pp0_iter16_reg <= v10_5_addr_reg_2027_pp0_iter15_reg;
        v10_5_addr_reg_2027_pp0_iter17_reg <= v10_5_addr_reg_2027_pp0_iter16_reg;
        v10_5_addr_reg_2027_pp0_iter18_reg <= v10_5_addr_reg_2027_pp0_iter17_reg;
        v10_6_addr_reg_2033 <= zext_ln180_2_fu_1511_p1;
        v10_6_addr_reg_2033_pp0_iter11_reg <= v10_6_addr_reg_2033;
        v10_6_addr_reg_2033_pp0_iter12_reg <= v10_6_addr_reg_2033_pp0_iter11_reg;
        v10_6_addr_reg_2033_pp0_iter13_reg <= v10_6_addr_reg_2033_pp0_iter12_reg;
        v10_6_addr_reg_2033_pp0_iter14_reg <= v10_6_addr_reg_2033_pp0_iter13_reg;
        v10_6_addr_reg_2033_pp0_iter15_reg <= v10_6_addr_reg_2033_pp0_iter14_reg;
        v10_6_addr_reg_2033_pp0_iter16_reg <= v10_6_addr_reg_2033_pp0_iter15_reg;
        v10_6_addr_reg_2033_pp0_iter17_reg <= v10_6_addr_reg_2033_pp0_iter16_reg;
        v10_6_addr_reg_2033_pp0_iter18_reg <= v10_6_addr_reg_2033_pp0_iter17_reg;
        v10_7_addr_reg_2039 <= zext_ln180_2_fu_1511_p1;
        v10_7_addr_reg_2039_pp0_iter11_reg <= v10_7_addr_reg_2039;
        v10_7_addr_reg_2039_pp0_iter12_reg <= v10_7_addr_reg_2039_pp0_iter11_reg;
        v10_7_addr_reg_2039_pp0_iter13_reg <= v10_7_addr_reg_2039_pp0_iter12_reg;
        v10_7_addr_reg_2039_pp0_iter14_reg <= v10_7_addr_reg_2039_pp0_iter13_reg;
        v10_7_addr_reg_2039_pp0_iter15_reg <= v10_7_addr_reg_2039_pp0_iter14_reg;
        v10_7_addr_reg_2039_pp0_iter16_reg <= v10_7_addr_reg_2039_pp0_iter15_reg;
        v10_7_addr_reg_2039_pp0_iter17_reg <= v10_7_addr_reg_2039_pp0_iter16_reg;
        v10_7_addr_reg_2039_pp0_iter18_reg <= v10_7_addr_reg_2039_pp0_iter17_reg;
        v1_0_load_reg_1900 <= v1_0_Dout_A;
        v1_1_load_reg_1905 <= v1_1_Dout_A;
        v1_2_load_reg_1910 <= v1_2_Dout_A;
        v1_3_load_reg_1915 <= v1_3_Dout_A;
        v1_4_load_reg_1920 <= v1_4_Dout_A;
        v1_5_load_reg_1925 <= v1_5_Dout_A;
        v1_6_load_reg_1930 <= v1_6_Dout_A;
        v1_7_load_reg_1935 <= v1_7_Dout_A;
        v28_load_reg_1940 <= v28_Dout_A;
        v33_1_reg_1732 <= v33_fu_166;
        v40_reg_2045 <= grp_fu_12608_p_dout0;
        v42_reg_2165 <= grp_fu_12576_p_dout0;
        v44_reg_2055 <= grp_fu_12612_p_dout0;
        v46_reg_2170 <= grp_fu_12580_p_dout0;
        v48_reg_2065 <= grp_fu_12616_p_dout0;
        v50_reg_2175 <= grp_fu_12584_p_dout0;
        v52_reg_2075 <= grp_fu_12620_p_dout0;
        v54_reg_2180 <= grp_fu_12588_p_dout0;
        v56_reg_2085 <= grp_fu_12624_p_dout0;
        v58_reg_2185 <= grp_fu_12592_p_dout0;
        v60_reg_2095 <= grp_fu_12628_p_dout0;
        v62_reg_2190 <= grp_fu_12596_p_dout0;
        v64_reg_2105 <= grp_fu_12632_p_dout0;
        v66_reg_2195 <= grp_fu_12600_p_dout0;
        v68_reg_2115 <= grp_fu_12636_p_dout0;
        v70_reg_2200 <= grp_fu_12604_p_dout0;
        xor_ln170_reg_1680_pp0_iter3_reg <= xor_ln170_reg_1680;
        xor_ln170_reg_1680_pp0_iter4_reg <= xor_ln170_reg_1680_pp0_iter3_reg;
    end
end

always @ (posedge ap_clk) begin
    if (((icmp_ln170_reg_1663_pp0_iter4_reg == 1'd0) & (1'b0 == ap_block_pp0_stage0_11001))) begin
        add_ln177_1_reg_1835 <= add_ln177_1_fu_1329_p2;
        add_ln177_reg_1845 <= add_ln177_fu_1339_p2;
        add_ln180_reg_1830 <= add_ln180_fu_1305_p2;
        select_ln174_reg_1825 <= select_ln174_fu_1285_p3;
        trunc_ln177_reg_1840 <= trunc_ln177_fu_1335_p1;
    end
end

always @ (posedge ap_clk) begin
    if (((icmp_ln170_reg_1663 == 1'd0) & (1'b0 == ap_block_pp0_stage0_11001))) begin
        and_ln170_3_reg_1692 <= and_ln170_3_fu_616_p2;
        icmp_ln172_reg_1687 <= icmp_ln172_fu_610_p2;
        or_ln171_reg_1700 <= or_ln171_fu_622_p2;
        xor_ln170_reg_1680 <= xor_ln170_fu_605_p2;
    end
end

always @ (posedge ap_clk) begin
    if (((icmp_ln170_reg_1663_pp0_iter2_reg == 1'd0) & (1'b0 == ap_block_pp0_stage0_11001))) begin
        and_ln171_2_reg_1712 <= and_ln171_2_fu_670_p2;
        or_ln171_1_reg_1706 <= or_ln171_1_fu_665_p2;
        or_ln172_1_reg_1727 <= or_ln172_1_fu_681_p2;
        or_ln172_reg_1722 <= or_ln172_fu_676_p2;
    end
end

always @ (posedge ap_clk) begin
    if (((1'b1 == ap_CS_fsm_pp0_stage0) & (1'b0 == ap_block_pp0_stage0_11001))) begin
        ap_loop_exit_ready_pp0_iter2_reg <= ap_loop_exit_ready;
        icmp_ln170_reg_1663 <= icmp_ln170_fu_557_p2;
    end
end

always @ (posedge ap_clk) begin
    if (((icmp_ln171_reg_1667_pp0_iter3_reg == 1'd0) & (1'd0 == and_ln171_2_reg_1712) & (1'd0 == and_ln170_3_reg_1692_pp0_iter3_reg) & (1'b0 == ap_block_pp0_stage0_11001))) begin
        empty_364_reg_1738 <= empty_364_fu_744_p2;
    end
end

always @ (posedge ap_clk) begin
    if (((icmp_ln171_reg_1667_pp0_iter4_reg == 1'd0) & (1'd0 == and_ln172_1_reg_1782) & (1'd0 == and_ln171_2_reg_1712_pp0_iter4_reg) & (1'd0 == and_ln170_3_reg_1692_pp0_iter4_reg) & (1'b0 == ap_block_pp0_stage0_11001))) begin
        empty_370_reg_1805 <= empty_370_fu_1004_p2;
    end
end

always @ (posedge ap_clk) begin
    if (((1'd0 == and_ln172_1_reg_1782) & (1'd0 == and_ln171_2_reg_1712_pp0_iter4_reg) & (icmp_ln170_reg_1663_pp0_iter4_reg == 1'd0) & (1'd1 == and_ln170_3_reg_1692_pp0_iter4_reg) & (1'b0 == ap_block_pp0_stage0_11001))) begin
        empty_375_reg_1810 <= empty_375_fu_1088_p2;
    end
end

always @ (posedge ap_clk) begin
    if (((1'd0 == and_ln172_1_reg_1782) & (icmp_ln170_reg_1663_pp0_iter4_reg == 1'd0) & (1'd1 == and_ln171_2_reg_1712_pp0_iter4_reg) & (1'b0 == ap_block_pp0_stage0_11001))) begin
        empty_378_reg_1815 <= empty_378_fu_1155_p2;
    end
end

always @ (posedge ap_clk) begin
    if (((icmp_ln170_reg_1663_pp0_iter4_reg == 1'd0) & (1'd1 == and_ln172_1_reg_1782) & (1'b0 == ap_block_pp0_stage0_11001))) begin
        empty_386_reg_1820 <= empty_386_fu_1228_p2;
    end
end

always @ (posedge ap_clk) begin
    if (((1'b1 == ap_CS_fsm_pp0_stage0) & (icmp_ln170_fu_557_p2 == 1'd0) & (1'b0 == ap_block_pp0_stage0_11001))) begin
        icmp_ln171_reg_1667 <= icmp_ln171_fu_572_p2;
    end
end

always @ (posedge ap_clk) begin
    if (((ap_enable_reg_pp0_iter11 == 1'b1) & (1'b0 == ap_block_pp0_stage0_11001))) begin
        v10_0_load_reg_2050 <= v10_0_Dout_B;
        v10_1_load_reg_2060 <= v10_1_Dout_B;
        v10_2_load_reg_2070 <= v10_2_Dout_B;
        v10_3_load_reg_2080 <= v10_3_Dout_B;
        v10_4_load_reg_2090 <= v10_4_Dout_B;
        v10_5_load_reg_2100 <= v10_5_Dout_B;
        v10_6_load_reg_2110 <= v10_6_Dout_B;
        v10_7_load_reg_2120 <= v10_7_Dout_B;
    end
end

always @ (*) begin
    if (((ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0) & (icmp_ln170_fu_557_p2 == 1'd1) & (1'b0 == ap_block_pp0_stage0_subdone))) begin
        ap_condition_exit_pp0_iter1_stage0 = 1'b1;
    end else begin
        ap_condition_exit_pp0_iter1_stage0 = 1'b0;
    end
end

always @ (*) begin
    if (((ap_enable_reg_pp0_iter5 == 1'b1) & (icmp_ln170_reg_1663_pp0_iter4_reg == 1'd1) & (1'b0 == ap_block_pp0_stage0_subdone))) begin
        ap_condition_exit_pp0_iter5_stage0 = 1'b1;
    end else begin
        ap_condition_exit_pp0_iter5_stage0 = 1'b0;
    end
end

always @ (*) begin
    if (((ap_loop_exit_ready_pp0_iter18_reg == 1'b1) & (1'b0 == ap_block_pp0_stage0_subdone))) begin
        ap_done_int = 1'b1;
    end else begin
        ap_done_int = ap_done_reg;
    end
end

always @ (*) begin
    if (((ap_idle_pp0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0) & (ap_start_int == 1'b0))) begin
        ap_idle = 1'b1;
    end else begin
        ap_idle = 1'b0;
    end
end

always @ (*) begin
    if (((ap_enable_reg_pp0_iter19 == 1'b0) & (ap_enable_reg_pp0_iter18 == 1'b0) & (ap_enable_reg_pp0_iter17 == 1'b0) & (ap_enable_reg_pp0_iter16 == 1'b0) & (ap_enable_reg_pp0_iter15 == 1'b0) & (ap_enable_reg_pp0_iter14 == 1'b0) & (ap_enable_reg_pp0_iter13 == 1'b0) & (ap_enable_reg_pp0_iter12 == 1'b0) & (ap_enable_reg_pp0_iter11 == 1'b0) & (ap_enable_reg_pp0_iter10 == 1'b0) & (ap_enable_reg_pp0_iter9 == 1'b0) & (ap_enable_reg_pp0_iter8 == 1'b0) & (ap_enable_reg_pp0_iter7 == 1'b0) & (ap_enable_reg_pp0_iter6 == 1'b0) & (ap_enable_reg_pp0_iter5 == 1'b0) & (ap_enable_reg_pp0_iter4 == 1'b0) & (ap_enable_reg_pp0_iter3 == 1'b0) & (ap_enable_reg_pp0_iter2 == 1'b0) & (ap_enable_reg_pp0_iter1 == 1'b0) & (ap_enable_reg_pp0_iter0 == 1'b0))) begin
        ap_idle_pp0 = 1'b1;
    end else begin
        ap_idle_pp0 = 1'b0;
    end
end

always @ (*) begin
    if (((ap_enable_reg_pp0_iter0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0) & (1'b0 == ap_block_pp0_stage0_subdone))) begin
        ap_ready_int = 1'b1;
    end else begin
        ap_ready_int = 1'b0;
    end
end

always @ (*) begin
    if (((ap_enable_reg_pp0_iter19 == 1'b1) & (1'b0 == ap_block_pp0_stage0_11001))) begin
        v10_0_EN_A = 1'b1;
    end else begin
        v10_0_EN_A = 1'b0;
    end
end

always @ (*) begin
    if (((ap_enable_reg_pp0_iter10 == 1'b1) & (1'b0 == ap_block_pp0_stage0_11001))) begin
        v10_0_EN_B = 1'b1;
    end else begin
        v10_0_EN_B = 1'b0;
    end
end

always @ (*) begin
    if (((ap_enable_reg_pp0_iter19 == 1'b1) & (1'b0 == ap_block_pp0_stage0_11001))) begin
        v10_0_WEN_A = 4'd15;
    end else begin
        v10_0_WEN_A = 4'd0;
    end
end

always @ (*) begin
    if (((ap_enable_reg_pp0_iter19 == 1'b1) & (1'b0 == ap_block_pp0_stage0_11001))) begin
        v10_1_EN_A = 1'b1;
    end else begin
        v10_1_EN_A = 1'b0;
    end
end

always @ (*) begin
    if (((ap_enable_reg_pp0_iter10 == 1'b1) & (1'b0 == ap_block_pp0_stage0_11001))) begin
        v10_1_EN_B = 1'b1;
    end else begin
        v10_1_EN_B = 1'b0;
    end
end

always @ (*) begin
    if (((ap_enable_reg_pp0_iter19 == 1'b1) & (1'b0 == ap_block_pp0_stage0_11001))) begin
        v10_1_WEN_A = 4'd15;
    end else begin
        v10_1_WEN_A = 4'd0;
    end
end

always @ (*) begin
    if (((ap_enable_reg_pp0_iter19 == 1'b1) & (1'b0 == ap_block_pp0_stage0_11001))) begin
        v10_2_EN_A = 1'b1;
    end else begin
        v10_2_EN_A = 1'b0;
    end
end

always @ (*) begin
    if (((ap_enable_reg_pp0_iter10 == 1'b1) & (1'b0 == ap_block_pp0_stage0_11001))) begin
        v10_2_EN_B = 1'b1;
    end else begin
        v10_2_EN_B = 1'b0;
    end
end

always @ (*) begin
    if (((ap_enable_reg_pp0_iter19 == 1'b1) & (1'b0 == ap_block_pp0_stage0_11001))) begin
        v10_2_WEN_A = 4'd15;
    end else begin
        v10_2_WEN_A = 4'd0;
    end
end

always @ (*) begin
    if (((ap_enable_reg_pp0_iter19 == 1'b1) & (1'b0 == ap_block_pp0_stage0_11001))) begin
        v10_3_EN_A = 1'b1;
    end else begin
        v10_3_EN_A = 1'b0;
    end
end

always @ (*) begin
    if (((ap_enable_reg_pp0_iter10 == 1'b1) & (1'b0 == ap_block_pp0_stage0_11001))) begin
        v10_3_EN_B = 1'b1;
    end else begin
        v10_3_EN_B = 1'b0;
    end
end

always @ (*) begin
    if (((ap_enable_reg_pp0_iter19 == 1'b1) & (1'b0 == ap_block_pp0_stage0_11001))) begin
        v10_3_WEN_A = 4'd15;
    end else begin
        v10_3_WEN_A = 4'd0;
    end
end

always @ (*) begin
    if (((ap_enable_reg_pp0_iter19 == 1'b1) & (1'b0 == ap_block_pp0_stage0_11001))) begin
        v10_4_EN_A = 1'b1;
    end else begin
        v10_4_EN_A = 1'b0;
    end
end

always @ (*) begin
    if (((ap_enable_reg_pp0_iter10 == 1'b1) & (1'b0 == ap_block_pp0_stage0_11001))) begin
        v10_4_EN_B = 1'b1;
    end else begin
        v10_4_EN_B = 1'b0;
    end
end

always @ (*) begin
    if (((ap_enable_reg_pp0_iter19 == 1'b1) & (1'b0 == ap_block_pp0_stage0_11001))) begin
        v10_4_WEN_A = 4'd15;
    end else begin
        v10_4_WEN_A = 4'd0;
    end
end

always @ (*) begin
    if (((ap_enable_reg_pp0_iter19 == 1'b1) & (1'b0 == ap_block_pp0_stage0_11001))) begin
        v10_5_EN_A = 1'b1;
    end else begin
        v10_5_EN_A = 1'b0;
    end
end

always @ (*) begin
    if (((ap_enable_reg_pp0_iter10 == 1'b1) & (1'b0 == ap_block_pp0_stage0_11001))) begin
        v10_5_EN_B = 1'b1;
    end else begin
        v10_5_EN_B = 1'b0;
    end
end

always @ (*) begin
    if (((ap_enable_reg_pp0_iter19 == 1'b1) & (1'b0 == ap_block_pp0_stage0_11001))) begin
        v10_5_WEN_A = 4'd15;
    end else begin
        v10_5_WEN_A = 4'd0;
    end
end

always @ (*) begin
    if (((ap_enable_reg_pp0_iter19 == 1'b1) & (1'b0 == ap_block_pp0_stage0_11001))) begin
        v10_6_EN_A = 1'b1;
    end else begin
        v10_6_EN_A = 1'b0;
    end
end

always @ (*) begin
    if (((ap_enable_reg_pp0_iter10 == 1'b1) & (1'b0 == ap_block_pp0_stage0_11001))) begin
        v10_6_EN_B = 1'b1;
    end else begin
        v10_6_EN_B = 1'b0;
    end
end

always @ (*) begin
    if (((ap_enable_reg_pp0_iter19 == 1'b1) & (1'b0 == ap_block_pp0_stage0_11001))) begin
        v10_6_WEN_A = 4'd15;
    end else begin
        v10_6_WEN_A = 4'd0;
    end
end

always @ (*) begin
    if (((ap_enable_reg_pp0_iter19 == 1'b1) & (1'b0 == ap_block_pp0_stage0_11001))) begin
        v10_7_EN_A = 1'b1;
    end else begin
        v10_7_EN_A = 1'b0;
    end
end

always @ (*) begin
    if (((ap_enable_reg_pp0_iter10 == 1'b1) & (1'b0 == ap_block_pp0_stage0_11001))) begin
        v10_7_EN_B = 1'b1;
    end else begin
        v10_7_EN_B = 1'b0;
    end
end

always @ (*) begin
    if (((ap_enable_reg_pp0_iter19 == 1'b1) & (1'b0 == ap_block_pp0_stage0_11001))) begin
        v10_7_WEN_A = 4'd15;
    end else begin
        v10_7_WEN_A = 4'd0;
    end
end

always @ (*) begin
    if (((ap_enable_reg_pp0_iter6 == 1'b1) & (1'b0 == ap_block_pp0_stage0_11001))) begin
        v1_0_EN_A = 1'b1;
    end else begin
        v1_0_EN_A = 1'b0;
    end
end

always @ (*) begin
    if (((ap_enable_reg_pp0_iter6 == 1'b1) & (1'b0 == ap_block_pp0_stage0_11001))) begin
        v1_1_EN_A = 1'b1;
    end else begin
        v1_1_EN_A = 1'b0;
    end
end

always @ (*) begin
    if (((ap_enable_reg_pp0_iter6 == 1'b1) & (1'b0 == ap_block_pp0_stage0_11001))) begin
        v1_2_EN_A = 1'b1;
    end else begin
        v1_2_EN_A = 1'b0;
    end
end

always @ (*) begin
    if (((ap_enable_reg_pp0_iter6 == 1'b1) & (1'b0 == ap_block_pp0_stage0_11001))) begin
        v1_3_EN_A = 1'b1;
    end else begin
        v1_3_EN_A = 1'b0;
    end
end

always @ (*) begin
    if (((ap_enable_reg_pp0_iter6 == 1'b1) & (1'b0 == ap_block_pp0_stage0_11001))) begin
        v1_4_EN_A = 1'b1;
    end else begin
        v1_4_EN_A = 1'b0;
    end
end

always @ (*) begin
    if (((ap_enable_reg_pp0_iter6 == 1'b1) & (1'b0 == ap_block_pp0_stage0_11001))) begin
        v1_5_EN_A = 1'b1;
    end else begin
        v1_5_EN_A = 1'b0;
    end
end

always @ (*) begin
    if (((ap_enable_reg_pp0_iter6 == 1'b1) & (1'b0 == ap_block_pp0_stage0_11001))) begin
        v1_6_EN_A = 1'b1;
    end else begin
        v1_6_EN_A = 1'b0;
    end
end

always @ (*) begin
    if (((ap_enable_reg_pp0_iter6 == 1'b1) & (1'b0 == ap_block_pp0_stage0_11001))) begin
        v1_7_EN_A = 1'b1;
    end else begin
        v1_7_EN_A = 1'b0;
    end
end

always @ (*) begin
    if (((ap_enable_reg_pp0_iter6 == 1'b1) & (1'b0 == ap_block_pp0_stage0_11001))) begin
        v28_EN_A = 1'b1;
    end else begin
        v28_EN_A = 1'b0;
    end
end

always @ (*) begin
    case (ap_CS_fsm)
        ap_ST_fsm_pp0_stage0 : begin
            ap_NS_fsm = ap_ST_fsm_pp0_stage0;
        end
        default : begin
            ap_NS_fsm = 'bx;
        end
    endcase
end

assign add_ln170_1_fu_563_p2 = (indvar_flatten289_fu_178 + 18'd1);

assign add_ln170_fu_753_p2 = (v32_fu_174 + 2'd1);

assign add_ln171_1_fu_578_p2 = (indvar_flatten189_fu_170 + 17'd1);

assign add_ln171_fu_792_p2 = (select_ln170_fu_759_p3 + 2'd1);

assign add_ln172_1_fu_627_p2 = (indvar_flatten101_fu_162 + 16'd1);

assign add_ln172_fu_1106_p2 = (select_ln171_fu_1051_p3 + 2'd1);

assign add_ln173_1_fu_686_p2 = (indvar_flatten25_fu_154 + 15'd1);

assign add_ln173_cast_fu_862_p1 = add_ln173_fu_846_p2;

assign add_ln173_fu_846_p2 = (select_ln172_fu_828_p3 + 4'd1);

assign add_ln174_1_fu_906_p2 = (indvar_flatten_fu_146 + 12'd1);

assign add_ln174_fu_1264_p2 = (select_ln173_fu_1173_p3 + 6'd1);

assign add_ln175_fu_1345_p2 = (select_ln174_fu_1285_p3 + 6'd1);

assign add_ln177_1_fu_1329_p2 = (zext_ln170_1_fu_1029_p1 + zext_ln177_2_fu_1325_p1);

assign add_ln177_2_fu_1439_p2 = (p_shl6_fu_1421_p3 + zext_ln177_3_fu_1435_p1);

assign add_ln177_3_fu_1457_p2 = (add_ln177_2_fu_1439_p2 + zext_ln177_4_fu_1454_p1);

assign add_ln177_fu_1339_p2 = (select_ln174_fu_1285_p3 + select_ln172_3_cast_fu_1127_p1);

assign add_ln180_1_fu_1448_p2 = (tmp_61_fu_1414_p3 + zext_ln180_1_fu_1445_p1);

assign add_ln180_fu_1305_p2 = (tmp_59_cast_fu_1234_p3 + zext_ln180_fu_1301_p1);

assign and_ln170_1_fu_787_p2 = (xor_ln170_reg_1680_pp0_iter3_reg & icmp_ln174_fu_781_p2);

assign and_ln170_2_fu_655_p2 = (xor_ln170_reg_1680 & icmp_ln173_fu_649_p2);

assign and_ln170_3_fu_616_p2 = (xor_ln170_fu_605_p2 & icmp_ln172_fu_610_p2);

assign and_ln170_fu_1046_p2 = (xor_ln170_reg_1680_pp0_iter4_reg & icmp_ln175_fu_1040_p2);

assign and_ln171_1_fu_823_p2 = (or_ln171_1_reg_1706 & and_ln170_1_fu_787_p2);

assign and_ln171_2_fu_670_p2 = (or_ln171_1_fu_665_p2 & and_ln170_2_fu_655_p2);

assign and_ln171_fu_1101_p2 = (or_ln171_1_reg_1706_pp0_iter4_reg & and_ln170_fu_1046_p2);

assign and_ln172_1_fu_840_p2 = (xor_ln172_fu_835_p2 & and_ln171_1_fu_823_p2);

assign and_ln172_fu_1168_p2 = (xor_ln172_reg_1777 & and_ln171_fu_1101_p2);

assign and_ln173_fu_1258_p2 = (or_ln173_2_fu_1253_p2 & and_ln172_fu_1168_p2);

assign ap_CS_fsm_pp0_stage0 = ap_CS_fsm[32'd0];

assign ap_block_pp0_stage0 = ~(1'b1 == 1'b1);

assign ap_block_pp0_stage0_00001 = ~(1'b1 == 1'b1);

assign ap_block_pp0_stage0_11001 = ~(1'b1 == 1'b1);

assign ap_block_pp0_stage0_subdone = ~(1'b1 == 1'b1);

assign ap_block_state10_pp0_stage0_iter9 = ~(1'b1 == 1'b1);

assign ap_block_state11_pp0_stage0_iter10 = ~(1'b1 == 1'b1);

assign ap_block_state12_pp0_stage0_iter11 = ~(1'b1 == 1'b1);

assign ap_block_state13_pp0_stage0_iter12 = ~(1'b1 == 1'b1);

assign ap_block_state14_pp0_stage0_iter13 = ~(1'b1 == 1'b1);

assign ap_block_state15_pp0_stage0_iter14 = ~(1'b1 == 1'b1);

assign ap_block_state16_pp0_stage0_iter15 = ~(1'b1 == 1'b1);

assign ap_block_state17_pp0_stage0_iter16 = ~(1'b1 == 1'b1);

assign ap_block_state18_pp0_stage0_iter17 = ~(1'b1 == 1'b1);

assign ap_block_state19_pp0_stage0_iter18 = ~(1'b1 == 1'b1);

assign ap_block_state1_pp0_stage0_iter0 = ~(1'b1 == 1'b1);

assign ap_block_state20_pp0_stage0_iter19 = ~(1'b1 == 1'b1);

assign ap_block_state2_pp0_stage0_iter1 = ~(1'b1 == 1'b1);

assign ap_block_state3_pp0_stage0_iter2 = ~(1'b1 == 1'b1);

assign ap_block_state4_pp0_stage0_iter3 = ~(1'b1 == 1'b1);

assign ap_block_state5_pp0_stage0_iter4 = ~(1'b1 == 1'b1);

assign ap_block_state6_pp0_stage0_iter5 = ~(1'b1 == 1'b1);

assign ap_block_state7_pp0_stage0_iter6 = ~(1'b1 == 1'b1);

assign ap_block_state8_pp0_stage0_iter7 = ~(1'b1 == 1'b1);

assign ap_block_state9_pp0_stage0_iter8 = ~(1'b1 == 1'b1);

assign ap_enable_pp0 = (ap_idle_pp0 ^ 1'b1);

assign ap_enable_reg_pp0_iter0 = ap_start_int;

assign ap_loop_exit_ready = ap_condition_exit_pp0_iter1_stage0;

assign bitcast_ln173_1_fu_1472_p1 = v1_1_load_reg_1905;

assign bitcast_ln173_2_fu_1476_p1 = v1_2_load_reg_1910;

assign bitcast_ln173_3_fu_1480_p1 = v1_3_load_reg_1915;

assign bitcast_ln173_4_fu_1484_p1 = v1_4_load_reg_1920;

assign bitcast_ln173_5_fu_1488_p1 = v1_5_load_reg_1925;

assign bitcast_ln173_6_fu_1492_p1 = v1_6_load_reg_1930;

assign bitcast_ln173_7_fu_1496_p1 = v1_7_load_reg_1935;

assign bitcast_ln173_fu_1468_p1 = v1_0_load_reg_1900;

assign empty_364_fu_744_p2 = ($signed(p_cast_fu_740_p1) + $signed(zext_ln170_fu_714_p1));

assign empty_365_fu_970_p2 = ($signed(p_shl1_fu_966_p1) - $signed(p_cast1_fu_956_p1));

assign empty_366_fu_976_p2 = (empty_365_fu_970_p2 + zext_ln171_fu_946_p1);

assign empty_367_fu_982_p1 = empty_366_fu_976_p2[7:0];

assign empty_368_fu_986_p1 = empty_366_fu_976_p2[5:0];

assign empty_369_fu_998_p2 = (p_shl_fu_990_p3 - empty_367_fu_982_p1);

assign empty_370_fu_1004_p2 = (empty_369_fu_998_p2 + zext_ln172_fu_952_p1);

assign empty_371_fu_1010_p2 = (v36_fu_142 + zext_ln171_1_fu_949_p1);

assign empty_373_fu_817_p2 = (tmp_53_cast_fu_813_p1 - zext_ln177_1_fu_777_p1);

assign empty_374_fu_1070_p2 = ($signed(p_cast4_fu_1067_p1) + $signed(zext_ln171_2_fu_1058_p1));

assign empty_375_fu_1088_p2 = ($signed(p_shl2_fu_1080_p3) - $signed(p_cast5_fu_1076_p1));

assign empty_376_fu_1131_p2 = ($signed(p_cast4_fu_1067_p1) + $signed(zext_ln171_4_fu_1064_p1));

assign empty_377_fu_1149_p2 = ($signed(p_shl3_fu_1141_p3) - $signed(p_cast6_fu_1137_p1));

assign empty_378_fu_1155_p2 = (empty_377_fu_1149_p2 + zext_ln172_1_fu_1112_p1);

assign empty_379_fu_878_p2 = (tmp_56_cast_fu_874_p1 - add_ln173_cast_fu_862_p1);

assign empty_380_fu_888_p2 = ($signed(p_cast7_fu_884_p1) + $signed(zext_ln177_fu_773_p1));

assign empty_381_fu_1194_p2 = ($signed(p_shl4_fu_1190_p1) - $signed(p_cast9_fu_1180_p1));

assign empty_382_fu_1200_p2 = (empty_381_fu_1194_p2 + zext_ln171_3_fu_1061_p1);

assign empty_383_fu_1206_p1 = empty_382_fu_1200_p2[7:0];

assign empty_384_fu_1210_p1 = empty_382_fu_1200_p2[5:0];

assign empty_385_fu_1222_p2 = (p_shl5_fu_1214_p3 - empty_383_fu_1206_p1);

assign empty_386_fu_1228_p2 = (empty_385_fu_1222_p2 + zext_ln172_2_fu_1123_p1);

assign empty_fu_734_p2 = (tmp_45_cast_fu_730_p1 - v35_cast_fu_718_p1);

assign grp_fu_12576_p_ce = 1'b1;

assign grp_fu_12576_p_din0 = v40_reg_2045;

assign grp_fu_12576_p_din1 = v41_fu_1522_p1;

assign grp_fu_12576_p_opcode = 2'd0;

assign grp_fu_12580_p_ce = 1'b1;

assign grp_fu_12580_p_din0 = v44_reg_2055;

assign grp_fu_12580_p_din1 = v45_fu_1526_p1;

assign grp_fu_12580_p_opcode = 2'd0;

assign grp_fu_12584_p_ce = 1'b1;

assign grp_fu_12584_p_din0 = v48_reg_2065;

assign grp_fu_12584_p_din1 = v49_fu_1530_p1;

assign grp_fu_12584_p_opcode = 2'd0;

assign grp_fu_12588_p_ce = 1'b1;

assign grp_fu_12588_p_din0 = v52_reg_2075;

assign grp_fu_12588_p_din1 = v53_fu_1534_p1;

assign grp_fu_12588_p_opcode = 2'd0;

assign grp_fu_12592_p_ce = 1'b1;

assign grp_fu_12592_p_din0 = v56_reg_2085;

assign grp_fu_12592_p_din1 = v57_fu_1538_p1;

assign grp_fu_12592_p_opcode = 2'd0;

assign grp_fu_12596_p_ce = 1'b1;

assign grp_fu_12596_p_din0 = v60_reg_2095;

assign grp_fu_12596_p_din1 = v61_fu_1542_p1;

assign grp_fu_12596_p_opcode = 2'd0;

assign grp_fu_12600_p_ce = 1'b1;

assign grp_fu_12600_p_din0 = v64_reg_2105;

assign grp_fu_12600_p_din1 = v65_fu_1546_p1;

assign grp_fu_12600_p_opcode = 2'd0;

assign grp_fu_12604_p_ce = 1'b1;

assign grp_fu_12604_p_din0 = v68_reg_2115;

assign grp_fu_12604_p_din1 = v69_fu_1550_p1;

assign grp_fu_12604_p_opcode = 2'd0;

assign grp_fu_12608_p_ce = 1'b1;

assign grp_fu_12608_p_din0 = v38_fu_1500_p1;

assign grp_fu_12608_p_din1 = bitcast_ln173_fu_1468_p1;

assign grp_fu_12612_p_ce = 1'b1;

assign grp_fu_12612_p_din0 = v38_fu_1500_p1;

assign grp_fu_12612_p_din1 = bitcast_ln173_1_fu_1472_p1;

assign grp_fu_12616_p_ce = 1'b1;

assign grp_fu_12616_p_din0 = v38_fu_1500_p1;

assign grp_fu_12616_p_din1 = bitcast_ln173_2_fu_1476_p1;

assign grp_fu_12620_p_ce = 1'b1;

assign grp_fu_12620_p_din0 = v38_fu_1500_p1;

assign grp_fu_12620_p_din1 = bitcast_ln173_3_fu_1480_p1;

assign grp_fu_12624_p_ce = 1'b1;

assign grp_fu_12624_p_din0 = v38_fu_1500_p1;

assign grp_fu_12624_p_din1 = bitcast_ln173_4_fu_1484_p1;

assign grp_fu_12628_p_ce = 1'b1;

assign grp_fu_12628_p_din0 = v38_fu_1500_p1;

assign grp_fu_12628_p_din1 = bitcast_ln173_5_fu_1488_p1;

assign grp_fu_12632_p_ce = 1'b1;

assign grp_fu_12632_p_din0 = v38_fu_1500_p1;

assign grp_fu_12632_p_din1 = bitcast_ln173_6_fu_1492_p1;

assign grp_fu_12636_p_ce = 1'b1;

assign grp_fu_12636_p_din0 = v38_fu_1500_p1;

assign grp_fu_12636_p_din1 = bitcast_ln173_7_fu_1496_p1;

assign icmp_ln170_fu_557_p2 = ((indvar_flatten289_fu_178 == 18'd221184) ? 1'b1 : 1'b0);

assign icmp_ln171_fu_572_p2 = ((indvar_flatten189_fu_170 == 17'd73728) ? 1'b1 : 1'b0);

assign icmp_ln172_fu_610_p2 = ((indvar_flatten101_fu_162 == 16'd24576) ? 1'b1 : 1'b0);

assign icmp_ln173_fu_649_p2 = ((indvar_flatten25_fu_154 == 15'd8192) ? 1'b1 : 1'b0);

assign icmp_ln174_fu_781_p2 = ((indvar_flatten_fu_146 == 12'd1024) ? 1'b1 : 1'b0);

assign icmp_ln175_fu_1040_p2 = ((v37_fu_138 == 6'd32) ? 1'b1 : 1'b0);

assign or_ln171_1_fu_665_p2 = (xor_ln171_fu_660_p2 | icmp_ln171_reg_1667_pp0_iter2_reg);

assign or_ln171_fu_622_p2 = (icmp_ln171_reg_1667 | and_ln170_3_fu_616_p2);

assign or_ln172_1_fu_681_p2 = (or_ln172_fu_676_p2 | icmp_ln171_reg_1667_pp0_iter2_reg);

assign or_ln172_fu_676_p2 = (and_ln171_2_fu_670_p2 | and_ln170_3_reg_1692);

assign or_ln173_1_fu_857_p2 = (or_ln173_fu_852_p2 | or_ln171_reg_1700_pp0_iter3_reg);

assign or_ln173_2_fu_1253_p2 = (xor_ln173_fu_1248_p2 | and_ln171_2_reg_1712_pp0_iter4_reg);

assign or_ln173_fu_852_p2 = (and_ln172_1_fu_840_p2 | and_ln171_2_reg_1712);

assign or_ln174_1_fu_1275_p2 = (or_ln174_fu_1270_p2 | or_ln172_reg_1722_pp0_iter4_reg);

assign or_ln174_2_fu_1280_p2 = (or_ln174_1_fu_1275_p2 | icmp_ln171_reg_1667_pp0_iter4_reg);

assign or_ln174_fu_1270_p2 = (and_ln173_fu_1258_p2 | and_ln172_1_reg_1782);

assign or_ln_fu_1019_p5 = {{{{select_ln170_1_reg_1750}, {2'd0}}, {select_ln170_1_reg_1750}}, {1'd0}};

assign p_cast1_fu_956_p1 = empty_364_reg_1738;

assign p_cast4_fu_1067_p1 = $signed(empty_373_reg_1767);

assign p_cast5_fu_1076_p1 = empty_374_fu_1070_p2;

assign p_cast6_fu_1137_p1 = empty_376_fu_1131_p2;

assign p_cast7_fu_884_p1 = $signed(empty_379_fu_878_p2);

assign p_cast9_fu_1180_p1 = empty_380_reg_1794;

assign p_cast_fu_740_p1 = $signed(empty_fu_734_p2);

assign p_mid1_fu_1311_p2 = (add_ln174_fu_1264_p2 + zext_ln171_4_fu_1064_p1);

assign p_shl1_fu_966_p1 = $signed(tmp_fu_959_p3);

assign p_shl2_fu_1080_p3 = {{empty_374_fu_1070_p2}, {2'd0}};

assign p_shl3_fu_1141_p3 = {{empty_376_fu_1131_p2}, {2'd0}};

assign p_shl4_fu_1190_p1 = $signed(tmp_69_fu_1183_p3);

assign p_shl5_fu_1214_p3 = {{empty_384_fu_1210_p1}, {2'd0}};

assign p_shl6_fu_1421_p3 = {{trunc_ln177_reg_1840}, {5'd0}};

assign p_shl_fu_990_p3 = {{empty_368_fu_986_p1}, {2'd0}};

assign select_ln170_1_fu_766_p3 = ((icmp_ln171_reg_1667_pp0_iter3_reg[0:0] == 1'b1) ? add_ln170_fu_753_p2 : v32_fu_174);

assign select_ln170_2_fu_1378_p3 = ((icmp_ln171_reg_1667_pp0_iter5_reg[0:0] == 1'b1) ? zext_ln173_fu_1374_p1 : empty_370_reg_1805);

assign select_ln170_3_fu_1033_p3 = ((icmp_ln171_reg_1667_pp0_iter4_reg[0:0] == 1'b1) ? 6'd0 : empty_371_fu_1010_p2);

assign select_ln170_fu_759_p3 = ((icmp_ln171_reg_1667_pp0_iter3_reg[0:0] == 1'b1) ? 2'd0 : v33_fu_166);

assign select_ln171_1_fu_798_p3 = ((and_ln170_3_reg_1692_pp0_iter3_reg[0:0] == 1'b1) ? add_ln171_fu_792_p2 : select_ln170_fu_759_p3);

assign select_ln171_2_fu_1384_p3 = ((and_ln170_3_reg_1692_pp0_iter5_reg[0:0] == 1'b1) ? empty_375_reg_1810 : select_ln170_2_fu_1378_p3);

assign select_ln171_3_fu_1094_p3 = ((and_ln170_3_reg_1692_pp0_iter4_reg[0:0] == 1'b1) ? zext_ln171_2_fu_1058_p1 : select_ln170_3_fu_1033_p3);

assign select_ln171_4_fu_584_p3 = ((icmp_ln171_fu_572_p2[0:0] == 1'b1) ? 17'd1 : add_ln171_1_fu_578_p2);

assign select_ln171_fu_1051_p3 = ((or_ln171_reg_1700_pp0_iter4_reg[0:0] == 1'b1) ? 2'd0 : v34_fu_158);

assign select_ln172_1_fu_1116_p3 = ((and_ln171_2_reg_1712_pp0_iter4_reg[0:0] == 1'b1) ? add_ln172_fu_1106_p2 : select_ln171_fu_1051_p3);

assign select_ln172_2_fu_1390_p3 = ((and_ln171_2_reg_1712_pp0_iter5_reg[0:0] == 1'b1) ? empty_378_reg_1815 : select_ln171_2_fu_1384_p3);

assign select_ln172_3_cast_fu_1127_p1 = select_ln172_1_fu_1116_p3;

assign select_ln172_3_fu_1161_p3 = ((and_ln171_2_reg_1712_pp0_iter4_reg[0:0] == 1'b1) ? zext_ln171_4_fu_1064_p1 : select_ln171_3_fu_1094_p3);

assign select_ln172_4_fu_633_p3 = ((or_ln171_fu_622_p2[0:0] == 1'b1) ? 16'd1 : add_ln172_1_fu_627_p2);

assign select_ln172_fu_828_p3 = ((or_ln172_1_reg_1727[0:0] == 1'b1) ? 4'd0 : v35_fu_150);

assign select_ln173_1_fu_894_p3 = ((and_ln172_1_fu_840_p2[0:0] == 1'b1) ? add_ln173_fu_846_p2 : select_ln172_fu_828_p3);

assign select_ln173_2_cast_fu_1402_p1 = select_ln173_2_fu_1396_p3;

assign select_ln173_2_fu_1396_p3 = ((and_ln172_1_reg_1782_pp0_iter5_reg[0:0] == 1'b1) ? empty_386_reg_1820 : select_ln172_2_fu_1390_p3);

assign select_ln173_3_fu_1241_p3 = ((and_ln172_1_reg_1782[0:0] == 1'b1) ? zext_ln171_4_fu_1064_p1 : select_ln172_3_fu_1161_p3);

assign select_ln173_4_fu_692_p3 = ((or_ln172_1_fu_681_p2[0:0] == 1'b1) ? 15'd1 : add_ln173_1_fu_686_p2);

assign select_ln173_fu_1173_p3 = ((or_ln173_1_reg_1789[0:0] == 1'b1) ? 6'd0 : v36_fu_142);

assign select_ln174_1_fu_1293_p3 = ((and_ln173_fu_1258_p2[0:0] == 1'b1) ? add_ln174_fu_1264_p2 : select_ln173_fu_1173_p3);

assign select_ln174_2_fu_1317_p3 = ((and_ln173_fu_1258_p2[0:0] == 1'b1) ? p_mid1_fu_1311_p2 : select_ln173_3_fu_1241_p3);

assign select_ln174_3_fu_912_p3 = ((or_ln173_1_fu_857_p2[0:0] == 1'b1) ? 12'd1 : add_ln174_1_fu_906_p2);

assign select_ln174_fu_1285_p3 = ((or_ln174_2_fu_1280_p2[0:0] == 1'b1) ? 6'd0 : v37_fu_138);

assign tmp_45_cast_fu_730_p1 = tmp_45_fu_722_p3;

assign tmp_45_fu_722_p3 = {{v35_fu_150}, {2'd0}};

assign tmp_53_cast_fu_813_p1 = tmp_53_fu_805_p3;

assign tmp_53_fu_805_p3 = {{select_ln170_1_fu_766_p3}, {2'd0}};

assign tmp_56_cast_fu_874_p1 = tmp_56_fu_866_p3;

assign tmp_56_fu_866_p3 = {{add_ln173_fu_846_p2}, {2'd0}};

assign tmp_59_cast_fu_1234_p3 = {{trunc_ln180_reg_1800}, {5'd0}};

assign tmp_61_fu_1414_p3 = {{add_ln180_reg_1830}, {5'd0}};

assign tmp_68_fu_1366_p4 = {{{add_ln170_reg_1744_pp0_iter5_reg}, {1'd0}}, {add_ln170_reg_1744_pp0_iter5_reg}};

assign tmp_69_fu_1183_p3 = {{empty_380_reg_1794}, {2'd0}};

assign tmp_70_fu_1428_p3 = {{add_ln177_1_reg_1835}, {1'd0}};

assign tmp_fu_959_p3 = {{empty_364_reg_1738}, {2'd0}};

assign trunc_ln177_fu_1335_p1 = add_ln177_1_fu_1329_p2[6:0];

assign trunc_ln180_fu_902_p1 = select_ln173_1_fu_894_p3[2:0];

assign v10_0_Addr_A = v10_0_Addr_A_orig << 32'd2;

assign v10_0_Addr_A_orig = v10_0_addr_reg_1997_pp0_iter18_reg;

assign v10_0_Addr_B = v10_0_Addr_B_orig << 32'd2;

assign v10_0_Addr_B_orig = zext_ln180_2_fu_1511_p1;

assign v10_0_Din_A = v42_reg_2165;

assign v10_0_Din_B = 32'd0;

assign v10_0_WEN_B = 4'd0;

assign v10_1_Addr_A = v10_1_Addr_A_orig << 32'd2;

assign v10_1_Addr_A_orig = v10_1_addr_reg_2003_pp0_iter18_reg;

assign v10_1_Addr_B = v10_1_Addr_B_orig << 32'd2;

assign v10_1_Addr_B_orig = zext_ln180_2_fu_1511_p1;

assign v10_1_Din_A = v46_reg_2170;

assign v10_1_Din_B = 32'd0;

assign v10_1_WEN_B = 4'd0;

assign v10_2_Addr_A = v10_2_Addr_A_orig << 32'd2;

assign v10_2_Addr_A_orig = v10_2_addr_reg_2009_pp0_iter18_reg;

assign v10_2_Addr_B = v10_2_Addr_B_orig << 32'd2;

assign v10_2_Addr_B_orig = zext_ln180_2_fu_1511_p1;

assign v10_2_Din_A = v50_reg_2175;

assign v10_2_Din_B = 32'd0;

assign v10_2_WEN_B = 4'd0;

assign v10_3_Addr_A = v10_3_Addr_A_orig << 32'd2;

assign v10_3_Addr_A_orig = v10_3_addr_reg_2015_pp0_iter18_reg;

assign v10_3_Addr_B = v10_3_Addr_B_orig << 32'd2;

assign v10_3_Addr_B_orig = zext_ln180_2_fu_1511_p1;

assign v10_3_Din_A = v54_reg_2180;

assign v10_3_Din_B = 32'd0;

assign v10_3_WEN_B = 4'd0;

assign v10_4_Addr_A = v10_4_Addr_A_orig << 32'd2;

assign v10_4_Addr_A_orig = v10_4_addr_reg_2021_pp0_iter18_reg;

assign v10_4_Addr_B = v10_4_Addr_B_orig << 32'd2;

assign v10_4_Addr_B_orig = zext_ln180_2_fu_1511_p1;

assign v10_4_Din_A = v58_reg_2185;

assign v10_4_Din_B = 32'd0;

assign v10_4_WEN_B = 4'd0;

assign v10_5_Addr_A = v10_5_Addr_A_orig << 32'd2;

assign v10_5_Addr_A_orig = v10_5_addr_reg_2027_pp0_iter18_reg;

assign v10_5_Addr_B = v10_5_Addr_B_orig << 32'd2;

assign v10_5_Addr_B_orig = zext_ln180_2_fu_1511_p1;

assign v10_5_Din_A = v62_reg_2190;

assign v10_5_Din_B = 32'd0;

assign v10_5_WEN_B = 4'd0;

assign v10_6_Addr_A = v10_6_Addr_A_orig << 32'd2;

assign v10_6_Addr_A_orig = v10_6_addr_reg_2033_pp0_iter18_reg;

assign v10_6_Addr_B = v10_6_Addr_B_orig << 32'd2;

assign v10_6_Addr_B_orig = zext_ln180_2_fu_1511_p1;

assign v10_6_Din_A = v66_reg_2195;

assign v10_6_Din_B = 32'd0;

assign v10_6_WEN_B = 4'd0;

assign v10_7_Addr_A = v10_7_Addr_A_orig << 32'd2;

assign v10_7_Addr_A_orig = v10_7_addr_reg_2039_pp0_iter18_reg;

assign v10_7_Addr_B = v10_7_Addr_B_orig << 32'd2;

assign v10_7_Addr_B_orig = zext_ln180_2_fu_1511_p1;

assign v10_7_Din_A = v70_reg_2200;

assign v10_7_Din_B = 32'd0;

assign v10_7_WEN_B = 4'd0;

assign v1_0_Addr_A = v1_0_Addr_A_orig << 32'd2;

assign v1_0_Addr_A_orig = select_ln173_2_cast_fu_1402_p1;

assign v1_0_Din_A = 32'd0;

assign v1_0_WEN_A = 4'd0;

assign v1_1_Addr_A = v1_1_Addr_A_orig << 32'd2;

assign v1_1_Addr_A_orig = select_ln173_2_cast_fu_1402_p1;

assign v1_1_Din_A = 32'd0;

assign v1_1_WEN_A = 4'd0;

assign v1_2_Addr_A = v1_2_Addr_A_orig << 32'd2;

assign v1_2_Addr_A_orig = select_ln173_2_cast_fu_1402_p1;

assign v1_2_Din_A = 32'd0;

assign v1_2_WEN_A = 4'd0;

assign v1_3_Addr_A = v1_3_Addr_A_orig << 32'd2;

assign v1_3_Addr_A_orig = select_ln173_2_cast_fu_1402_p1;

assign v1_3_Din_A = 32'd0;

assign v1_3_WEN_A = 4'd0;

assign v1_4_Addr_A = v1_4_Addr_A_orig << 32'd2;

assign v1_4_Addr_A_orig = select_ln173_2_cast_fu_1402_p1;

assign v1_4_Din_A = 32'd0;

assign v1_4_WEN_A = 4'd0;

assign v1_5_Addr_A = v1_5_Addr_A_orig << 32'd2;

assign v1_5_Addr_A_orig = select_ln173_2_cast_fu_1402_p1;

assign v1_5_Din_A = 32'd0;

assign v1_5_WEN_A = 4'd0;

assign v1_6_Addr_A = v1_6_Addr_A_orig << 32'd2;

assign v1_6_Addr_A_orig = select_ln173_2_cast_fu_1402_p1;

assign v1_6_Din_A = 32'd0;

assign v1_6_WEN_A = 4'd0;

assign v1_7_Addr_A = v1_7_Addr_A_orig << 32'd2;

assign v1_7_Addr_A_orig = select_ln173_2_cast_fu_1402_p1;

assign v1_7_Din_A = 32'd0;

assign v1_7_WEN_A = 4'd0;

assign v28_Addr_A = v28_Addr_A_orig << 32'd2;

assign v28_Addr_A_orig = zext_ln177_5_fu_1463_p1;

assign v28_Din_A = 32'd0;

assign v28_WEN_A = 4'd0;

assign v35_cast_fu_718_p1 = v35_fu_150;

assign v38_fu_1500_p1 = v28_load_reg_1940;

assign v41_fu_1522_p1 = v10_0_load_reg_2050;

assign v45_fu_1526_p1 = v10_1_load_reg_2060;

assign v49_fu_1530_p1 = v10_2_load_reg_2070;

assign v53_fu_1534_p1 = v10_3_load_reg_2080;

assign v57_fu_1538_p1 = v10_4_load_reg_2090;

assign v61_fu_1542_p1 = v10_5_load_reg_2100;

assign v65_fu_1546_p1 = v10_6_load_reg_2110;

assign v69_fu_1550_p1 = v10_7_load_reg_2120;

assign xor_ln170_fu_605_p2 = (icmp_ln171_reg_1667 ^ 1'd1);

assign xor_ln171_fu_660_p2 = (icmp_ln172_reg_1687 ^ 1'd1);

assign xor_ln172_fu_835_p2 = (1'd1 ^ and_ln171_2_reg_1712);

assign xor_ln173_fu_1248_p2 = (1'd1 ^ and_ln171_1_reg_1772);

assign zext_ln170_1_fu_1029_p1 = or_ln_fu_1019_p5;

assign zext_ln170_fu_714_p1 = v32_fu_174;

assign zext_ln171_1_fu_949_p1 = v33_1_reg_1732;

assign zext_ln171_2_fu_1058_p1 = add_ln171_reg_1756;

assign zext_ln171_3_fu_1061_p1 = select_ln171_1_reg_1761;

assign zext_ln171_4_fu_1064_p1 = select_ln171_1_reg_1761;

assign zext_ln171_fu_946_p1 = v33_1_reg_1732;

assign zext_ln172_1_fu_1112_p1 = add_ln172_fu_1106_p2;

assign zext_ln172_2_fu_1123_p1 = select_ln172_1_fu_1116_p3;

assign zext_ln172_fu_952_p1 = v34_fu_158;

assign zext_ln173_fu_1374_p1 = tmp_68_fu_1366_p4;

assign zext_ln177_1_fu_777_p1 = select_ln170_1_fu_766_p3;

assign zext_ln177_2_fu_1325_p1 = select_ln174_2_fu_1317_p3;

assign zext_ln177_3_fu_1435_p1 = tmp_70_fu_1428_p3;

assign zext_ln177_4_fu_1454_p1 = add_ln177_reg_1845;

assign zext_ln177_5_fu_1463_p1 = add_ln177_3_fu_1457_p2;

assign zext_ln177_fu_773_p1 = select_ln170_1_fu_766_p3;

assign zext_ln180_1_fu_1445_p1 = select_ln174_reg_1825;

assign zext_ln180_2_fu_1511_p1 = add_ln180_1_reg_1890_pp0_iter9_reg;

assign zext_ln180_fu_1301_p1 = select_ln174_1_fu_1293_p3;

endmodule //test_vgg16_test_vgg16_Pipeline_VITIS_LOOP_170_4_VITIS_LOOP_172_6_VITIS_LOOP_174_8_VITIS_LOO
